const freezeList = (values = []) => Object.freeze([...values]);

const topic = (id, config) => Object.freeze({
  id,
  supportingPaths: freezeList(config.supportingPaths),
  forbiddenCompetingOwners: freezeList(config.forbiddenCompetingOwners),
  ...config,
});

export const CANONICAL_TOPIC_SUBJECTS = Object.freeze([
  'resources',
  'phonics-reading',
  'grammar-writing',
  'speaking-communication',
  'schools-research',
  'general-english',
]);

export const CANONICAL_TOPIC_OWNER_ROLES = Object.freeze([
  'gateway',
  'subject-hub',
  'editorial-library',
  'editorial-pillar',
  'skill-guide',
  'activity-guide',
  'diagnostic-owner',
  'practice-hub',
  'practice-category',
  'commercial-programme',
  'commercial-research',
  'commercial-comparison',
  'problem-landing',
  'support-hub',
  'conversion',
  'b2b-hub',
]);

/**
 * Brick 5 canonical topic ownership registry.
 *
 * One topic/intent key has exactly one ownerPath. Resources hubs are allowed to
 * orchestrate and link to owners, but cannot silently become alternate owners
 * for an existing informational, diagnostic, practice, or commercial intent.
 */
export const CANONICAL_TOPIC_OWNERSHIP = Object.freeze([
  topic('resources-gateway', {
    subject: 'resources',
    intent: 'informational',
    ownerPath: '/resources',
    ownerRole: 'gateway',
    hubPath: '/resources',
    queryIntent: 'Tiny Steps learning resources and where to start',
    supportingPaths: ['/blog', '/parents', '/free-english-games-for-kids', '/for-schools'],
  }),
  topic('all-english-guides', {
    subject: 'general-english',
    intent: 'informational',
    ownerPath: '/blog',
    ownerRole: 'editorial-library',
    hubPath: '/resources',
    queryIntent: 'Tiny Steps English learning guides',
    supportingPaths: ['/resources'],
  }),
  topic('parent-help-hub', {
    subject: 'general-english',
    intent: 'problem-aware',
    ownerPath: '/parents',
    ownerRole: 'support-hub',
    hubPath: '/resources',
    queryIntent: 'parent help for child English learning problems',
    supportingPaths: ['/resources'],
  }),
  topic('free-english-practice', {
    subject: 'general-english',
    intent: 'practice',
    ownerPath: '/free-english-games-for-kids',
    ownerRole: 'practice-hub',
    hubPath: '/resources',
    queryIntent: 'free English games for kids',
    supportingPaths: ['/resources'],
  }),
  topic('schools-phonics-partnership', {
    subject: 'schools-research',
    intent: 'commercial',
    ownerPath: '/for-schools',
    ownerRole: 'b2b-hub',
    hubPath: '/resources',
    queryIntent: 'systematic phonics programme for schools in India',
    supportingPaths: ['/resources'],
  }),
  topic('free-assessment-booking', {
    subject: 'general-english',
    intent: 'transactional-brand',
    ownerPath: '/book-demo',
    ownerRole: 'conversion',
    hubPath: null,
    queryIntent: 'book Tiny Steps free assessment',
    supportingPaths: ['/phonics', '/grammar', '/speaking', '/pricing'],
  }),

  topic('phonics-subject-discovery', {
    subject: 'phonics-reading',
    intent: 'informational',
    ownerPath: '/resources/phonics',
    ownerRole: 'subject-hub',
    hubPath: '/resources/phonics',
    queryIntent: 'Tiny Steps phonics and reading resources',
    supportingPaths: ['/resources', '/blog?topic=Phonics'],
  }),
  topic('live-phonics-classes', {
    subject: 'phonics-reading',
    intent: 'high-commercial',
    ownerPath: '/phonics',
    ownerRole: 'commercial-programme',
    hubPath: '/resources/phonics',
    queryIntent: 'online phonics classes for kids in India',
    supportingPaths: ['/resources/phonics', '/best-online-phonics-classes-for-kids-in-india'],
    forbiddenCompetingOwners: ['/resources/phonics'],
  }),
  topic('phonics-parent-guide', {
    subject: 'phonics-reading',
    intent: 'informational',
    ownerPath: '/blog/phonics-for-parents-guide',
    ownerRole: 'editorial-pillar',
    hubPath: '/resources/phonics',
    queryIntent: 'phonics for parents',
    supportingPaths: ['/resources/phonics'],
  }),
  topic('phonics-definition', {
    subject: 'phonics-reading',
    intent: 'informational',
    ownerPath: '/blog/what-is-phonics-for-kids',
    ownerRole: 'skill-guide',
    hubPath: '/resources/phonics',
    queryIntent: 'what is phonics for kids',
    supportingPaths: ['/resources/phonics'],
  }),
  topic('satpin-phonics', {
    subject: 'phonics-reading',
    intent: 'informational',
    ownerPath: '/blog/satpin-phonics-guide',
    ownerRole: 'editorial-pillar',
    hubPath: '/resources/phonics',
    queryIntent: 'SATPIN phonics guide',
    supportingPaths: ['/resources/phonics'],
  }),
  topic('phonics-blending-progression', {
    subject: 'phonics-reading',
    intent: 'progress-aware',
    ownerPath: '/blog/how-kids-learn-blending',
    ownerRole: 'skill-guide',
    hubPath: '/resources/phonics',
    queryIntent: 'how kids learn phonics blending',
    supportingPaths: ['/resources/phonics'],
  }),
  topic('phonics-blending-practice', {
    subject: 'phonics-reading',
    intent: 'practice',
    ownerPath: '/blog/phonics-blending-activities',
    ownerRole: 'activity-guide',
    hubPath: '/resources/phonics',
    queryIntent: 'phonics blending activities',
    supportingPaths: ['/resources/phonics', '/free-word-building-games-for-kids'],
  }),
  topic('cvc-words-explanation', {
    subject: 'phonics-reading',
    intent: 'informational',
    ownerPath: '/blog/cvc-words-explained-for-parents',
    ownerRole: 'skill-guide',
    hubPath: '/resources/phonics',
    queryIntent: 'CVC words explained for parents',
    supportingPaths: ['/resources/phonics'],
  }),
  topic('abc-known-reading-fails', {
    subject: 'phonics-reading',
    intent: 'problem-aware',
    ownerPath: '/blog/child-knows-abc-but-cannot-read',
    ownerRole: 'diagnostic-owner',
    hubPath: '/resources/phonics',
    queryIntent: 'child knows ABC but cannot read',
    supportingPaths: ['/resources/phonics', '/child-not-reading-properly'],
  }),
  topic('letter-sounds-known-word-reading-fails', {
    subject: 'phonics-reading',
    intent: 'problem-aware',
    ownerPath: '/blog/why-child-knows-letter-sounds-but-cannot-read-words',
    ownerRole: 'diagnostic-owner',
    hubPath: '/resources/phonics',
    queryIntent: 'child knows letter sounds but cannot read words',
    supportingPaths: ['/resources/phonics', '/child-not-reading-properly'],
  }),
  topic('reading-fluency-guide', {
    subject: 'phonics-reading',
    intent: 'problem-aware',
    ownerPath: '/blog/how-to-improve-reading-fluency-in-children',
    ownerRole: 'editorial-pillar',
    hubPath: '/resources/phonics',
    queryIntent: 'how to improve reading fluency in children',
    supportingPaths: ['/resources/phonics', '/slow-reader-child-help'],
  }),
  topic('reading-fluency-programme', {
    subject: 'phonics-reading',
    intent: 'commercial',
    ownerPath: '/reading-fluency-program',
    ownerRole: 'commercial-programme',
    hubPath: '/resources/phonics',
    queryIntent: 'reading fluency program for kids',
    supportingPaths: ['/resources/phonics', '/slow-reader-child-help'],
  }),
  topic('broad-child-reading-problem', {
    subject: 'phonics-reading',
    intent: 'problem-aware',
    ownerPath: '/child-not-reading-properly',
    ownerRole: 'problem-landing',
    hubPath: '/resources/phonics',
    queryIntent: 'child not reading properly',
    supportingPaths: ['/resources/phonics'],
  }),
  topic('slow-reader-help', {
    subject: 'phonics-reading',
    intent: 'problem-aware',
    ownerPath: '/slow-reader-child-help',
    ownerRole: 'problem-landing',
    hubPath: '/resources/phonics',
    queryIntent: 'slow reader child help',
    supportingPaths: ['/resources/phonics'],
  }),
  topic('phonics-fees-india', {
    subject: 'phonics-reading',
    intent: 'solution-aware',
    ownerPath: '/phonics-fees-india',
    ownerRole: 'commercial-research',
    hubPath: '/resources/phonics',
    queryIntent: 'phonics class fees in India',
    supportingPaths: ['/pricing', '/phonics'],
  }),
  topic('best-online-phonics-comparison', {
    subject: 'phonics-reading',
    intent: 'high-commercial',
    ownerPath: '/best-online-phonics-classes-for-kids-in-india',
    ownerRole: 'commercial-comparison',
    hubPath: '/resources/phonics',
    queryIntent: 'best online phonics classes for kids in India',
    supportingPaths: ['/phonics', '/resources/phonics'],
  }),
  topic('letter-sound-practice', {
    subject: 'phonics-reading',
    intent: 'practice',
    ownerPath: '/free-letter-sound-games-for-kids',
    ownerRole: 'practice-category',
    hubPath: '/resources/phonics',
    queryIntent: 'free letter sound games for kids',
    supportingPaths: ['/resources/phonics', '/free-english-games-for-kids'],
  }),
  topic('word-building-practice', {
    subject: 'phonics-reading',
    intent: 'practice',
    ownerPath: '/free-word-building-games-for-kids',
    ownerRole: 'practice-category',
    hubPath: '/resources/phonics',
    queryIntent: 'free word building games for kids',
    supportingPaths: ['/resources/phonics', '/free-english-games-for-kids'],
  }),
  topic('reading-practice', {
    subject: 'phonics-reading',
    intent: 'practice',
    ownerPath: '/free-reading-games-for-kids',
    ownerRole: 'practice-category',
    hubPath: '/resources/phonics',
    queryIntent: 'free reading games for kids',
    supportingPaths: ['/resources/phonics', '/free-english-games-for-kids'],
  }),

  topic('grammar-subject-discovery', {
    subject: 'grammar-writing',
    intent: 'informational',
    ownerPath: '/resources/grammar',
    ownerRole: 'subject-hub',
    hubPath: '/resources/grammar',
    queryIntent: 'Tiny Steps grammar and writing resources',
    supportingPaths: ['/resources', '/blog?topic=Grammar'],
  }),
  topic('live-grammar-classes', {
    subject: 'grammar-writing',
    intent: 'high-commercial',
    ownerPath: '/grammar',
    ownerRole: 'commercial-programme',
    hubPath: '/resources/grammar',
    queryIntent: 'grammar classes for kids in India',
    supportingPaths: ['/resources/grammar'],
    forbiddenCompetingOwners: ['/resources/grammar'],
  }),
  topic('writing-classes', {
    subject: 'grammar-writing',
    intent: 'commercial',
    ownerPath: '/writing-classes-for-kids',
    ownerRole: 'commercial-programme',
    hubPath: '/resources/grammar',
    queryIntent: 'writing classes for kids',
    supportingPaths: ['/resources/grammar', '/grammar'],
  }),
  topic('grammar-progression', {
    subject: 'grammar-writing',
    intent: 'progress-aware',
    ownerPath: '/blog/grammar-nouns-to-paragraphs',
    ownerRole: 'editorial-pillar',
    hubPath: '/resources/grammar',
    queryIntent: 'grammar progression from nouns to paragraphs',
    supportingPaths: ['/resources/grammar'],
  }),
  topic('sentence-formation', {
    subject: 'grammar-writing',
    intent: 'problem-aware',
    ownerPath: '/blog/how-to-improve-sentence-formation-in-kids',
    ownerRole: 'diagnostic-owner',
    hubPath: '/resources/grammar',
    queryIntent: 'how to improve sentence formation in kids',
    supportingPaths: ['/resources/grammar'],
  }),
  topic('grammar-transfer-mistakes', {
    subject: 'grammar-writing',
    intent: 'problem-aware',
    ownerPath: '/blog/child-knows-grammar-but-makes-mistakes',
    ownerRole: 'diagnostic-owner',
    hubPath: '/resources/grammar',
    queryIntent: 'child knows grammar but makes mistakes',
    supportingPaths: ['/resources/grammar'],
  }),
  topic('grammar-practice', {
    subject: 'grammar-writing',
    intent: 'practice',
    ownerPath: '/free-grammar-games-for-kids',
    ownerRole: 'practice-category',
    hubPath: '/resources/grammar',
    queryIntent: 'free grammar games for kids',
    supportingPaths: ['/resources/grammar', '/free-english-games-for-kids'],
  }),
  topic('sentence-building-practice', {
    subject: 'grammar-writing',
    intent: 'practice',
    ownerPath: '/free-sentence-building-games-for-kids',
    ownerRole: 'practice-category',
    hubPath: '/resources/grammar',
    queryIntent: 'free sentence building games for kids',
    supportingPaths: ['/resources/grammar', '/free-english-games-for-kids'],
  }),
  topic('grammar-focused-practice-game', {
    subject: 'grammar-writing',
    intent: 'practice',
    ownerPath: '/free-grammar-practice-game-for-kids',
    ownerRole: 'practice-category',
    hubPath: '/resources/grammar',
    queryIntent: 'free grammar practice game for kids',
    supportingPaths: ['/resources/grammar', '/free-grammar-games-for-kids'],
  }),

  topic('speaking-subject-discovery', {
    subject: 'speaking-communication',
    intent: 'informational',
    ownerPath: '/resources/speaking',
    ownerRole: 'subject-hub',
    hubPath: '/resources/speaking',
    queryIntent: 'Tiny Steps speaking and communication resources',
    supportingPaths: ['/resources', '/blog?topic=Speaking%20%26%20Communication'],
  }),
  topic('live-public-speaking-classes', {
    subject: 'speaking-communication',
    intent: 'high-commercial',
    ownerPath: '/speaking',
    ownerRole: 'commercial-programme',
    hubPath: '/resources/speaking',
    queryIntent: 'public speaking classes for kids in India',
    supportingPaths: ['/resources/speaking'],
    forbiddenCompetingOwners: ['/resources/speaking'],
  }),
  topic('spoken-english-classes', {
    subject: 'speaking-communication',
    intent: 'commercial',
    ownerPath: '/spoken-english-classes-for-kids-online',
    ownerRole: 'commercial-programme',
    hubPath: '/resources/speaking',
    queryIntent: 'spoken English classes for kids online',
    supportingPaths: ['/resources/speaking', '/speaking'],
  }),
  topic('speaking-confidence-progression', {
    subject: 'speaking-communication',
    intent: 'progress-aware',
    ownerPath: '/blog/speaking-confidence-seeds',
    ownerRole: 'editorial-pillar',
    hubPath: '/resources/speaking',
    queryIntent: 'speaking confidence progression for kids',
    supportingPaths: ['/resources/speaking'],
  }),
  topic('one-word-answers', {
    subject: 'speaking-communication',
    intent: 'problem-aware',
    ownerPath: '/blog/child-gives-one-word-answers',
    ownerRole: 'diagnostic-owner',
    hubPath: '/resources/speaking',
    queryIntent: 'child gives one word answers',
    supportingPaths: ['/resources/speaking'],
  }),
  topic('understands-english-does-not-speak', {
    subject: 'speaking-communication',
    intent: 'problem-aware',
    ownerPath: '/blog/child-understands-english-but-does-not-speak',
    ownerRole: 'diagnostic-owner',
    hubPath: '/resources/speaking',
    queryIntent: 'child understands English but does not speak',
    supportingPaths: ['/resources/speaking'],
  }),
  topic('shy-child-speaking-confidence', {
    subject: 'speaking-communication',
    intent: 'problem-aware',
    ownerPath: '/shy-child-speaking-confidence',
    ownerRole: 'problem-landing',
    hubPath: '/resources/speaking',
    queryIntent: 'shy child speaking confidence',
    supportingPaths: ['/resources/speaking'],
  }),
  topic('speaking-practice', {
    subject: 'speaking-communication',
    intent: 'practice',
    ownerPath: '/free-speaking-games-for-kids',
    ownerRole: 'practice-category',
    hubPath: '/resources/speaking',
    queryIntent: 'free speaking games for kids',
    supportingPaths: ['/resources/speaking', '/free-english-games-for-kids'],
  }),
  topic('speaking-focused-practice-game', {
    subject: 'speaking-communication',
    intent: 'practice',
    ownerPath: '/free-speaking-practice-game-for-kids',
    ownerRole: 'practice-category',
    hubPath: '/resources/speaking',
    queryIntent: 'free speaking practice game for kids',
    supportingPaths: ['/resources/speaking', '/free-speaking-games-for-kids'],
  }),
  topic('communication-confidence-programme', {
    subject: 'speaking-communication',
    intent: 'commercial',
    ownerPath: '/confidence-building-program-kids',
    ownerRole: 'commercial-programme',
    hubPath: '/resources/speaking',
    queryIntent: 'confidence building program for kids',
    supportingPaths: ['/resources/speaking', '/shy-child-speaking-confidence'],
  }),
]);

export const CANONICAL_TOPIC_OWNERS_BY_ID = Object.freeze(
  Object.fromEntries(CANONICAL_TOPIC_OWNERSHIP.map((entry) => [entry.id, entry])),
);

export function getCanonicalTopicOwner(topicId) {
  const entry = CANONICAL_TOPIC_OWNERS_BY_ID[topicId];
  if (!entry) throw new Error(`Unknown canonical topic ownership id: ${topicId}`);
  return entry;
}

export function getCanonicalTopicOwnerPath(topicId) {
  return getCanonicalTopicOwner(topicId).ownerPath;
}

export function getCanonicalTopicsForSubject(subject) {
  return CANONICAL_TOPIC_OWNERSHIP.filter((entry) => entry.subject === subject);
}
