const freeze = (value) => Object.freeze(value);

export const GRAMMAR_KNOWLEDGE_SOURCES = Object.freeze({
  'cambridge-grammar': freeze({
    id: 'cambridge-grammar',
    publisher: 'Cambridge Dictionary',
    title: 'English Grammar Today',
    url: 'https://dictionary.cambridge.org/grammar/british-grammar/',
    note: 'Broad grammar reference based on English Grammar Today and the Cambridge English Corpus.',
  }),
  'british-council-grammar': freeze({
    id: 'british-council-grammar',
    publisher: 'British Council LearnEnglish',
    title: 'English grammar reference',
    url: 'https://learnenglish.britishcouncil.org/free-resources/grammar/english-grammar-reference',
    note: 'Learner-focused grammar reference with explanations and examples.',
  }),
  'cambridge-nouns': freeze({
    id: 'cambridge-nouns',
    publisher: 'Cambridge Dictionary',
    title: 'Nouns',
    url: 'https://dictionary.cambridge.org/grammar/british-grammar/nouns-types-of-nouns',
    note: 'Reference for common, proper, concrete and abstract noun categories.',
  }),
  'cambridge-adjectives': freeze({
    id: 'cambridge-adjectives',
    publisher: 'Cambridge Dictionary',
    title: 'Adjectives',
    url: 'https://dictionary.cambridge.org/grammar/british-grammar/adjectives_2',
    note: 'Reference for adjective meanings and functions.',
  }),
  'cambridge-adjectives-adverbs': freeze({
    id: 'cambridge-adjectives-adverbs',
    publisher: 'Cambridge Dictionary',
    title: 'Adjectives and adverbs',
    url: 'https://dictionary.cambridge.org/grammar/british-grammar/adjectives-and-adverbs',
    note: 'Reference for distinguishing adjective and adverb functions.',
  }),
  'cambridge-prepositions': freeze({
    id: 'cambridge-prepositions',
    publisher: 'Cambridge Dictionary',
    title: 'Prepositions and particles',
    url: 'https://dictionary.cambridge.org/grammar/british-grammar/particles',
    note: 'Reference for relationships expressed by prepositions and particles.',
  }),
  'cambridge-determiners': freeze({
    id: 'cambridge-determiners',
    publisher: 'Cambridge Dictionary',
    title: 'Determiners',
    url: 'https://dictionary.cambridge.org/grammar/british-grammar/determiners-the-my-some-this',
    note: 'Reference covering articles, demonstratives, possessives and quantifiers.',
  }),
  'british-council-articles': freeze({
    id: 'british-council-articles',
    publisher: 'British Council LearnEnglish',
    title: "Articles: 'a', 'an', 'the'",
    url: 'https://learnenglish.britishcouncil.org/free-resources/grammar/a1-a2-grammar/articles-a-an-the',
    note: 'Learner reference for indefinite and definite article use.',
  }),
  'british-council-indefinite-article': freeze({
    id: 'british-council-indefinite-article',
    publisher: 'British Council LearnEnglish',
    title: "The indefinite article: 'a' and 'an'",
    url: 'https://learnenglish.britishcouncil.org/free-resources/grammar/english-grammar-reference/indefinite-article',
    note: 'Reference for a/an, including the sound-based choice between the two forms.',
  }),
  'cambridge-present-simple': freeze({
    id: 'cambridge-present-simple',
    publisher: 'Cambridge Dictionary',
    title: 'Present simple (I work)',
    url: 'https://dictionary.cambridge.org/grammar/british-grammar/present-simple',
    note: 'Reference for present-simple form and uses.',
  }),
  'british-council-present-continuous': freeze({
    id: 'british-council-present-continuous',
    publisher: 'British Council LearnEnglish',
    title: 'Present continuous',
    url: 'https://learnenglish.britishcouncil.org/free-resources/grammar/english-grammar-reference/present-continuous',
    note: 'Reference for present-continuous form, current activity and arrangements.',
  }),
  'cambridge-past-simple-continuous': freeze({
    id: 'cambridge-past-simple-continuous',
    publisher: 'Cambridge Dictionary',
    title: 'Past continuous or past simple?',
    url: 'https://dictionary.cambridge.org/grammar/british-grammar/past-continuous-or-past-simple',
    note: 'Reference for completed past events versus events in progress or background.',
  }),
  'british-council-present-perfect': freeze({
    id: 'british-council-present-perfect',
    publisher: 'British Council LearnEnglish',
    title: 'Present perfect',
    url: 'https://learnenglish.britishcouncil.org/free-resources/grammar/english-grammar-reference/present-perfect',
    note: 'Reference for present-perfect form, unfinished time and finished-time contrasts.',
  }),
  'cambridge-past-perfect': freeze({
    id: 'cambridge-past-perfect',
    publisher: 'Cambridge Dictionary',
    title: 'Past perfect simple or past perfect continuous?',
    url: 'https://dictionary.cambridge.org/grammar/british-grammar/past-perfect-continuous',
    note: 'Reference for past-perfect relationships and completion before another past point.',
  }),
  'british-council-modals': freeze({
    id: 'british-council-modals',
    publisher: 'British Council LearnEnglish',
    title: 'Modal verbs',
    url: 'https://learnenglish.britishcouncil.org/free-resources/grammar/english-grammar-reference/modal-verbs',
    note: 'Reference for ability, possibility, permission, advice, obligation and related modal meanings.',
  }),
  'british-council-clauses': freeze({
    id: 'british-council-clauses',
    publisher: 'British Council LearnEnglish',
    title: 'Clause structure and verb patterns',
    url: 'https://learnenglish.britishcouncil.org/free-resources/grammar/english-grammar-reference/clause-structure-verb-patterns',
    note: 'Reference for subject, verb phrase, objects, complements and clause structure.',
  }),
  'cambridge-questions': freeze({
    id: 'cambridge-questions',
    publisher: 'Cambridge Dictionary',
    title: 'Questions',
    url: 'https://dictionary.cambridge.org/grammar/british-grammar/questions',
    note: 'Reference for interrogative clause structure and question word order.',
  }),
  'cambridge-negation': freeze({
    id: 'cambridge-negation',
    publisher: 'Cambridge Dictionary',
    title: 'Negation',
    url: 'https://dictionary.cambridge.org/grammar/british-grammar/negation_2',
    note: 'Reference for not, negative auxiliaries and other forms of negation.',
  }),
  'british-council-quantifiers': freeze({
    id: 'british-council-quantifiers',
    publisher: 'British Council LearnEnglish',
    title: 'Determiners and quantifiers',
    url: 'https://learnenglish.britishcouncil.org/free-resources/grammar/english-grammar-reference/determiners-quantifiers',
    note: 'Reference for much, many, some, any, few, little and related quantifiers.',
  }),
  'cambridge-conjunctions': freeze({
    id: 'cambridge-conjunctions',
    publisher: 'Cambridge Dictionary',
    title: 'Conjunctions',
    url: 'https://dictionary.cambridge.org/grammar/british-grammar/conjunctions',
    note: 'Reference for coordinating and other linking conjunctions.',
  }),
  'british-council-conditionals': freeze({
    id: 'british-council-conditionals',
    publisher: 'British Council LearnEnglish',
    title: "Verbs in time clauses and 'if' clauses",
    url: 'https://learnenglish.britishcouncil.org/free-resources/grammar/english-grammar-reference/verbs-time-clauses-if-clauses',
    note: 'Reference for condition, hypothesis and verb choices in if/time clauses.',
  }),
  'british-council-relative-clauses': freeze({
    id: 'british-council-relative-clauses',
    publisher: 'British Council LearnEnglish',
    title: 'Relative pronouns and relative clauses',
    url: 'https://learnenglish.britishcouncil.org/free-resources/grammar/english-grammar-reference/relative-pronouns-relative-clauses',
    note: 'Reference for relative pronouns and defining/non-defining relative clauses.',
  }),
  'cambridge-reported-speech': freeze({
    id: 'cambridge-reported-speech',
    publisher: 'Cambridge Dictionary',
    title: 'Reported speech',
    url: 'https://dictionary.cambridge.org/grammar/british-grammar/reporting-clauses',
    note: 'Reference for direct and indirect speech, reporting clauses and reporting verbs.',
  }),
  'cambridge-passive': freeze({
    id: 'cambridge-passive',
    publisher: 'Cambridge Dictionary',
    title: 'Passive: forms',
    url: 'https://dictionary.cambridge.org/grammar/british-grammar/passive-forms',
    note: 'Reference for passive structures and when passive forms are available.',
  }),
  'british-council-future-forms': freeze({
    id: 'british-council-future-forms',
    publisher: 'British Council LearnEnglish',
    title: "Future forms: 'will', 'be going to' and present continuous",
    url: 'https://learnenglish.britishcouncil.org/free-resources/grammar/b1-b2/future-forms-will-be-going-present-continuous',
    note: 'Reference for choosing among common future forms according to meaning.',
  }),
  'cambridge-future': freeze({
    id: 'cambridge-future',
    publisher: 'Cambridge Dictionary',
    title: 'Future',
    url: 'https://dictionary.cambridge.org/grammar/british-grammar/future',
    note: 'Reference for the range of forms English uses to express future time.',
  }),
  'purdue-fragments': freeze({
    id: 'purdue-fragments',
    publisher: 'Purdue Online Writing Lab',
    title: 'Sentence Fragments',
    url: 'https://owl.purdue.edu/owl/general_writing/mechanics/sentence_fragments.html',
    note: 'Writing reference for identifying and repairing sentence fragments.',
  }),
  'purdue-runons': freeze({
    id: 'purdue-runons',
    publisher: 'Purdue Online Writing Lab',
    title: 'Run-ons, comma splices and fused sentences',
    url: 'https://owl.purdue.edu/owl/general_writing/punctuation/independent_and_dependent_clauses/runonsentences.html',
    note: 'Writing reference for independent-clause boundaries and run-on repair.',
  }),
  'purdue-sentence-clarity': freeze({
    id: 'purdue-sentence-clarity',
    publisher: 'Purdue Online Writing Lab',
    title: 'Sentence Clarity',
    url: 'https://owl.purdue.edu/owl/general_writing/mechanics/sentence_clarity.html',
    note: 'Writing reference for clarity, sentence structure and appropriate active/passive choices.',
  }),
  'cambridge-determiners-types-noun': freeze({
    id: 'cambridge-determiners-types-noun',
    publisher: 'Cambridge Dictionary',
    title: 'Determiners and types of noun',
    url: 'https://dictionary.cambridge.org/grammar/british-grammar/determiners-and-types-of-noun',
    note: 'Reference for how determiner choice changes with singular, plural, countable and uncountable nouns.',
  }),
  'cambridge-countable-uncountable': freeze({
    id: 'cambridge-countable-uncountable',
    publisher: 'Cambridge Dictionary',
    title: 'Nouns: countable and uncountable',
    url: 'https://dictionary.cambridge.org/grammar/british-grammar/nouns-countable-and-uncountable',
    note: 'Reference for countable and uncountable noun behaviour, quantity expressions and countable phrases for mass nouns.',
  }),
  'british-council-countable-uncountable': freeze({
    id: 'british-council-countable-uncountable',
    publisher: 'British Council LearnEnglish',
    title: 'Nouns: countable and uncountable',
    url: 'https://learnenglish.britishcouncil.org/free-resources/grammar/a1-a2/nouns-countable-uncountable',
    note: 'Learner-focused reference for a/an, some, any, much and many with countable and uncountable nouns.',
  }),
  'cambridge-noun-phrases-dependent': freeze({
    id: 'cambridge-noun-phrases-dependent',
    publisher: 'Cambridge Dictionary',
    title: 'Noun phrases: dependent words',
    url: 'https://dictionary.cambridge.org/grammar/british-grammar/noun-phrases-dependent-words',
    note: 'Reference for noun-phrase heads, determiners, premodifiers, complements and postmodifiers.',
  }),
  'cambridge-verb-forms': freeze({
    id: 'cambridge-verb-forms',
    publisher: 'Cambridge Dictionary',
    title: 'Verb forms',
    url: 'https://dictionary.cambridge.org/grammar/british-grammar/verb-forms',
    note: 'Reference for base, past, past participle, -ing and third-person singular forms of English verbs.',
  }),
  'british-council-irregular-verbs': freeze({
    id: 'british-council-irregular-verbs',
    publisher: 'British Council LearnEnglish',
    title: 'Irregular verbs',
    url: 'https://learnenglish.britishcouncil.org/free-resources/grammar/english-grammar-reference/irregular-verbs',
    note: 'Learner reference for common irregular past and past-participle forms alongside regular -ed patterns.',
  }),
  'cambridge-word-order-focus': freeze({
    id: 'cambridge-word-order-focus',
    publisher: 'Cambridge Dictionary',
    title: 'Word order and focus',
    url: 'https://dictionary.cambridge.org/grammar/british-grammar/word-order-and-focus_2',
    note: 'Reference for typical subject-verb-object order, alternative arrangements and how word order changes information focus.',
  }),
  'cambridge-common-mistakes': freeze({
    id: 'cambridge-common-mistakes',
    publisher: 'Cambridge Dictionary',
    title: 'Common mistakes in English',
    url: 'https://dictionary.cambridge.org/grammar/british-grammar/common-mistakes-in-english',
    note: 'Corpus-informed reference grouping frequent learner errors in countability, determiners, prepositions, spelling, word choice, order and patterns.',
  }),
});

export const getGrammarKnowledgeSources = (sourceIds = []) => Object.freeze(
  sourceIds
    .map((id) => GRAMMAR_KNOWLEDGE_SOURCES[id])
    .filter(Boolean),
);
