const freeze = (value) => Object.freeze(value);
const freezeList = (values = []) => Object.freeze([...values]);

const page = (config) => freeze({
  state: 'published',
  hubPath: '/resources/grammar',
  ...config,
  path: `/resources/grammar/${config.slug}`,
  examples: freezeList(config.examples),
  commonMistakes: freezeList(config.commonMistakes),
  practicePrompts: freezeList(config.practicePrompts),
  relatedPaths: freezeList(config.relatedPaths),
});

const existing = (config) => freeze({
  state: 'existing-owner',
  hubPath: '/resources/grammar',
  ...config,
});

export const GRAMMAR_PROGRAMMATIC_REVISION = '2026-09-27-gp1';

/**
 * Curriculum-aligned discovery sequence. This is a learning progression, not a
 * universal age timetable. Existing canonical owners remain owners where they
 * already cover an intent strongly; only uncovered concepts receive a focused
 * /resources/grammar/* page.
 */
export const GRAMMAR_PROGRAMMATIC_SEQUENCE = freezeList([
  page({
    order: 1,
    id: 'nouns',
    slug: 'nouns-for-kids',
    cardTitle: 'Nouns for Kids',
    seoTitle: 'Nouns for Kids: Meaning, Types & Examples | Tiny Steps',
    seoDescription: 'Learn what nouns are, how children can identify naming words in sentences, and how common and proper nouns support clear sentence building.',
    quickAnswer: 'A noun is a word used to name a person, place, animal, thing or idea. Children learn nouns best by finding the naming word inside a complete sentence, not by memorising a list.',
    concept: 'Nouns give a sentence the people, places, things and ideas it is about. Early grammar work should connect the label noun to a real sentence job: naming who or what the message concerns.',
    examples: ['Riya opened the window.', 'The puppy chased the ball.', 'Kindness can change a difficult moment.'],
    commonMistakes: ['Calling every object word a noun without checking its sentence job.', 'Confusing a noun with an adjective that describes it.', 'Identifying a noun in isolation but not using it in a complete sentence.'],
    practicePrompts: ['Underline the naming word in a fresh sentence.', 'Replace one noun with a different noun and explain how the meaning changes.', 'Write one sentence containing a person noun and one thing noun.'],
    relatedPaths: ['/blog/grammar-nouns-to-paragraphs', '/resources/grammar/proper-nouns-for-kids'],
  }),
  page({
    order: 2,
    id: 'proper-nouns',
    slug: 'proper-nouns-for-kids',
    cardTitle: 'Proper Nouns for Kids',
    seoTitle: 'Proper Nouns for Kids: Capitals, Names & Examples | Tiny Steps',
    seoDescription: 'Teach proper nouns as specific names that begin with capital letters, with clear contrasts between common and proper nouns.',
    quickAnswer: 'A proper noun names a specific person, place, organisation, day or other named entity and normally begins with a capital letter, such as Maya, Hyderabad or Monday.',
    concept: 'Proper nouns are a useful bridge between word classes and punctuation because the child must understand both naming and capitalisation. The goal is to distinguish a general category from one specific name.',
    examples: ['city → Hyderabad', 'girl → Ananya', 'day → Friday'],
    commonMistakes: ['Capitalising every noun instead of only specific names.', 'Forgetting capitals when the proper noun appears in the middle of a sentence.', 'Treating the first word of a sentence as a proper noun just because it has a capital.'],
    practicePrompts: ['Sort six words into common nouns and proper nouns.', 'Turn a common noun into a specific named example.', 'Correct the capitals in a sentence containing two proper nouns.'],
    relatedPaths: ['/resources/grammar/nouns-for-kids', '/blog/punctuation-and-capital-letters-for-kids'],
  }),
  page({
    order: 3,
    id: 'verbs',
    slug: 'verbs-for-kids',
    cardTitle: 'Verbs for Kids',
    seoTitle: 'Verbs for Kids: Action, Being & Helping Verbs | Tiny Steps',
    seoDescription: 'Learn how verbs carry action, state or helping meaning in sentences and prepare children for tense and subject-verb agreement.',
    quickAnswer: 'A verb is the part of a sentence that carries action, state or helping meaning. Finding the verb helps a child understand what is happening and prepares for later tense and agreement work.',
    concept: 'Children need to see verbs as sentence engines rather than only action words. Some verbs show actions, while others show states or help another verb form a complete verb phrase.',
    examples: ['The children laugh.', 'Aarav is tired.', 'She has finished the puzzle.'],
    commonMistakes: ['Believing every verb must show a visible action.', 'Missing helping verbs such as is, have or will.', 'Changing the verb form without checking the subject or time meaning.'],
    practicePrompts: ['Circle the complete verb phrase in a sentence.', 'Change a sentence from one time frame to another.', 'Replace a weak verb with a more precise verb while keeping the sentence meaning clear.'],
    relatedPaths: ['/resources/grammar/nouns-for-kids', '/blog/grammar-subject-verb'],
  }),
  page({
    order: 4,
    id: 'adjectives',
    slug: 'adjectives-for-kids',
    cardTitle: 'Adjectives for Kids',
    seoTitle: 'Adjectives for Kids: Describing Words & Examples | Tiny Steps',
    seoDescription: 'Teach adjectives as meaningful words that describe or identify nouns, with sentence-level examples and practice.',
    quickAnswer: 'An adjective gives useful information about a noun, such as what kind, which one or how many. Good adjective use adds precision rather than simply making a sentence longer.',
    concept: 'Adjectives support sentence expansion when they add information the reader needs. Children should learn to choose a relevant description and place it naturally around the noun it describes.',
    examples: ['The narrow bridge crossed the river.', 'Three curious students asked questions.', 'That blue folder belongs to Meera.'],
    commonMistakes: ['Adding many adjectives without improving meaning.', 'Confusing adjectives with adverbs.', 'Using an adjective that does not clearly describe a noun.'],
    practicePrompts: ['Add one precise adjective to a plain sentence.', 'Remove an unnecessary adjective and explain why the sentence is clearer.', 'Match each adjective to the noun it describes.'],
    relatedPaths: ['/resources/grammar/verbs-for-kids', '/resources/grammar/adverbs-for-kids'],
  }),
  page({
    order: 5,
    id: 'pronouns',
    slug: 'pronouns-for-kids',
    cardTitle: 'Pronouns for Kids',
    seoTitle: 'Pronouns for Kids: Clear Reference & Examples | Tiny Steps',
    seoDescription: 'Learn how pronouns replace or refer to nouns without creating confusing or repetitive sentences.',
    quickAnswer: 'A pronoun refers to a noun or noun phrase so a sentence does not repeat the same name unnecessarily. The reader should always be able to tell who or what the pronoun refers to.',
    concept: 'Pronouns improve flow only when their reference is clear. Early practice should combine correct form with a visible antecedent instead of teaching pronouns as a disconnected word list.',
    examples: ['Mina found the book. She returned it.', 'The boys packed their bags.', 'This is my pencil; that is yours.'],
    commonMistakes: ['Using a pronoun when two possible nouns could be its reference.', 'Mixing singular and plural reference.', 'Repeating the noun in every sentence instead of using a clear pronoun.'],
    practicePrompts: ['Replace repeated nouns with clear pronouns.', 'Find the noun each pronoun refers to.', 'Rewrite an ambiguous pronoun sentence so the meaning is obvious.'],
    relatedPaths: ['/resources/grammar/nouns-for-kids', '/resources/grammar/singular-and-plural-nouns'],
  }),
  page({
    order: 6,
    id: 'singular-plural',
    slug: 'singular-and-plural-nouns',
    cardTitle: 'Singular & Plural Nouns',
    seoTitle: 'Singular and Plural Nouns for Kids: Rules & Examples | Tiny Steps',
    seoDescription: 'Teach one-and-many noun forms, regular plural patterns and common irregular plurals without overgeneralising one rule.',
    quickAnswer: 'A singular noun refers to one; a plural noun normally refers to more than one. Many plurals use -s or -es, but children also need common irregular forms such as children, feet and mice.',
    concept: 'Plural learning combines meaning and word form. The child should first identify whether the message means one or more than one, then choose the form that matches.',
    examples: ['book → books', 'box → boxes', 'child → children'],
    commonMistakes: ['Adding -s to every noun, including irregular plurals.', 'Changing the noun to plural while leaving the rest of the sentence singular.', 'Confusing possessive apostrophes with plural endings.'],
    practicePrompts: ['Change a singular sentence into a plural sentence.', 'Sort regular and irregular plural examples.', 'Correct a sentence where the noun and verb do not agree in number.'],
    relatedPaths: ['/resources/grammar/pronouns-for-kids', '/blog/grammar-subject-verb'],
  }),
  page({
    order: 7,
    id: 'articles-a-an',
    slug: 'a-an-articles-for-kids',
    cardTitle: 'Articles: a & an',
    seoTitle: 'A or An for Kids: Article Rules, Sounds & Examples | Tiny Steps',
    seoDescription: 'Teach a and an through the sound that begins the next word, with clear examples and common exceptions.',
    quickAnswer: 'Use a before a consonant sound and an before a vowel sound. The choice depends on pronunciation, not simply the first written letter.',
    concept: 'The useful rule is sound-based: a university begins with a /y/ sound, while an hour begins with a vowel sound. Children should say the phrase aloud and listen to the opening sound.',
    examples: ['a dog', 'an apple', 'a university / an hour'],
    commonMistakes: ['Choosing only from the first written letter.', 'Using a or an with plural nouns.', 'Adding an article where no singular countable noun is intended.'],
    practicePrompts: ['Choose a or an and explain the opening sound.', 'Find one apparent exception and say it aloud.', 'Write three noun phrases using a/an correctly.'],
    relatedPaths: ['/resources/grammar/singular-and-plural-nouns', '/resources/grammar/the-article-for-kids'],
  }),
  page({
    order: 8,
    id: 'article-the',
    slug: 'the-article-for-kids',
    cardTitle: 'The Article “the”',
    seoTitle: 'The Article for Kids: When to Use “the” | Tiny Steps',
    seoDescription: 'Explain when children use the for a specific or already-known noun and when an article may not be needed.',
    quickAnswer: 'Use the when the speaker and listener can identify the specific person, place or thing being referred to, or when context makes that reference clear.',
    concept: 'The is about shared identification, not simply importance. Children learn it more reliably when they compare a first general mention with a later specific reference.',
    examples: ['I saw a dog. The dog followed me.', 'Please close the door.', 'The sun was bright.'],
    commonMistakes: ['Using the before every noun.', 'Leaving out the when a specific shared noun is intended.', 'Treating a/an and the as interchangeable.'],
    practicePrompts: ['Compare a first mention with a second mention.', 'Choose whether a/an, the or no article fits a short context.', 'Explain what makes a noun specific in a sentence.'],
    relatedPaths: ['/resources/grammar/a-an-articles-for-kids', '/resources/grammar/prepositions-for-kids'],
  }),
  page({
    order: 9,
    id: 'prepositions',
    slug: 'prepositions-for-kids',
    cardTitle: 'Prepositions for Kids',
    seoTitle: 'Prepositions for Kids: Place, Time & Movement Examples | Tiny Steps',
    seoDescription: 'Learn prepositions of place, time and movement through sentence relationships rather than memorised word lists.',
    quickAnswer: 'A preposition helps show a relationship such as place, time, position or movement: in the box, after lunch, under the table, toward the gate.',
    concept: 'Prepositions become meaningful when a child can identify the relationship between two parts of a sentence. Visual and movement examples work well, but the final check should be a fresh sentence.',
    examples: ['The keys are under the notebook.', 'We will meet after lunch.', 'The puppy ran toward the gate.'],
    commonMistakes: ['Choosing a preposition from habit without checking meaning.', 'Memorising lists but struggling to use the word in a sentence.', 'Confusing a preposition with an adverb when there is no object or relationship stated.'],
    practicePrompts: ['Describe an object location using two different prepositions.', 'Choose a preposition that changes the sentence meaning.', 'Write one place, one time and one movement example.'],
    relatedPaths: ['/resources/grammar/the-article-for-kids', '/blog/grammar-conjunctions'],
  }),
  existing({
    order: 10,
    id: 'punctuation',
    label: 'Capital Letters & Punctuation',
    path: '/blog/punctuation-and-capital-letters-for-kids',
    reason: 'Existing substantial canonical owner.',
  }),
  existing({
    order: 11,
    id: 'sentence-formation',
    label: 'Simple Sentences & Sentence Formation',
    path: '/blog/how-to-improve-sentence-formation-in-kids',
    reason: 'Existing diagnostic and instructional owner.',
  }),
  existing({
    order: 12,
    id: 'conjunctions',
    label: 'Conjunctions',
    path: '/blog/grammar-conjunctions',
    reason: 'Existing page-one canonical owner.',
  }),
  page({
    order: 13,
    id: 'adverbs',
    slug: 'adverbs-for-kids',
    cardTitle: 'Adverbs for Kids',
    seoTitle: 'Adverbs for Kids: How, When & Where Examples | Tiny Steps',
    seoDescription: 'Teach adverbs as words that add useful information about how, when or where an action happens.',
    quickAnswer: 'An adverb can add information about how, when, where or to what degree something happens. Many adverbs end in -ly, but not all adverbs do.',
    concept: 'Adverbs help children add precise detail to a verb, adjective or another adverb. The sentence should become more informative, not merely longer.',
    examples: ['She answered calmly.', 'We arrived yesterday.', 'The children waited outside.'],
    commonMistakes: ['Assuming every -ly word is an adverb.', 'Confusing an adjective that describes a noun with an adverb that modifies a verb.', 'Adding unnecessary adverbs to already precise verbs.'],
    practicePrompts: ['Add a how adverb to one sentence.', 'Replace a vague adverb-plus-verb combination with a stronger verb.', 'Sort examples into how, when and where.'],
    relatedPaths: ['/resources/grammar/adjectives-for-kids', '/blog/grammar-conjunctions'],
  }),
  existing({
    order: 14,
    id: 'subject-verb-agreement',
    label: 'Subject–Verb Agreement',
    path: '/blog/grammar-subject-verb',
    reason: 'Existing canonical owner with search visibility.',
  }),
  existing({
    order: 15,
    id: 'tenses-overview',
    label: 'English Tenses Overview',
    path: '/blog/grammar-tenses',
    reason: 'Existing canonical overview owner.',
  }),
  page({
    order: 16,
    id: 'simple-present',
    slug: 'simple-present-tense-for-kids',
    cardTitle: 'Simple Present Tense',
    seoTitle: 'Simple Present Tense for Kids: Rules & Examples | Tiny Steps',
    seoDescription: 'Teach simple present for routines, repeated actions, facts and stable states, including third-person singular agreement.',
    quickAnswer: 'Use the simple present for routines, repeated actions, facts and generally true states. It is not the default tense for an action happening right now.',
    concept: 'Children need both meaning and form: I/you/we/they use the base form in common patterns, while he/she/it commonly takes -s or -es in affirmative statements.',
    examples: ['I read every evening.', 'Maya walks to school.', 'Plants need water.'],
    commonMistakes: ['Using simple present for every present-time action.', 'Omitting third-person -s/-es.', 'Using does with a main verb that still carries -s.'],
    practicePrompts: ['Write one routine and one fact.', 'Change I play to she plays.', 'Contrast a routine sentence with an action happening now.'],
    relatedPaths: ['/blog/grammar-tenses', '/resources/grammar/simple-past-tense-for-kids'],
  }),
  page({
    order: 17,
    id: 'simple-past',
    slug: 'simple-past-tense-for-kids',
    cardTitle: 'Simple Past Tense',
    seoTitle: 'Simple Past Tense for Kids: Regular, Irregular & Examples | Tiny Steps',
    seoDescription: 'Teach simple past for completed past events with regular and irregular verb forms and correct did/did not patterns.',
    quickAnswer: 'Use the simple past for an event or state understood as completed in the past. Some verbs use -ed; many high-frequency verbs have irregular past forms.',
    concept: 'Past meaning comes first. Children then choose the required past form, while questions and negatives with did return the main verb to its base form.',
    examples: ['We visited the museum yesterday.', 'She went home early.', 'Did he finish the book?'],
    commonMistakes: ['Adding -ed to every verb.', 'Using did plus a past-form verb.', 'Switching back to present tense inside a past-event sequence.'],
    practicePrompts: ['Retell three completed events in order.', 'Correct a did + past-form error.', 'Sort regular and irregular past verbs.'],
    relatedPaths: ['/resources/grammar/simple-present-tense-for-kids', '/resources/grammar/simple-future-tense-for-kids'],
  }),
  page({
    order: 18,
    id: 'simple-future',
    slug: 'simple-future-tense-for-kids',
    cardTitle: 'Simple Future with “will”',
    seoTitle: 'Simple Future Tense for Kids: Will + Verb Examples | Tiny Steps',
    seoDescription: 'Teach the beginner future pattern will + base verb and distinguish it from the wider system of future forms.',
    quickAnswer: 'A useful beginner future form is will + base verb, for example “I will call you.” English also uses other forms for plans, arrangements and schedules, so will should not be taught as the only way to talk about the future.',
    concept: 'At beginner level, will provides a clear future pattern. At advanced level, children should choose among will, going to, present continuous and simple present according to meaning.',
    examples: ['I will help you.', 'They will arrive tomorrow.', 'Will she join us?'],
    commonMistakes: ['Changing the main verb after will.', 'Using will for every future context.', 'Omitting will in a future form the child is trying to construct.'],
    practicePrompts: ['Build three will + base verb sentences.', 'Turn one statement into a question and negative.', 'Compare a prediction with a planned arrangement.'],
    relatedPaths: ['/resources/grammar/simple-past-tense-for-kids', '/blog/grammar-tenses'],
  }),
  page({
    order: 19,
    id: 'modal-verbs',
    slug: 'modal-verbs-for-kids',
    cardTitle: 'Modal Verbs for Kids',
    seoTitle: 'Modal Verbs for Kids: Can, Could, Should, Must & More | Tiny Steps',
    seoDescription: 'Teach common modal verbs by meaning: ability, possibility, advice, permission and obligation.',
    quickAnswer: 'Modal verbs such as can, could, may, might, should and must help express meanings like ability, possibility, permission, advice and obligation. A modal is normally followed by the base form of the main verb.',
    concept: 'The important skill is choosing the modal that matches the intended strength and meaning, not memorising a list. Children should compare close choices such as should versus must.',
    examples: ['You should check your work.', 'She can swim.', 'It might rain later.'],
    commonMistakes: ['Adding -s or -ed to the verb after a modal.', 'Treating should and must as equal in strength.', 'Using can for every type of permission or possibility without considering context.'],
    practicePrompts: ['Choose a modal for advice, ability and possibility.', 'Rewrite one sentence to make the obligation stronger or weaker.', 'Explain why two modal choices change the meaning.'],
    relatedPaths: ['/resources/grammar/simple-future-tense-for-kids', '/resources/grammar/independent-and-dependent-clauses'],
  }),
  page({
    order: 20,
    id: 'clauses',
    slug: 'independent-and-dependent-clauses',
    cardTitle: 'Independent & Dependent Clauses',
    seoTitle: 'Independent and Dependent Clauses for Kids | Tiny Steps',
    seoDescription: 'Help children distinguish complete independent clauses from dependent clauses and combine them into clear sentences.',
    quickAnswer: 'An independent clause can stand as a complete sentence; a dependent clause cannot stand alone because it leaves the meaning unfinished and needs an independent clause.',
    concept: 'Clause awareness helps children move beyond short sentences without creating fragments or run-ons. The goal is to recognise completeness and then combine ideas according to meaning.',
    examples: ['We stayed inside. / because it was raining', 'Although Maya was tired, she finished the project.', 'I called him when I reached home.'],
    commonMistakes: ['Writing a dependent clause as a complete sentence.', 'Joining two independent clauses without suitable punctuation or a connector.', 'Confusing a phrase with a clause that contains a subject-verb relationship.'],
    practicePrompts: ['Label each clause independent or dependent.', 'Complete a dependent clause with a clear main clause.', 'Combine two ideas using because, although, when or if.'],
    relatedPaths: ['/blog/grammar-conjunctions', '/blog/how-to-teach-paragraph-writing-to-kids'],
  }),
  existing({
    order: 21,
    id: 'paragraph-writing',
    label: 'Paragraph Writing',
    path: '/blog/how-to-teach-paragraph-writing-to-kids',
    reason: 'Existing substantial canonical owner.',
  }),
  page({
    order: 22,
    id: 'present-simple-vs-continuous',
    slug: 'simple-present-vs-present-continuous-for-kids',
    cardTitle: 'Simple Present vs Present Continuous',
    seoTitle: 'Simple Present vs Present Continuous for Kids | Tiny Steps',
    seoDescription: 'Help children choose between routines and facts in the simple present and actions happening around now in the present continuous.',
    quickAnswer: 'Use the simple present for routines, repeated actions, facts and stable states. Use the present continuous for an action happening now or around the current time when the context calls for an ongoing action.',
    concept: 'The useful contrast is meaning before form: routine or fact versus action in progress. Children then match the meaning to the simple-present verb form or am/is/are + -ing.',
    examples: ['Maya walks to school every day. / Maya is walking to school now.', 'I read before bed. / I am reading a mystery today.', 'The shop opens at nine. / The assistant is opening the shop now.'],
    commonMistakes: ['Using the continuous for routines simply because the action is happening in the present period.', 'Leaving out am/is/are before the -ing form.', 'Forgetting third-person -s in the simple present.'],
    practicePrompts: ['Choose the tense from a routine-versus-now context.', 'Rewrite a routine as an action happening now.', 'Explain the time meaning that justifies each tense choice.'],
    relatedPaths: ['/resources/grammar/simple-present-tense-for-kids', '/blog/grammar-tenses'],
  }),
  page({
    order: 23,
    id: 'past-simple-vs-continuous',
    slug: 'simple-past-vs-past-continuous-for-kids',
    cardTitle: 'Simple Past vs Past Continuous',
    seoTitle: 'Simple Past vs Past Continuous for Kids | Tiny Steps',
    seoDescription: 'Teach completed past events versus actions that were in progress, including when and while patterns.',
    quickAnswer: 'Use the simple past for completed past events. Use the past continuous for an action that was in progress at a past time, often to give background or show an interrupted action.',
    concept: 'Children need to see how the two forms work together in a timeline. The continuous form sets an ongoing background; the simple past often names the completed event that happened during it.',
    examples: ['I was reading when the phone rang.', 'They played football after school.', 'While we were waiting, the rain started.'],
    commonMistakes: ['Using was/were with a past-form verb instead of an -ing form.', 'Using past continuous for every action in a past story.', 'Confusing when and while without checking which event is ongoing.'],
    practicePrompts: ['Mark the background action and the completed event.', 'Combine two past events using when or while.', 'Correct one sentence with the wrong past-time form.'],
    relatedPaths: ['/resources/grammar/simple-past-tense-for-kids', '/blog/grammar-tenses'],
  }),
  page({
    order: 24,
    id: 'future-forms',
    slug: 'future-forms-for-kids',
    cardTitle: 'Future Forms: will, going to & arrangements',
    seoTitle: 'Future Forms for Kids: Will, Going To & Present Continuous | Tiny Steps',
    seoDescription: 'Compare common English future forms for decisions, predictions, plans, arrangements and schedules.',
    quickAnswer: 'English uses several future forms. Will often expresses decisions or predictions, going to commonly expresses plans or evidence-based predictions, present continuous can show arrangements, and simple present can show fixed schedules.',
    concept: 'Advanced future control comes from choosing a form for the intended meaning, not from treating will as a universal future tense. Children should compare the speaker’s intention, evidence and degree of arrangement.',
    examples: ['I will answer the door.', 'We are going to visit Jaipur.', 'I am meeting my coach at five.'],
    commonMistakes: ['Using will for every future sentence.', 'Using going to without the correct form of be.', 'Confusing a personal arrangement with a fixed timetable.'],
    practicePrompts: ['Choose a form for a decision, plan and arrangement.', 'Explain why two future forms create different meanings.', 'Rewrite one future sentence using a different context and form.'],
    relatedPaths: ['/resources/grammar/simple-future-tense-for-kids', '/blog/grammar-tenses'],
  }),
  page({
    order: 25,
    id: 'present-perfect-vs-past',
    slug: 'present-perfect-vs-simple-past-for-kids',
    cardTitle: 'Present Perfect vs Simple Past',
    seoTitle: 'Present Perfect vs Simple Past for Kids | Tiny Steps',
    seoDescription: 'Compare life experience and present relevance with finished past events and finished-time expressions.',
    quickAnswer: 'Use the simple past for a finished event tied to a finished past time. Use the present perfect when the past experience or result connects to the present and no finished past time is the focus.',
    concept: 'The key contrast is not merely verb form; it is how the speaker frames time. Finished-time words such as yesterday normally point to simple past, while experience or recent-result meanings often support present perfect.',
    examples: ['I visited Delhi last year. / I have visited Delhi three times.', 'She finished the report yesterday. / She has just finished the report.', 'Did you see the film on Friday? / Have you ever seen the film?'],
    commonMistakes: ['Using present perfect with a finished-time phrase such as yesterday.', 'Using the simple past when the intended meaning is life experience with no finished time.', 'Using the past form instead of the past participle after have/has.'],
    practicePrompts: ['Sort sentences by finished past versus present connection.', 'Add an appropriate time expression to each tense.', 'Explain the meaning difference between a matched pair.'],
    relatedPaths: ['/resources/grammar/simple-past-tense-for-kids', '/blog/grammar-tenses'],
  }),
  page({
    order: 26,
    id: 'past-perfect',
    slug: 'past-perfect-tense-for-kids',
    cardTitle: 'Past Perfect Tense',
    seoTitle: 'Past Perfect Tense for Kids: Had + Past Participle | Tiny Steps',
    seoDescription: 'Teach past perfect for showing an earlier event before another past reference point without overusing the form.',
    quickAnswer: 'Use the past perfect, had + past participle, when you need to make clear that one past event happened before another past event or reference point.',
    concept: 'Past perfect is an event-order tool. Children should first establish the two past moments, decide which event happened earlier, and use past perfect only when that earlier-before-later relationship needs to be made explicit.',
    examples: ['The train had left before we reached the station.', 'She had finished dinner when I called.', 'After they had packed, they checked the tickets.'],
    commonMistakes: ['Using past perfect for every verb in a past story.', 'Using had + simple-past form instead of a past participle.', 'Using past perfect when the event order is already clear and the extra form adds no value.'],
    practicePrompts: ['Put two events in order and identify the earlier one.', 'Combine two past events using past perfect once.', 'Remove unnecessary past-perfect forms from an overcorrected paragraph.'],
    relatedPaths: ['/resources/grammar/simple-past-tense-for-kids', '/resources/grammar/present-perfect-vs-simple-past-for-kids'],
  }),
  page({
    order: 27,
    id: 'questions',
    slug: 'forming-questions-in-english-for-kids',
    cardTitle: 'Forming Questions Naturally',
    seoTitle: 'How to Form Questions in English for Kids | Tiny Steps',
    seoDescription: 'Teach yes/no and wh- questions with correct auxiliaries and natural English word order.',
    quickAnswer: 'English questions often need an auxiliary before the subject: Do you play? Is she reading? Has he finished? Wh- questions add a question word before the appropriate auxiliary pattern.',
    concept: 'Question formation depends on the tense and verb system already in the sentence. Children should identify the time and verb phrase first, then choose the correct auxiliary and move it into question position.',
    examples: ['You play chess. → Do you play chess?', 'She is reading. → What is she reading?', 'They finished. → When did they finish?'],
    commonMistakes: ['Keeping statement word order in a question.', 'Using did with a past-form main verb.', 'Choosing a question word that does not match the missing information.'],
    practicePrompts: ['Turn three statements into questions.', 'Choose the right auxiliary for three different tenses.', 'Write one yes/no and one wh- question about the same event.'],
    relatedPaths: ['/resources/grammar/simple-present-tense-for-kids', '/resources/grammar/negative-sentences-and-short-answers'],
  }),
  page({
    order: 28,
    id: 'negatives-short-answers',
    slug: 'negative-sentences-and-short-answers',
    cardTitle: 'Negative Sentences & Short Answers',
    seoTitle: 'Negative Sentences and Short Answers for Kids | Tiny Steps',
    seoDescription: 'Teach accurate negatives, contractions and short answers by matching the correct auxiliary to the tense.',
    quickAnswer: 'Negative sentences and short answers reuse the auxiliary system of the tense: do/does/did, be, have or a modal. The main verb normally returns to its base form after do/does/did.',
    concept: 'Instead of memorising isolated negative patterns, children should identify the helping verb or auxiliary that carries tense and agreement, then build the negative or short answer around it.',
    examples: ['She does not like olives. / No, she does not.', 'They were not waiting. / No, they were not.', 'Can he swim? / Yes, he can.'],
    commonMistakes: ['Using does not with a main verb that still has -s.', 'Answering a yes/no question with the wrong auxiliary.', 'Mixing contraction forms with incorrect verb forms.'],
    practicePrompts: ['Turn three affirmative sentences into negatives.', 'Answer three questions with accurate short answers.', 'Correct an auxiliary-main-verb mismatch.'],
    relatedPaths: ['/resources/grammar/forming-questions-in-english-for-kids', '/resources/grammar/modal-verbs-for-kids'],
  }),
  page({
    order: 29,
    id: 'quantifiers',
    slug: 'quantifiers-for-kids',
    cardTitle: 'Quantifiers: much, many, some, any & more',
    seoTitle: 'Quantifiers for Kids: Much, Many, Some, Any, Few & Little | Tiny Steps',
    seoDescription: 'Teach quantity expressions by connecting them to countable and uncountable nouns and sentence meaning.',
    quickAnswer: 'Quantifiers express amount or number. Choices such as much/many, a few/a little and some/any depend on whether the noun is countable, the sentence pattern and the meaning the speaker intends.',
    concept: 'Quantity grammar starts with the noun: can it normally be counted as separate units in this meaning? Once that is clear, children can select a quantifier and notice how small changes such as few versus a few change the message.',
    examples: ['many books / much water', 'a few questions / a little time', 'Do you have any pencils? / I have some pencils.'],
    commonMistakes: ['Using much with plural countable nouns.', 'Treating few and a few as identical in meaning.', 'Applying a simple some-in-positive/any-in-negative rule to every context.'],
    practicePrompts: ['Sort nouns into countable and uncountable uses.', 'Choose a quantifier and explain the noun clue.', 'Compare few/a few and little/a little in context.'],
    relatedPaths: ['/resources/grammar/singular-and-plural-nouns', '/resources/grammar/pronouns-for-kids'],
  }),
  page({
    order: 30,
    id: 'compound-sentences',
    slug: 'compound-sentences-for-kids',
    cardTitle: 'Compound Sentences',
    seoTitle: 'Compound Sentences for Kids: Joining Complete Ideas | Tiny Steps',
    seoDescription: 'Teach children to join related independent clauses with suitable coordinating conjunctions and punctuation.',
    quickAnswer: 'A compound sentence joins two related independent clauses. Each clause could stand alone, and a coordinating conjunction such as and, but or so can show the relationship between them.',
    concept: 'The key skill is recognising two complete ideas before joining them. This prevents fragments, run-ons and mechanical connector use while helping children vary sentence structure.',
    examples: ['I wanted to go outside, but it started raining.', 'Mina finished her work, so she read a book.', 'The bell rang, and the students packed their bags.'],
    commonMistakes: ['Joining fragments as if both sides were complete clauses.', 'Creating a run-on by placing two clauses together without punctuation or a connector.', 'Choosing a conjunction that does not match the meaning relationship.'],
    practicePrompts: ['Check whether both halves can stand alone.', 'Join two related clauses with an appropriate conjunction.', 'Split a run-on into two sentences or one correct compound sentence.'],
    relatedPaths: ['/blog/grammar-conjunctions', '/resources/grammar/independent-and-dependent-clauses'],
  }),
  page({
    order: 31,
    id: 'reason-result',
    slug: 'reason-and-result-connectors-for-kids',
    cardTitle: 'Reason & Result Connectors',
    seoTitle: 'Reason and Result Connectors for Kids: Because, So & Therefore | Tiny Steps',
    seoDescription: 'Teach children to distinguish causes from results and connect them with because, so, therefore and related expressions.',
    quickAnswer: 'Reason connectors explain why something happens; result connectors explain what happens because of it. Because commonly introduces a reason, while so and therefore commonly introduce a result.',
    concept: 'Children should first label the cause and the outcome, then choose a connector that matches the direction of the relationship. This supports both sentence accuracy and logical explanation.',
    examples: ['We stayed inside because it was raining.', 'It was raining, so we stayed inside.', 'The road was closed; therefore, the bus was delayed.'],
    commonMistakes: ['Using because and so redundantly in the same simple cause-result structure.', 'Reversing which idea is the reason and which is the result.', 'Using formal connectors without appropriate punctuation.'],
    practicePrompts: ['Label the reason and result in three pairs.', 'Rewrite because sentences using so.', 'Choose a connector that best matches the level of formality.'],
    relatedPaths: ['/blog/grammar-conjunctions', '/resources/grammar/compound-sentences-for-kids'],
  }),
  page({
    order: 32,
    id: 'time-sequence',
    slug: 'time-and-sequence-connectors-for-kids',
    cardTitle: 'Time & Sequence Connectors',
    seoTitle: 'Time and Sequence Connectors for Kids | Before, After, When, While | Tiny Steps',
    seoDescription: 'Teach children to order events clearly with before, after, when, while, first, next and other sequence language.',
    quickAnswer: 'Time and sequence connectors show when events happen and how they relate in order. Words such as before, after, when and while link clauses, while first, next and finally help organise a sequence.',
    concept: 'Good sequencing combines logical event order with accurate tense. Children should be able to retell the same events from more than one starting point without accidentally reversing what happened first.',
    examples: ['After we ate, we went for a walk.', 'While I was reading, the lights went out.', 'First gather the materials; next, follow the instructions.'],
    commonMistakes: ['Confusing before and after and reversing event order.', 'Using while with two completed point events when an ongoing background is intended.', 'Listing sequence words without maintaining tense consistency.'],
    practicePrompts: ['Put four events in logical order.', 'Combine two events with before or after.', 'Retell a sequence using a different opening connector.'],
    relatedPaths: ['/resources/grammar/simple-past-vs-past-continuous-for-kids', '/resources/grammar/reason-and-result-connectors-for-kids'],
  }),
  page({
    order: 33,
    id: 'conditionals',
    slug: 'conditionals-for-kids',
    cardTitle: 'Conditions & Possibilities',
    seoTitle: 'Conditionals for Kids: If, Unless & Possibility Sentences | Tiny Steps',
    seoDescription: 'Introduce condition-result relationships with if and unless and distinguish real from imagined possibilities.',
    quickAnswer: 'Conditional sentences connect a condition with a result. If introduces a condition directly; unless often means “if not.” The verb forms change according to whether the situation is general, realistically possible or imagined.',
    concept: 'The important idea is the relationship between condition and consequence. Children can begin with real, clear conditions before comparing hypothetical patterns and the effect of unless.',
    examples: ['If it rains, we will stay inside.', 'Unless you hurry, you will miss the bus.', 'If I had more time, I would learn another language.'],
    commonMistakes: ['Adding will inside a basic if-clause when standard first-conditional form does not require it.', 'Treating unless as a direct synonym for if rather than if not.', 'Mixing real and hypothetical verb patterns.'],
    practicePrompts: ['Match three conditions to logical results.', 'Rewrite an if-not sentence with unless.', 'Sort examples into real and imagined possibilities.'],
    relatedPaths: ['/resources/grammar/modal-verbs-for-kids', '/resources/grammar/contrast-and-concession-for-kids'],
  }),
  page({
    order: 34,
    id: 'contrast-concession',
    slug: 'contrast-and-concession-for-kids',
    cardTitle: 'Contrast & Concession',
    seoTitle: 'Contrast and Concession for Kids: But, Although, However & Despite | Tiny Steps',
    seoDescription: 'Teach children to connect contrasting ideas accurately with but, although, however and despite.',
    quickAnswer: 'Contrast shows a difference between ideas; concession recognises an unexpected contrast. But joins clauses, although introduces a clause, however links sentences or clauses with suitable punctuation, and despite is followed by a noun phrase or -ing form.',
    concept: 'These connectors are not interchangeable. Children should learn the grammatical shape that follows each connector as well as the relationship it expresses.',
    examples: ['I was tired, but I finished the work.', 'Although I was tired, I finished the work.', 'Despite being tired, I finished the work.'],
    commonMistakes: ['Using although and but together in the same basic structure.', 'Following despite with a full finite clause without the required structure.', 'Using however without sentence-appropriate punctuation.'],
    practicePrompts: ['Rewrite one contrast using but, although and despite.', 'Choose the connector that fits the following grammatical structure.', 'Punctuate a sentence containing however.'],
    relatedPaths: ['/blog/grammar-conjunctions', '/resources/grammar/conditionals-for-kids'],
  }),
  page({
    order: 35,
    id: 'relative-clauses',
    slug: 'relative-clauses-for-kids',
    cardTitle: 'Relative Clauses',
    seoTitle: 'Relative Clauses for Kids: Who, Which & That | Tiny Steps',
    seoDescription: 'Teach relative clauses as a way to add information about a noun with who, which, that and related forms.',
    quickAnswer: 'A relative clause adds information about a noun. Who commonly refers to people, which to things, and that can be used in many defining clauses; punctuation depends on whether the information is essential to identifying the noun.',
    concept: 'Relative clauses help combine sentences without repeating the noun. Children should first identify the noun being described, then choose an appropriate relative word and decide whether the information is defining or extra.',
    examples: ['The girl who won the race is my cousin.', 'I found the book that you recommended.', 'My bicycle, which is ten years old, still works well.'],
    commonMistakes: ['Using who for a thing or which for a person without a reason.', 'Repeating the noun or pronoun unnecessarily inside the relative clause.', 'Adding or omitting commas without considering whether the information is essential.'],
    practicePrompts: ['Combine two sentences with a relative clause.', 'Choose who, which or that.', 'Compare a defining clause with a non-defining clause.'],
    relatedPaths: ['/resources/grammar/independent-and-dependent-clauses', '/resources/grammar/compound-sentences-for-kids'],
  }),
  page({
    order: 36,
    id: 'fragments-runons',
    slug: 'sentence-fragments-and-run-ons-for-kids',
    cardTitle: 'Sentence Fragments & Run-ons',
    seoTitle: 'Sentence Fragments and Run-ons for Kids: How to Fix Them | Tiny Steps',
    seoDescription: 'Help children diagnose incomplete fragments, run-on sentences and comma splices, then repair sentence boundaries.',
    quickAnswer: 'A fragment is not a complete sentence in context; a run-on incorrectly joins complete sentences without suitable punctuation or connection. Repair depends on identifying the sentence boundary first.',
    concept: 'Editing improves when children diagnose the structural problem instead of adding punctuation at random. They should test for a complete subject-predicate idea, then decide whether to complete, separate or correctly join the parts.',
    examples: ['Because we were late. → Because we were late, we took a taxi.', 'I finished my homework I watched a film. → I finished my homework. I watched a film.', 'The rain stopped, we left. → The rain stopped, so we left.'],
    commonMistakes: ['Assuming every short sentence is a fragment.', 'Fixing a run-on by inserting only a comma between independent clauses.', 'Adding words to a fragment without creating a complete main clause.'],
    practicePrompts: ['Label each example complete, fragment or run-on.', 'Repair a fragment in two different ways.', 'Fix a run-on using separation and then using coordination.'],
    relatedPaths: ['/resources/grammar/independent-and-dependent-clauses', '/resources/grammar/compound-sentences-for-kids'],
  }),
  page({
    order: 37,
    id: 'reported-speech',
    slug: 'direct-and-reported-speech-for-kids',
    cardTitle: 'Direct & Reported Speech',
    seoTitle: 'Direct and Reported Speech for Kids: Rules & Examples | Tiny Steps',
    seoDescription: 'Teach quotation punctuation, reporting verbs and accurate changes when reporting what someone said.',
    quickAnswer: 'Direct speech gives the speaker’s exact words, usually inside quotation marks. Reported speech communicates the message without quoting the exact wording and may require changes to pronouns, time words and tense.',
    concept: 'Children need two separate skills: punctuating exact speech clearly and retelling the message from a new reporting viewpoint. Tense changes are context-sensitive rather than a mechanical shift in every sentence.',
    examples: ['Maya said, “I am tired.”', 'Maya said that she was tired.', '“I will call tomorrow,” he said. → He said that he would call the next day.'],
    commonMistakes: ['Using quotation marks around reported speech.', 'Changing tense mechanically when the fact is still current or context does not require a shift.', 'Using said and told with the same object pattern.'],
    practicePrompts: ['Punctuate one line of direct speech.', 'Convert a direct statement into reported speech.', 'Choose an appropriate reporting verb and explain the changes made.'],
    relatedPaths: ['/resources/grammar/forming-questions-in-english-for-kids', '/resources/grammar/active-and-passive-voice-for-kids'],
  }),
  page({
    order: 38,
    id: 'active-passive',
    slug: 'active-and-passive-voice-for-kids',
    cardTitle: 'Active & Passive Voice',
    seoTitle: 'Active and Passive Voice for Kids: Rules & Examples | Tiny Steps',
    seoDescription: 'Teach children how active and passive voice change sentence focus while preserving tense and core meaning.',
    quickAnswer: 'Active voice usually puts the doer before the verb. Passive voice puts the receiver of the action in subject position and uses a form of be plus the past participle; the doer may be included or omitted.',
    concept: 'Voice is a choice about focus, not a rule that passive is always wrong. Children should preserve tense and meaning when converting a sentence, then decide which voice better suits the purpose.',
    examples: ['The chef prepared the meal. / The meal was prepared by the chef.', 'The class will present the project. / The project will be presented by the class.', 'Someone broke the window. / The window was broken.'],
    commonMistakes: ['Changing the tense when converting voice.', 'Using be plus a simple-past form instead of a past participle.', 'Forcing passive voice into sentences where no useful focus change is achieved.'],
    practicePrompts: ['Convert two active sentences to passive while keeping tense.', 'Decide whether the doer needs to be named.', 'Choose the clearer voice for a news-style and a personal sentence.'],
    relatedPaths: ['/resources/grammar/direct-and-reported-speech-for-kids', '/blog/how-to-teach-paragraph-writing-to-kids'],
  }),
]);

export const GRAMMAR_PROGRAMMATIC_PAGES = freezeList(
  GRAMMAR_PROGRAMMATIC_SEQUENCE.filter((entry) => entry.state === 'published'),
);
export const GRAMMAR_PROGRAMMATIC_PATHS = freezeList(GRAMMAR_PROGRAMMATIC_PAGES.map((entry) => entry.path));
export const GRAMMAR_PROGRAMMATIC_RESOURCE_SEO = freeze(
  Object.fromEntries(GRAMMAR_PROGRAMMATIC_PAGES.map((entry) => [
    entry.path,
    freeze({
      title: entry.seoTitle,
      description: entry.seoDescription,
      canonicalPath: entry.path,
      ogType: 'article',
    }),
  ])),
);

const bySlug = new Map(GRAMMAR_PROGRAMMATIC_PAGES.map((entry) => [entry.slug, entry]));
const byPath = new Map(GRAMMAR_PROGRAMMATIC_PAGES.map((entry) => [entry.path, entry]));

export const getGrammarProgrammaticPageBySlug = (slug) => bySlug.get(String(slug || '')) ?? null;
export const getGrammarProgrammaticPageByPath = (pathname) => byPath.get(String(pathname || '').replace(/\/+$/, '')) ?? null;

if (GRAMMAR_PROGRAMMATIC_SEQUENCE.map((entry) => entry.order).join(',') !== Array.from({ length: GRAMMAR_PROGRAMMATIC_SEQUENCE.length }, (_, index) => index + 1).join(',')) {
  throw new Error('Grammar programmatic sequence order must remain contiguous.');
}
if (new Set(GRAMMAR_PROGRAMMATIC_PATHS).size !== GRAMMAR_PROGRAMMATIC_PATHS.length) {
  throw new Error('Grammar programmatic paths must be unique.');
}
