const freeze = (value) => Object.freeze(value);
const freezeList = (values = []) => Object.freeze([...values]);

// Lightweight public-route/SEO manifest for the 32 governed Grammar guides.
// Keep this module free of lesson examples, practice prompts and concept copy so
// eager SEO/analytics imports do not pull the full Grammar content corpus into
// the initial public JavaScript bundle.
export const GRAMMAR_PROGRAMMATIC_ROUTE_MANIFEST = freezeList([
  freeze({
    order: 1,
    id: "nouns",
    slug: "nouns-for-kids",
    path: "/resources/grammar/nouns-for-kids",
    cardTitle: "Nouns for Kids",
    seoTitle: "Nouns for Kids: Meaning, Types & Examples | Tiny Steps",
    seoDescription: "Learn what nouns are, how children can identify naming words in sentences, and how common and proper nouns support clear sentence building.",
  }),
  freeze({
    order: 2,
    id: "proper-nouns",
    slug: "proper-nouns-for-kids",
    path: "/resources/grammar/proper-nouns-for-kids",
    cardTitle: "Proper Nouns for Kids",
    seoTitle: "Proper Nouns for Kids: Capitals, Names & Examples | Tiny Steps",
    seoDescription: "Teach proper nouns as specific names that begin with capital letters, with clear contrasts between common and proper nouns.",
  }),
  freeze({
    order: 3,
    id: "verbs",
    slug: "verbs-for-kids",
    path: "/resources/grammar/verbs-for-kids",
    cardTitle: "Verbs for Kids",
    seoTitle: "Verbs for Kids: Action, Being & Helping Verbs | Tiny Steps",
    seoDescription: "Learn how verbs carry action, state or helping meaning in sentences and prepare children for tense and subject-verb agreement.",
  }),
  freeze({
    order: 4,
    id: "adjectives",
    slug: "adjectives-for-kids",
    path: "/resources/grammar/adjectives-for-kids",
    cardTitle: "Adjectives for Kids",
    seoTitle: "Adjectives for Kids: Describing Words & Examples | Tiny Steps",
    seoDescription: "Teach adjectives as meaningful words that describe or identify nouns, with sentence-level examples and practice.",
  }),
  freeze({
    order: 5,
    id: "pronouns",
    slug: "pronouns-for-kids",
    path: "/resources/grammar/pronouns-for-kids",
    cardTitle: "Pronouns for Kids",
    seoTitle: "Pronouns for Kids: Clear Reference & Examples | Tiny Steps",
    seoDescription: "Learn how pronouns replace or refer to nouns without creating confusing or repetitive sentences.",
  }),
  freeze({
    order: 6,
    id: "singular-plural",
    slug: "singular-and-plural-nouns",
    path: "/resources/grammar/singular-and-plural-nouns",
    cardTitle: "Singular & Plural Nouns",
    seoTitle: "Singular and Plural Nouns for Kids: Rules & Examples | Tiny Steps",
    seoDescription: "Teach one-and-many noun forms, regular plural patterns and common irregular plurals without overgeneralising one rule.",
  }),
  freeze({
    order: 7,
    id: "articles-a-an",
    slug: "a-an-articles-for-kids",
    path: "/resources/grammar/a-an-articles-for-kids",
    cardTitle: "Articles: a & an",
    seoTitle: "A or An for Kids: Article Rules, Sounds & Examples | Tiny Steps",
    seoDescription: "Teach a and an through the sound that begins the next word, with clear examples and common exceptions.",
  }),
  freeze({
    order: 8,
    id: "article-the",
    slug: "the-article-for-kids",
    path: "/resources/grammar/the-article-for-kids",
    cardTitle: "The Article “the”",
    seoTitle: "The Article for Kids: When to Use “the” | Tiny Steps",
    seoDescription: "Explain when children use the for a specific or already-known noun and when an article may not be needed.",
  }),
  freeze({
    order: 9,
    id: "prepositions",
    slug: "prepositions-for-kids",
    path: "/resources/grammar/prepositions-for-kids",
    cardTitle: "Prepositions for Kids",
    seoTitle: "Prepositions for Kids: Place, Time & Movement Examples | Tiny Steps",
    seoDescription: "Learn prepositions of place, time and movement through sentence relationships rather than memorised word lists.",
  }),
  freeze({
    order: 13,
    id: "adverbs",
    slug: "adverbs-for-kids",
    path: "/resources/grammar/adverbs-for-kids",
    cardTitle: "Adverbs for Kids",
    seoTitle: "Adverbs for Kids: How, When & Where Examples | Tiny Steps",
    seoDescription: "Teach adverbs as words that add useful information about how, when or where an action happens.",
  }),
  freeze({
    order: 16,
    id: "simple-present",
    slug: "simple-present-tense-for-kids",
    path: "/resources/grammar/simple-present-tense-for-kids",
    cardTitle: "Simple Present Tense",
    seoTitle: "Simple Present Tense for Kids: Rules & Examples | Tiny Steps",
    seoDescription: "Teach simple present for routines, repeated actions, facts and stable states, including third-person singular agreement.",
  }),
  freeze({
    order: 17,
    id: "simple-past",
    slug: "simple-past-tense-for-kids",
    path: "/resources/grammar/simple-past-tense-for-kids",
    cardTitle: "Simple Past Tense",
    seoTitle: "Simple Past Tense for Kids: Regular, Irregular & Examples | Tiny Steps",
    seoDescription: "Teach simple past for completed past events with regular and irregular verb forms and correct did/did not patterns.",
  }),
  freeze({
    order: 18,
    id: "simple-future",
    slug: "simple-future-tense-for-kids",
    path: "/resources/grammar/simple-future-tense-for-kids",
    cardTitle: "Simple Future with “will”",
    seoTitle: "Simple Future Tense for Kids: Will + Verb Examples | Tiny Steps",
    seoDescription: "Teach the beginner future pattern will + base verb and distinguish it from the wider system of future forms.",
  }),
  freeze({
    order: 19,
    id: "modal-verbs",
    slug: "modal-verbs-for-kids",
    path: "/resources/grammar/modal-verbs-for-kids",
    cardTitle: "Modal Verbs for Kids",
    seoTitle: "Modal Verbs for Kids: Can, Could, Should, Must & More | Tiny Steps",
    seoDescription: "Teach common modal verbs by meaning: ability, possibility, advice, permission and obligation.",
  }),
  freeze({
    order: 20,
    id: "clauses",
    slug: "independent-and-dependent-clauses",
    path: "/resources/grammar/independent-and-dependent-clauses",
    cardTitle: "Independent & Dependent Clauses",
    seoTitle: "Independent and Dependent Clauses for Kids | Tiny Steps",
    seoDescription: "Help children distinguish complete independent clauses from dependent clauses and combine them into clear sentences.",
  }),
  freeze({
    order: 22,
    id: "present-simple-vs-continuous",
    slug: "simple-present-vs-present-continuous-for-kids",
    path: "/resources/grammar/simple-present-vs-present-continuous-for-kids",
    cardTitle: "Simple Present vs Present Continuous",
    seoTitle: "Simple Present vs Present Continuous for Kids | Tiny Steps",
    seoDescription: "Help children choose between routines and facts in the simple present and actions happening around now in the present continuous.",
  }),
  freeze({
    order: 23,
    id: "past-simple-vs-continuous",
    slug: "simple-past-vs-past-continuous-for-kids",
    path: "/resources/grammar/simple-past-vs-past-continuous-for-kids",
    cardTitle: "Simple Past vs Past Continuous",
    seoTitle: "Simple Past vs Past Continuous for Kids | Tiny Steps",
    seoDescription: "Teach completed past events versus actions that were in progress, including when and while patterns.",
  }),
  freeze({
    order: 24,
    id: "future-forms",
    slug: "future-forms-for-kids",
    path: "/resources/grammar/future-forms-for-kids",
    cardTitle: "Future Forms: will, going to & arrangements",
    seoTitle: "Future Forms for Kids: Will, Going To & Present Continuous | Tiny Steps",
    seoDescription: "Compare common English future forms for decisions, predictions, plans, arrangements and schedules.",
  }),
  freeze({
    order: 25,
    id: "present-perfect-vs-past",
    slug: "present-perfect-vs-simple-past-for-kids",
    path: "/resources/grammar/present-perfect-vs-simple-past-for-kids",
    cardTitle: "Present Perfect vs Simple Past",
    seoTitle: "Present Perfect vs Simple Past for Kids | Tiny Steps",
    seoDescription: "Compare life experience and present relevance with finished past events and finished-time expressions.",
  }),
  freeze({
    order: 26,
    id: "past-perfect",
    slug: "past-perfect-tense-for-kids",
    path: "/resources/grammar/past-perfect-tense-for-kids",
    cardTitle: "Past Perfect Tense",
    seoTitle: "Past Perfect Tense for Kids: Had + Past Participle | Tiny Steps",
    seoDescription: "Teach past perfect for showing an earlier event before another past reference point without overusing the form.",
  }),
  freeze({
    order: 27,
    id: "questions",
    slug: "forming-questions-in-english-for-kids",
    path: "/resources/grammar/forming-questions-in-english-for-kids",
    cardTitle: "Forming Questions Naturally",
    seoTitle: "How to Form Questions in English for Kids | Tiny Steps",
    seoDescription: "Teach yes/no and wh- questions with correct auxiliaries and natural English word order.",
  }),
  freeze({
    order: 28,
    id: "negatives-short-answers",
    slug: "negative-sentences-and-short-answers",
    path: "/resources/grammar/negative-sentences-and-short-answers",
    cardTitle: "Negative Sentences & Short Answers",
    seoTitle: "Negative Sentences and Short Answers for Kids | Tiny Steps",
    seoDescription: "Teach accurate negatives, contractions and short answers by matching the correct auxiliary to the tense.",
  }),
  freeze({
    order: 29,
    id: "quantifiers",
    slug: "quantifiers-for-kids",
    path: "/resources/grammar/quantifiers-for-kids",
    cardTitle: "Quantifiers: much, many, some, any & more",
    seoTitle: "Quantifiers for Kids: Much, Many, Some, Any, Few & Little | Tiny Steps",
    seoDescription: "Teach quantity expressions by connecting them to countable and uncountable nouns and sentence meaning.",
  }),
  freeze({
    order: 30,
    id: "compound-sentences",
    slug: "compound-sentences-for-kids",
    path: "/resources/grammar/compound-sentences-for-kids",
    cardTitle: "Compound Sentences",
    seoTitle: "Compound Sentences for Kids: Joining Complete Ideas | Tiny Steps",
    seoDescription: "Teach children to join related independent clauses with suitable coordinating conjunctions and punctuation.",
  }),
  freeze({
    order: 31,
    id: "reason-result",
    slug: "reason-and-result-connectors-for-kids",
    path: "/resources/grammar/reason-and-result-connectors-for-kids",
    cardTitle: "Reason & Result Connectors",
    seoTitle: "Reason and Result Connectors for Kids: Because, So & Therefore | Tiny Steps",
    seoDescription: "Teach children to distinguish causes from results and connect them with because, so, therefore and related expressions.",
  }),
  freeze({
    order: 32,
    id: "time-sequence",
    slug: "time-and-sequence-connectors-for-kids",
    path: "/resources/grammar/time-and-sequence-connectors-for-kids",
    cardTitle: "Time & Sequence Connectors",
    seoTitle: "Time and Sequence Connectors for Kids | Before, After, When, While | Tiny Steps",
    seoDescription: "Teach children to order events clearly with before, after, when, while, first, next and other sequence language.",
  }),
  freeze({
    order: 33,
    id: "conditionals",
    slug: "conditionals-for-kids",
    path: "/resources/grammar/conditionals-for-kids",
    cardTitle: "Conditions & Possibilities",
    seoTitle: "Conditionals for Kids: If, Unless & Possibility Sentences | Tiny Steps",
    seoDescription: "Introduce condition-result relationships with if and unless and distinguish real from imagined possibilities.",
  }),
  freeze({
    order: 34,
    id: "contrast-concession",
    slug: "contrast-and-concession-for-kids",
    path: "/resources/grammar/contrast-and-concession-for-kids",
    cardTitle: "Contrast & Concession",
    seoTitle: "Contrast and Concession for Kids: But, Although, However & Despite | Tiny Steps",
    seoDescription: "Teach children to connect contrasting ideas accurately with but, although, however and despite.",
  }),
  freeze({
    order: 35,
    id: "relative-clauses",
    slug: "relative-clauses-for-kids",
    path: "/resources/grammar/relative-clauses-for-kids",
    cardTitle: "Relative Clauses",
    seoTitle: "Relative Clauses for Kids: Who, Which & That | Tiny Steps",
    seoDescription: "Teach relative clauses as a way to add information about a noun with who, which, that and related forms.",
  }),
  freeze({
    order: 36,
    id: "fragments-runons",
    slug: "sentence-fragments-and-run-ons-for-kids",
    path: "/resources/grammar/sentence-fragments-and-run-ons-for-kids",
    cardTitle: "Sentence Fragments & Run-ons",
    seoTitle: "Sentence Fragments and Run-ons for Kids: How to Fix Them | Tiny Steps",
    seoDescription: "Help children diagnose incomplete fragments, run-on sentences and comma splices, then repair sentence boundaries.",
  }),
  freeze({
    order: 37,
    id: "reported-speech",
    slug: "direct-and-reported-speech-for-kids",
    path: "/resources/grammar/direct-and-reported-speech-for-kids",
    cardTitle: "Direct & Reported Speech",
    seoTitle: "Direct and Reported Speech for Kids: Rules & Examples | Tiny Steps",
    seoDescription: "Teach quotation punctuation, reporting verbs and accurate changes when reporting what someone said.",
  }),
  freeze({
    order: 38,
    id: "active-passive",
    slug: "active-and-passive-voice-for-kids",
    path: "/resources/grammar/active-and-passive-voice-for-kids",
    cardTitle: "Active & Passive Voice",
    seoTitle: "Active and Passive Voice for Kids: Rules & Examples | Tiny Steps",
    seoDescription: "Teach children how active and passive voice change sentence focus while preserving tense and core meaning.",
  })
]);

export const GRAMMAR_PROGRAMMATIC_PATHS = freezeList(
  GRAMMAR_PROGRAMMATIC_ROUTE_MANIFEST.map((entry) => entry.path),
);

export const GRAMMAR_PROGRAMMATIC_RESOURCE_SEO = freeze(
  Object.fromEntries(GRAMMAR_PROGRAMMATIC_ROUTE_MANIFEST.map((entry) => [
    entry.path,
    freeze({
      title: entry.seoTitle,
      description: entry.seoDescription,
      canonicalPath: entry.path,
      ogType: 'article',
    }),
  ])),
);

if (GRAMMAR_PROGRAMMATIC_ROUTE_MANIFEST.length !== 32) {
  throw new Error('Grammar programmatic route manifest must remain bounded to 32 published pages.');
}
if (new Set(GRAMMAR_PROGRAMMATIC_PATHS).size !== GRAMMAR_PROGRAMMATIC_PATHS.length) {
  throw new Error('Grammar programmatic route manifest paths must be unique.');
}
