const freeze = (value) => Object.freeze(value);
const freezeList = (values = []) => Object.freeze([...values]);

const page = (config) => freeze({
  state: 'published',
  hubPath: '/resources/grammar',
  ...config,
  path: `/resources/grammar/${config.slug}`,
  examples: freezeList(config.examples),
  commonMistakes: freezeList(config.commonMistakes),
  practicePrompts: freezeList(config.practicePrompts),
  relatedPaths: freezeList(config.relatedPaths),
});

const existing = (config) => freeze({
  state: 'existing-owner',
  hubPath: '/resources/grammar',
  ...config,
});

export const GRAMMAR_PROGRAMMATIC_REVISION = '2026-09-27-gp1';

/**
 * Curriculum-aligned discovery sequence. This is a learning progression, not a
 * universal age timetable. Existing canonical owners remain owners where they
 * already cover an intent strongly; only uncovered concepts receive a focused
 * /resources/grammar/* page.
 */
export const GRAMMAR_PROGRAMMATIC_SEQUENCE = freezeList([
  page({
    order: 1,
    id: 'nouns',
    slug: 'nouns-for-kids',
    cardTitle: 'Nouns for Kids',
    seoTitle: 'Nouns for Kids: Meaning, Types & Examples | Tiny Steps',
    seoDescription: 'Learn what nouns are, how children can identify naming words in sentences, and how common and proper nouns support clear sentence building.',
    quickAnswer: 'A noun is a word used to name a person, place, animal, thing or idea. Children learn nouns best by finding the naming word inside a complete sentence, not by memorising a list.',
    concept: 'Nouns give a sentence the people, places, things and ideas it is about. Early grammar work should connect the label noun to a real sentence job: naming who or what the message concerns.',
    examples: ['Riya opened the window.', 'The puppy chased the ball.', 'Kindness can change a difficult moment.'],
    commonMistakes: ['Calling every object word a noun without checking its sentence job.', 'Confusing a noun with an adjective that describes it.', 'Identifying a noun in isolation but not using it in a complete sentence.'],
    practicePrompts: ['Underline the naming word in a fresh sentence.', 'Replace one noun with a different noun and explain how the meaning changes.', 'Write one sentence containing a person noun and one thing noun.'],
    relatedPaths: ['/blog/grammar-nouns-to-paragraphs', '/resources/grammar/proper-nouns-for-kids'],
  }),
  page({
    order: 2,
    id: 'proper-nouns',
    slug: 'proper-nouns-for-kids',
    cardTitle: 'Proper Nouns for Kids',
    seoTitle: 'Proper Nouns for Kids: Capitals, Names & Examples | Tiny Steps',
    seoDescription: 'Teach proper nouns as specific names that begin with capital letters, with clear contrasts between common and proper nouns.',
    quickAnswer: 'A proper noun names a specific person, place, organisation, day or other named entity and normally begins with a capital letter, such as Maya, Hyderabad or Monday.',
    concept: 'Proper nouns are a useful bridge between word classes and punctuation because the child must understand both naming and capitalisation. The goal is to distinguish a general category from one specific name.',
    examples: ['city → Hyderabad', 'girl → Ananya', 'day → Friday'],
    commonMistakes: ['Capitalising every noun instead of only specific names.', 'Forgetting capitals when the proper noun appears in the middle of a sentence.', 'Treating the first word of a sentence as a proper noun just because it has a capital.'],
    practicePrompts: ['Sort six words into common nouns and proper nouns.', 'Turn a common noun into a specific named example.', 'Correct the capitals in a sentence containing two proper nouns.'],
    relatedPaths: ['/resources/grammar/nouns-for-kids', '/blog/punctuation-and-capital-letters-for-kids'],
  }),
  page({
    order: 3,
    id: 'verbs',
    slug: 'verbs-for-kids',
    cardTitle: 'Verbs for Kids',
    seoTitle: 'Verbs for Kids: Action, Being & Helping Verbs | Tiny Steps',
    seoDescription: 'Learn how verbs carry action, state or helping meaning in sentences and prepare children for tense and subject-verb agreement.',
    quickAnswer: 'A verb is the part of a sentence that carries action, state or helping meaning. Finding the verb helps a child understand what is happening and prepares for later tense and agreement work.',
    concept: 'Children need to see verbs as sentence engines rather than only action words. Some verbs show actions, while others show states or help another verb form a complete verb phrase.',
    examples: ['The children laugh.', 'Aarav is tired.', 'She has finished the puzzle.'],
    commonMistakes: ['Believing every verb must show a visible action.', 'Missing helping verbs such as is, have or will.', 'Changing the verb form without checking the subject or time meaning.'],
    practicePrompts: ['Circle the complete verb phrase in a sentence.', 'Change a sentence from one time frame to another.', 'Replace a weak verb with a more precise verb while keeping the sentence meaning clear.'],
    relatedPaths: ['/resources/grammar/nouns-for-kids', '/blog/grammar-subject-verb'],
  }),
  page({
    order: 4,
    id: 'adjectives',
    slug: 'adjectives-for-kids',
    cardTitle: 'Adjectives for Kids',
    seoTitle: 'Adjectives for Kids: Describing Words & Examples | Tiny Steps',
    seoDescription: 'Teach adjectives as meaningful words that describe or identify nouns, with sentence-level examples and practice.',
    quickAnswer: 'An adjective gives useful information about a noun, such as what kind, which one or how many. Good adjective use adds precision rather than simply making a sentence longer.',
    concept: 'Adjectives support sentence expansion when they add information the reader needs. Children should learn to choose a relevant description and place it naturally around the noun it describes.',
    examples: ['The narrow bridge crossed the river.', 'Three curious students asked questions.', 'That blue folder belongs to Meera.'],
    commonMistakes: ['Adding many adjectives without improving meaning.', 'Confusing adjectives with adverbs.', 'Using an adjective that does not clearly describe a noun.'],
    practicePrompts: ['Add one precise adjective to a plain sentence.', 'Remove an unnecessary adjective and explain why the sentence is clearer.', 'Match each adjective to the noun it describes.'],
    relatedPaths: ['/resources/grammar/verbs-for-kids', '/resources/grammar/adverbs-for-kids'],
  }),
  page({
    order: 5,
    id: 'pronouns',
    slug: 'pronouns-for-kids',
    cardTitle: 'Pronouns for Kids',
    seoTitle: 'Pronouns for Kids: Clear Reference & Examples | Tiny Steps',
    seoDescription: 'Learn how pronouns replace or refer to nouns without creating confusing or repetitive sentences.',
    quickAnswer: 'A pronoun refers to a noun or noun phrase so a sentence does not repeat the same name unnecessarily. The reader should always be able to tell who or what the pronoun refers to.',
    concept: 'Pronouns improve flow only when their reference is clear. Early practice should combine correct form with a visible antecedent instead of teaching pronouns as a disconnected word list.',
    examples: ['Mina found the book. She returned it.', 'The boys packed their bags.', 'This is my pencil; that is yours.'],
    commonMistakes: ['Using a pronoun when two possible nouns could be its reference.', 'Mixing singular and plural reference.', 'Repeating the noun in every sentence instead of using a clear pronoun.'],
    practicePrompts: ['Replace repeated nouns with clear pronouns.', 'Find the noun each pronoun refers to.', 'Rewrite an ambiguous pronoun sentence so the meaning is obvious.'],
    relatedPaths: ['/resources/grammar/nouns-for-kids', '/resources/grammar/singular-and-plural-nouns'],
  }),
  page({
    order: 6,
    id: 'singular-plural',
    slug: 'singular-and-plural-nouns',
    cardTitle: 'Singular & Plural Nouns',
    seoTitle: 'Singular and Plural Nouns for Kids: Rules & Examples | Tiny Steps',
    seoDescription: 'Teach one-and-many noun forms, regular plural patterns and common irregular plurals without overgeneralising one rule.',
    quickAnswer: 'A singular noun refers to one; a plural noun normally refers to more than one. Many plurals use -s or -es, but children also need common irregular forms such as children, feet and mice.',
    concept: 'Plural learning combines meaning and word form. The child should first identify whether the message means one or more than one, then choose the form that matches.',
    examples: ['book → books', 'box → boxes', 'child → children'],
    commonMistakes: ['Adding -s to every noun, including irregular plurals.', 'Changing the noun to plural while leaving the rest of the sentence singular.', 'Confusing possessive apostrophes with plural endings.'],
    practicePrompts: ['Change a singular sentence into a plural sentence.', 'Sort regular and irregular plural examples.', 'Correct a sentence where the noun and verb do not agree in number.'],
    relatedPaths: ['/resources/grammar/pronouns-for-kids', '/blog/grammar-subject-verb'],
  }),
  page({
    order: 7,
    id: 'articles-a-an',
    slug: 'a-an-articles-for-kids',
    cardTitle: 'Articles: a & an',
    seoTitle: 'A or An for Kids: Article Rules, Sounds & Examples | Tiny Steps',
    seoDescription: 'Teach a and an through the sound that begins the next word, with clear examples and common exceptions.',
    quickAnswer: 'Use a before a consonant sound and an before a vowel sound. The choice depends on pronunciation, not simply the first written letter.',
    concept: 'The useful rule is sound-based: a university begins with a /y/ sound, while an hour begins with a vowel sound. Children should say the phrase aloud and listen to the opening sound.',
    examples: ['a dog', 'an apple', 'a university / an hour'],
    commonMistakes: ['Choosing only from the first written letter.', 'Using a or an with plural nouns.', 'Adding an article where no singular countable noun is intended.'],
    practicePrompts: ['Choose a or an and explain the opening sound.', 'Find one apparent exception and say it aloud.', 'Write three noun phrases using a/an correctly.'],
    relatedPaths: ['/resources/grammar/singular-and-plural-nouns', '/resources/grammar/the-article-for-kids'],
  }),
  page({
    order: 8,
    id: 'article-the',
    slug: 'the-article-for-kids',
    cardTitle: 'The Article “the”',
    seoTitle: 'The Article for Kids: When to Use “the” | Tiny Steps',
    seoDescription: 'Explain when children use the for a specific or already-known noun and when an article may not be needed.',
    quickAnswer: 'Use the when the speaker and listener can identify the specific person, place or thing being referred to, or when context makes that reference clear.',
    concept: 'The is about shared identification, not simply importance. Children learn it more reliably when they compare a first general mention with a later specific reference.',
    examples: ['I saw a dog. The dog followed me.', 'Please close the door.', 'The sun was bright.'],
    commonMistakes: ['Using the before every noun.', 'Leaving out the when a specific shared noun is intended.', 'Treating a/an and the as interchangeable.'],
    practicePrompts: ['Compare a first mention with a second mention.', 'Choose whether a/an, the or no article fits a short context.', 'Explain what makes a noun specific in a sentence.'],
    relatedPaths: ['/resources/grammar/a-an-articles-for-kids', '/resources/grammar/prepositions-for-kids'],
  }),
  page({
    order: 9,
    id: 'prepositions',
    slug: 'prepositions-for-kids',
    cardTitle: 'Prepositions for Kids',
    seoTitle: 'Prepositions for Kids: Place, Time & Movement Examples | Tiny Steps',
    seoDescription: 'Learn prepositions of place, time and movement through sentence relationships rather than memorised word lists.',
    quickAnswer: 'A preposition helps show a relationship such as place, time, position or movement: in the box, after lunch, under the table, toward the gate.',
    concept: 'Prepositions become meaningful when a child can identify the relationship between two parts of a sentence. Visual and movement examples work well, but the final check should be a fresh sentence.',
    examples: ['The keys are under the notebook.', 'We will meet after lunch.', 'The puppy ran toward the gate.'],
    commonMistakes: ['Choosing a preposition from habit without checking meaning.', 'Memorising lists but struggling to use the word in a sentence.', 'Confusing a preposition with an adverb when there is no object or relationship stated.'],
    practicePrompts: ['Describe an object location using two different prepositions.', 'Choose a preposition that changes the sentence meaning.', 'Write one place, one time and one movement example.'],
    relatedPaths: ['/resources/grammar/the-article-for-kids', '/blog/grammar-conjunctions'],
  }),
  existing({
    order: 10,
    id: 'punctuation',
    label: 'Capital Letters & Punctuation',
    path: '/blog/punctuation-and-capital-letters-for-kids',
    reason: 'Existing substantial canonical owner.',
  }),
  existing({
    order: 11,
    id: 'sentence-formation',
    label: 'Simple Sentences & Sentence Formation',
    path: '/blog/how-to-improve-sentence-formation-in-kids',
    reason: 'Existing diagnostic and instructional owner.',
  }),
  existing({
    order: 12,
    id: 'conjunctions',
    label: 'Conjunctions',
    path: '/blog/grammar-conjunctions',
    reason: 'Existing page-one canonical owner.',
  }),
  page({
    order: 13,
    id: 'adverbs',
    slug: 'adverbs-for-kids',
    cardTitle: 'Adverbs for Kids',
    seoTitle: 'Adverbs for Kids: How, When & Where Examples | Tiny Steps',
    seoDescription: 'Teach adverbs as words that add useful information about how, when or where an action happens.',
    quickAnswer: 'An adverb can add information about how, when, where or to what degree something happens. Many adverbs end in -ly, but not all adverbs do.',
    concept: 'Adverbs help children add precise detail to a verb, adjective or another adverb. The sentence should become more informative, not merely longer.',
    examples: ['She answered calmly.', 'We arrived yesterday.', 'The children waited outside.'],
    commonMistakes: ['Assuming every -ly word is an adverb.', 'Confusing an adjective that describes a noun with an adverb that modifies a verb.', 'Adding unnecessary adverbs to already precise verbs.'],
    practicePrompts: ['Add a how adverb to one sentence.', 'Replace a vague adverb-plus-verb combination with a stronger verb.', 'Sort examples into how, when and where.'],
    relatedPaths: ['/resources/grammar/adjectives-for-kids', '/blog/grammar-conjunctions'],
  }),
  existing({
    order: 14,
    id: 'subject-verb-agreement',
    label: 'Subject–Verb Agreement',
    path: '/blog/grammar-subject-verb',
    reason: 'Existing canonical owner with search visibility.',
  }),
  existing({
    order: 15,
    id: 'tenses-overview',
    label: 'English Tenses Overview',
    path: '/blog/grammar-tenses',
    reason: 'Existing canonical overview owner.',
  }),
  page({
    order: 16,
    id: 'simple-present',
    slug: 'simple-present-tense-for-kids',
    cardTitle: 'Simple Present Tense',
    seoTitle: 'Simple Present Tense for Kids: Rules & Examples | Tiny Steps',
    seoDescription: 'Teach simple present for routines, repeated actions, facts and stable states, including third-person singular agreement.',
    quickAnswer: 'Use the simple present for routines, repeated actions, facts and generally true states. It is not the default tense for an action happening right now.',
    concept: 'Children need both meaning and form: I/you/we/they use the base form in common patterns, while he/she/it commonly takes -s or -es in affirmative statements.',
    examples: ['I read every evening.', 'Maya walks to school.', 'Plants need water.'],
    commonMistakes: ['Using simple present for every present-time action.', 'Omitting third-person -s/-es.', 'Using does with a main verb that still carries -s.'],
    practicePrompts: ['Write one routine and one fact.', 'Change I play to she plays.', 'Contrast a routine sentence with an action happening now.'],
    relatedPaths: ['/blog/grammar-tenses', '/resources/grammar/simple-past-tense-for-kids'],
  }),
  page({
    order: 17,
    id: 'simple-past',
    slug: 'simple-past-tense-for-kids',
    cardTitle: 'Simple Past Tense',
    seoTitle: 'Simple Past Tense for Kids: Regular, Irregular & Examples | Tiny Steps',
    seoDescription: 'Teach simple past for completed past events with regular and irregular verb forms and correct did/did not patterns.',
    quickAnswer: 'Use the simple past for an event or state understood as completed in the past. Some verbs use -ed; many high-frequency verbs have irregular past forms.',
    concept: 'Past meaning comes first. Children then choose the required past form, while questions and negatives with did return the main verb to its base form.',
    examples: ['We visited the museum yesterday.', 'She went home early.', 'Did he finish the book?'],
    commonMistakes: ['Adding -ed to every verb.', 'Using did plus a past-form verb.', 'Switching back to present tense inside a past-event sequence.'],
    practicePrompts: ['Retell three completed events in order.', 'Correct a did + past-form error.', 'Sort regular and irregular past verbs.'],
    relatedPaths: ['/resources/grammar/simple-present-tense-for-kids', '/resources/grammar/simple-future-tense-for-kids'],
  }),
  page({
    order: 18,
    id: 'simple-future',
    slug: 'simple-future-tense-for-kids',
    cardTitle: 'Simple Future with “will”',
    seoTitle: 'Simple Future Tense for Kids: Will + Verb Examples | Tiny Steps',
    seoDescription: 'Teach the beginner future pattern will + base verb and distinguish it from the wider system of future forms.',
    quickAnswer: 'A useful beginner future form is will + base verb, for example “I will call you.” English also uses other forms for plans, arrangements and schedules, so will should not be taught as the only way to talk about the future.',
    concept: 'At beginner level, will provides a clear future pattern. At advanced level, children should choose among will, going to, present continuous and simple present according to meaning.',
    examples: ['I will help you.', 'They will arrive tomorrow.', 'Will she join us?'],
    commonMistakes: ['Changing the main verb after will.', 'Using will for every future context.', 'Omitting will in a future form the child is trying to construct.'],
    practicePrompts: ['Build three will + base verb sentences.', 'Turn one statement into a question and negative.', 'Compare a prediction with a planned arrangement.'],
    relatedPaths: ['/resources/grammar/simple-past-tense-for-kids', '/blog/grammar-tenses'],
  }),
  page({
    order: 19,
    id: 'modal-verbs',
    slug: 'modal-verbs-for-kids',
    cardTitle: 'Modal Verbs for Kids',
    seoTitle: 'Modal Verbs for Kids: Can, Could, Should, Must & More | Tiny Steps',
    seoDescription: 'Teach common modal verbs by meaning: ability, possibility, advice, permission and obligation.',
    quickAnswer: 'Modal verbs such as can, could, may, might, should and must help express meanings like ability, possibility, permission, advice and obligation. A modal is normally followed by the base form of the main verb.',
    concept: 'The important skill is choosing the modal that matches the intended strength and meaning, not memorising a list. Children should compare close choices such as should versus must.',
    examples: ['You should check your work.', 'She can swim.', 'It might rain later.'],
    commonMistakes: ['Adding -s or -ed to the verb after a modal.', 'Treating should and must as equal in strength.', 'Using can for every type of permission or possibility without considering context.'],
    practicePrompts: ['Choose a modal for advice, ability and possibility.', 'Rewrite one sentence to make the obligation stronger or weaker.', 'Explain why two modal choices change the meaning.'],
    relatedPaths: ['/resources/grammar/simple-future-tense-for-kids', '/resources/grammar/independent-and-dependent-clauses'],
  }),
  page({
    order: 20,
    id: 'clauses',
    slug: 'independent-and-dependent-clauses',
    cardTitle: 'Independent & Dependent Clauses',
    seoTitle: 'Independent and Dependent Clauses for Kids | Tiny Steps',
    seoDescription: 'Help children distinguish complete independent clauses from dependent clauses and combine them into clear sentences.',
    quickAnswer: 'An independent clause can stand as a complete sentence; a dependent clause cannot stand alone because it leaves the meaning unfinished and needs an independent clause.',
    concept: 'Clause awareness helps children move beyond short sentences without creating fragments or run-ons. The goal is to recognise completeness and then combine ideas according to meaning.',
    examples: ['We stayed inside. / because it was raining', 'Although Maya was tired, she finished the project.', 'I called him when I reached home.'],
    commonMistakes: ['Writing a dependent clause as a complete sentence.', 'Joining two independent clauses without suitable punctuation or a connector.', 'Confusing a phrase with a clause that contains a subject-verb relationship.'],
    practicePrompts: ['Label each clause independent or dependent.', 'Complete a dependent clause with a clear main clause.', 'Combine two ideas using because, although, when or if.'],
    relatedPaths: ['/blog/grammar-conjunctions', '/blog/how-to-teach-paragraph-writing-to-kids'],
  }),
  existing({
    order: 21,
    id: 'paragraph-writing',
    label: 'Paragraph Writing',
    path: '/blog/how-to-teach-paragraph-writing-to-kids',
    reason: 'Existing substantial canonical owner.',
  }),
]);

export const GRAMMAR_PROGRAMMATIC_PAGES = freezeList(
  GRAMMAR_PROGRAMMATIC_SEQUENCE.filter((entry) => entry.state === 'published'),
);
export const GRAMMAR_PROGRAMMATIC_PATHS = freezeList(GRAMMAR_PROGRAMMATIC_PAGES.map((entry) => entry.path));

const bySlug = new Map(GRAMMAR_PROGRAMMATIC_PAGES.map((entry) => [entry.slug, entry]));
const byPath = new Map(GRAMMAR_PROGRAMMATIC_PAGES.map((entry) => [entry.path, entry]));

export const getGrammarProgrammaticPageBySlug = (slug) => bySlug.get(String(slug || '')) ?? null;
export const getGrammarProgrammaticPageByPath = (pathname) => byPath.get(String(pathname || '').replace(/\/+$/, '')) ?? null;

if (GRAMMAR_PROGRAMMATIC_SEQUENCE.map((entry) => entry.order).join(',') !== Array.from({ length: GRAMMAR_PROGRAMMATIC_SEQUENCE.length }, (_, index) => index + 1).join(',')) {
  throw new Error('Grammar programmatic sequence order must remain contiguous.');
}
if (new Set(GRAMMAR_PROGRAMMATIC_PATHS).size !== GRAMMAR_PROGRAMMATIC_PATHS.length) {
  throw new Error('Grammar programmatic paths must be unique.');
}
