import { GRAMMAR_COURSES } from '../content/grammarCurriculum';

const freeze = (value) => Object.freeze(value);
const freezeList = (values = []) => Object.freeze([...values]);

export const GRAMMAR_PUBLICATION_REVISION = '2026-09-27-gr-pseo-1';
export const GRAMMAR_PUBLICATION_PREFIX = '/resources/grammar';

const courseById = GRAMMAR_COURSES;

function curriculumRef(courseId, lessonNumber) {
  const lesson = courseById[courseId]?.lessons?.find((item) => item.lessonNumber === lessonNumber);
  if (!lesson) throw new Error(`Unknown Grammar curriculum reference: ${courseId} lesson ${lessonNumber}`);
  return freeze({
    courseId,
    lessonNumber,
    lessonTitle: lesson.label,
    stageOrder: lesson.stageOrder,
    stageLabel: lesson.stageLabel,
  });
}

function page(config) {
  const path = `${GRAMMAR_PUBLICATION_PREFIX}/${config.slug}`;
  const refs = freezeList(config.curriculumRefs.map(([courseId, lessonNumber]) => curriculumRef(courseId, lessonNumber)));
  return freeze({
    ...config,
    path,
    curriculumRefs: refs,
    examples: freezeList(config.examples),
    teachingSteps: freezeList(config.teachingSteps),
    commonMistakes: freezeList(config.commonMistakes),
    practiceIdeas: freezeList(config.practiceIdeas),
    prerequisiteIds: freezeList(config.prerequisiteIds || []),
    nextIds: freezeList(config.nextIds || []),
    relatedPaths: freezeList(config.relatedPaths || []),
    practicePaths: freezeList(config.practicePaths || ['/free-grammar-games-for-kids']),
    publicationState: 'published',
  });
}

export const GRAMMAR_PUBLISHED_RESOURCE_PAGES = freezeList([
  page({
    id: 'nouns', slug: 'nouns-for-kids', level: 'beginner', stageOrder: 1, progressionRank: 10,
    label: 'Nouns', cardTitle: 'Nouns for Kids', parentQuestion: 'What is a noun for kids?',
    quickAnswer: 'A noun names a person, place, animal, object or idea. Children learn nouns first because nouns help them identify who or what a sentence is about.',
    teachingBoundary: 'Do not teach every naming word as a proper noun. Start with common naming words, then contrast them with specific names and capitalisation.',
    examples: ['teacher, city, rabbit, backpack, kindness', 'The rabbit hid behind the chair.', 'Mina carried the backpack.'],
    teachingSteps: ['Name familiar people, places and objects.', 'Find the noun inside a complete sentence.', 'Use a noun as the subject or object of a new sentence.'],
    commonMistakes: ['Calling every word in a sentence a noun.', 'Confusing action words with naming words.', 'Treating a specific name and a common noun as the same type.'],
    practiceIdeas: ['Sort words into noun/not-a-noun groups.', 'Underline nouns in short sentences.', 'Replace one noun with a different sensible noun.'],
    curriculumRefs: [['basic-grammar', 1]], nextIds: ['proper-nouns', 'verbs'],
    relatedPaths: ['/blog/grammar-nouns-to-paragraphs'],
  }),
  page({
    id: 'proper-nouns', slug: 'proper-nouns-for-kids', level: 'beginner', stageOrder: 1, progressionRank: 20,
    label: 'Proper Nouns', cardTitle: 'Proper Nouns for Kids', parentQuestion: 'What is a proper noun for kids?',
    quickAnswer: 'A proper noun is the specific name of a person, place, organisation or named thing, so it begins with a capital letter in ordinary English writing.',
    teachingBoundary: 'Capital letters do not make every word a proper noun. Teach the naming distinction first, then connect it to capitalisation.',
    examples: ['girl → Aanya', 'city → Hyderabad', 'river → Godavari', 'Aanya visited Hyderabad in June.'],
    teachingSteps: ['Compare a general noun with a specific name.', 'Notice the capital letter on the specific name.', 'Use both common and proper nouns in one sentence.'],
    commonMistakes: ['Capitalising all common nouns.', 'Forgetting capitals in names.', 'Assuming a sentence-start capital automatically means proper noun.'],
    practiceIdeas: ['Match common nouns to possible proper nouns.', 'Correct capital letters in names.', 'Write one sentence containing both kinds of nouns.'],
    curriculumRefs: [['basic-grammar', 2]], prerequisiteIds: ['nouns'], nextIds: ['verbs'],
    relatedPaths: ['/blog/punctuation-and-capital-letters-for-kids'],
  }),
  page({
    id: 'verbs', slug: 'verbs-for-kids', level: 'beginner', stageOrder: 1, progressionRank: 30,
    label: 'Verbs', cardTitle: 'Verbs for Kids', parentQuestion: 'What is a verb for kids?',
    quickAnswer: 'A verb tells what someone or something does, is or experiences. Verbs are central to sentence building because a complete clause normally needs a verb.',
    teachingBoundary: 'Do not define verbs only as physical actions. Forms of be and verbs such as know, seem or belong also function as verbs.',
    examples: ['run, whisper, think, is, became', 'The puppy sleeps.', 'The answer is correct.'],
    teachingSteps: ['Act out easy action verbs.', 'Find the verb in complete sentences.', 'Compare action verbs with forms of be and state verbs.'],
    commonMistakes: ['Missing is/am/are as verbs.', 'Confusing nouns such as a run with verb uses such as I run.', 'Choosing a verb form that does not agree with the subject.'],
    practiceIdeas: ['Circle the verb in each sentence.', 'Replace a weak verb with a more precise one.', 'Build sentences from subject + verb prompts.'],
    curriculumRefs: [['basic-grammar', 3]], prerequisiteIds: ['nouns'], nextIds: ['adjectives', 'pronouns'],
    relatedPaths: ['/blog/grammar-subject-verb'],
  }),
  page({
    id: 'adjectives', slug: 'adjectives-for-kids', level: 'beginner', stageOrder: 1, progressionRank: 40,
    label: 'Adjectives', cardTitle: 'Adjectives for Kids', parentQuestion: 'What is an adjective for kids?',
    quickAnswer: 'An adjective describes or gives information about a noun or pronoun, helping a sentence become more precise without simply making it longer.',
    teachingBoundary: 'Do not encourage children to add many adjectives to every noun. The goal is useful description that improves meaning.',
    examples: ['a narrow bridge', 'three bright lanterns', 'The soup is hot.'],
    teachingSteps: ['Start with a clear noun.', 'Ask what useful detail the listener needs.', 'Add one accurate adjective and reread the sentence.'],
    commonMistakes: ['Using an adverb where an adjective is needed.', 'Stacking too many describing words.', 'Choosing an adjective that does not fit the noun.'],
    practiceIdeas: ['Add one precise adjective to a plain noun.', 'Remove unnecessary adjectives from an overloaded sentence.', 'Compare two objects using accurate adjectives.'],
    curriculumRefs: [['basic-grammar', 4]], prerequisiteIds: ['nouns'], nextIds: ['pronouns', 'expanding-sentences'],
    relatedPaths: ['/blog/how-to-improve-sentence-formation-in-kids'],
  }),
  page({
    id: 'pronouns', slug: 'pronouns-for-kids', level: 'beginner', stageOrder: 1, progressionRank: 50,
    label: 'Pronouns', cardTitle: 'Pronouns for Kids', parentQuestion: 'What is a pronoun for kids?',
    quickAnswer: 'A pronoun can stand in for a noun when the reference is clear, helping speakers and writers avoid unnecessary repetition.',
    teachingBoundary: 'A pronoun only helps when the listener or reader can tell who or what it refers to. Clarity is more important than avoiding every repeated noun.',
    examples: ['Riya found the book. She opened it.', 'The dogs were tired, so they rested.', 'I, you, he, she, it, we, they'],
    teachingSteps: ['Name the noun first.', 'Replace it with a pronoun only when the reference stays clear.', 'Check number and person agreement.'],
    commonMistakes: ['Using he/she/they without a clear noun.', 'Mixing subject and object forms.', 'Changing singular/plural reference accidentally.'],
    practiceIdeas: ['Replace repeated nouns with clear pronouns.', 'Match pronouns to noun phrases.', 'Repair sentences with unclear pronoun reference.'],
    curriculumRefs: [['basic-grammar', 5], ['advanced-grammar', 17]], prerequisiteIds: ['nouns'], nextIds: ['singular-plural', 'clear-pronoun-reference'],
    relatedPaths: ['/blog/how-to-improve-sentence-formation-in-kids'],
  }),
  page({
    id: 'singular-plural', slug: 'singular-and-plural-nouns-for-kids', level: 'beginner', stageOrder: 2, progressionRank: 60,
    label: 'Singular & Plural Nouns', cardTitle: 'Singular and Plural Nouns for Kids', parentQuestion: 'How do singular and plural nouns work for kids?',
    quickAnswer: 'A singular noun names one person, place, animal or thing; a plural noun names more than one. English uses several plural patterns, not only adding -s.',
    teachingBoundary: 'Do not teach “add s” as a universal rule. Children need common -s/-es patterns and later irregular plurals in context.',
    examples: ['book → books', 'box → boxes', 'baby → babies', 'child → children'],
    teachingSteps: ['Contrast one and more than one.', 'Sort regular patterns before adding irregular forms.', 'Use the plural inside a complete sentence.'],
    commonMistakes: ['Adding s to every plural.', 'Missing spelling changes such as baby → babies.', 'Using a plural noun with a singular verb.'],
    practiceIdeas: ['Sort singular and plural pairs.', 'Choose the correct plural in a sentence.', 'Write one singular and one plural sentence.'],
    curriculumRefs: [['basic-grammar', 7], ['basic-grammar', 8]], prerequisiteIds: ['nouns'], nextIds: ['articles', 'prepositions'],
    relatedPaths: ['/blog/grammar-subject-verb'],
  }),
  page({
    id: 'articles', slug: 'articles-a-an-the-for-kids', level: 'beginner', stageOrder: 2, progressionRank: 70,
    label: 'Articles: a, an & the', cardTitle: 'Articles a, an and the for Kids', parentQuestion: 'How do children learn a, an and the?',
    quickAnswer: 'Use a or an when introducing one non-specific singular countable noun, and the when the noun is specific or already clear in the context.',
    teachingBoundary: 'The choice between a and an follows the next sound, not simply the first written letter. The is about shared or specific reference, not “more important” nouns.',
    examples: ['a cat', 'an apple', 'an hour', 'the blue notebook on the desk'],
    teachingSteps: ['Contrast one general item with one specific item.', 'Listen to the starting sound for a/an.', 'Use a short context to decide whether the listener knows which item is meant.'],
    commonMistakes: ['Choosing a/an by letter instead of sound.', 'Using the for every noun.', 'Omitting an article before a singular countable noun.'],
    practiceIdeas: ['Choose a/an from spoken examples.', 'Turn a general noun into a specific one using context.', 'Edit missing or unnecessary articles.'],
    curriculumRefs: [['basic-grammar', 9], ['basic-grammar', 10]], prerequisiteIds: ['nouns', 'singular-plural'], nextIds: ['prepositions', 'simple-sentences'],
    relatedPaths: ['/blog/how-to-improve-sentence-formation-in-kids'],
  }),
  page({
    id: 'prepositions', slug: 'prepositions-for-kids', level: 'beginner', stageOrder: 2, progressionRank: 80,
    label: 'Prepositions', cardTitle: 'Prepositions for Kids', parentQuestion: 'What are prepositions for kids?',
    quickAnswer: 'Prepositions help show relationships such as place, direction, time or connection between parts of a sentence.',
    teachingBoundary: 'Avoid teaching prepositions only as a memorised list. Their meaning depends on the relationship expressed in the sentence.',
    examples: ['under the table', 'after lunch', 'through the tunnel', 'The keys are beside the lamp.'],
    teachingSteps: ['Use real objects for place relationships.', 'Move to time and direction examples.', 'Use the prepositional phrase inside a complete sentence.'],
    commonMistakes: ['Choosing in/on/at mechanically.', 'Leaving out the noun or phrase after the preposition.', 'Using a preposition that changes the intended relationship.'],
    practiceIdeas: ['Describe object positions.', 'Complete sentences using context-appropriate prepositions.', 'Compare two possible prepositions and explain the meaning change.'],
    curriculumRefs: [['basic-grammar', 11]], prerequisiteIds: ['nouns', 'articles'], nextIds: ['simple-sentences'],
    relatedPaths: ['/blog/how-to-improve-sentence-formation-in-kids'],
  }),
  page({
    id: 'simple-sentences', slug: 'simple-sentences-for-kids', level: 'beginner', stageOrder: 3, progressionRank: 90,
    label: 'Simple Sentences', cardTitle: 'Simple Sentences for Kids', parentQuestion: 'What makes a simple sentence complete?',
    quickAnswer: 'A simple sentence expresses one complete independent idea with a subject and a verb. It can contain detail and still remain a simple sentence.',
    teachingBoundary: 'Simple does not mean short. A longer sentence can still be grammatically simple if it contains one independent clause.',
    examples: ['Birds fly.', 'The curious child opened the heavy wooden door.', 'My cousins play chess after dinner.'],
    teachingSteps: ['Find who or what the sentence is about.', 'Find the verb.', 'Check whether the words express a complete thought.'],
    commonMistakes: ['Treating every short word group as a sentence.', 'Missing a verb.', 'Assuming any long sentence must be compound or complex.'],
    practiceIdeas: ['Sort complete sentences and fragments.', 'Expand a complete simple sentence without adding another clause.', 'Build sentences from subject and verb cards.'],
    curriculumRefs: [['basic-grammar', 16]], prerequisiteIds: ['nouns', 'verbs'], nextIds: ['expanding-sentences'],
    relatedPaths: ['/blog/how-to-improve-sentence-formation-in-kids', '/blog/punctuation-and-capital-letters-for-kids'],
    practicePaths: ['/free-sentence-building-games-for-kids'],
  }),
  page({
    id: 'adverbs', slug: 'adverbs-for-kids', level: 'beginner', stageOrder: 4, progressionRank: 100,
    label: 'Adverbs', cardTitle: 'Adverbs for Kids', parentQuestion: 'What is an adverb for kids?',
    quickAnswer: 'An adverb can add information about how, when, where, how often or to what degree an action or description applies.',
    teachingBoundary: 'Not every adverb ends in -ly, and not every -ly word should be taught as an adverb without checking its job in the sentence.',
    examples: ['She spoke softly.', 'We will leave tomorrow.', 'The children waited outside.', 'He often reads before bed.'],
    teachingSteps: ['Start with a clear verb or description.', 'Ask what extra information is useful.', 'Check where the adverb fits naturally in the sentence.'],
    commonMistakes: ['Confusing adjectives and adverbs.', 'Assuming every -ly word is an adverb.', 'Adding adverbs that do not improve meaning.'],
    practiceIdeas: ['Sort how/when/where adverbs.', 'Add one useful adverb to a sentence.', 'Move an adverb and discuss whether meaning or emphasis changes.'],
    curriculumRefs: [['basic-grammar', 21], ['basic-grammar', 22]], prerequisiteIds: ['verbs'], nextIds: ['expanding-sentences'],
    relatedPaths: ['/blog/how-to-improve-sentence-formation-in-kids'],
  }),
  page({
    id: 'expanding-sentences', slug: 'expanding-sentences-for-kids', level: 'beginner', stageOrder: 4, progressionRank: 110,
    label: 'Expanding Sentences', cardTitle: 'Expanding Sentences for Kids', parentQuestion: 'How can children expand a sentence without making it confusing?',
    quickAnswer: 'Sentence expansion adds relevant detail to a complete core idea using precise words, phrases or connected information while keeping the original meaning clear.',
    teachingBoundary: 'Longer is not automatically better. Add only details that answer a useful question such as where, when, how, which one or why.',
    examples: ['The bird sang. → The small bird sang loudly at dawn.', 'We walked. → We walked slowly along the river after lunch.'],
    teachingSteps: ['Secure a complete core sentence.', 'Add one meaningful detail at a time.', 'Reread for clarity and remove details that do not help.'],
    commonMistakes: ['Adding random adjectives or adverbs.', 'Creating a run-on sentence while expanding.', 'Losing the original subject or verb.'],
    practiceIdeas: ['Expand from who + did what.', 'Add where/when/how details.', 'Compare useful detail with unnecessary detail.'],
    curriculumRefs: [['basic-grammar', 23], ['advanced-grammar', 6]], prerequisiteIds: ['simple-sentences', 'adjectives', 'adverbs'], nextIds: ['simple-present', 'subject-verb-object'],
    relatedPaths: ['/blog/how-to-improve-sentence-formation-in-kids'],
    practicePaths: ['/free-sentence-building-games-for-kids'],
  }),
  page({
    id: 'simple-present', slug: 'simple-present-tense-for-kids', level: 'beginner', stageOrder: 5, progressionRank: 120,
    label: 'Simple Present Tense', cardTitle: 'Simple Present Tense for Kids', parentQuestion: 'When do children use the simple present tense?',
    quickAnswer: 'Use the simple present for routines, repeated actions, facts and generally true states. With he, she or it, the main verb usually takes -s or -es in affirmative sentences.',
    teachingBoundary: 'Do not define the simple present as “what is happening now.” Actions happening at this moment are often expressed with the present continuous.',
    examples: ['I read every evening.', 'Maya walks to school.', 'Water freezes at 0°C.'],
    teachingSteps: ['Connect the tense to routine or general meaning.', 'Practise subject–verb agreement.', 'Contrast a routine with an action happening now.'],
    commonMistakes: ['Missing -s/-es with he/she/it.', 'Using simple present for an action happening now without the intended routine meaning.', 'Using does with an -s main verb.'],
    practiceIdeas: ['Write a daily-routine sentence.', 'Correct subject–verb agreement.', 'Compare “I read every day” with “I am reading now.”'],
    curriculumRefs: [['basic-grammar', 25], ['advanced-grammar', 2], ['advanced-grammar', 7]], prerequisiteIds: ['simple-sentences'], nextIds: ['simple-past', 'present-simple-vs-continuous'],
    relatedPaths: ['/blog/grammar-tenses', '/blog/grammar-subject-verb'],
  }),
  page({
    id: 'simple-past', slug: 'simple-past-tense-for-kids', level: 'beginner', stageOrder: 5, progressionRank: 130,
    label: 'Simple Past Tense', cardTitle: 'Simple Past Tense for Kids', parentQuestion: 'When do children use the simple past tense?',
    quickAnswer: 'Use the simple past for actions, events or states understood as completed in the past. English uses both regular past forms and many common irregular forms.',
    teachingBoundary: 'Do not teach past tense as “add -ed” only. After did or did not, the main verb returns to its base form.',
    examples: ['We visited the museum yesterday.', 'She went home early.', 'Did you finish the book?'],
    teachingSteps: ['Identify a finished past time.', 'Choose the correct regular or irregular past form.', 'Practise statements, negatives and questions.'],
    commonMistakes: ['Overgeneralising -ed to irregular verbs.', 'Using did + past form.', 'Switching back to present inside a past retelling without reason.'],
    practiceIdeas: ['Retell three completed events.', 'Sort regular and irregular past verbs.', 'Repair did/didn’t sentences.'],
    curriculumRefs: [['basic-grammar', 26], ['advanced-grammar', 3], ['advanced-grammar', 8], ['advanced-grammar', 10], ['advanced-grammar', 11]], prerequisiteIds: ['simple-present'], nextIds: ['simple-future', 'past-simple-vs-continuous'],
    relatedPaths: ['/blog/grammar-tenses'],
  }),
  page({
    id: 'simple-future', slug: 'simple-future-tense-for-kids', level: 'beginner', stageOrder: 5, progressionRank: 140,
    label: 'Simple Future with Will', cardTitle: 'Simple Future Tense for Kids', parentQuestion: 'How do children use will for future time?',
    quickAnswer: 'Will + base verb is a useful starting future form for predictions, decisions, promises and straightforward statements about later time.',
    teachingBoundary: 'Will is not the only way English expresses the future. Later learning should include going to, present continuous arrangements and timetable uses of simple present.',
    examples: ['I will call you later.', 'It will rain tomorrow.', 'We will help you.'],
    teachingSteps: ['Connect will to a future meaning.', 'Keep the main verb in base form.', 'Compare predictions, decisions and planned arrangements.'],
    commonMistakes: ['Using will + past or -s verb form.', 'Using will for every future context.', 'Confusing a plan with a decision made at the moment.'],
    practiceIdeas: ['Make a prediction.', 'Respond to a situation with an immediate decision.', 'Rewrite future sentences using the correct base verb.'],
    curriculumRefs: [['basic-grammar', 27], ['advanced-grammar', 4], ['advanced-grammar', 9]], prerequisiteIds: ['simple-past'], nextIds: ['future-forms'],
    relatedPaths: ['/blog/grammar-tenses'],
  }),
  page({
    id: 'questions-short-answers', slug: 'questions-and-short-answers-for-kids', level: 'beginner', stageOrder: 5, progressionRank: 150,
    label: 'Questions & Short Answers', cardTitle: 'Questions and Short Answers for Kids', parentQuestion: 'How do children form clear questions and short answers?',
    quickAnswer: 'English questions often use an auxiliary before the subject, while short answers repeat the matching auxiliary rather than the whole sentence.',
    teachingBoundary: 'Question formation depends on the verb system. Do not teach one fixed word order for every question type.',
    examples: ['Do you like puzzles? Yes, I do.', 'Is she ready? No, she isn’t.', 'Where did they go?'],
    teachingSteps: ['Identify the tense or verb type.', 'Choose the matching auxiliary or be verb.', 'Build the question and answer with natural word order.'],
    commonMistakes: ['Missing the auxiliary.', 'Using did + past form.', 'Answering Yes, I am to a do-question.'],
    practiceIdeas: ['Turn statements into questions.', 'Match questions to short answers.', 'Ask follow-up questions from a picture or topic.'],
    curriculumRefs: [['basic-grammar', 29], ['advanced-grammar', 13], ['advanced-grammar', 14]], prerequisiteIds: ['simple-present', 'simple-past'], nextIds: ['negative-sentences'],
    relatedPaths: ['/blog/grammar-tenses'],
  }),
  page({
    id: 'word-order', slug: 'word-order-and-jumbled-sentences-for-kids', level: 'beginner', stageOrder: 6, progressionRank: 160,
    label: 'Word Order & Jumbled Sentences', cardTitle: 'Word Order and Jumbled Sentences for Kids', parentQuestion: 'How can jumbled sentences help children learn English word order?',
    quickAnswer: 'Jumbled-sentence practice helps children notice how English subjects, verbs, objects and details fit together, but the goal is independent sentence generation rather than puzzle solving alone.',
    teachingBoundary: 'Do not use only one repeated sentence pattern. Children need varied sentence types and fresh writing so word order transfers beyond rearranging cards.',
    examples: ['reads / Maya / every night → Maya reads every night.', 'the kite / flew / above the trees → The kite flew above the trees.'],
    teachingSteps: ['Find the likely subject and verb first.', 'Add objects and details in a natural order.', 'Read the sentence aloud and check meaning.'],
    commonMistakes: ['Placing time/place details mechanically.', 'Making a grammatical order that changes the intended meaning.', 'Succeeding with rearranging but not generating a new sentence.'],
    practiceIdeas: ['Reorder mixed words.', 'Explain why one order sounds clearer.', 'Write a fresh sentence with the same structure.'],
    curriculumRefs: [['basic-grammar', 31]], prerequisiteIds: ['simple-sentences'], nextIds: ['picture-description', 'subject-verb-object'],
    relatedPaths: ['/blog/how-to-improve-sentence-formation-in-kids'],
    practicePaths: ['/free-sentence-building-games-for-kids'],
  }),
  page({
    id: 'picture-description', slug: 'picture-description-for-kids', level: 'beginner', stageOrder: 6, progressionRank: 170,
    label: 'Picture Description', cardTitle: 'Picture Description for Kids', parentQuestion: 'How can children describe a picture using clear sentences?',
    quickAnswer: 'Picture description helps children turn observation into complete sentences by selecting relevant details, using precise vocabulary and organising what they notice.',
    teachingBoundary: 'The goal is not to list every object in the picture. Encourage complete, connected observations that communicate what is important.',
    examples: ['A boy is balancing on a red bicycle.', 'Behind him, two friends are waiting near the gate.', 'The dark clouds suggest that rain may start soon.'],
    teachingSteps: ['Observe before speaking or writing.', 'Choose the main action or focus.', 'Add location, detail or inference only when it improves meaning.'],
    commonMistakes: ['Listing nouns instead of making sentences.', 'Repeating “I can see” in every sentence.', 'Adding details that are not supported by the picture.'],
    practiceIdeas: ['Describe one foreground and one background detail.', 'Combine two related observations.', 'Move from oral description to a short written paragraph.'],
    curriculumRefs: [['basic-grammar', 33]], prerequisiteIds: ['word-order', 'expanding-sentences'], nextIds: ['subject-verb-object', 'paragraph-cohesion'],
    relatedPaths: ['/blog/how-to-teach-paragraph-writing-to-kids'],
    practicePaths: ['/free-sentence-building-games-for-kids'],
  }),
  page({
    id: 'subject-verb-object', slug: 'subject-verb-object-for-kids', level: 'advanced', stageOrder: 1, progressionRank: 210,
    label: 'Subject, Verb & Object', cardTitle: 'Subject, Verb and Object for Kids', parentQuestion: 'What are the subject, verb and object in a sentence?',
    quickAnswer: 'The subject is who or what the clause is about, the verb expresses the action or state, and an object receives or completes certain verb meanings when the verb requires one.',
    teachingBoundary: 'Not every sentence has an object, and not every word after a verb is an object. Identify the verb and meaning before labelling sentence parts.',
    examples: ['Maya opened the window. → Maya / opened / the window', 'The baby slept. → subject + verb, no object', 'They became tired. → tired is a complement, not an object'],
    teachingSteps: ['Find the main verb.', 'Ask who or what performs or carries the clause meaning.', 'Check whether the verb has an object.'],
    commonMistakes: ['Assuming every sentence is SVO.', 'Calling an adjective complement an object.', 'Confusing the subject with the first noun in a longer sentence.'],
    practiceIdeas: ['Label subject and verb first, then test for an object.', 'Compare transitive and non-object examples.', 'Build several sentence patterns from the same vocabulary.'],
    curriculumRefs: [['advanced-grammar', 1]], prerequisiteIds: ['simple-sentences', 'word-order'], nextIds: ['present-simple-vs-continuous', 'compound-sentences'],
    relatedPaths: ['/blog/how-to-improve-sentence-formation-in-kids'],
  }),
  page({
    id: 'present-simple-vs-continuous', slug: 'simple-present-vs-present-continuous-for-kids', level: 'advanced', stageOrder: 2, progressionRank: 220,
    label: 'Simple Present vs Present Continuous', cardTitle: 'Simple Present vs Present Continuous for Kids', parentQuestion: 'What is the difference between simple present and present continuous?',
    quickAnswer: 'Use simple present for routines, repeated actions and general states; use present continuous for actions or temporary situations in progress around now.',
    teachingBoundary: 'Time words are clues, not automatic rules. Choose the tense from the intended meaning and context.',
    examples: ['Maya wears glasses. / Maya is wearing sunglasses today.', 'I read every evening. / I am reading now.'],
    teachingSteps: ['Decide whether the meaning is routine/general or in progress/temporary.', 'Build the correct form.', 'Explain the choice in a fresh context.'],
    commonMistakes: ['Using simple present for every present-time action.', 'Omitting am/is/are from the continuous.', 'Using -ing alone as a complete verb phrase.'],
    practiceIdeas: ['Sort routine vs happening-now situations.', 'Write a contrast pair.', 'Correct tense choice from a short context.'],
    curriculumRefs: [['advanced-grammar', 7]], prerequisiteIds: ['simple-present'], nextIds: ['past-simple-vs-continuous', 'future-forms'],
    relatedPaths: ['/blog/grammar-tenses'],
  }),
  page({
    id: 'past-simple-vs-continuous', slug: 'simple-past-vs-past-continuous-for-kids', level: 'advanced', stageOrder: 2, progressionRank: 230,
    label: 'Simple Past vs Past Continuous', cardTitle: 'Simple Past vs Past Continuous for Kids', parentQuestion: 'What is the difference between simple past and past continuous?',
    quickAnswer: 'Use simple past for completed events or event steps; use past continuous for an action that was in progress at a past time, often as background around another event.',
    teachingBoundary: 'Past continuous should not replace simple past for every event in a story. Use it when the ongoing past frame matters.',
    examples: ['The phone rang. / I was reading when the phone rang.', 'We played outside. / We were playing when it started to rain.'],
    teachingSteps: ['Identify completed event versus ongoing background.', 'Build was/were + verb-ing correctly.', 'Combine background and event in one meaningful sentence.'],
    commonMistakes: ['Using was/were with the wrong subject.', 'Using past continuous for a short completed event.', 'Confusing when and while mechanically.'],
    practiceIdeas: ['Match background actions to interrupting events.', 'Complete when/while sentence pairs.', 'Retell a scene using both tenses.'],
    curriculumRefs: [['advanced-grammar', 8]], prerequisiteIds: ['simple-past', 'present-simple-vs-continuous'], nextIds: ['future-forms', 'present-perfect-vs-simple-past'],
    relatedPaths: ['/blog/grammar-tenses'],
  }),
  page({
    id: 'future-forms', slug: 'future-forms-for-kids', level: 'advanced', stageOrder: 2, progressionRank: 240,
    label: 'Future Forms', cardTitle: 'Future Forms for Kids', parentQuestion: 'When should children use will, going to or present forms for the future?',
    quickAnswer: 'English future meaning can use will, be going to, present continuous or simple present depending on whether the speaker is predicting, deciding, planning, arranging or referring to a schedule.',
    teachingBoundary: 'These forms are related but not interchangeable. Teach the meaning choice rather than treating every future reference as will.',
    examples: ['I think it will rain.', 'We are going to visit the museum.', 'I am meeting my teacher at five.', 'The train leaves at six.'],
    teachingSteps: ['Identify the speaker’s purpose.', 'Choose the form that best matches that purpose.', 'Compare a different form and explain the meaning shift.'],
    commonMistakes: ['Using will for every future sentence.', 'Omitting be in going to.', 'Confusing an intention with a fixed arrangement or schedule.'],
    practiceIdeas: ['Sort predictions, intentions, arrangements and timetables.', 'Rewrite one context with the most natural future form.', 'Explain why two future forms are not identical.'],
    curriculumRefs: [['advanced-grammar', 9]], prerequisiteIds: ['simple-future', 'present-simple-vs-continuous'], nextIds: ['present-perfect-vs-simple-past'],
    relatedPaths: ['/blog/grammar-tenses'],
  }),
  page({
    id: 'present-perfect-vs-simple-past', slug: 'present-perfect-vs-simple-past-for-kids', level: 'advanced', stageOrder: 2, progressionRank: 250,
    label: 'Present Perfect vs Simple Past', cardTitle: 'Present Perfect vs Simple Past for Kids', parentQuestion: 'What is the difference between present perfect and simple past?',
    quickAnswer: 'Use simple past for a finished past event at a finished past time; use present perfect when a past experience or event is connected to the present and the focus is not a finished past time point.',
    teachingBoundary: 'Do not use present perfect with a finished time marker such as yesterday when the sentence refers to that completed time.',
    examples: ['I visited Jaipur last year. / I have visited Jaipur three times.', 'She finished her homework at six. / She has just finished her homework.'],
    teachingSteps: ['Ask whether the past time is finished and named.', 'Check whether the present connection matters.', 'Build have/has + past participle accurately.'],
    commonMistakes: ['Using present perfect with yesterday/last year.', 'Using simple past form instead of past participle.', 'Confusing have and has.'],
    practiceIdeas: ['Sort finished-time and present-linked contexts.', 'Create contrast pairs.', 'Edit already/yet/ever/last-week examples.'],
    curriculumRefs: [['advanced-grammar', 10]], prerequisiteIds: ['simple-past'], nextIds: ['past-perfect'],
    relatedPaths: ['/blog/grammar-tenses'],
  }),
  page({
    id: 'past-perfect', slug: 'past-perfect-tense-for-kids', level: 'advanced', stageOrder: 2, progressionRank: 260,
    label: 'Past Perfect', cardTitle: 'Past Perfect Tense for Kids', parentQuestion: 'When do children use the past perfect tense?',
    quickAnswer: 'Use past perfect to make one past event clearly earlier than another past reference point when that earlier relationship needs to be explicit.',
    teachingBoundary: 'Do not force past perfect into every story with two past events. Use it when it clarifies which event happened first.',
    examples: ['The film had started before we arrived.', 'She had finished her work when her friend called.'],
    teachingSteps: ['Identify two past reference points.', 'Decide whether the earlier event needs explicit marking.', 'Use had + past participle for that earlier event.'],
    commonMistakes: ['Using past perfect for both events unnecessarily.', 'Using had + simple past instead of participle.', 'Choosing the wrong event as earlier.'],
    practiceIdeas: ['Order two past events.', 'Combine them using past perfect where useful.', 'Remove unnecessary past perfect from over-marked examples.'],
    curriculumRefs: [['advanced-grammar', 11]], prerequisiteIds: ['present-perfect-vs-simple-past'], nextIds: ['negative-sentences'],
    relatedPaths: ['/blog/grammar-tenses'],
  }),
  page({
    id: 'negative-sentences', slug: 'negative-sentences-for-kids', level: 'advanced', stageOrder: 3, progressionRank: 270,
    label: 'Negative Sentences', cardTitle: 'Negative Sentences for Kids', parentQuestion: 'How do children form negative sentences correctly?',
    quickAnswer: 'Negative sentences use the appropriate auxiliary or be verb with not, while the main verb form depends on the tense and construction.',
    teachingBoundary: 'Do not attach not to the main verb mechanically. First identify whether the sentence uses be, do-support, a modal or another auxiliary.',
    examples: ['She is not ready.', 'He does not play chess.', 'They did not arrive late.', 'We cannot stay.'],
    teachingSteps: ['Identify the verb system.', 'Choose the correct auxiliary.', 'Place not correctly and keep the main verb form accurate.'],
    commonMistakes: ['He doesn’t plays.', 'They not went.', 'Using the wrong auxiliary for tense or subject.'],
    practiceIdeas: ['Change affirmative sentences into negatives.', 'Repair auxiliary + verb errors.', 'Write positive/negative contrast pairs.'],
    curriculumRefs: [['advanced-grammar', 14]], prerequisiteIds: ['questions-short-answers'], nextIds: ['modal-verbs'],
    relatedPaths: ['/blog/grammar-tenses'],
  }),
  page({
    id: 'modal-verbs', slug: 'modal-verbs-for-kids', level: 'advanced', stageOrder: 3, progressionRank: 280,
    label: 'Modal Verbs', cardTitle: 'Modal Verbs for Kids', parentQuestion: 'What are modal verbs and how do children choose them?',
    quickAnswer: 'Modal verbs such as can, could, may, might, should and must help express meanings including ability, possibility, permission, advice and obligation.',
    teachingBoundary: 'Teach the meaning and strength of the modal, not just a list. A modal is normally followed by the base form of the main verb.',
    examples: ['You should rest.', 'She can swim.', 'It might rain.', 'We must wear helmets.'],
    teachingSteps: ['Name the intended meaning.', 'Compare modals with different strength or politeness.', 'Use modal + base verb in a complete sentence.'],
    commonMistakes: ['Adding -s or to after a modal.', 'Treating should and must as identical.', 'Using can/could without considering meaning or politeness.'],
    practiceIdeas: ['Rank advice from weak to strong.', 'Choose a modal for a real-life situation.', 'Rewrite one sentence with a different modal and discuss the change.'],
    curriculumRefs: [['advanced-grammar', 15]], prerequisiteIds: ['negative-sentences'], nextIds: ['quantifiers'],
    relatedPaths: ['/blog/grammar-tenses'],
  }),
  page({
    id: 'quantifiers', slug: 'quantifiers-for-kids', level: 'advanced', stageOrder: 3, progressionRank: 290,
    label: 'Quantifiers', cardTitle: 'Quantifiers for Kids', parentQuestion: 'How do children use much, many, some, any, few and little?',
    quickAnswer: 'Quantifiers express amount or number, and the correct choice depends on whether the noun is countable, uncountable and what meaning the speaker wants.',
    teachingBoundary: 'Do not teach much/many or few/little as isolated pairs without first establishing countable versus uncountable nouns and the intended quantity meaning.',
    examples: ['many books', 'much water', 'a few questions', 'a little time', 'some rice', 'any ideas?'],
    teachingSteps: ['Classify the noun as countable or uncountable.', 'Choose the quantity meaning.', 'Select the quantifier that fits both grammar and meaning.'],
    commonMistakes: ['much books / many water.', 'Confusing few with a few.', 'Using some and any mechanically without context.'],
    practiceIdeas: ['Sort nouns by countability.', 'Choose quantifiers in mini-dialogues.', 'Explain how few and a few change the message.'],
    curriculumRefs: [['advanced-grammar', 16]], prerequisiteIds: ['singular-plural', 'articles'], nextIds: ['clear-pronoun-reference'],
    relatedPaths: ['/blog/how-to-improve-sentence-formation-in-kids'],
  }),
  page({
    id: 'clear-pronoun-reference', slug: 'clear-pronoun-reference-for-kids', level: 'advanced', stageOrder: 3, progressionRank: 300,
    label: 'Clear Pronoun Reference', cardTitle: 'Clear Pronoun Reference for Kids', parentQuestion: 'How can children avoid unclear pronouns and repetition?',
    quickAnswer: 'A pronoun should point clearly to the intended noun. Good writing balances useful pronouns with repeated nouns when repetition is needed for clarity.',
    teachingBoundary: 'Avoid replacing every repeated noun. If two possible antecedents exist, repeating the noun can be clearer than using he, she, it or they.',
    examples: ['Ravi spoke to Arjun after he arrived. → Who arrived?', 'Ravi arrived and then spoke to Arjun. He explained the plan.'],
    teachingSteps: ['Find the pronoun.', 'Identify every noun it could refer to.', 'Rewrite until only the intended reference is plausible.'],
    commonMistakes: ['Ambiguous he/she/they.', 'Number mismatch.', 'Overusing pronouns until the topic becomes unclear.'],
    practiceIdeas: ['Repair ambiguous references.', 'Replace repetition only where clarity remains.', 'Compare two rewrites and choose the clearest.'],
    curriculumRefs: [['advanced-grammar', 17]], prerequisiteIds: ['pronouns'], nextIds: ['compound-sentences'],
    relatedPaths: ['/blog/grammar-editing-camp'],
  }),
  page({
    id: 'compound-sentences', slug: 'compound-sentences-for-kids', level: 'advanced', stageOrder: 4, progressionRank: 310,
    label: 'Compound Sentences', cardTitle: 'Compound Sentences for Kids', parentQuestion: 'What is a compound sentence for kids?',
    quickAnswer: 'A compound sentence joins two independent clauses that could each stand alone, often with a coordinating conjunction such as and, but, or, so, yet, for or nor.',
    teachingBoundary: 'Do not call every sentence containing and a compound sentence. The joined parts must function as independent clauses.',
    examples: ['The rain stopped, and we went outside.', 'I wanted to stay, but the bus had arrived.'],
    teachingSteps: ['Check each clause for completeness.', 'Identify the relationship between the ideas.', 'Choose a connector and punctuation that fit.'],
    commonMistakes: ['Comma splices.', 'Run-ons without punctuation or connector.', 'Joining a sentence to a phrase and calling both clauses.'],
    practiceIdeas: ['Join clause pairs with suitable conjunctions.', 'Split a compound sentence into two complete clauses.', 'Compare and/but/so choices.'],
    curriculumRefs: [['advanced-grammar', 19]], prerequisiteIds: ['subject-verb-object', 'simple-sentences'], nextIds: ['reason-result', 'time-sequence'],
    relatedPaths: ['/blog/grammar-conjunctions'],
    practicePaths: ['/free-sentence-building-games-for-kids'],
  }),
  page({
    id: 'reason-result', slug: 'reason-and-result-connectors-for-kids', level: 'advanced', stageOrder: 4, progressionRank: 320,
    label: 'Reason & Result Connectors', cardTitle: 'Reason and Result Connectors for Kids', parentQuestion: 'How do children express reason and result clearly?',
    quickAnswer: 'Reason and result language shows why something happened and what happened because of it, using structures such as because, so, therefore and as a result according to sentence form and tone.',
    teachingBoundary: 'Because and so express related meanings from different directions; do not stack them automatically in the same basic sentence.',
    examples: ['We stayed inside because it was raining.', 'It was raining, so we stayed inside.', 'The road was closed; therefore, the bus was delayed.'],
    teachingSteps: ['Identify cause and effect.', 'Choose whether the sentence starts from the reason or result.', 'Select a connector and punctuate the structure correctly.'],
    commonMistakes: ['Because…so in the same basic construction.', 'Confusing cause and result.', 'Creating a because-clause fragment.'],
    practiceIdeas: ['Match causes to results.', 'Rewrite because sentences using so.', 'Explain which event is the reason.'],
    curriculumRefs: [['advanced-grammar', 20]], prerequisiteIds: ['compound-sentences'], nextIds: ['time-sequence', 'conditionals'],
    relatedPaths: ['/blog/grammar-conjunctions'],
  }),
  page({
    id: 'time-sequence', slug: 'time-and-sequence-connectors-for-kids', level: 'advanced', stageOrder: 4, progressionRank: 330,
    label: 'Time & Sequence Connectors', cardTitle: 'Time and Sequence Connectors for Kids', parentQuestion: 'How do children connect events in time and sequence?',
    quickAnswer: 'Time and sequence connectors such as before, after, when, while, first, next and finally help show the order or timing relationship between events.',
    teachingBoundary: 'Do not treat sequence words as decoration. Choose them only when they clarify order, overlap or timing.',
    examples: ['Before we left, we checked the tickets.', 'I was reading while my sister was drawing.', 'First we measured; then we mixed the ingredients.'],
    teachingSteps: ['Put events in logical order.', 'Decide whether they happen before, after or at the same time.', 'Choose a connector that expresses that relationship.'],
    commonMistakes: ['Reversing before/after logic.', 'Confusing when and while.', 'Using first/next/finally in every paragraph even when no sequence is needed.'],
    practiceIdeas: ['Arrange event cards.', 'Join event pairs with different time connectors.', 'Write a short process or narrative sequence.'],
    curriculumRefs: [['advanced-grammar', 21]], prerequisiteIds: ['compound-sentences'], nextIds: ['conditionals', 'contrast-concession'],
    relatedPaths: ['/blog/grammar-conjunctions'],
  }),
  page({
    id: 'conditionals', slug: 'conditionals-for-kids', level: 'advanced', stageOrder: 4, progressionRank: 340,
    label: 'Conditions & Possibilities', cardTitle: 'Conditionals for Kids', parentQuestion: 'How do conditionals help children talk about possibilities?',
    quickAnswer: 'Conditional sentences connect a condition with its result, allowing children to express real possibilities, general results and later imagined or hypothetical situations.',
    teachingBoundary: 'Do not force every if-sentence into one formula. Choose the form from the meaning, and avoid unnecessary will inside a basic if-clause.',
    examples: ['If you heat ice, it melts.', 'If it rains tomorrow, we will stay inside.', 'If I had more time, I would learn the guitar.'],
    teachingSteps: ['Identify the condition and result.', 'Decide whether the meaning is general, real future or imagined.', 'Build both clauses with the appropriate verb forms.'],
    commonMistakes: ['Using will in both clauses of a first conditional.', 'Confusing real and hypothetical meaning.', 'Leaving one clause incomplete.'],
    practiceIdeas: ['Finish realistic if-sentences.', 'Compare real and imagined conditions.', 'Rewrite unless as an if-not meaning where appropriate.'],
    curriculumRefs: [['advanced-grammar', 22]], prerequisiteIds: ['future-forms', 'compound-sentences'], nextIds: ['contrast-concession'],
    relatedPaths: ['/blog/grammar-conjunctions'],
  }),
  page({
    id: 'contrast-concession', slug: 'contrast-and-concession-for-kids', level: 'advanced', stageOrder: 4, progressionRank: 350,
    label: 'Contrast & Concession', cardTitle: 'Contrast and Concession for Kids', parentQuestion: 'How do children connect contrasting ideas?',
    quickAnswer: 'Contrast and concession structures show difference or an unexpected relationship between ideas using words such as but, although, however, despite and even though.',
    teachingBoundary: 'Different connectors require different grammar and punctuation. Avoid combinations such as although… but in the same basic structure.',
    examples: ['I was tired, but I finished the project.', 'Although it was raining, the match continued.', 'The task was difficult; however, we solved it.'],
    teachingSteps: ['Identify the two contrasting ideas.', 'Choose a connector suitable for clause or phrase structure.', 'Punctuate the resulting sentence correctly.'],
    commonMistakes: ['Although + but together.', 'Using despite before a full clause without adjustment.', 'Missing punctuation around however.'],
    practiceIdeas: ['Join contrast pairs in two different ways.', 'Change but to although or however with correct restructuring.', 'Explain whether the relationship is simple contrast or concession.'],
    curriculumRefs: [['advanced-grammar', 23]], prerequisiteIds: ['compound-sentences'], nextIds: ['independent-dependent-clauses'],
    relatedPaths: ['/blog/grammar-conjunctions'],
  }),
  page({
    id: 'independent-dependent-clauses', slug: 'independent-and-dependent-clauses-for-kids', level: 'advanced', stageOrder: 5, progressionRank: 360,
    label: 'Independent & Dependent Clauses', cardTitle: 'Independent and Dependent Clauses for Kids', parentQuestion: 'What is the difference between an independent and dependent clause?',
    quickAnswer: 'An independent clause expresses a complete thought and can stand as a sentence; a dependent clause has a subject and verb but depends on another clause to complete the intended sentence meaning.',
    teachingBoundary: 'A dependent clause is not the same as any phrase. Clauses contain a subject-verb relationship; phrases may not.',
    examples: ['We stayed home. → independent', 'because it was raining → dependent', 'We stayed home because it was raining.'],
    teachingSteps: ['Find the subject and verb.', 'Test whether the clause can stand independently.', 'Combine clauses so the relationship is clear.'],
    commonMistakes: ['Treating a dependent clause as a complete sentence.', 'Calling every word group a clause.', 'Using commas mechanically with all clause combinations.'],
    practiceIdeas: ['Sort independent clauses, dependent clauses and phrases.', 'Repair clause fragments.', 'Combine clauses with different subordinators.'],
    curriculumRefs: [['advanced-grammar', 25]], prerequisiteIds: ['compound-sentences', 'conditionals'], nextIds: ['relative-clauses', 'sentence-variety'],
    relatedPaths: ['/blog/how-to-improve-sentence-formation-in-kids'],
  }),
  page({
    id: 'relative-clauses', slug: 'relative-clauses-for-kids', level: 'advanced', stageOrder: 5, progressionRank: 370,
    label: 'Relative Clauses', cardTitle: 'Relative Clauses for Kids', parentQuestion: 'How do relative clauses add information to a sentence?',
    quickAnswer: 'A relative clause adds information about a noun, often using who, which or that, so related ideas can be combined without repeating the noun.',
    teachingBoundary: 'Teach the noun being described before choosing the relative word. Comma use differs between information that identifies the noun and extra non-essential information.',
    examples: ['The girl who won the race is my cousin.', 'The book that I borrowed was fascinating.', 'My bicycle, which is ten years old, still works well.'],
    teachingSteps: ['Identify the noun to describe.', 'Choose the relative word.', 'Decide whether the information is identifying or extra.'],
    commonMistakes: ['Unclear noun reference.', 'Choosing who/which/that without considering the noun.', 'Using commas around every relative clause.'],
    practiceIdeas: ['Combine two sentences using a relative clause.', 'Identify the described noun.', 'Compare defining and extra-information examples.'],
    curriculumRefs: [['advanced-grammar', 26]], prerequisiteIds: ['independent-dependent-clauses'], nextIds: ['sentence-variety'],
    relatedPaths: ['/blog/how-to-improve-sentence-formation-in-kids'],
  }),
  page({
    id: 'sentence-variety', slug: 'sentence-variety-for-kids', level: 'advanced', stageOrder: 5, progressionRank: 380,
    label: 'Sentence Combining & Variety', cardTitle: 'Sentence Variety for Kids', parentQuestion: 'How can children combine sentences and create better sentence variety?',
    quickAnswer: 'Sentence variety comes from deliberately changing sentence length, structure, openings and clause relationships while preserving clear meaning.',
    teachingBoundary: 'Variety is not complexity for its own sake. The best structure is the one that communicates the intended relationship clearly.',
    examples: ['The storm ended. We went outside. → When the storm ended, we went outside.', 'Mira packed the map, and Arjun checked the water bottles.'],
    teachingSteps: ['Identify the relationship between ideas.', 'Choose coordination, subordination or another suitable structure.', 'Reread for clarity and rhythm.'],
    commonMistakes: ['Creating run-ons while combining.', 'Using the same opening repeatedly.', 'Changing the original meaning just to make the sentence longer.'],
    practiceIdeas: ['Combine sentence pairs in two ways.', 'Vary three repeated sentence openings.', 'Compare a clear short version with an overloaded long version.'],
    curriculumRefs: [['advanced-grammar', 27]], prerequisiteIds: ['relative-clauses', 'compound-sentences'], nextIds: ['sentence-repair'],
    relatedPaths: ['/blog/how-to-improve-sentence-formation-in-kids', '/blog/grammar-editing-camp'],
    practicePaths: ['/free-sentence-building-games-for-kids'],
  }),
  page({
    id: 'sentence-repair', slug: 'fragments-run-ons-and-comma-splices-for-kids', level: 'advanced', stageOrder: 5, progressionRank: 390,
    label: 'Fragments, Run-ons & Comma Splices', cardTitle: 'Fragments, Run-ons and Comma Splices for Kids', parentQuestion: 'How can children fix fragments, run-ons and comma splices?',
    quickAnswer: 'Sentence repair starts by checking whether each clause is complete and whether independent clauses are joined with suitable punctuation, conjunctions or sentence boundaries.',
    teachingBoundary: 'Do not fix every long sentence by cutting it in half. First diagnose whether the problem is incompleteness, missing connection or incorrect punctuation.',
    examples: ['Because we missed the bus. → fragment', 'I called her she answered. → run-on', 'I called her, she answered. → comma splice'],
    teachingSteps: ['Find each clause.', 'Decide whether each is independent or dependent.', 'Choose a repair that preserves the intended relationship.'],
    commonMistakes: ['Adding a period without fixing a dependent fragment.', 'Using a comma alone between independent clauses.', 'Joining too many clauses with and.'],
    practiceIdeas: ['Diagnose the error type before editing.', 'Repair one sentence in two valid ways.', 'Edit a short paragraph for sentence boundaries.'],
    curriculumRefs: [['advanced-grammar', 28]], prerequisiteIds: ['sentence-variety', 'independent-dependent-clauses'], nextIds: ['direct-reported-speech'],
    relatedPaths: ['/blog/grammar-editing-camp', '/blog/punctuation-and-capital-letters-for-kids'],
  }),
  page({
    id: 'direct-reported-speech', slug: 'direct-and-reported-speech-for-kids', level: 'advanced', stageOrder: 5, progressionRank: 400,
    label: 'Direct & Reported Speech', cardTitle: 'Direct and Reported Speech for Kids', parentQuestion: 'What is the difference between direct and reported speech?',
    quickAnswer: 'Direct speech gives a speaker’s words as a quotation; reported speech tells the content of what someone said and may require changes to pronouns, time words or tense depending on context.',
    teachingBoundary: 'Reported speech does not require a mechanical tense shift in every situation. Preserve meaning and consider whether the original statement is still current or the reporting context has changed.',
    examples: ['Asha said, “I am tired.”', 'Asha said that she was tired.', 'Ravi told me that the meeting starts at six.'],
    teachingSteps: ['Identify speaker and original message.', 'Choose direct quotation or reporting structure.', 'Adjust pronouns, time reference and tense only where needed.'],
    commonMistakes: ['Confusing said and told.', 'Incorrect quotation punctuation.', 'Changing tense even when context does not call for it.'],
    practiceIdeas: ['Convert short quotations to reported speech.', 'Restore reported messages as plausible direct speech.', 'Edit said/told usage.'],
    curriculumRefs: [['advanced-grammar', 29]], prerequisiteIds: ['sentence-repair'], nextIds: ['active-passive-voice'],
    relatedPaths: ['/blog/grammar-editing-camp'],
  }),
  page({
    id: 'active-passive-voice', slug: 'active-and-passive-voice-for-kids', level: 'advanced', stageOrder: 5, progressionRank: 410,
    label: 'Active & Passive Voice', cardTitle: 'Active and Passive Voice for Kids', parentQuestion: 'What is the difference between active and passive voice?',
    quickAnswer: 'Active voice usually places the doer as subject; passive voice makes the receiver or result more prominent using a form of be plus a past participle.',
    teachingBoundary: 'Passive voice is not automatically bad writing. Choose it when the receiver, process or result is more important or the doer is unknown or unnecessary.',
    examples: ['The chef prepared the meal. / The meal was prepared by the chef.', 'The window was broken during the storm.'],
    teachingSteps: ['Find who does the action and what receives it.', 'Build the passive with the correct be form and past participle.', 'Choose the voice that best fits purpose and focus.'],
    commonMistakes: ['Using be + simple past instead of participle.', 'Losing the original tense during conversion.', 'Adding an unnecessary by-phrase.'],
    practiceIdeas: ['Convert active to passive while keeping tense.', 'Choose the clearer voice for different purposes.', 'Find passive sentences where the doer is intentionally omitted.'],
    curriculumRefs: [['advanced-grammar', 30]], prerequisiteIds: ['direct-reported-speech'], nextIds: ['paragraph-cohesion'],
    relatedPaths: ['/blog/grammar-editing-camp'],
  }),
  page({
    id: 'paragraph-cohesion', slug: 'paragraph-cohesion-for-kids', level: 'advanced', stageOrder: 6, progressionRank: 420,
    label: 'Paragraph Cohesion & Flow', cardTitle: 'Paragraph Cohesion for Kids', parentQuestion: 'How can children make a paragraph flow clearly?',
    quickAnswer: 'A cohesive paragraph keeps one clear focus and connects sentences through logical order, reference, repeated key ideas and purposeful transitions rather than adding linking words everywhere.',
    teachingBoundary: 'Cohesion is more than transition words. A paragraph can contain many connectors and still feel disconnected if the ideas do not develop logically.',
    examples: ['Topic sentence → relevant detail → example → explanation → closing link', 'Pronouns and repeated key nouns can connect ideas when their reference is clear.'],
    teachingSteps: ['Check the paragraph focus.', 'Order sentences so each develops the previous idea.', 'Add transitions or reference words only where they clarify the connection.'],
    commonMistakes: ['Using firstly/secondly/finally in every paragraph.', 'Unclear pronoun reference between sentences.', 'Including details that do not support the main idea.'],
    practiceIdeas: ['Reorder a mixed paragraph.', 'Remove an off-topic sentence.', 'Improve transitions without changing the content.'],
    curriculumRefs: [['advanced-grammar', 31], ['advanced-grammar', 32]], prerequisiteIds: ['sentence-variety'], nextIds: ['narrative-grammar', 'description-explanation'],
    relatedPaths: ['/blog/how-to-teach-paragraph-writing-to-kids', '/blog/grammar-editing-camp'],
  }),
  page({
    id: 'narrative-grammar', slug: 'narrative-grammar-for-kids', level: 'advanced', stageOrder: 6, progressionRank: 430,
    label: 'Narrative Grammar', cardTitle: 'Narrative Grammar for Kids', parentQuestion: 'How does grammar support clear narrative writing?',
    quickAnswer: 'Narrative grammar helps a child sequence events, maintain an appropriate time frame, vary sentences and connect actions, background and details so a story is easy to follow.',
    teachingBoundary: 'A good narrative is not created by using “advanced grammar” in every sentence. Grammar should support event order, viewpoint and clarity.',
    examples: ['I was packing my bag when the lights went out.', 'After we found the torch, we continued preparing for the trip.'],
    teachingSteps: ['Establish the main time frame.', 'Sequence events and background clearly.', 'Vary sentence structures where the story meaning benefits.'],
    commonMistakes: ['Unplanned tense shifts.', 'Events presented out of order without signals.', 'Run-on sentences during excited storytelling.'],
    practiceIdeas: ['Retell a short event in one consistent time frame.', 'Add one background action using past continuous.', 'Edit a narrative for tense and sequence.'],
    curriculumRefs: [['advanced-grammar', 33]], prerequisiteIds: ['paragraph-cohesion', 'past-simple-vs-continuous'], nextIds: ['description-explanation'],
    relatedPaths: ['/blog/grammar-creative-writing', '/blog/how-to-teach-storytelling-to-kids'],
  }),
  page({
    id: 'description-explanation', slug: 'descriptive-and-explanatory-writing-for-kids', level: 'advanced', stageOrder: 6, progressionRank: 440,
    label: 'Description & Explanation', cardTitle: 'Descriptive and Explanatory Writing for Kids', parentQuestion: 'How can children write clearer descriptions and explanations?',
    quickAnswer: 'Clear descriptive and explanatory writing selects precise information, organises it for the reader and uses sentence structures and connectors that make relationships easy to follow.',
    teachingBoundary: 'Description is not a list of adjectives, and explanation is not a list of facts. Both require selection, organisation and clear relationships between ideas.',
    examples: ['The narrow trail curved between two steep hills.', 'Water evaporates faster when heat gives its particles more energy.'],
    teachingSteps: ['Decide the purpose: describe or explain.', 'Select precise relevant details.', 'Organise sentences so the reader can build the intended picture or understanding.'],
    commonMistakes: ['Vague vocabulary.', 'List-like sentences with no connection.', 'Adding decorative detail that distracts from the purpose.'],
    practiceIdeas: ['Improve vague nouns and verbs.', 'Turn a fact list into an explanation.', 'Compare descriptive detail with explanatory detail.'],
    curriculumRefs: [['advanced-grammar', 34]], prerequisiteIds: ['paragraph-cohesion'], nextIds: ['opinion-reason-evidence'],
    relatedPaths: ['/blog/grammar-creative-writing'],
  }),
  page({
    id: 'opinion-reason-evidence', slug: 'opinion-reason-and-evidence-for-kids', level: 'advanced', stageOrder: 6, progressionRank: 450,
    label: 'Opinion, Reason & Evidence', cardTitle: 'Opinion, Reason and Evidence for Kids', parentQuestion: 'How can children support an opinion with reasons and evidence?',
    quickAnswer: 'Strong opinion writing states a clear position, gives relevant reasons and supports those reasons with examples, facts or explanations so the reader can follow the argument.',
    teachingBoundary: 'A reason is not automatically evidence. Teach children to distinguish the claim, why they believe it and what example or evidence supports that reason.',
    examples: ['Claim: School gardens are useful. Reason: They support practical science learning. Evidence: Students can observe plant growth and measure changes over time.'],
    teachingSteps: ['State one clear opinion.', 'Give a reason that directly supports it.', 'Add an example or evidence and explain the connection.'],
    commonMistakes: ['Repeating the claim as the reason.', 'Using unrelated evidence.', 'Adding strong words instead of support.'],
    practiceIdeas: ['Sort claim/reason/evidence cards.', 'Strengthen a weak reason with an example.', 'Write a short CER-style paragraph and edit for relevance.'],
    curriculumRefs: [['advanced-grammar', 35]], prerequisiteIds: ['paragraph-cohesion', 'reason-result'], nextIds: [],
    relatedPaths: ['/blog/grammar-creative-writing', '/writing-classes-for-kids'],
  }),
]);

export const GRAMMAR_PUBLISHED_RESOURCE_PATHS = freezeList(
  GRAMMAR_PUBLISHED_RESOURCE_PAGES.map((item) => item.path),
);

export const GRAMMAR_PUBLISHED_RESOURCE_SEO = freeze(Object.fromEntries(
  GRAMMAR_PUBLISHED_RESOURCE_PAGES.map((item) => [item.path, freeze({
    title: `${item.cardTitle} | Examples & Practice | Tiny Steps`,
    description: `${item.quickAnswer} See examples, common mistakes, curriculum placement and practice ideas.`,
    canonicalPath: item.path,
    robots: 'index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1',
    ogType: 'website',
  })]),
));

const bySlug = new Map(GRAMMAR_PUBLISHED_RESOURCE_PAGES.map((item) => [item.slug, item]));
const byId = new Map(GRAMMAR_PUBLISHED_RESOURCE_PAGES.map((item) => [item.id, item]));
const byPath = new Map(GRAMMAR_PUBLISHED_RESOURCE_PAGES.map((item) => [item.path, item]));

export const getPublishedGrammarResourcePageBySlug = (slug) => bySlug.get(String(slug || '')) ?? null;
export const getPublishedGrammarResourcePageById = (id) => byId.get(String(id || '')) ?? null;
export const getPublishedGrammarResourcePageByPath = (pathname) => {
  const normalized = String(pathname || '').split(/[?#]/, 1)[0].replace(/\/+$/, '');
  return byPath.get(normalized) ?? null;
};
export const getPublishedGrammarResourcePagesForStage = (level, stageOrder) => freezeList(
  GRAMMAR_PUBLISHED_RESOURCE_PAGES.filter((item) => item.level === level && item.stageOrder === Number(stageOrder)),
);

for (const [label, values] of [
  ['id', GRAMMAR_PUBLISHED_RESOURCE_PAGES.map((item) => item.id)],
  ['slug', GRAMMAR_PUBLISHED_RESOURCE_PAGES.map((item) => item.slug)],
  ['path', GRAMMAR_PUBLISHED_RESOURCE_PAGES.map((item) => item.path)],
]) {
  if (new Set(values).size !== values.length) throw new Error(`Grammar publication registry contains duplicate ${label} values.`);
}
if (GRAMMAR_PUBLISHED_RESOURCE_PAGES.some((item, index, list) => index > 0 && item.progressionRank <= list[index - 1].progressionRank)) {
  throw new Error('Grammar publication registry must remain in strict curriculum progression order.');
}
