const normalizePublicAnalyticsPath = (pathname = '/') =>
  (String(pathname || '/').toLowerCase().replace(/\/+$/, '') || '/');

const PUBLIC_ANALYTICS_STATIC_PATHS = new Set([
  "/",
  "/best-online-phonics-classes-for-kids-in-india",
  "/blog",
  "/blog/what-is-jolly-phonics-and-is-it-the-best-way-to-teach-reading",
  "/book-demo",
  "/careers",
  "/child-not-reading-properly",
  "/class-samples",
  "/confidence-building-program-kids",
  "/contact",
  "/courses",
  "/curriculum",
  "/english-classes-for-4-year-old",
  "/english-classes-for-5-year-old",
  "/english-classes-for-6-year-old",
  "/english-classes-for-7-10-year-old",
  "/english-foundation-program",
  "/english-grammar-writing-classes",
  "/faq",
  "/for-schools",
  "/free-balloon-pop-phonics-game-for-kids",
  "/free-english-games-for-kids",
  "/free-games/word-meaning-flashcards",
  "/free-grammar-games-for-kids",
  "/free-grammar-practice-game-for-kids",
  "/free-letter-sound-games-for-kids",
  "/free-letter-sounds-game-for-kids",
  "/free-letter-tracing-game-for-kids",
  "/free-phonics-games-for-kids",
  "/free-reading-fluency-game-for-kids",
  "/free-reading-games-for-kids",
  "/free-sentence-building-games-for-kids",
  "/free-sentence-making-game-for-kids",
  "/free-sound-listening-game-for-kids",
  "/free-speaking-games-for-kids",
  "/free-speaking-practice-game-for-kids",
  "/free-spelling-game-for-kids",
  "/free-word-building-game-for-kids",
  "/free-word-building-games-for-kids",
  "/grammar",
  "/learning-partner",
  "/letter-tracing-with-sounds-game",
  "/online-english-classes-for-kids",
  "/online-english-classes-hyderabad",
  "/parents",
  "/parents/choosing-course",
  "/parents/common-mistakes",
  "/parents/getting-started",
  "/parents/helping-with-homework",
  "/parents/payments",
  "/parents/phonics-mission",
  "/parents/reading-at-home",
  "/parents/scheduling",
  "/parents/speech-confidence",
  "/parents/tracking-progress",
  "/phonics",
  "/phonics-apps-for-preschoolers-india",
  "/phonics-fees-india",
  "/phonics-games-for-preschoolers",
  "/phonics-learning-games",
  "/pricing",
  "/privacy-policy",
  "/reading-classes-for-kids",
  "/reading-fluency-program",
  "/refund-guarantee",
  "/resources",
  "/resources/grammar",
  "/resources/phonics",
  "/resources/speaking",
  "/seasonal/christmas-tree",
  "/shy-child-speaking-confidence",
  "/sitemap",
  "/slow-reader-child-help",
  "/speaking",
  "/speaking-progress-framework",
  "/spoken-english-classes-for-kids-online",
  "/summer-camp-for-kids-india",
  "/summer-camps",
  "/summer-camps/grammar-fast-track",
  "/summer-camps/phonics-fast-track",
  "/summer-camps/speaking-fast-track",
  "/summer-reading-program-kids",
  "/summer-speaking-camp-kids",
  "/team",
  "/team/vannala-ravali-priya",
  "/terms-and-conditions",
  "/testimonials",
  "/why-tiny-steps",
  "/writing-classes-for-kids",
]);

const PUBLIC_ANALYTICS_DYNAMIC_PREFIXES = Object.freeze([
  '/blog/',
  '/courses/',
  '/resources/phonics/',
  '/resources/grammar/',
]);

const PUBLIC_ANALYTICS_EXCLUSIONS = new Set(['/parents/payments']);
const PUBLIC_ANALYTICS_ALIASES = new Set([
  '/games/english-excellence',
  '/online-phonics-reading-classes',
]);

export function isPublicAnalyticsPath(pathname) {
  const normalized = normalizePublicAnalyticsPath(pathname);
  if (PUBLIC_ANALYTICS_EXCLUSIONS.has(normalized)) return false;
  if (PUBLIC_ANALYTICS_ALIASES.has(normalized)) return true;
  if (PUBLIC_ANALYTICS_STATIC_PATHS.has(normalized)) return true;
  return PUBLIC_ANALYTICS_DYNAMIC_PREFIXES.some((prefix) => normalized.startsWith(prefix));
}
