export const RESOURCE_SEARCH_INTENTS = Object.freeze([
  'informational',
  'practice',
  'problem-aware',
  'progress-aware',
  'solution-aware',
  'commercial',
  'high-commercial',
  'transactional-brand',
]);

export const RESOURCE_CTA_POLICIES = Object.freeze([
  'none',
  'related-resource',
  'practice',
  'assessment',
  'programme',
  'pricing',
  'demo',
  'schools',
]);

export const RESOURCE_COMMERCIAL_READINESS = Object.freeze([
  'none',
  'low',
  'medium',
  'high',
  'very-high',
]);

const entry = (path, config) => Object.freeze({ path, ...config });

/**
 * R0 semantic ownership registry for the Resources architecture.
 *
 * This does NOT change routing, canonicals, redirects, indexability, or CTAs.
 * It records the current job of protected public URLs so later Resources bricks
 * can add a semantic orchestration layer without silently changing intent owners.
 */
export const RESOURCE_ECOSYSTEM_REGISTRY = Object.freeze([
  entry('/', {
    currentState: 'route',
    pageFamily: 'commercial-hub',
    audience: 'parents',
    subject: 'general-english',
    currentPurpose: 'Brand and broad online English class acquisition.',
    primaryIntent: 'commercial',
    primaryQueryOwner: 'online English classes for kids',
    commercialReadiness: 'high',
    ctaPolicy: 'demo',
    primaryDestination: '/book-demo',
    protection: 'protected',
    futureResourceNode: null,
  }),
  entry('/courses', {
    currentState: 'route',
    pageFamily: 'commercial-hub',
    audience: 'parents',
    subject: 'general-english',
    currentPurpose: 'Course comparison and programme selection.',
    primaryIntent: 'solution-aware',
    primaryQueryOwner: 'Tiny Steps English courses for kids',
    commercialReadiness: 'high',
    ctaPolicy: 'programme',
    primaryDestination: '/book-demo',
    protection: 'protected',
    futureResourceNode: null,
  }),
  entry('/curriculum', {
    currentState: 'route',
    pageFamily: 'academic-roadmap',
    audience: 'parents',
    subject: 'general-english',
    currentPurpose: 'Canonical academic progression across Tiny Steps programmes.',
    primaryIntent: 'progress-aware',
    primaryQueryOwner: 'Tiny Steps English curriculum for kids',
    commercialReadiness: 'medium',
    ctaPolicy: 'programme',
    primaryDestination: '/courses',
    protection: 'protected',
    futureResourceNode: null,
  }),
  entry('/phonics', {
    currentState: 'route',
    pageFamily: 'commercial-programme',
    audience: 'parents',
    subject: 'phonics-reading',
    currentPurpose: 'Live 1:1 phonics programme acquisition and assessment-first placement.',
    primaryIntent: 'high-commercial',
    primaryQueryOwner: 'online phonics classes for kids in India',
    commercialReadiness: 'very-high',
    ctaPolicy: 'demo',
    primaryDestination: '/book-demo',
    protection: 'protected',
    futureResourceNode: '/resources/phonics',
  }),
  entry('/grammar', {
    currentState: 'route',
    pageFamily: 'commercial-programme',
    audience: 'parents',
    subject: 'grammar-writing',
    currentPurpose: 'Live grammar and sentence-building programme acquisition.',
    primaryIntent: 'high-commercial',
    primaryQueryOwner: 'grammar classes for kids in India',
    commercialReadiness: 'very-high',
    ctaPolicy: 'demo',
    primaryDestination: '/book-demo',
    protection: 'protected',
    futureResourceNode: '/resources/grammar',
  }),
  entry('/speaking', {
    currentState: 'route',
    pageFamily: 'commercial-programme',
    audience: 'parents',
    subject: 'speaking-communication',
    currentPurpose: 'Live public-speaking and communication programme acquisition.',
    primaryIntent: 'high-commercial',
    primaryQueryOwner: 'public speaking classes for kids in India',
    commercialReadiness: 'very-high',
    ctaPolicy: 'demo',
    primaryDestination: '/book-demo',
    protection: 'protected',
    futureResourceNode: '/resources/speaking',
  }),
  entry('/pricing', {
    currentState: 'route',
    pageFamily: 'commercial-decision',
    audience: 'parents',
    subject: 'general-english',
    currentPurpose: 'Canonical public pricing and package information.',
    primaryIntent: 'transactional-brand',
    primaryQueryOwner: 'Tiny Steps pricing',
    commercialReadiness: 'very-high',
    ctaPolicy: 'pricing',
    primaryDestination: '/book-demo',
    protection: 'protected',
    futureResourceNode: null,
  }),
  entry('/phonics-fees-india', {
    currentState: 'route',
    pageFamily: 'commercial-research',
    audience: 'parents',
    subject: 'phonics-reading',
    currentPurpose: 'India phonics fee research and price-comparison intent.',
    primaryIntent: 'solution-aware',
    primaryQueryOwner: 'phonics class fees in India',
    commercialReadiness: 'high',
    ctaPolicy: 'pricing',
    primaryDestination: '/pricing',
    protection: 'protected',
    futureResourceNode: '/resources/phonics',
  }),
  entry('/best-online-phonics-classes-for-kids-in-india', {
    currentState: 'route',
    pageFamily: 'commercial-comparison',
    audience: 'parents',
    subject: 'phonics-reading',
    currentPurpose: 'Buyer comparison for online phonics classes in India.',
    primaryIntent: 'high-commercial',
    primaryQueryOwner: 'best online phonics classes for kids in India',
    commercialReadiness: 'very-high',
    ctaPolicy: 'assessment',
    primaryDestination: '/book-demo',
    protection: 'protected',
    futureResourceNode: '/resources/phonics',
  }),
  entry('/reading-classes-for-kids', {
    currentState: 'route',
    pageFamily: 'commercial-programme',
    audience: 'parents',
    subject: 'phonics-reading',
    currentPurpose: 'Reading-support class acquisition distinct from broad phonics intent.',
    primaryIntent: 'commercial',
    primaryQueryOwner: 'reading classes for kids',
    commercialReadiness: 'high',
    ctaPolicy: 'assessment',
    primaryDestination: '/book-demo',
    protection: 'protected',
    futureResourceNode: '/resources/phonics',
  }),
  entry('/writing-classes-for-kids', {
    currentState: 'route',
    pageFamily: 'commercial-programme',
    audience: 'parents',
    subject: 'grammar-writing',
    currentPurpose: 'Writing-support acquisition distinct from broad grammar intent.',
    primaryIntent: 'commercial',
    primaryQueryOwner: 'writing classes for kids',
    commercialReadiness: 'high',
    ctaPolicy: 'assessment',
    primaryDestination: '/book-demo',
    protection: 'protected',
    futureResourceNode: '/resources/grammar',
  }),
  entry('/spoken-english-classes-for-kids-online', {
    currentState: 'route',
    pageFamily: 'commercial-programme',
    audience: 'parents',
    subject: 'speaking-communication',
    currentPurpose: 'Spoken-English acquisition distinct from formal public-speaking intent.',
    primaryIntent: 'commercial',
    primaryQueryOwner: 'spoken English classes for kids online',
    commercialReadiness: 'high',
    ctaPolicy: 'assessment',
    primaryDestination: '/book-demo',
    protection: 'protected',
    futureResourceNode: '/resources/speaking',
  }),
  entry('/online-english-classes-for-kids', {
    currentState: 'route',
    pageFamily: 'commercial-acquisition',
    audience: 'parents',
    subject: 'general-english',
    currentPurpose: 'Broad non-brand online English class acquisition.',
    primaryIntent: 'high-commercial',
    primaryQueryOwner: 'online English classes for kids',
    commercialReadiness: 'very-high',
    ctaPolicy: 'demo',
    primaryDestination: '/book-demo',
    protection: 'protected',
    futureResourceNode: null,
  }),
  entry('/online-english-classes-hyderabad', {
    currentState: 'route',
    pageFamily: 'commercial-location',
    audience: 'parents',
    subject: 'general-english',
    currentPurpose: 'Hyderabad-specific online English class acquisition.',
    primaryIntent: 'high-commercial',
    primaryQueryOwner: 'online English classes for kids Hyderabad',
    commercialReadiness: 'very-high',
    ctaPolicy: 'demo',
    primaryDestination: '/book-demo',
    protection: 'protected',
    futureResourceNode: null,
  }),
  entry('/parents', {
    currentState: 'route',
    pageFamily: 'support-hub',
    audience: 'parents',
    subject: 'general-english',
    currentPurpose: 'Parent problem-solving and next-step support hub.',
    primaryIntent: 'problem-aware',
    primaryQueryOwner: 'parent help for child English learning problems',
    commercialReadiness: 'medium',
    ctaPolicy: 'related-resource',
    primaryDestination: '/parents/getting-started',
    protection: 'protected',
    futureResourceNode: '/resources',
  }),
  entry('/for-schools', {
    currentState: 'route',
    pageFamily: 'b2b-hub',
    audience: 'schools',
    subject: 'schools-research',
    currentPurpose: 'Canonical B2B school phonics implementation and partnership owner.',
    primaryIntent: 'commercial',
    primaryQueryOwner: 'systematic phonics programme for schools in India',
    commercialReadiness: 'high',
    ctaPolicy: 'schools',
    primaryDestination: '/contact',
    protection: 'protected',
    futureResourceNode: '/resources',
  }),
  entry('/free-english-games-for-kids', {
    currentState: 'route',
    pageFamily: 'practice-hub',
    audience: 'parents-children',
    subject: 'general-english',
    currentPurpose: 'Canonical free interactive English-practice ecosystem.',
    primaryIntent: 'practice',
    primaryQueryOwner: 'free English games for kids',
    commercialReadiness: 'low',
    ctaPolicy: 'practice',
    primaryDestination: '/phonics-learning-games',
    protection: 'protected',
    futureResourceNode: '/resources',
  }),
  entry('/blog', {
    currentState: 'route',
    pageFamily: 'editorial-library',
    audience: 'mixed',
    subject: 'general-english',
    currentPurpose: 'Full editorial discovery, search, and archive surface.',
    primaryIntent: 'informational',
    primaryQueryOwner: 'Tiny Steps English learning guides',
    commercialReadiness: 'low',
    ctaPolicy: 'related-resource',
    primaryDestination: null,
    protection: 'protected',
    futureResourceNode: '/resources',
  }),
  entry('/book-demo', {
    currentState: 'route',
    pageFamily: 'conversion',
    audience: 'parents',
    subject: 'general-english',
    currentPurpose: 'Canonical free 35-minute 1:1 assessment and lead submission page.',
    primaryIntent: 'transactional-brand',
    primaryQueryOwner: 'book Tiny Steps free assessment',
    commercialReadiness: 'very-high',
    ctaPolicy: 'demo',
    primaryDestination: null,
    protection: 'protected',
    futureResourceNode: null,
  }),
  entry('/class-samples', {
    currentState: 'route',
    pageFamily: 'trust-evidence',
    audience: 'parents',
    subject: 'general-english',
    currentPurpose: 'Teaching-sample evidence for programme evaluation.',
    primaryIntent: 'solution-aware',
    primaryQueryOwner: 'Tiny Steps class samples',
    commercialReadiness: 'high',
    ctaPolicy: 'assessment',
    primaryDestination: '/book-demo',
    protection: 'protected',
    futureResourceNode: null,
  }),
  entry('/testimonials', {
    currentState: 'route',
    pageFamily: 'trust-evidence',
    audience: 'parents',
    subject: 'general-english',
    currentPurpose: 'First-party parent proof and programme trust support.',
    primaryIntent: 'transactional-brand',
    primaryQueryOwner: 'Tiny Steps reviews and parent testimonials',
    commercialReadiness: 'high',
    ctaPolicy: 'assessment',
    primaryDestination: '/book-demo',
    protection: 'protected',
    futureResourceNode: null,
  }),
  entry('/child-not-reading-properly', {
    currentState: 'route',
    pageFamily: 'problem-landing',
    audience: 'parents',
    subject: 'phonics-reading',
    currentPurpose: 'Broad reading-difficulty parent problem acquisition.',
    primaryIntent: 'problem-aware',
    primaryQueryOwner: 'child not reading properly',
    commercialReadiness: 'medium',
    ctaPolicy: 'assessment',
    primaryDestination: '/book-demo',
    protection: 'protected',
    futureResourceNode: '/resources/phonics',
  }),
  entry('/slow-reader-child-help', {
    currentState: 'route',
    pageFamily: 'problem-landing',
    audience: 'parents',
    subject: 'phonics-reading',
    currentPurpose: 'Slow-reading problem and fluency support acquisition.',
    primaryIntent: 'problem-aware',
    primaryQueryOwner: 'slow reader child help',
    commercialReadiness: 'medium',
    ctaPolicy: 'assessment',
    primaryDestination: '/book-demo',
    protection: 'protected',
    futureResourceNode: '/resources/phonics',
  }),
  entry('/shy-child-speaking-confidence', {
    currentState: 'route',
    pageFamily: 'problem-landing',
    audience: 'parents',
    subject: 'speaking-communication',
    currentPurpose: 'Speaking-confidence problem acquisition.',
    primaryIntent: 'problem-aware',
    primaryQueryOwner: 'shy child speaking confidence',
    commercialReadiness: 'medium',
    ctaPolicy: 'assessment',
    primaryDestination: '/book-demo',
    protection: 'protected',
    futureResourceNode: '/resources/speaking',
  }),
  entry('/reading-fluency-program', {
    currentState: 'route',
    pageFamily: 'commercial-programme',
    audience: 'parents',
    subject: 'phonics-reading',
    currentPurpose: 'Reading-fluency programme acquisition.',
    primaryIntent: 'commercial',
    primaryQueryOwner: 'reading fluency program for kids',
    commercialReadiness: 'high',
    ctaPolicy: 'assessment',
    primaryDestination: '/book-demo',
    protection: 'protected',
    futureResourceNode: '/resources/phonics',
  }),
  entry('/confidence-building-program-kids', {
    currentState: 'route',
    pageFamily: 'commercial-programme',
    audience: 'parents',
    subject: 'speaking-communication',
    currentPurpose: 'Communication-confidence programme acquisition.',
    primaryIntent: 'commercial',
    primaryQueryOwner: 'confidence building program for kids',
    commercialReadiness: 'high',
    ctaPolicy: 'assessment',
    primaryDestination: '/book-demo',
    protection: 'protected',
    futureResourceNode: '/resources/speaking',
  }),

  // Protected editorial authorities. Physical /blog/* URLs remain unchanged.
  entry('/blog/satpin-phonics-guide', {
    currentState: 'blog-route', pageFamily: 'editorial-authority', audience: 'parents', subject: 'phonics-reading',
    currentPurpose: 'Canonical SATPIN and early decoding guide.', primaryIntent: 'informational',
    primaryQueryOwner: 'SATPIN phonics guide', commercialReadiness: 'low', ctaPolicy: 'related-resource',
    primaryDestination: '/phonics', protection: 'protected', futureResourceNode: '/resources/phonics',
  }),
  entry('/blog/phonics-for-parents-guide', {
    currentState: 'blog-route', pageFamily: 'editorial-authority', audience: 'parents', subject: 'phonics-reading',
    currentPurpose: 'Broad parent phonics authority and home-support overview.', primaryIntent: 'informational',
    primaryQueryOwner: 'phonics for parents', commercialReadiness: 'low', ctaPolicy: 'related-resource',
    primaryDestination: '/phonics', protection: 'protected', futureResourceNode: '/resources/phonics',
  }),
  entry('/blog/child-knows-abc-but-cannot-read', {
    currentState: 'blog-route', pageFamily: 'editorial-diagnostic', audience: 'parents', subject: 'phonics-reading',
    currentPurpose: 'Alphabet knowledge without transferable decoding diagnostic owner.', primaryIntent: 'problem-aware',
    primaryQueryOwner: 'child knows ABC but cannot read', commercialReadiness: 'high', ctaPolicy: 'assessment',
    primaryDestination: '/book-demo', protection: 'protected', futureResourceNode: '/resources/phonics',
  }),
  entry('/blog/why-child-knows-letter-sounds-but-cannot-read-words', {
    currentState: 'blog-route', pageFamily: 'editorial-diagnostic', audience: 'parents', subject: 'phonics-reading',
    currentPurpose: 'Letter sounds known but blending/word reading fails.', primaryIntent: 'problem-aware',
    primaryQueryOwner: 'child knows letter sounds but cannot read words', commercialReadiness: 'high', ctaPolicy: 'assessment',
    primaryDestination: '/book-demo', protection: 'protected', futureResourceNode: '/resources/phonics',
  }),
  entry('/blog/how-kids-learn-blending', {
    currentState: 'blog-route', pageFamily: 'editorial-skill', audience: 'parents', subject: 'phonics-reading',
    currentPurpose: 'Blending progression and developmental-stage explanation.', primaryIntent: 'progress-aware',
    primaryQueryOwner: 'how kids learn blending', commercialReadiness: 'medium', ctaPolicy: 'related-resource',
    primaryDestination: '/phonics', protection: 'protected', futureResourceNode: '/resources/phonics',
  }),
  entry('/blog/phonics-blending-activities', {
    currentState: 'blog-route', pageFamily: 'editorial-activity', audience: 'parents', subject: 'phonics-reading',
    currentPurpose: 'Blending activity and guided home-practice owner.', primaryIntent: 'practice',
    primaryQueryOwner: 'phonics blending activities', commercialReadiness: 'low', ctaPolicy: 'practice',
    primaryDestination: '/free-word-building-game-for-kids', protection: 'protected', futureResourceNode: '/resources/phonics',
  }),
  entry('/blog/cvc-words-explained-for-parents', {
    currentState: 'blog-route', pageFamily: 'editorial-skill', audience: 'parents', subject: 'phonics-reading',
    currentPurpose: 'Canonical CVC decoding explanation for parents.', primaryIntent: 'informational',
    primaryQueryOwner: 'CVC words explained for parents', commercialReadiness: 'low', ctaPolicy: 'practice',
    primaryDestination: '/free-word-building-game-for-kids', protection: 'protected', futureResourceNode: '/resources/phonics',
  }),
  entry('/blog/how-to-improve-reading-fluency-in-children', {
    currentState: 'blog-route', pageFamily: 'editorial-authority', audience: 'parents', subject: 'phonics-reading',
    currentPurpose: 'Canonical reading-fluency explanation and support guide.', primaryIntent: 'problem-aware',
    primaryQueryOwner: 'how to improve reading fluency in children', commercialReadiness: 'medium', ctaPolicy: 'assessment',
    primaryDestination: '/book-demo', protection: 'protected', futureResourceNode: '/resources/phonics',
  }),
  entry('/blog/grammar-nouns-to-paragraphs', {
    currentState: 'blog-route', pageFamily: 'editorial-authority', audience: 'parents', subject: 'grammar-writing',
    currentPurpose: 'Broad grammar progression from sentence foundations to paragraphs.', primaryIntent: 'progress-aware',
    primaryQueryOwner: 'grammar roadmap for kids', commercialReadiness: 'medium', ctaPolicy: 'related-resource',
    primaryDestination: '/grammar', protection: 'protected', futureResourceNode: '/resources/grammar',
  }),
  entry('/blog/how-to-improve-sentence-formation-in-kids', {
    currentState: 'blog-route', pageFamily: 'editorial-diagnostic', audience: 'parents', subject: 'grammar-writing',
    currentPurpose: 'Sentence formation and expansion diagnostic owner.', primaryIntent: 'problem-aware',
    primaryQueryOwner: 'how to improve sentence formation in kids', commercialReadiness: 'high', ctaPolicy: 'assessment',
    primaryDestination: '/book-demo', protection: 'protected', futureResourceNode: '/resources/grammar',
  }),
  entry('/blog/child-knows-grammar-but-makes-mistakes', {
    currentState: 'blog-route', pageFamily: 'editorial-diagnostic', audience: 'parents', subject: 'grammar-writing',
    currentPurpose: 'Grammar rule knowledge that does not transfer into spontaneous use.', primaryIntent: 'problem-aware',
    primaryQueryOwner: 'child knows grammar but makes mistakes', commercialReadiness: 'high', ctaPolicy: 'assessment',
    primaryDestination: '/book-demo', protection: 'protected', futureResourceNode: '/resources/grammar',
  }),
  entry('/blog/speaking-confidence-seeds', {
    currentState: 'blog-route', pageFamily: 'editorial-authority', audience: 'parents', subject: 'speaking-communication',
    currentPurpose: 'Broad speaking-confidence and communication progression.', primaryIntent: 'progress-aware',
    primaryQueryOwner: 'speaking confidence for kids', commercialReadiness: 'medium', ctaPolicy: 'related-resource',
    primaryDestination: '/speaking', protection: 'protected', futureResourceNode: '/resources/speaking',
  }),
  entry('/blog/child-understands-english-but-does-not-speak', {
    currentState: 'blog-route', pageFamily: 'editorial-diagnostic', audience: 'parents', subject: 'speaking-communication',
    currentPurpose: 'Understanding stronger than independent spoken response diagnostic owner.', primaryIntent: 'problem-aware',
    primaryQueryOwner: 'child understands English but does not speak', commercialReadiness: 'high', ctaPolicy: 'assessment',
    primaryDestination: '/book-demo', protection: 'protected', futureResourceNode: '/resources/speaking',
  }),
  entry('/blog/child-gives-one-word-answers', {
    currentState: 'blog-route', pageFamily: 'editorial-diagnostic', audience: 'parents', subject: 'speaking-communication',
    currentPurpose: 'One-word answers and spoken sentence expansion diagnostic owner.', primaryIntent: 'problem-aware',
    primaryQueryOwner: 'child gives one-word answers', commercialReadiness: 'high', ctaPolicy: 'assessment',
    primaryDestination: '/book-demo', protection: 'protected', futureResourceNode: '/resources/speaking',
  }),

  // R0 records the current redirect state. Brick 2 must change all route/hosting
  // systems atomically before this becomes an independent indexable page.
  entry('/resources', {
    currentState: 'redirect',
    expectedRedirectTarget: '/blog',
    pageFamily: 'architecture-opportunity',
    audience: 'mixed',
    subject: 'general-english',
    currentPurpose: 'Legacy alias only; no independent search intent owner today.',
    primaryIntent: 'informational',
    primaryQueryOwner: 'none-currently',
    commercialReadiness: 'none',
    ctaPolicy: 'none',
    primaryDestination: '/blog',
    protection: 'opportunity',
    futureResourceNode: '/resources',
    futurePurpose: 'Primary educational-discovery gateway for the Tiny Steps learning ecosystem.',
  }),
  entry('/resources/phonics', {
    currentState: 'planned', pageFamily: 'subject-resource-hub', audience: 'parents', subject: 'phonics-reading',
    currentPurpose: 'Not live in R0.', primaryIntent: 'informational', primaryQueryOwner: 'planned: phonics and reading learning hub',
    commercialReadiness: 'low', ctaPolicy: 'related-resource', primaryDestination: null, protection: 'planned', futureResourceNode: '/resources/phonics',
  }),
  entry('/resources/grammar', {
    currentState: 'planned', pageFamily: 'subject-resource-hub', audience: 'parents', subject: 'grammar-writing',
    currentPurpose: 'Not live in R0.', primaryIntent: 'informational', primaryQueryOwner: 'planned: grammar and writing learning hub',
    commercialReadiness: 'low', ctaPolicy: 'related-resource', primaryDestination: null, protection: 'planned', futureResourceNode: '/resources/grammar',
  }),
  entry('/resources/speaking', {
    currentState: 'planned', pageFamily: 'subject-resource-hub', audience: 'parents', subject: 'speaking-communication',
    currentPurpose: 'Not live in R0.', primaryIntent: 'informational', primaryQueryOwner: 'planned: speaking and communication learning hub',
    commercialReadiness: 'low', ctaPolicy: 'related-resource', primaryDestination: null, protection: 'planned', futureResourceNode: '/resources/speaking',
  }),
]);

export const RESOURCE_PROTECTED_PATHS = Object.freeze(
  RESOURCE_ECOSYSTEM_REGISTRY.filter((item) => item.protection === 'protected').map((item) => item.path),
);

export const RESOURCE_PERFORMANCE_PRIORITY_PATHS = Object.freeze([
  '/resources',
  '/blog',
  '/phonics',
  '/grammar',
  '/speaking',
  '/parents',
  '/for-schools',
  '/free-english-games-for-kids',
  '/book-demo',
  '/best-online-phonics-classes-for-kids-in-india',
  '/phonics-fees-india',
  '/blog/satpin-phonics-guide',
  '/blog/child-knows-abc-but-cannot-read',
  '/blog/why-child-knows-letter-sounds-but-cannot-read-words',
  '/blog/how-kids-learn-blending',
  '/blog/cvc-words-explained-for-parents',
  '/blog/how-to-improve-reading-fluency-in-children',
  '/blog/how-to-improve-sentence-formation-in-kids',
  '/blog/child-knows-grammar-but-makes-mistakes',
  '/blog/speaking-confidence-seeds',
  '/blog/child-understands-english-but-does-not-speak',
  '/blog/child-gives-one-word-answers',
]);
