import { definePhonicsKnowledge as concept } from './schema.js';

export const ADVANCED_DIPHTHONG_AND_ENDING_KNOWLEDGE = Object.freeze([
  concept('diphthong-oi-oy', {
    label: 'OI and OY patterns',
    knowledgeStage: 'advanced-patterns',
    conceptType: 'diphthong',
    progressionRank: 14,
    searchIntent: 'how oi and oy commonly spell the same vowel sound in different positions',
    parentQuestion: 'When should a child use oi or oy?',
    quickAnswer: 'OI and OY commonly represent the same vowel sound. OI is often found inside a word, as in coin, while OY often appears at the end, as in boy. Position is a useful spelling tendency, not an absolute rule.',
    graphemes: ['oi', 'oy'],
    exampleWords: ['coin', 'boil', 'soil', 'boy', 'toy'],
    commonConfusions: [
      'Choosing oi or oy from sound alone without considering spelling position.',
      'Teaching the position tendency as a rule with no exceptions.',
    ],
    teachingNotes: [
      'Teach the shared sound first, then compare common positions for the two spellings.',
      'Use spelling sorts after reading accuracy is established.',
    ],
    practiceIdeas: [
      'Sort decoded words by oi and oy.',
      'Complete a word with oi or oy and explain the position clue.',
    ],
    prerequisiteIds: ['diphthong-oo'],
    nextIds: ['diphthong-au-aw', 'diphthong-ou-ow'],
    curriculumAlignment: 'direct',
    curriculumRefs: [
      { courseId: 'early-phonics', lessonNumber: 35, label: 'Diphthongs OI and OY' },
      { courseId: 'advanced-phonics', lessonNumber: 17, label: 'Diphthongs OI, OY, AU, and AW' },
    ],
    canonicalOwnerTopicId: null,
    expansionState: 'future-wave-2',
    futureSlugCandidate: 'oi-oy-phonics',
    expansionRationale: 'Strong spelling-choice concept but suitable for a later wave after core pilot patterns prove demand.',
    distinctValueSignals: ['same-sound-two-spellings', 'position-tendency', 'spelling-sort', 'encoding-choice'],
  }),
  concept('diphthong-au-aw', {
    label: 'AU and AW patterns',
    knowledgeStage: 'advanced-patterns',
    conceptType: 'diphthong',
    progressionRank: 14,
    searchIntent: 'how au and aw commonly represent a similar vowel sound',
    parentQuestion: 'How do children choose between au and aw?',
    quickAnswer: 'AU and AW commonly represent a similar vowel sound in words such as haul and saw. The sound alone does not always determine which grapheme to write, so children need spelling-family experience.',
    graphemes: ['au', 'aw'],
    exampleWords: ['haul', 'pause', 'saw', 'draw', 'straw'],
    commonConfusions: [
      'Expecting the sound alone to identify whether au or aw is correct.',
      'Introducing too many alternative spellings for the same sound at once.',
    ],
    teachingNotes: [
      'Teach one spelling set, then compare the second in a controlled word sort.',
      'Use position and known-word memory as clues without claiming a perfect rule.',
    ],
    practiceIdeas: [
      'Sort decoded words into au and aw columns.',
      'Dictate a known mixed set and recall the spelling family.',
    ],
    prerequisiteIds: ['diphthong-oi-oy'],
    nextIds: ['diphthong-ou-ow'],
    curriculumAlignment: 'direct',
    curriculumRefs: [
      { courseId: 'early-phonics', lessonNumber: 36, label: 'Diphthongs AU and AW' },
      { courseId: 'advanced-phonics', lessonNumber: 17, label: 'Diphthongs OI, OY, AU, and AW' },
    ],
    canonicalOwnerTopicId: null,
    expansionState: 'future-wave-2',
    futureSlugCandidate: 'au-aw-phonics',
    expansionRationale: 'Useful spelling-family page but lower priority than first-wave vowel teams.',
    distinctValueSignals: ['same-sound-two-spellings', 'word-sort', 'spelling-memory', 'position-clue'],
  }),
  concept('diphthong-ou-ow', {
    label: 'OU and OW patterns',
    knowledgeStage: 'advanced-patterns',
    conceptType: 'diphthong',
    progressionRank: 14,
    searchIntent: 'how ou and ow can represent the /ow/ sound and other pronunciations',
    parentQuestion: 'Why are ou and ow tricky for children?',
    quickAnswer: 'OU and OW can represent the /ow/ sound in words such as out and cow, but both spellings also appear in other pronunciation patterns. Early teaching should use a controlled /ow/ set first, then add alternatives explicitly.',
    graphemes: ['ou', 'ow'],
    exampleWords: ['out', 'cloud', 'cow', 'town', 'brown'],
    commonConfusions: [
      'Assuming every ou or ow word has the /ow/ sound.',
      'Mixing multiple pronunciations before the target correspondence is secure.',
    ],
    teachingNotes: [
      'Teach a clean /ow/ set first and label later pronunciations as additional families.',
      'Use familiar vocabulary to confirm a decoded pronunciation when the grapheme is variable.',
    ],
    practiceIdeas: [
      'Sort /ow/ words by ou and ow spelling.',
      'Read a familiar mixed list and flag words where the grapheme represents another sound.',
    ],
    prerequisiteIds: ['diphthong-oi-oy'],
    nextIds: ['j-sounds', 'shun-family'],
    curriculumAlignment: 'direct',
    curriculumRefs: [
      { courseId: 'early-phonics', lessonNumber: 37, label: 'Diphthongs OU and OW' },
      { courseId: 'advanced-phonics', lessonNumber: 18, label: 'Diphthongs OU and OW' },
    ],
    canonicalOwnerTopicId: null,
    expansionState: 'future-wave-2',
    futureSlugCandidate: 'ou-ow-phonics',
    expansionRationale: 'Good variable-pattern candidate but intentionally held for wave 2.',
    distinctValueSignals: ['shared-target-sound', 'alternative-pronunciation-boundary', 'spelling-sort', 'vocabulary-confirmation'],
  }),
  concept('j-sounds', {
    label: 'Three common spellings for the J sound',
    knowledgeStage: 'advanced-patterns',
    conceptType: 'advanced-pattern',
    progressionRank: 15,
    searchIntent: 'how j g and dge can represent the /j/ sound',
    parentQuestion: 'Why can the /j/ sound be written in different ways?',
    quickAnswer: 'The /j/ sound can be represented by several spellings, including j, soft g and dge in different contexts. Reading the sound is only part of the job; spelling requires learning the pattern and position.',
    graphemes: ['j', 'g', 'dge'],
    exampleWords: ['jam', 'giant', 'badge', 'edge', 'joke'],
    commonConfusions: [
      'Expecting one spelling to represent /j/ in every word.',
      'Choosing a spelling from sound alone without considering position and surrounding letters.',
    ],
    teachingNotes: [
      'Connect soft g to the earlier e-i-y clue and introduce dge as a separate context.',
      'Separate reading recognition from spelling choice.',
    ],
    practiceIdeas: [
      'Sort /j/ words by j, g and dge after decoding.',
      'Dictate a familiar mixed set and explain the spelling family used.',
    ],
    prerequisiteIds: ['soft-g-hard-g', 'ck-rule'],
    nextIds: ['shun-family', 'schwa-lazy-vowel'],
    curriculumAlignment: 'direct',
    curriculumRefs: [
      { courseId: 'early-phonics', lessonNumber: 38, label: 'J Sounds' },
      { courseId: 'advanced-phonics', lessonNumber: 16, label: '3 Different J Sounds' },
    ],
    canonicalOwnerTopicId: null,
    expansionState: 'future-wave-2',
    futureSlugCandidate: 'j-sound-spellings-phonics',
    expansionRationale: 'Valuable spelling-choice intent, but later than the foundational pilot sequence.',
    distinctValueSignals: ['same-sound-multiple-spellings', 'position-context', 'soft-g-link', 'encoding-choice'],
  }),
  concept('shun-family', {
    label: 'SHUN sound family',
    knowledgeStage: 'advanced-patterns',
    conceptType: 'advanced-pattern',
    progressionRank: 15,
    searchIntent: 'how common endings can represent the /shun/ sound',
    parentQuestion: 'Why can the ending sound /shun/ be spelled in different ways?',
    quickAnswer: 'The /shun/ ending appears in several spelling families, including common endings such as -tion and -sion. Children should learn these as word-ending patterns linked to vocabulary and morphology, not as a one-to-one rule.',
    graphemes: ['tion', 'sion'],
    exampleWords: ['station', 'action', 'motion', 'vision', 'mission'],
    commonConfusions: [
      'Trying to spell every /shun/ ending with one fixed grapheme.',
      'Teaching the ending only as a sound without connecting it to whole words and meaningful parts.',
    ],
    teachingNotes: [
      'Introduce one high-frequency ending family at a time in complete words.',
      'Use morphology and vocabulary because spelling choice is not determined by sound alone.',
    ],
    practiceIdeas: [
      'Sort familiar words by -tion and -sion endings.',
      'Highlight the base or meaningful part before reading the ending.',
    ],
    prerequisiteIds: ['digraph-sh', 'j-sounds'],
    nextIds: ['schwa-lazy-vowel', 'long-vowel-families'],
    curriculumAlignment: 'direct',
    curriculumRefs: [
      { courseId: 'early-phonics', lessonNumber: 39, label: 'The SHUN Family' },
      { courseId: 'advanced-phonics', lessonNumber: 20, label: 'The SHUN Sound Family' },
    ],
    canonicalOwnerTopicId: null,
    expansionState: 'future-wave-2',
    futureSlugCandidate: 'shun-sound-family-phonics',
    expansionRationale: 'Strong advanced spelling intent but requires more morphology context than the first pilot.',
    distinctValueSignals: ['suffix-family', 'sound-vs-spelling-choice', 'morphology-link', 'ending-sort'],
  }),
  concept('schwa-lazy-vowel', {
    label: 'Schwa / lazy vowel in unstressed syllables',
    knowledgeStage: 'advanced-patterns',
    conceptType: 'alternate-vowel',
    progressionRank: 17,
    searchIntent: 'why an unstressed vowel can sound reduced in longer words',
    parentQuestion: 'Why does a written vowel sometimes sound weak or unclear in a longer word?',
    quickAnswer: 'In many unstressed syllables, a vowel can reduce toward schwa, a weak neutral vowel sound. This helps explain why spelling cannot always be recovered from careful pronunciation alone in longer words.',
    graphemes: ['a', 'e', 'i', 'o', 'u'],
    exampleWords: ['about', 'sofa', 'problem', 'pencil', 'support'],
    commonConfusions: [
      'Expecting every written vowel in an unstressed syllable to keep a strong short or long sound.',
      'Telling a child to stretch the word harder when natural pronunciation already contains vowel reduction.',
    ],
    teachingNotes: [
      'Introduce schwa after children can identify syllables and stress in familiar words.',
      'Connect pronunciation to stored spelling and morphology.',
    ],
    practiceIdeas: [
      'Mark the stressed syllable and notice the weaker vowel in another syllable.',
      'Compare natural pronunciation with the written vowel and practise the stable spelling.',
    ],
    prerequisiteIds: ['rabbit-rule', 'consonant-le'],
    nextIds: ['missing-sleepy-sounds'],
    curriculumAlignment: 'direct',
    curriculumRefs: [
      { courseId: 'early-phonics', lessonNumber: 40, label: 'The Lazy Sound' },
      { courseId: 'advanced-phonics', lessonNumber: 30, label: 'The Lazy Vowel Mystery' },
    ],
    canonicalOwnerTopicId: null,
    expansionState: 'future-wave-2',
    futureSlugCandidate: 'schwa-sound-for-kids-phonics',
    expansionRationale: 'High explanatory value but more advanced than the Brick 9 core pilot.',
    distinctValueSignals: ['stress-awareness', 'vowel-reduction', 'pronunciation-spelling-gap', 'multisyllabic-transfer'],
  }),
]);
