import { definePhonicsKnowledge as concept } from './schema.js';

export const ADVANCED_R_CONTROLLED_AND_VOWEL_KNOWLEDGE = Object.freeze([
  concept('soft-g-hard-g', {
    label: 'Soft G and hard G',
    knowledgeStage: 'advanced-patterns',
    conceptType: 'advanced-pattern',
    progressionRank: 11,
    searchIntent: 'when g commonly represents /j/ or hard /g/',
    parentQuestion: 'Why does g sound different in game and giant?',
    quickAnswer: 'G commonly represents hard /g/ as in game, but often represents /j/ before e, i or y, as in gem and giant. The context clue is useful but has exceptions.',
    graphemes: ['g'],
    exampleWords: ['game', 'go', 'gem', 'giant', 'gym'],
    commonConfusions: [
      'Assuming the e-i-y clue guarantees soft g in every word.',
      'Calling an exception a child mistake when the spelling pattern itself is variable.',
    ],
    teachingNotes: [
      'Teach hard and soft g in contrast and explicitly state that the context clue has exceptions.',
      'Use known vocabulary to confirm the predicted pronunciation.',
    ],
    practiceIdeas: [
      'Sort g words by /g/ and /j/.',
      'Predict from the following letter, then read the complete word and check.',
    ],
    prerequisiteIds: ['soft-c-hard-c'],
    nextIds: ['r-controlled-ar', 'r-controlled-or'],
    curriculumAlignment: 'direct',
    curriculumRefs: [
      { courseId: 'early-phonics', lessonNumber: 29, label: 'Soft G and Hard G' },
      { courseId: 'advanced-phonics', lessonNumber: 13, label: 'Soft C and G, Hard C and G' },
    ],
    canonicalOwnerTopicId: null,
    expansionState: 'future-wave-2',
    futureSlugCandidate: 'soft-g-hard-g-phonics',
    expansionRationale: 'Useful standalone contrast, but it follows the higher-priority soft-c pilot.',
    distinctValueSignals: ['soft-hard-contrast', 'e-i-y-context', 'variable-rule-boundary', 'vocabulary-confirmation'],
  }),
  concept('r-controlled-ar', {
    label: 'R-controlled AR',
    knowledgeStage: 'advanced-patterns',
    conceptType: 'r-controlled',
    progressionRank: 12,
    searchIntent: 'how ar works as an r-controlled vowel pattern',
    parentQuestion: 'Why does a not keep its usual short or long sound in car and star?',
    quickAnswer: 'In r-controlled patterns, the vowel and following r work together. AR is common in words such as car, star and farm, so children should recognise ar as a pattern rather than apply the ordinary short-a rule.',
    graphemes: ['ar'],
    exampleWords: ['car', 'star', 'farm', 'park', 'hard'],
    commonConfusions: [
      'Reading a with its ordinary short-vowel sound before adding r.',
      'Treating every written ar sequence as identical without checking the word.',
    ],
    teachingNotes: [
      'Mark ar as one vowel-r pattern and compare it with a familiar short-a word.',
      'Keep the first set regular and add less common pronunciations later.',
    ],
    practiceIdeas: [
      'Build ar word families by changing onset and final consonants.',
      'Sort words by short a versus ar after decoding.',
    ],
    prerequisiteIds: ['short-vowels', 'soft-c-hard-c'],
    nextIds: ['r-controlled-or', 'r-controlled-er-ir-ur'],
    curriculumAlignment: 'direct',
    curriculumRefs: [
      { courseId: 'early-phonics', lessonNumber: 30, label: 'Controlling R: AR' },
      { courseId: 'advanced-phonics', lessonNumber: 21, label: 'Controlling R: AR' },
    ],
    canonicalOwnerTopicId: null,
    expansionState: 'future-wave-2',
    futureSlugCandidate: 'ar-r-controlled-vowels-phonics',
    expansionRationale: 'Granular pattern should wait for Brick 9 because broad r-controlled authority content already exists.',
    distinctValueSignals: ['vowel-r-unit', 'short-a-contrast', 'word-family', 'pronunciation-boundary'],
  }),
  concept('r-controlled-or', {
    label: 'R-controlled OR',
    knowledgeStage: 'advanced-patterns',
    conceptType: 'r-controlled',
    progressionRank: 12,
    searchIntent: 'how or works as an r-controlled vowel pattern',
    parentQuestion: 'How should children read or in fork and storm?',
    quickAnswer: 'OR is a common r-controlled spelling pattern in words such as fork, storm and short. Children should process the vowel-plus-r pattern as a unit instead of applying short o first.',
    graphemes: ['or'],
    exampleWords: ['fork', 'storm', 'short', 'corn', 'horse'],
    commonConfusions: [
      'Reading o first as a standalone short vowel.',
      'Assuming every or spelling has exactly the same pronunciation across words and accents.',
    ],
    teachingNotes: [
      'Teach a regular core set and acknowledge variation later.',
      'Compare or with already known ar as part of an r-controlled system.',
    ],
    practiceIdeas: [
      'Sort ar and or words after decoding.',
      'Build an or family and read each word in a short phrase.',
    ],
    prerequisiteIds: ['r-controlled-ar'],
    nextIds: ['r-controlled-er-ir-ur'],
    curriculumAlignment: 'direct',
    curriculumRefs: [
      { courseId: 'early-phonics', lessonNumber: 31, label: 'Controlling R: OR' },
      { courseId: 'advanced-phonics', lessonNumber: 22, label: 'Controlling R: OR' },
    ],
    canonicalOwnerTopicId: null,
    expansionState: 'future-wave-2',
    futureSlugCandidate: 'or-r-controlled-vowels-phonics',
    expansionRationale: 'Granular r-controlled pattern is useful but must not compete with the existing broad authority owner.',
    distinctValueSignals: ['vowel-r-unit', 'ar-or-contrast', 'accent-awareness', 'word-family'],
  }),
  concept('r-controlled-er-ir-ur', {
    label: 'R-controlled ER, IR and UR',
    knowledgeStage: 'advanced-patterns',
    conceptType: 'r-controlled',
    progressionRank: 12,
    searchIntent: 'why er ir and ur can represent a similar r-controlled sound',
    parentQuestion: 'How can children spell a sound that may be written er, ir or ur?',
    quickAnswer: 'ER, IR and UR often represent a similar r-controlled vowel sound in words such as her, bird and turn. Reading can be easier than spelling because the same sound has several common spellings.',
    graphemes: ['er', 'ir', 'ur'],
    exampleWords: ['her', 'term', 'bird', 'shirt', 'turn', 'curl'],
    commonConfusions: [
      'Expecting the sound alone to determine whether er, ir or ur is correct.',
      'Teaching the three spellings as unrelated patterns rather than connected sound families.',
    ],
    teachingNotes: [
      'Teach the shared sound relationship while keeping spelling groups visible.',
      'Use reading first, then word-family memory for encoding.',
    ],
    practiceIdeas: [
      'Sort decoded words into er, ir and ur columns.',
      'Dictate a known set and recall which spelling family each word belongs to.',
    ],
    prerequisiteIds: ['r-controlled-ar', 'r-controlled-or'],
    nextIds: ['y-secret-vowel', 'diphthong-oo'],
    curriculumAlignment: 'direct',
    curriculumRefs: [
      { courseId: 'early-phonics', lessonNumber: 32, label: 'Controlling R: ER, IR, UR' },
      { courseId: 'advanced-phonics', lessonNumber: 23, label: 'Controlling R: IR, UR, ER' },
    ],
    canonicalOwnerTopicId: null,
    expansionState: 'future-wave-2',
    futureSlugCandidate: 'er-ir-ur-r-controlled-vowels-phonics',
    expansionRationale: 'Valuable spelling-choice concept, but broad r-controlled ownership must be protected first.',
    distinctValueSignals: ['same-sound-multiple-spellings', 'reading-vs-spelling', 'word-family-memory', 'encoding-diagnosis'],
  }),
  concept('y-secret-vowel', {
    label: 'Y as a vowel',
    knowledgeStage: 'advanced-patterns',
    conceptType: 'alternate-vowel',
    progressionRank: 13,
    searchIntent: 'how y can represent vowel sounds',
    parentQuestion: 'When does y act like a vowel?',
    quickAnswer: 'Y can represent vowel sounds when it occupies a vowel position in a word, as in my, happy and gym. Children benefit from learning the position and word pattern rather than being told that y is only a consonant.',
    graphemes: ['y'],
    exampleWords: ['my', 'cry', 'happy', 'baby', 'gym'],
    commonConfusions: [
      'Teaching y only as the consonant sound at the beginning of yes.',
      'Assuming y has one vowel pronunciation whenever it is not initial.',
    ],
    teachingNotes: [
      'Contrast initial consonant y with final or medial vowel y.',
      'Teach common position patterns separately, such as my versus happy.',
    ],
    practiceIdeas: [
      'Sort y words by consonant use and vowel use.',
      'Group vowel-y words by the sound y represents.',
    ],
    prerequisiteIds: ['short-vowels', 'magic-e'],
    nextIds: ['diphthong-oo', 'long-vowel-families'],
    curriculumAlignment: 'direct',
    curriculumRefs: [
      { courseId: 'early-phonics', lessonNumber: 33, label: 'Y as a Secret Vowel' },
      { courseId: 'advanced-phonics', lessonNumber: 14, label: 'Y as a Secret Vowel' },
    ],
    canonicalOwnerTopicId: null,
    expansionState: 'future-wave-2',
    futureSlugCandidate: 'y-as-a-vowel-phonics',
    expansionRationale: 'Useful alternate-vowel concept that should follow higher-priority core pattern pages.',
    distinctValueSignals: ['position-pattern', 'consonant-vowel-contrast', 'multiple-pronunciations', 'word-sort'],
  }),
  concept('diphthong-oo', {
    label: 'OO sound patterns',
    knowledgeStage: 'advanced-patterns',
    conceptType: 'diphthong',
    progressionRank: 14,
    searchIntent: 'why oo has different common pronunciations',
    parentQuestion: 'Why does oo sound different in moon and book?',
    quickAnswer: 'OO commonly appears with more than one pronunciation, including the sound in moon and the shorter sound in book. Children should learn the patterns in contrast sets rather than force every oo word into one family.',
    graphemes: ['oo'],
    exampleWords: ['moon', 'food', 'book', 'look', 'foot'],
    commonConfusions: [
      'Applying the moon pronunciation to every oo word.',
      'Calling the book set random exceptions instead of another common pronunciation family.',
    ],
    teachingNotes: [
      'Teach one oo family first, then contrast it with a small set from the other family.',
      'Use familiar vocabulary and repeated reading for the less predictable choice.',
    ],
    practiceIdeas: [
      'Sort oo words into moon-sound and book-sound groups.',
      'Read mixed oo cards and state the sound family.',
    ],
    prerequisiteIds: ['vowel-team-ee', 'vowel-team-oa'],
    nextIds: ['diphthong-oi-oy', 'diphthong-au-aw'],
    curriculumAlignment: 'direct',
    curriculumRefs: [
      { courseId: 'early-phonics', lessonNumber: 34, label: 'Diphthong OO' },
      { courseId: 'advanced-phonics', lessonNumber: 19, label: 'Diphthongs OO and UI' },
    ],
    canonicalOwnerTopicId: null,
    expansionState: 'future-wave-2',
    futureSlugCandidate: 'oo-sounds-phonics',
    expansionRationale: 'High parent-confusion value but lower pilot priority than the first core digraph and vowel-team set.',
    distinctValueSignals: ['two-pronunciation-families', 'contrast-sort', 'vocabulary-confirmation', 'mixed-reading'],
  }),
]);
