import { definePhonicsKnowledge as concept } from './schema.js';

export const FOUNDATION_PHONICS_KNOWLEDGE = Object.freeze([
  concept('phonemic-awareness', {
    label: 'Phonemic awareness before print',
    knowledgeStage: 'pre-phonics',
    conceptType: 'phonological-foundation',
    progressionRank: 0,
    searchIntent: 'why listening to and manipulating sounds matters before decoding',
    parentQuestion: 'Why can a child know letters but still struggle to blend words?',
    quickAnswer: 'Phonemic awareness is the ability to notice and work with speech sounds without relying on print. Blending is easier when a child can hear separate sounds and combine them orally before decoding written words.',
    graphemes: [],
    exampleWords: ['sat', 'map', 'sun', 'fish'],
    commonConfusions: [
      'Treating letter-name recall as proof that the child can hear sounds inside words.',
      'Adding more printed words when the same words cannot yet be blended or segmented orally.',
    ],
    teachingNotes: [
      'Use oral blending, sound identification and segmentation before increasing print demand.',
      'Connect letters after the child can attend to the target speech sounds with reasonable consistency.',
    ],
    practiceIdeas: [
      'Say /s/ /a/ /t/ and ask the child to blend the spoken sounds into sat.',
      'Say a simple word and tap one counter for each sound heard.',
    ],
    prerequisiteIds: [],
    nextIds: ['letter-sound-foundations', 'blending'],
    curriculumAlignment: 'prerequisite-context',
    curriculumRefs: [],
    canonicalOwnerTopicId: null,
    expansionState: 'supporting-only',
    futureSlugCandidate: null,
    expansionRationale: 'Foundational context supports many pages; a separate granular URL is not required for the first pilot.',
    distinctValueSignals: ['oral-sound-readiness', 'diagnostic-boundary', 'teaching-progression'],
  }),
  concept('letter-sound-foundations', {
    label: 'Letter-sound foundations',
    knowledgeStage: 'foundations',
    conceptType: 'sound-symbol',
    progressionRank: 1,
    searchIntent: 'connecting letters to useful early sound correspondences',
    parentQuestion: 'What should a child know about letter sounds before beginning word reading?',
    quickAnswer: 'Early phonics connects a small useful set of letters to sounds and builds recall accurate enough for the child to begin blending them into words.',
    graphemes: ['s', 'a', 't', 'i', 'p', 'n'],
    exampleWords: ['sat', 'tap', 'pin', 'sit'],
    commonConfusions: [
      'Using letter names instead of the sound needed for blending.',
      'Adding a strong extra vowel after a consonant sound, such as /suh/ instead of a clipped /s/.',
    ],
    teachingNotes: [
      'Teach a small useful set and begin combining it rather than waiting for all 26 letters.',
      'Use clean pronunciation and cumulative review.',
    ],
    practiceIdeas: [
      'Mix known letter cards and ask for sounds in random order.',
      'Build words only from correspondences already taught.',
    ],
    prerequisiteIds: ['phonemic-awareness'],
    nextIds: ['satpin', 'blending'],
    curriculumAlignment: 'direct',
    curriculumRefs: [
      { courseId: 'phonics-foundations', lessonNumber: 1, label: 'Letter S' },
      { courseId: 'phonics-foundations', lessonNumber: 2, label: 'Letter A' },
      { courseId: 'phonics-foundations', lessonNumber: 3, label: 'Letter T' },
    ],
    canonicalOwnerTopicId: null,
    expansionState: 'supporting-only',
    futureSlugCandidate: null,
    expansionRationale: 'Existing phonics definition, SATPIN and letter-sound practice owners already cover discovery paths.',
    distinctValueSignals: ['sound-pronunciation', 'cumulative-sequence', 'blend-readiness'],
  }),
  concept('satpin', {
    label: 'SATPIN starter sound set',
    knowledgeStage: 'foundations',
    conceptType: 'sound-symbol',
    progressionRank: 2,
    searchIntent: 'SATPIN phonics starter sequence',
    parentQuestion: 'Why are s, a, t, p, i and n often taught together?',
    quickAnswer: 'SATPIN gives children six useful correspondences that can quickly be rearranged into decodable combinations, allowing blending practice to begin before the whole alphabet is known.',
    graphemes: ['s', 'a', 't', 'p', 'i', 'n'],
    exampleWords: ['sat', 'tap', 'pin', 'sit', 'nap'],
    commonConfusions: [
      'Treating SATPIN as a rigid calendar schedule rather than a readiness-based starter sequence.',
      'Drilling six isolated sounds without using them for blending.',
    ],
    teachingNotes: [
      'Keep sound recall cumulative and begin blending as soon as enough correspondences are secure.',
      'Move forward based on usable sound recall and blending readiness.',
    ],
    practiceIdeas: [
      'Build sat, tap, pin and nap with movable letters.',
      'Mix the six letters before asking for sounds and a fresh blend.',
    ],
    prerequisiteIds: ['phonemic-awareness', 'letter-sound-foundations'],
    nextIds: ['blending', 'cvc-words'],
    curriculumAlignment: 'direct',
    curriculumRefs: [
      { courseId: 'early-phonics', lessonNumber: 1, label: 'Letters S, A, T' },
      { courseId: 'early-phonics', lessonNumber: 2, label: 'Letters I, P, N' },
    ],
    canonicalOwnerTopicId: 'satpin-phonics',
    expansionState: 'existing-owner',
    futureSlugCandidate: null,
    expansionRationale: 'Brick 5 already assigns SATPIN intent to the existing SATPIN guide.',
    distinctValueSignals: ['starter-sequence', 'blend-readiness', 'decodable-word-bank'],
  }),
  concept('blending', {
    label: 'Sound blending for word reading',
    knowledgeStage: 'early-decoding',
    conceptType: 'decoding-skill',
    progressionRank: 3,
    searchIntent: 'how children combine known sounds to read a word',
    parentQuestion: 'What does blending actually mean in phonics?',
    quickAnswer: 'Blending means holding a sequence of known speech sounds in order and combining them into a whole spoken word. It is the bridge between isolated sound knowledge and decoding.',
    graphemes: [],
    exampleWords: ['sat', 'pin', 'map', 'dog'],
    commonConfusions: [
      'Pausing so long between sounds that the sequence is lost.',
      'Guessing from the first letter or picture instead of attending to the complete sound sequence.',
    ],
    teachingNotes: [
      'Start orally, then use printed words containing only taught correspondences.',
      'Model smooth left-to-right blending and reduce support gradually.',
    ],
    practiceIdeas: [
      'Slide a finger under each grapheme while combining the sounds.',
      'Contrast two decodable words that differ in one sound.',
    ],
    prerequisiteIds: ['phonemic-awareness', 'letter-sound-foundations'],
    nextIds: ['short-vowels', 'cvc-words'],
    curriculumAlignment: 'embedded-skill',
    curriculumRefs: [
      { courseId: 'early-phonics', lessonNumber: 1, label: 'Letters S, A, T' },
      { courseId: 'early-phonics', lessonNumber: 2, label: 'Letters I, P, N' },
    ],
    canonicalOwnerTopicId: 'phonics-blending-progression',
    expansionState: 'existing-owner',
    futureSlugCandidate: null,
    expansionRationale: 'Brick 5 already assigns blending progression to the existing blending guide.',
    distinctValueSignals: ['decoding-process', 'error-diagnosis', 'teaching-progression'],
  }),
  concept('short-vowels', {
    label: 'Short vowel system',
    knowledgeStage: 'early-decoding',
    conceptType: 'vowel-system',
    progressionRank: 4,
    searchIntent: 'short vowel discrimination in early decoding',
    parentQuestion: 'How should children practise short a, e, i, o and u without mixing them up?',
    quickAnswer: 'Short vowels are best learned through hearing, contrasting and decoding them inside simple words. The child should be able to hear the middle vowel and use it while blending and spelling.',
    graphemes: ['a', 'e', 'i', 'o', 'u'],
    exampleWords: ['cat', 'bed', 'sit', 'hot', 'sun'],
    commonConfusions: [
      'Choosing a vowel from its written shape without listening to the middle sound.',
      'Practising one vowel in a fixed list so long that mixed discrimination remains weak.',
    ],
    teachingNotes: [
      'Contrast short vowels in decodable words once individual sounds are established.',
      'Use listening, reading and spelling together.',
    ],
    practiceIdeas: [
      'Sort decoded CVC words by middle vowel.',
      'Say a CVC word and choose the grapheme for the middle sound.',
    ],
    prerequisiteIds: ['phonemic-awareness', 'letter-sound-foundations'],
    nextIds: ['cvc-words', 'ck-rule', 'floss-rule'],
    curriculumAlignment: 'direct',
    curriculumRefs: [
      { courseId: 'phonics-foundations', lessonNumber: 27, label: 'Short Vowels' },
      { courseId: 'early-phonics', lessonNumber: 12, label: 'Short Vowels' },
    ],
    canonicalOwnerTopicId: null,
    expansionState: 'supporting-only',
    futureSlugCandidate: null,
    expansionRationale: 'Broad short-vowel intent remains shared knowledge until Brick 9 evaluates narrower non-duplicative opportunities.',
    distinctValueSignals: ['vowel-contrast', 'middle-sound-diagnosis', 'encoding-transfer'],
  }),
  concept('cvc-words', {
    label: 'CVC word decoding',
    knowledgeStage: 'early-decoding',
    conceptType: 'decoding-skill',
    progressionRank: 4,
    searchIntent: 'consonant-vowel-consonant words as first transferable decoding',
    parentQuestion: 'Why are CVC words an important early reading milestone?',
    quickAnswer: 'CVC words give children a compact structure for applying known consonant and short-vowel correspondences from left to right, making them a useful test of transferable decoding.',
    graphemes: ['CVC'],
    exampleWords: ['cat', 'pin', 'sun', 'map', 'dog'],
    commonConfusions: [
      'Calling every three-letter word CVC even when it contains an untaught pattern.',
      'Using the same cards so often that visual memorisation replaces fresh decoding.',
    ],
    teachingNotes: [
      'Use words built only from correspondences already known.',
      'Mix familiar and fresh words to check transfer.',
    ],
    practiceIdeas: [
      'Build a word with three sound boxes and change one phoneme at a time.',
      'Sort fresh CVC words by middle vowel after decoding.',
    ],
    prerequisiteIds: ['blending', 'short-vowels'],
    nextIds: ['ck-rule', 'floss-rule', 'digraph-ch'],
    curriculumAlignment: 'embedded-skill',
    curriculumRefs: [
      { courseId: 'phonics-foundations', lessonNumber: 27, label: 'Short Vowels' },
      { courseId: 'early-phonics', lessonNumber: 12, label: 'Short Vowels' },
    ],
    canonicalOwnerTopicId: 'cvc-words-explanation',
    expansionState: 'existing-owner',
    futureSlugCandidate: null,
    expansionRationale: 'Brick 5 already assigns CVC explanation intent to the existing parent guide.',
    distinctValueSignals: ['decoding-structure', 'fresh-word-transfer', 'sound-box-practice'],
  }),
]);
