import { definePhonicsKnowledge as concept } from './schema.js';
import { getKnowledgeCurriculumRefs } from './curriculum.js';

export const LATER_VOWEL_FAMILY_KNOWLEDGE = Object.freeze([
  concept('vowel-team-ui', {
    label: 'UI in the long /oo/ family', standardTerm: 'Alternate vowel spelling ui',
    knowledgeStage: 'advanced-patterns', conceptType: 'alternate-vowel', progressionRank: 15,
    searchIntent: 'recognising ui in fruit and suit without assuming every ui sounds alike',
    parentQuestion: 'Why can fruit and moon share a vowel sound with different spellings?',
    quickAnswer: 'UI represents /oo/ in fruit, suit and juice. Other ui words, such as build, use a different pronunciation, so teach a selected family rather than one pronunciation for every adjacent u and i.',
    phonemeDescription: 'UI represents /uː/ in the target family; build has /ɪ/.',
    graphemes: ['ui'], exampleWords: ['fruit', 'suit', 'juice', 'bruise'], contrastWords: ['build', 'guilt'],
    commonConfusions: ['Separating u and i in fruit.', 'Applying the fruit pronunciation to build.'],
    teachingNotes: ['Connect the target sound to the moon family of oo.', 'Juice also requires soft c and bruise requires s pronounced /z/; use them with teacher support until those mappings are known.'],
    practiceIdeas: ['Sort fruit, moon and build by vowel sound, then notice spelling differences.', 'Read suit and fruit in a short phrase and recall their ui spelling in dictation.'],
    prerequisiteIds: ['diphthong-oo'], nextIds: ['long-vowel-families'],
    curriculumAlignment: 'direct',
    curriculumRefs: [{ courseId: 'advanced-phonics', lessonNumber: 19, label: 'Diphthongs OO and UI' }],
    canonicalOwnerTopicId: null, expansionState: 'future-wave-2', futureSlugCandidate: 'ui-vowel-sound-phonics',
    expansionRationale: 'Small alternate-spelling family requires stronger demand evidence before a standalone page.',
    distinctValueSignals: ['ui-oo-connection', 'alternative-pronunciation', 'supported-word-choice'],
    supportingPaths: ['/blog/long-vowel-sounds-for-kids', '/free-reading-games-for-kids'],
  }),
  concept('long-vowel-families', {
    label: 'Long A, E, I, O and U sound families', standardTerm: 'Alternative graphemes for long-vowel sounds',
    knowledgeStage: 'advanced-patterns', conceptType: 'alternate-vowel', progressionRank: 16,
    searchIntent: 'comparing alternative long vowel spellings across sound families',
    parentQuestion: 'How can one long vowel sound have so many spellings?',
    quickAnswer: 'A long vowel sound may be written in several ways. After a child can read a taught pattern, compare a few spellings for that same sound and keep the correct spelling attached to each known word. The five sound families are connected knowledge, not five automatic page opportunities.',
    graphemes: ['a_e', 'ai', 'ay', 'eigh', 'ee', 'ea', 'ey', 'ie', 'igh', 'y', 'oa', 'ow', 'oe', 'u_e', 'ue', 'ew'],
    exampleWords: ['cake', 'rain', 'play', 'eight', 'see', 'leaf', 'key', 'pie', 'night', 'my', 'boat', 'snow', 'toe', 'cube', 'blue', 'new'],
    contrastWords: ['head', 'cow', 'give'],
    commonConfusions: ['Assuming the sound alone determines the correct spelling.', 'Generalising long o in snow to every ow word, including cow.', 'Treating long u as identical across every word and accent.'],
    teachingNotes: [
      'Long A: compare cake, rain and play before adding eigh in eight; position is a clue with exceptions.',
      'Long E: connect see, leaf and key while retaining each word spelling; ea in head is a later contrast.',
      'Long I: connect pie, night and my; treat igh as a three-letter spelling unit in night.',
      'Long O: compare boat, snow and toe, then contrast ow in cow without abandoning either correspondence.',
      'Long U: distinguish /yoo/ in cube and /oo/ in blue, acknowledging accent variation in new.',
      'The lesson titles establish five families. These are curated example choices, not a transcription of the programme lesson word lists; confirm less common spellings with the teacher before expansion.',
    ],
    practiceIdeas: ['Choose one secure vowel sound and sort three taught spellings, reading each word first.', 'Hide the list, dictate familiar words, and use a meaningful sentence to check the selected spelling.'],
    prerequisiteIds: ['magic-e', 'vowel-team-ai', 'vowel-team-ee', 'vowel-team-ie', 'vowel-team-oa'], nextIds: ['missing-sleepy-sounds'],
    curriculumAlignment: 'lesson-theme',
    curriculumRefs: getKnowledgeCurriculumRefs((lesson) => lesson.courseId === 'advanced-phonics' && /^Long [AEIOU] Sound Families$/.test(lesson.label)),
    canonicalOwnerTopicId: null, expansionState: 'supporting-only', futureSlugCandidate: null,
    expansionRationale: 'Broad long-vowel explanation already has an established editorial guide; preserve that guide without inventing a new Brick 5 topic ID.',
    distinctValueSignals: ['five-sound-families', 'spelling-choice', 'accent-boundary', 'sibling-pattern-contrast'],
    supportingPaths: ['/blog/long-vowel-sounds-for-kids', '/blog/phonics-long-vowels', '/free-word-building-games-for-kids'],
  }),
  concept('missing-sleepy-sounds', {
    label: 'Missing and Sleepy Sounds', standardTerm: 'Silent letters and pronunciation–spelling differences',
    knowledgeStage: 'advanced-patterns', conceptType: 'advanced-pattern', progressionRank: 17,
    searchIntent: 'noticing letters without a separate sound in familiar advanced words',
    parentQuestion: 'Should a child pronounce every written letter in a longer or unfamiliar word?',
    quickAnswer: 'Some familiar spelling patterns contain letters without a separate spoken sound, as in kn in knee, wr in write and mb in lamb. These written patterns should be learned in whole words. A silent letter is different from a weak vowel that is still pronounced.',
    graphemes: ['kn', 'wr', 'mb', 'augh', 'ough'], exampleWords: ['knee', 'write', 'lamb', 'caught', 'though', 'rough'], contrastWords: ['about', 'sofa'],
    commonConfusions: ['Forcing one sound from every written letter.', 'Treating every ough spelling as one sound.', 'Confusing a silent letter with the reduced but audible vowel in about.'],
    teachingNotes: [
      'The canonical curriculum supplies the brand lesson name, not an exact inventory of sleepy patterns. These candidate illustrations require teacher confirmation against the lesson materials.',
      'Start with the already taught kn correspondence; compare wr and mb only when the remaining patterns are familiar.',
      'Caught, though and rough illustrate advanced spelling families with different sounds. They are teacher-supported contrasts, not an initial independent decoding set or a claim that all gh is silent.',
      'Connect spelling to word meaning and related words where useful; never ask the child to guess from a picture.',
    ],
    practiceIdeas: ['Circle the known spelling unit in knee and write, say the whole word and account for the sounds heard.', 'Compare silent letters in lamb with the weak vowel in about, then revisit the written words in a short sentence.'],
    prerequisiteIds: ['digraph-kn', 'long-vowel-families'], nextIds: ['schwa-lazy-vowel'],
    curriculumAlignment: 'lesson-theme',
    curriculumRefs: [{ courseId: 'advanced-phonics', lessonNumber: 29, label: 'Missing and Sleepy Sounds' }],
    canonicalOwnerTopicId: null, expansionState: 'supporting-only', futureSlugCandidate: null,
    expansionRationale: 'Brand lesson theme needs a teacher-confirmed scope before any distinct search-page proposal.',
    distinctValueSignals: ['silent-vs-reduced', 'word-specific-pronunciation', 'teacher-scope-confirmation'],
    supportingPaths: ['/blog/digraphs-and-tricky-words', '/blog/phonics-multisyllabic'],
  }),
]);
