import { definePhonicsKnowledge as concept } from './schema.js';

export const LATER_CONSONANT_KNOWLEDGE = Object.freeze([
  concept('digraph-kn', {
    label: 'KN and the silent initial K',
    standardTerm: 'Initial kn representing /n/',
    knowledgeStage: 'pattern-decoding', conceptType: 'digraph', progressionRank: 6,
    searchIntent: 'reading initial kn without adding a k sound',
    parentQuestion: 'Why do knee and knot begin with a letter we do not say?',
    quickAnswer: 'In familiar words beginning with kn, the spelling represents /n/: knot sounds like not. Children can recognise the written pair while attending to the single initial sound.',
    phonemeDescription: 'Initial kn commonly represents /n/.',
    graphemes: ['kn'], exampleWords: ['knit', 'knot', 'knock', 'knee'], contrastWords: ['not', 'net'],
    commonConfusions: ['Adding /k/ before /n/.', 'Leaving out k in spelling because it cannot be heard.'],
    teachingNotes: ['Start with knit and knot; knee also needs ee knowledge.', 'Compare knot/not orally, then notice the different spellings and meanings.'],
    practiceIdeas: ['Underline kn and blend the remaining taught patterns.', 'Dictate a familiar kn word and explain why its first sound has two written letters.'],
    prerequisiteIds: ['cvc-words'], nextIds: ['missing-sleepy-sounds'],
    curriculumAlignment: 'direct',
    curriculumRefs: [{ courseId: 'early-phonics', lessonNumber: 15, label: 'Digraphs TH and KN' }],
    canonicalOwnerTopicId: null, expansionState: 'future-wave-2', futureSlugCandidate: 'kn-silent-k-phonics',
    expansionRationale: 'Useful silent-letter extension; retain outside the initial pilot until demand and overlap are reviewed.',
    distinctValueSignals: ['silent-letter-boundary', 'homophone-contrast', 'sound-spelling-gap'],
    supportingPaths: ['/blog/digraphs-and-tricky-words', '/free-word-building-games-for-kids'],
  }),
  concept('digraph-tch', {
    label: 'CH and TCH spelling choice',
    standardTerm: 'Consonant digraph ch and trigraph tch',
    knowledgeStage: 'advanced-patterns', conceptType: 'spelling-rule', progressionRank: 7,
    searchIntent: 'choosing tch or ch after a short vowel',
    parentQuestion: 'Why does match end in tch while much ends in ch?',
    quickAnswer: 'TCH commonly spells the /ch/ sound immediately after a single short vowel in a one-syllable word, as in match. CH also spells that sound, and familiar exceptions such as much and rich need explicit practice.',
    phonemeDescription: 'ch and tch can both represent /tʃ/.',
    graphemes: ['ch', 'tch'], exampleWords: ['match', 'catch', 'pitch', 'fetch', 'hutch'], contrastWords: ['much', 'rich', 'lunch'],
    commonConfusions: ['Reading tch as three separate sounds.', 'Applying tch to every /ch/ ending, including after another consonant.'],
    teachingNotes: ['Connect spelling choice to the preceding vowel and one-syllable context.', 'Show lunch after a consonant and much as a familiar exception; do not turn the tendency into a guarantee.'],
    practiceIdeas: ['Sort match, lunch and much and explain which follows the usual context.', 'Build pitch and change its first sound to make a fresh word before dictation.'],
    prerequisiteIds: ['digraph-ch', 'short-vowels'], nextIds: ['digraph-wh-ph'],
    curriculumAlignment: 'direct',
    curriculumRefs: [{ courseId: 'advanced-phonics', lessonNumber: 5, label: 'Digraphs CH and TCH' }],
    canonicalOwnerTopicId: null, expansionState: 'future-wave-2', futureSlugCandidate: 'ch-tch-spelling-phonics',
    expansionRationale: 'Distinct spelling contrast follows the CH pilot and requires a separate overlap and demand review.',
    distinctValueSignals: ['trigraph-vs-digraph', 'short-vowel-context', 'exception-contrast'],
    supportingPaths: ['/blog/digraphs-and-tricky-words', '/blog/phonics-rules-for-beginners'],
  }),
  concept('digraph-wh-ph', {
    label: 'WH and PH correspondences',
    standardTerm: 'Consonant digraphs with distinct pronunciations',
    knowledgeStage: 'advanced-patterns', conceptType: 'digraph', progressionRank: 7,
    searchIntent: 'recognising wh and ph as spelling patterns with different sounds',
    parentQuestion: 'Do wh and ph work like sh?',
    quickAnswer: 'Both are useful written pairs, but they represent different sounds. PH commonly represents /f/ in graph; WH commonly represents /w/ in when for many speakers, with accent differences and words such as who requiring separate attention.',
    phonemeDescription: 'PH commonly /f/; WH often /w/, or /ʍ/ in some accents; who uses /h/.',
    graphemes: ['wh', 'ph'], exampleWords: ['when', 'whip', 'whisk', 'graph', 'phone'], contrastWords: ['who', 'fish'],
    commonConfusions: ['Assuming h adds a separate /h/ after every consonant.', 'Treating a legitimate accent difference in wh as a reading error.'],
    teachingNotes: ['Practise WH and PH in separate small sets before mixing them.', 'Phone needs Magic E; explain this extra pattern rather than assuming the whole list is ready for every learner.'],
    practiceIdeas: ['Sort when, whip, graph and phone by written pair and say its sound.', 'Compare ph in graph with f in fish, then spell one familiar word from each set.'],
    prerequisiteIds: ['digraph-ch', 'digraph-sh'], nextIds: ['missing-sleepy-sounds'],
    curriculumAlignment: 'direct',
    curriculumRefs: [{ courseId: 'advanced-phonics', lessonNumber: 7, label: 'WH and PH' }],
    canonicalOwnerTopicId: null, expansionState: 'supporting-only', futureSlugCandidate: null,
    expansionRationale: 'The combined lesson is useful knowledge but does not establish one coherent standalone search intent.',
    distinctValueSignals: ['separate-correspondences', 'accent-awareness', 'decodability-boundary'],
    supportingPaths: ['/blog/digraphs-and-tricky-words', '/free-reading-games-for-kids'],
  }),
]);
