import { definePhonicsKnowledge as concept } from './schema.js';

export const PILOT_RULE_AND_DIGRAPH_KNOWLEDGE = Object.freeze([
  concept('ck-rule', {
    label: 'CK spelling rule',
    knowledgeStage: 'pattern-decoding',
    conceptType: 'spelling-rule',
    progressionRank: 5,
    searchIntent: 'when ck commonly spells /k/ after a short vowel',
    parentQuestion: 'When should a child use ck instead of k at the end of a word?',
    quickAnswer: 'In many one-syllable words, ck is used for /k/ immediately after a single short vowel, as in back, neck, sick, rock and duck. It is a useful spelling generalisation, not an exception-free law.',
    graphemes: ['ck', 'k'],
    exampleWords: ['back', 'neck', 'sick', 'rock', 'duck'],
    commonConfusions: [
      'Using ck after every vowel regardless of whether the vowel is short.',
      'Treating the pattern as universal instead of a useful spelling generalisation.',
    ],
    teachingNotes: [
      'Anchor the rule to one-syllable words with a single short vowel immediately before /k/.',
      'Contrast ck endings with familiar k endings so the child notices context rather than memorising a list.',
    ],
    practiceIdeas: [
      'Sort decodable words by k versus ck ending.',
      'Dictate short-vowel words and justify the final spelling choice.',
    ],
    prerequisiteIds: ['cvc-words', 'short-vowels'],
    nextIds: ['floss-rule', 'digraph-ch'],
    curriculumAlignment: 'direct',
    curriculumRefs: [
      { courseId: 'early-phonics', lessonNumber: 5, label: 'CK Rule' },
      { courseId: 'advanced-phonics', lessonNumber: 2, label: 'CK Rule' },
    ],
    supportingPaths: ['/blog/digraphs-and-tricky-words', '/blog/phonics-rules-for-beginners', '/free-word-building-games-for-kids'],
    canonicalOwnerTopicId: null,
    expansionState: 'pilot-wave-1',
    futureSlugCandidate: 'ck-rule-phonics',
    expansionRationale: 'Distinct spelling-rule intent with clear boundaries, examples and direct curriculum alignment.',
    distinctValueSignals: ['rule-boundary', 'k-vs-ck-contrast', 'dictation-transfer', 'exception-awareness'],
  }),
  concept('floss-rule', {
    label: 'Floss spelling rule',
    knowledgeStage: 'pattern-decoding',
    conceptType: 'spelling-rule',
    progressionRank: 5,
    searchIntent: 'why f l s and z are often doubled after a short vowel',
    parentQuestion: 'Why do words such as puff, hill, miss and buzz end with doubled consonants?',
    quickAnswer: 'In many one-syllable words with one short vowel, final f, l, s or z is doubled, as in puff, hill, miss and buzz. The Floss rule is a useful generalisation with exceptions.',
    graphemes: ['ff', 'll', 'ss', 'zz'],
    exampleWords: ['puff', 'hill', 'miss', 'buzz', 'off'],
    commonConfusions: [
      'Doubling f, l, s or z regardless of syllable and vowel context.',
      'Presenting the mnemonic as absolute despite common exceptions such as if, gas and yes.',
    ],
    teachingNotes: [
      'Teach the one-syllable and short-vowel context before the mnemonic.',
      'Use exceptions as contrast after the main generalisation is secure.',
    ],
    practiceIdeas: [
      'Sort short-vowel words into doubled and not-doubled spellings.',
      'Dictate a mixed set and explain which words fit the pattern.',
    ],
    prerequisiteIds: ['cvc-words', 'short-vowels'],
    nextIds: ['qu-sound', 'digraph-ch'],
    curriculumAlignment: 'direct',
    curriculumRefs: [
      { courseId: 'early-phonics', lessonNumber: 8, label: 'Floss Rule' },
      { courseId: 'advanced-phonics', lessonNumber: 4, label: 'Floss Rule' },
    ],
    supportingPaths: ['/blog/digraphs-and-tricky-words', '/blog/phonics-rules-for-beginners', '/free-word-building-games-for-kids'],
    canonicalOwnerTopicId: null,
    expansionState: 'pilot-wave-1',
    futureSlugCandidate: 'floss-rule-phonics',
    expansionRationale: 'Distinct rule intent with strong parent-confusion value and enough examples for original teaching value.',
    distinctValueSignals: ['rule-boundary', 'exception-set', 'doubling-contrast', 'spelling-transfer'],
  }),
  concept('qu-sound', {
    label: 'QU sound pattern',
    knowledgeStage: 'pattern-decoding',
    conceptType: 'sound-symbol',
    progressionRank: 5,
    searchIntent: 'how q and u commonly work together in early phonics words',
    parentQuestion: 'Why is q usually taught together with u?',
    quickAnswer: 'In many common English words, q is followed by u and the pair commonly represents /kw/, as in queen, quit and quiz. Less common exceptions can be added after the frequent pattern is secure.',
    graphemes: ['qu'],
    exampleWords: ['quit', 'quiz', 'queen', 'quick', 'quack'],
    commonConfusions: [
      'Sounding q and u as unrelated letters in a familiar qu pattern.',
      'Assuming qu has exactly the same pronunciation in every English word.',
    ],
    teachingNotes: [
      'Teach the frequent /kw/ correspondence as two phonemes /k/ + /w/, using words with known remaining patterns; queen also requires ee.',
      'Keep rare or borrowed-word exceptions outside the first teaching set.',
    ],
    practiceIdeas: [
      'Build qu words with a spelling card for qu, then count /k/ and /w/ as two phonemes.',
      'Sort familiar words by qu versus another /k/ spelling.',
    ],
    prerequisiteIds: ['cvc-words'],
    nextIds: ['digraph-ch', 'digraph-sh'],
    curriculumAlignment: 'direct',
    curriculumRefs: [{ courseId: 'early-phonics', lessonNumber: 11, label: 'QU Sound' }],
    supportingPaths: ['/blog/digraphs-and-tricky-words', '/blog/phonics-rules-for-beginners', '/free-word-building-games-for-kids'],
    canonicalOwnerTopicId: null,
    expansionState: 'pilot-wave-1',
    futureSlugCandidate: 'qu-sound-phonics',
    expansionRationale: 'Narrow grapheme pattern with clear decoding value and low overlap with broad guides.',
    distinctValueSignals: ['grapheme-unit', 'sound-boundary', 'decodable-examples', 'exception-awareness'],
  }),
  concept('digraph-ch', {
    label: 'CH digraph',
    knowledgeStage: 'pattern-decoding',
    conceptType: 'digraph',
    progressionRank: 6,
    searchIntent: 'how ch commonly represents one consonant sound',
    parentQuestion: 'How should children read ch without sounding c and h separately?',
    quickAnswer: 'In early phonics, ch is commonly taught as one grapheme representing /ch/ in words such as chat, chip and much. Less common pronunciations can be introduced later.',
    graphemes: ['ch'],
    exampleWords: ['chat', 'chip', 'much', 'chop', 'rich'],
    commonConfusions: [
      'Saying separate c and h sounds instead of recognising the digraph.',
      'Introducing /k/ in chemist or /sh/ in chef before the main pattern is secure.',
    ],
    teachingNotes: [
      'Begin with the frequent early correspondence and already taught vowels.',
      'Later contrast alternative pronunciations as vocabulary expands.',
    ],
    practiceIdeas: [
      'Highlight ch as one grapheme before blending.',
      'Sort decoded words with ch at the beginning and end.',
    ],
    prerequisiteIds: ['cvc-words'],
    nextIds: ['digraph-sh', 'digraph-th', 'digraph-tch'],
    curriculumAlignment: 'direct',
    curriculumRefs: [
      { courseId: 'early-phonics', lessonNumber: 13, label: 'Digraph CH' },
      { courseId: 'advanced-phonics', lessonNumber: 5, label: 'Digraphs CH and TCH' },
    ],
    supportingPaths: ['/blog/digraphs-and-tricky-words', '/blog/phonics-rules-for-beginners', '/free-word-building-games-for-kids'],
    canonicalOwnerTopicId: null,
    expansionState: 'pilot-wave-1',
    futureSlugCandidate: 'ch-digraph-phonics',
    expansionRationale: 'High-frequency digraph intent with a useful alternative-pronunciation boundary.',
    distinctValueSignals: ['digraph-recognition', 'position-contrast', 'alternative-pronunciation-boundary', 'decoding-practice'],
  }),
  concept('digraph-sh', {
    label: 'SH digraph',
    knowledgeStage: 'pattern-decoding',
    conceptType: 'digraph',
    progressionRank: 6,
    searchIntent: 'how sh represents one consonant sound in words',
    parentQuestion: 'How do I teach sh as one sound instead of two letters?',
    quickAnswer: 'The letters s and h frequently work together as the digraph sh, representing /sh/ in words such as ship, shop and fish.',
    graphemes: ['sh'],
    exampleWords: ['ship', 'shop', 'fish', 'rush', 'shell'],
    commonConfusions: [
      'Reading s and h separately when they form the taught digraph.',
      'Memorising a list without recognising sh inside fresh words.',
    ],
    teachingNotes: [
      'Mark sh as one grapheme, then blend it with known correspondences.',
      'Use both initial and final positions.',
    ],
    practiceIdeas: [
      'Build and read minimal contrasts such as ship and shop.',
      'Underline sh before decoding each word in a mixed list.',
    ],
    prerequisiteIds: ['cvc-words'],
    nextIds: ['digraph-th', 'digraph-ng'],
    curriculumAlignment: 'direct',
    curriculumRefs: [
      { courseId: 'early-phonics', lessonNumber: 14, label: 'Digraphs SH and NG' },
      { courseId: 'advanced-phonics', lessonNumber: 6, label: 'Digraphs SH and TH' },
    ],
    supportingPaths: ['/blog/digraphs-and-tricky-words', '/blog/phonics-rules-for-beginners', '/free-word-building-games-for-kids'],
    canonicalOwnerTopicId: null,
    expansionState: 'pilot-wave-1',
    futureSlugCandidate: 'sh-digraph-phonics',
    expansionRationale: 'Clear standalone grapheme intent with reusable position and blending practice.',
    distinctValueSignals: ['digraph-recognition', 'initial-final-position', 'fresh-word-transfer', 'minimal-contrast'],
  }),
  concept('digraph-th', {
    label: 'TH digraph: voiced and voiceless',
    knowledgeStage: 'pattern-decoding',
    conceptType: 'digraph',
    progressionRank: 6,
    searchIntent: 'why th has two common pronunciations',
    parentQuestion: 'Why does th sound different in thin and this?',
    quickAnswer: 'TH commonly represents two related sounds: voiceless /th/ as in thin and voiced /th/ as in this. Children benefit from hearing and feeling the contrast.',
    graphemes: ['th'],
    exampleWords: ['thin', 'bath', 'this', 'that', 'then'],
    commonConfusions: [
      'Teaching only one th pronunciation and treating the other as an exception.',
      'Replacing th with another sound without first noticing tongue position and voicing.',
    ],
    teachingNotes: [
      'Contrast voiced and voiceless examples in a small set.',
      'Keep decoding practice separate from accent judgement.',
    ],
    practiceIdeas: [
      'Sort decoded th words into voice-off and voice-on groups.',
      'Use a mirror to check tongue placement while reading.',
    ],
    prerequisiteIds: ['cvc-words'],
    nextIds: ['digraph-ng', 'digraph-wh-ph'],
    curriculumAlignment: 'direct',
    curriculumRefs: [
      { courseId: 'early-phonics', lessonNumber: 15, label: 'Digraphs TH and KN' },
      { courseId: 'advanced-phonics', lessonNumber: 6, label: 'Digraphs SH and TH' },
    ],
    supportingPaths: ['/blog/digraphs-and-tricky-words', '/blog/phonics-rules-for-beginners', '/free-word-building-games-for-kids'],
    canonicalOwnerTopicId: null,
    expansionState: 'pilot-wave-1',
    futureSlugCandidate: 'th-digraph-phonics',
    expansionRationale: 'Distinct two-sound teaching problem with strong diagnostic value.',
    distinctValueSignals: ['voicing-contrast', 'articulation-cue', 'two-sound-boundary', 'decoding-practice'],
  }),
  concept('digraph-ng', {
    label: 'NG digraph',
    knowledgeStage: 'pattern-decoding',
    conceptType: 'digraph',
    progressionRank: 6,
    searchIntent: 'how ng represents a nasal sound in many words',
    parentQuestion: 'Why should ng be read as one sound in words such as sing?',
    quickAnswer: 'N and g frequently work together as the grapheme ng, representing /ng/ in words such as sing, ring and long.',
    graphemes: ['ng'],
    exampleWords: ['sing', 'ring', 'long', 'song', 'king'],
    commonConfusions: [
      'Pronouncing n and hard g separately in a taught ng word.',
      'Recognising ng only in memorised endings rather than fresh words.',
    ],
    teachingNotes: [
      'Use familiar one-syllable examples first and mark ng as one sound unit.',
      'Connect reading and spelling so the child selects ng for the final sound.',
    ],
    practiceIdeas: [
      'Sort words by -ing, -ang, -ong and -ung after decoding.',
      'Say a word ending in /ng/ and build its final grapheme.',
    ],
    prerequisiteIds: ['cvc-words'],
    nextIds: ['vowel-team-ai', 'vowel-team-ee'],
    curriculumAlignment: 'direct',
    curriculumRefs: [{ courseId: 'early-phonics', lessonNumber: 14, label: 'Digraphs SH and NG' }],
    supportingPaths: ['/blog/digraphs-and-tricky-words', '/blog/phonics-rules-for-beginners', '/free-word-building-games-for-kids'],
    canonicalOwnerTopicId: null,
    expansionState: 'pilot-wave-1',
    futureSlugCandidate: 'ng-digraph-phonics',
    expansionRationale: 'Narrow reusable grapheme with a clear error pattern and spelling transfer.',
    distinctValueSignals: ['nasal-sound-unit', 'final-position', 'spelling-transfer', 'error-diagnosis'],
  }),
  concept('soft-c-hard-c', {
    label: 'Soft C and hard C',
    knowledgeStage: 'pattern-decoding',
    conceptType: 'advanced-pattern',
    progressionRank: 10,
    searchIntent: 'when c commonly represents /s/ or /k/',
    parentQuestion: 'Why does c sound different in cat and city?',
    quickAnswer: 'C commonly represents /k/ in cat and cup, but often represents /s/ before e, i or y, as in cent, city and cycle. The e-i-y clue is useful but not exception-free.',
    graphemes: ['c'],
    exampleWords: ['cat', 'cup', 'cent', 'city', 'cycle'],
    commonConfusions: [
      'Assuming c always represents /k/ because that was its first taught sound.',
      'Presenting the e-i-y clue as an absolute rule.',
    ],
    teachingNotes: [
      'Contrast hard-c and soft-c words and inspect what follows c.',
      'Use the e-i-y clue as a prediction that is checked against a known word.',
    ],
    practiceIdeas: [
      'Sort c words by /k/ and /s/.',
      'Highlight the letter after c and predict the likely sound before reading.',
    ],
    prerequisiteIds: ['digraph-ch', 'vowel-team-ee'],
    nextIds: ['soft-g-hard-g', 'r-controlled-ar'],
    curriculumAlignment: 'direct',
    curriculumRefs: [
      { courseId: 'early-phonics', lessonNumber: 28, label: 'Soft C and Hard C' },
      { courseId: 'advanced-phonics', lessonNumber: 13, label: 'Soft C and G, Hard C and G' },
    ],
    supportingPaths: ['/blog/digraphs-and-tricky-words', '/blog/phonics-rules-for-beginners', '/free-word-building-games-for-kids'],
    canonicalOwnerTopicId: null,
    expansionState: 'pilot-wave-1',
    futureSlugCandidate: 'soft-c-hard-c-phonics',
    expansionRationale: 'Strong contrast intent with a memorable but non-absolute context clue.',
    distinctValueSignals: ['soft-hard-contrast', 'e-i-y-context', 'prediction-check', 'exception-awareness'],
  }),
]);

