import { definePhonicsKnowledge as concept } from './schema.js';

export const PILOT_VOWEL_AND_SYLLABLE_KNOWLEDGE = Object.freeze([
  concept('vowel-team-ai', {
    label: 'AI vowel team',
    knowledgeStage: 'pattern-decoding',
    conceptType: 'vowel-team',
    progressionRank: 7,
    searchIntent: 'how ai commonly spells long a inside words',
    parentQuestion: 'When does ai make the long a sound?',
    quickAnswer: 'AI commonly represents long a in words such as rain, train and paint. It is often found inside a word, while other long-a spellings appear in other positions, so position is a useful tendency rather than an absolute rule.',
    graphemes: ['ai'],
    exampleWords: ['rain', 'train', 'paint', 'mail', 'snail'],
    commonConfusions: [
      'Treating ai and ay as interchangeable in every position.',
      'Reading the two vowel letters separately instead of as one grapheme.',
    ],
    teachingNotes: [
      'Teach ai as one grapheme before comparing other long-a spellings.',
      'Use position as a spelling clue, not a promise without exceptions.',
    ],
    practiceIdeas: [
      'Highlight ai before blending each word.',
      'Sort familiar long-a words by ai and another taught spelling.',
    ],
    prerequisiteIds: ['digraph-ch', 'digraph-sh'],
    nextIds: ['vowel-team-ee', 'vowel-team-ea'],
    curriculumAlignment: 'direct',
    curriculumRefs: [
      { courseId: 'early-phonics', lessonNumber: 16, label: 'Vowel Team AI' },
      { courseId: 'advanced-phonics', lessonNumber: 10, label: 'Vowel Teams AI, EE, and EA' },
    ],
    supportingPaths: ['/blog/long-vowel-sounds-for-kids', '/blog/phonics-multisyllabic', '/free-word-building-games-for-kids'],
    canonicalOwnerTopicId: null,
    expansionState: 'pilot-wave-1',
    futureSlugCandidate: 'ai-vowel-team-phonics',
    expansionRationale: 'Specific vowel-team intent with position guidance, spelling contrast and enough fresh examples.',
    distinctValueSignals: ['vowel-team-unit', 'position-tendency', 'spelling-contrast', 'decodable-example-bank'],
  }),
  concept('vowel-team-ee', {
    label: 'EE vowel team',
    knowledgeStage: 'pattern-decoding',
    conceptType: 'vowel-team',
    progressionRank: 7,
    searchIntent: 'how ee commonly represents long e',
    parentQuestion: 'How should children recognise ee in words such as green and feet?',
    quickAnswer: 'EE commonly represents long e in words such as green, feet and sleep. Children should learn ee as one grapheme and then compare it with other long-e spellings as pattern knowledge grows.',
    graphemes: ['ee'],
    exampleWords: ['see', 'green', 'feet', 'sleep', 'seed'],
    commonConfusions: [
      'Reading the two e letters separately.',
      'Assuming every long-e word must be spelled with ee.',
    ],
    teachingNotes: [
      'Begin with a stable set of ee words using already taught consonants.',
      'Introduce alternative long-e spellings only after the main pattern is secure.',
    ],
    practiceIdeas: [
      'Build ee words by changing onset or final consonant.',
      'Sort long-e words by ee and another taught spelling.',
    ],
    prerequisiteIds: ['digraph-ch', 'digraph-sh'],
    nextIds: ['vowel-team-ea', 'vowel-team-ie'],
    curriculumAlignment: 'direct',
    curriculumRefs: [
      { courseId: 'early-phonics', lessonNumber: 17, label: 'Vowel Team EE' },
      { courseId: 'advanced-phonics', lessonNumber: 10, label: 'Vowel Teams AI, EE, and EA' },
    ],
    supportingPaths: ['/blog/long-vowel-sounds-for-kids', '/blog/phonics-multisyllabic', '/free-word-building-games-for-kids'],
    canonicalOwnerTopicId: null,
    expansionState: 'pilot-wave-1',
    futureSlugCandidate: 'ee-vowel-team-phonics',
    expansionRationale: 'High-frequency vowel team with clear reading and spelling contrast value.',
    distinctValueSignals: ['vowel-team-unit', 'long-e-mapping', 'alternative-spelling-boundary', 'word-building'],
  }),
  concept('vowel-team-ea', {
    label: 'EA vowel team',
    knowledgeStage: 'pattern-decoding',
    conceptType: 'vowel-team',
    progressionRank: 7,
    searchIntent: 'why ea can represent more than one vowel sound',
    parentQuestion: 'Why does ea sound different in team and head?',
    quickAnswer: 'EA is variable. It often represents long e as in team and seat, but also appears with other pronunciations such as head and break. Teach a selected high-frequency pattern first, then add contrast sets.',
    graphemes: ['ea'],
    exampleWords: ['team', 'seat', 'leaf', 'head', 'break'],
    commonConfusions: [
      'Teaching every ea word as long e.',
      'Mixing multiple pronunciations before the first pattern is secure.',
    ],
    teachingNotes: [
      'Teach the target pronunciation in a controlled set, then add common alternatives.',
      'Describe alternative pronunciations as additional patterns, not random failures.',
    ],
    practiceIdeas: [
      'Sort familiar ea words by pronunciation after reading them.',
      'Build a long-e ea family, then compare one or two common alternatives.',
    ],
    prerequisiteIds: ['vowel-team-ee'],
    nextIds: ['vowel-team-ie', 'vowel-team-oa'],
    curriculumAlignment: 'direct',
    curriculumRefs: [
      { courseId: 'early-phonics', lessonNumber: 18, label: 'Vowel Team EA' },
      { courseId: 'advanced-phonics', lessonNumber: 10, label: 'Vowel Teams AI, EE, and EA' },
    ],
    supportingPaths: ['/blog/long-vowel-sounds-for-kids', '/blog/phonics-multisyllabic', '/free-word-building-games-for-kids'],
    canonicalOwnerTopicId: null,
    expansionState: 'pilot-wave-1',
    futureSlugCandidate: 'ea-vowel-team-phonics',
    expansionRationale: 'Strong parent-confusion intent because the same grapheme has common alternative pronunciations.',
    distinctValueSignals: ['pronunciation-contrast', 'frequency-first-teaching', 'exception-not-random', 'word-sort'],
  }),
  concept('vowel-team-ie', {
    label: 'IE vowel team',
    knowledgeStage: 'pattern-decoding',
    conceptType: 'vowel-team',
    progressionRank: 7,
    searchIntent: 'how ie can represent long i and other vowel sounds',
    parentQuestion: 'Why does ie not sound the same in every word?',
    quickAnswer: 'IE appears in more than one pronunciation pattern. Children can first learn a selected long-i set such as pie and tie, then later contrast other common ie words rather than forcing one pronunciation onto every spelling.',
    graphemes: ['ie'],
    exampleWords: ['pie', 'tie', 'cried', 'field', 'chief'],
    commonConfusions: [
      'Expecting one fixed pronunciation for every ie spelling.',
      'Mixing long-i and long-e examples before the first pattern is stable.',
    ],
    teachingNotes: [
      'Teach one selected pronunciation family at a time.',
      'Use context only after the child has attempted the taught phonics pattern.',
    ],
    practiceIdeas: [
      'Sort a controlled ie list by represented vowel sound.',
      'Read a familiar long-i family, then compare one contrast example.',
    ],
    prerequisiteIds: ['vowel-team-ee', 'vowel-team-ea'],
    nextIds: ['vowel-team-oa', 'magic-e'],
    curriculumAlignment: 'direct',
    curriculumRefs: [
      { courseId: 'early-phonics', lessonNumber: 19, label: 'Vowel Team IE' },
      { courseId: 'advanced-phonics', lessonNumber: 11, label: 'Vowel Teams IE and OA' },
    ],
    supportingPaths: ['/blog/long-vowel-sounds-for-kids', '/blog/phonics-multisyllabic', '/free-word-building-games-for-kids'],
    canonicalOwnerTopicId: null,
    expansionState: 'pilot-wave-1',
    futureSlugCandidate: 'ie-vowel-team-phonics',
    expansionRationale: 'Variable pronunciation creates a distinct teaching and parent-explanation need.',
    distinctValueSignals: ['pronunciation-family', 'contrast-sequencing', 'word-family-practice', 'context-after-decoding'],
  }),
  concept('vowel-team-oa', {
    label: 'OA vowel team',
    knowledgeStage: 'pattern-decoding',
    conceptType: 'vowel-team',
    progressionRank: 7,
    searchIntent: 'how oa commonly represents long o',
    parentQuestion: 'How should children read oa in words such as boat and road?',
    quickAnswer: 'OA commonly represents long o in words such as boat, coat and road. Teaching it as one grapheme helps children blend efficiently and compare it later with other long-o spellings.',
    graphemes: ['oa'],
    exampleWords: ['boat', 'coat', 'road', 'goat', 'soap'],
    commonConfusions: [
      'Reading o and a as separate vowel sounds.',
      'Assuming long o is always spelled oa.',
    ],
    teachingNotes: [
      'Use a controlled oa family first.',
      'Keep spelling choice connected to known word patterns rather than sound alone.',
    ],
    practiceIdeas: [
      'Build oa words by changing onset and final consonants.',
      'Sort long-o words by oa and another taught spelling.',
    ],
    prerequisiteIds: ['vowel-team-ai', 'vowel-team-ee'],
    nextIds: ['magic-e', 'rabbit-rule'],
    curriculumAlignment: 'direct',
    curriculumRefs: [
      { courseId: 'early-phonics', lessonNumber: 20, label: 'Vowel Team OA' },
      { courseId: 'advanced-phonics', lessonNumber: 11, label: 'Vowel Teams IE and OA' },
    ],
    supportingPaths: ['/blog/long-vowel-sounds-for-kids', '/blog/phonics-multisyllabic', '/free-word-building-games-for-kids'],
    canonicalOwnerTopicId: null,
    expansionState: 'pilot-wave-1',
    futureSlugCandidate: 'oa-vowel-team-phonics',
    expansionRationale: 'Stable high-frequency vowel-team intent with useful spelling-system comparisons.',
    distinctValueSignals: ['vowel-team-unit', 'long-o-mapping', 'spelling-choice', 'word-building'],
  }),
  concept('magic-e', {
    label: 'Magic E / silent-e pattern',
    knowledgeStage: 'pattern-decoding',
    conceptType: 'magic-e',
    progressionRank: 8,
    searchIntent: 'how final e often changes the vowel sound in VCe words',
    parentQuestion: 'What does Magic E do in cape, kite and hope?',
    quickAnswer: 'In many vowel-consonant-e words, final e is not pronounced as a separate syllable and the earlier vowel represents a long sound, as in cap/cape, kit/kite and hop/hope. Common exceptions such as have and give should be taught explicitly.',
    graphemes: ['a_e', 'e_e', 'i_e', 'o_e', 'u_e'],
    exampleWords: ['cape', 'these', 'kite', 'hope', 'cube'],
    commonConfusions: [
      'Reading final e as a separate sound or syllable in a standard VCe word.',
      'Calling every word ending in e a Magic E word.',
    ],
    teachingNotes: [
      'Use short-vowel versus VCe contrasts such as cap/cape and kit/kite.',
      'Teach common exceptions after the core pattern is secure.',
    ],
    practiceIdeas: [
      'Add and remove final e from decodable word pairs and reread.',
      'Sort final-e words into VCe pattern words and known exceptions.',
    ],
    prerequisiteIds: ['short-vowels', 'vowel-team-ai', 'vowel-team-oa'],
    nextIds: ['rabbit-rule', 'consonant-le'],
    curriculumAlignment: 'direct',
    curriculumRefs: [
      { courseId: 'early-phonics', lessonNumber: 21, label: 'Magic E: A_E' },
      { courseId: 'early-phonics', lessonNumber: 22, label: 'Magic E: E_E' },
      { courseId: 'early-phonics', lessonNumber: 23, label: 'Magic E: I_E' },
      { courseId: 'early-phonics', lessonNumber: 24, label: 'Magic E: O_E' },
      { courseId: 'early-phonics', lessonNumber: 25, label: 'Magic E: U_E' },
      { courseId: 'advanced-phonics', lessonNumber: 8, label: 'Magic E: A_E and E_E' },
      { courseId: 'advanced-phonics', lessonNumber: 9, label: 'Magic E: I_E, O_E, U_E' },
    ],
    supportingPaths: ['/blog/long-vowel-sounds-for-kids', '/blog/phonics-multisyllabic', '/free-word-building-games-for-kids'],
    canonicalOwnerTopicId: null,
    expansionState: 'pilot-wave-1',
    futureSlugCandidate: 'magic-e-phonics',
    expansionRationale: 'High-value standalone pattern with minimal-pair teaching, common exceptions and five curriculum variants.',
    distinctValueSignals: ['short-long-contrast', 'five-vce-patterns', 'exception-set', 'word-transformation'],
  }),
  concept('rabbit-rule', {
    label: 'Rabbit Rule for two-syllable words',
    knowledgeStage: 'pattern-decoding',
    conceptType: 'syllable-rule',
    progressionRank: 9,
    searchIntent: 'why the middle consonant is often doubled in rabbit-pattern words',
    parentQuestion: 'What is the Rabbit Rule in phonics?',
    quickAnswer: 'Tiny Steps uses the Rabbit Rule for the common two-syllable pattern where a consonant is doubled between vowels, helping keep the first vowel short, as in rabbit. It is a useful syllable-and-spelling pattern, not a rule for every two-syllable word.',
    graphemes: ['VC/CV'],
    exampleWords: ['rabbit', 'kitten', 'muffin', 'button', 'sudden'],
    commonConfusions: [
      'Doubling a middle consonant in every two-syllable word.',
      'Teaching the written doubling without connecting it to syllable chunking and the short first vowel.',
    ],
    teachingNotes: [
      'Mark the two syllables and show the doubled consonant between vowel sounds.',
      'Contrast Rabbit-pattern words with another familiar two-syllable structure later.',
    ],
    practiceIdeas: [
      'Split rab-bit and kit-ten, then blend the chunks.',
      'Sort two-syllable words into Rabbit-pattern and not-this-pattern groups.',
    ],
    prerequisiteIds: ['short-vowels', 'cvc-words'],
    nextIds: ['consonant-le', 'soft-c-hard-c'],
    curriculumAlignment: 'direct',
    curriculumRefs: [
      { courseId: 'early-phonics', lessonNumber: 26, label: 'Rabbit Rule' },
      { courseId: 'advanced-phonics', lessonNumber: 3, label: 'Rabbit Rule' },
    ],
    supportingPaths: ['/blog/long-vowel-sounds-for-kids', '/blog/phonics-multisyllabic', '/free-word-building-games-for-kids'],
    canonicalOwnerTopicId: null,
    expansionState: 'pilot-wave-1',
    futureSlugCandidate: 'rabbit-rule-phonics',
    expansionRationale: 'Distinct multisyllabic decoding and spelling intent with direct Tiny Steps curriculum alignment.',
    distinctValueSignals: ['syllable-chunking', 'double-consonant-pattern', 'short-vowel-link', 'pattern-boundary'],
  }),
  concept('consonant-le', {
    label: 'Consonant-le / Monster LE ending',
    knowledgeStage: 'pattern-decoding',
    conceptType: 'syllable-rule',
    progressionRank: 9,
    searchIntent: 'how consonant-le works as a final syllable',
    parentQuestion: 'Why does the ending in table, little and purple form its own syllable?',
    quickAnswer: 'In many words, a final consonant plus le forms a stable final syllable, as in table, little and purple. Recognising the chunk also prevents children from applying the Magic E explanation to every final-e word.',
    graphemes: ['-ble', '-dle', '-gle', '-ple', '-tle', '-zle'],
    exampleWords: ['table', 'little', 'purple', 'candle', 'jungle'],
    commonConfusions: [
      'Applying Magic E to every final-e word.',
      'Trying to sound every letter separately instead of recognising the final syllable chunk.',
    ],
    teachingNotes: [
      'Teach consonant-le after children have experience with shorter closed syllables.',
      'Contrast a consonant-le word with a true VCe word.',
    ],
    practiceIdeas: [
      'Circle the final consonant-le chunk and read by syllables.',
      'Sort final-e words into VCe and consonant-le groups.',
    ],
    prerequisiteIds: ['magic-e', 'rabbit-rule'],
    nextIds: ['soft-c-hard-c', 'soft-g-hard-g'],
    curriculumAlignment: 'direct',
    curriculumRefs: [
      { courseId: 'early-phonics', lessonNumber: 27, label: 'Monster LE' },
      { courseId: 'advanced-phonics', lessonNumber: 12, label: 'Monster LE / Consonant LE' },
    ],
    supportingPaths: ['/blog/long-vowel-sounds-for-kids', '/blog/phonics-multisyllabic', '/free-word-building-games-for-kids'],
    canonicalOwnerTopicId: null,
    expansionState: 'pilot-wave-1',
    futureSlugCandidate: 'consonant-le-phonics',
    expansionRationale: 'Distinct syllable pattern with a high-value Magic-E confusion boundary.',
    distinctValueSignals: ['final-syllable-chunk', 'magic-e-contrast', 'syllable-reading', 'ending-family'],
  }),
]);

