import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { useScrollAnimation } from '../../hooks/useScrollAnimation';
const Footer = () => {
    const { ref, isInView } = useScrollAnimation(0.2);
    return (_jsxs(motion.footer, { ref: ref, className: "bg-gray-900 px-6 py-12 text-gray-300 md:px-16", initial: { opacity: 0, y: 40 }, animate: isInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 40 }, transition: { duration: 0.6, ease: 'easeOut' }, children: [_jsxs("div", { className: "mx-auto grid max-w-6xl grid-cols-1 gap-10 md:grid-cols-4", children: [_jsxs("div", { children: [_jsx("h3", { className: "font-heading text-2xl text-white", children: "Tiny Steps" }), _jsx("p", { className: "mt-4 text-sm text-gray-400", children: "Empowering confident communicators through immersive phonics, grammar, and public speaking experiences." }), _jsxs("div", { className: "mt-4 flex gap-4 text-sm uppercase tracking-wide text-white", children: [_jsx("a", { href: "https://facebook.com", "aria-label": "Tiny Steps on Facebook", className: "interactive-link hover:text-primary-500", children: "Fb" }), _jsx("a", { href: "https://instagram.com", "aria-label": "Tiny Steps on Instagram", className: "interactive-link hover:text-primary-500", children: "Ig" }), _jsx("a", { href: "https://www.youtube.com", "aria-label": "Tiny Steps on YouTube", className: "interactive-link hover:text-primary-500", children: "YT" })] })] }), _jsxs("div", { children: [_jsx("h4", { className: "font-semibold text-white", children: "Quick Links" }), _jsx("ul", { className: "mt-4 space-y-2 text-sm", children: ['Home', 'Courses', 'About', 'FAQ'].map((item) => (_jsx("li", { children: _jsx(Link, { to: `/${item.toLowerCase()}`, className: "interactive-link transition-colors hover:text-primary-500", children: item }) }, item))) })] }), _jsxs("div", { children: [_jsx("h4", { className: "font-semibold text-white", children: "Legal" }), _jsx("ul", { className: "mt-4 space-y-2 text-sm", children: ['Privacy', 'Terms', 'Disclaimer'].map((item) => (_jsx("li", { children: _jsx(Link, { to: `/${item.toLowerCase()}`, className: "interactive-link transition-colors hover:text-primary-500", children: item }) }, item))) })] }), _jsxs("div", { children: [_jsx("h4", { className: "font-semibold text-white", children: "Contact" }), _jsxs("ul", { className: "mt-4 space-y-2 text-sm", children: [_jsx("li", { children: "Phone: +1 (555) 123-4567" }), _jsx("li", { children: "Email: hello@tinysteps.com" }), _jsx("li", { children: "Address: 123 Learning Lane, Wonder City" })] })] })] }), _jsx("p", { className: "mt-12 text-center text-xs text-gray-500", children: "\u00A9 2025 Tiny Steps Online School. All rights reserved." })] }));
};
export default Footer;
