import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import { useScrollReveal } from "../hooks/useScrollReveal";
export default function Hero() {
    const sectionRef = useScrollReveal({ variant: "zoom", threshold: 0.35 });
    const titleDelay = { "--reveal-child-delay": "120ms" };
    const bodyDelay = { "--reveal-child-delay": "200ms" };
    return (_jsxs("section", { ref: sectionRef, className: "relative min-h-[80vh] md:min-h-[74vh] text-white overflow-hidden flex items-end md:items-center", id: "home", "aria-labelledby": "hero-title", children: [_jsx("div", { className: "absolute inset-0 bg-center bg-cover will-change-transform", style: { backgroundImage: "url('/assets/images/mainbg.jpg')" }, "aria-hidden": "true" }), _jsx("div", { className: "absolute inset-0 bg-gradient-to-b from-black/20 via-black/45 to-black/70", "aria-hidden": "true" }), _jsx("div", { className: "relative mx-auto max-w-6xl px-4 pb-16 pt-28 md:py-20 lg:py-24 w-full", children: _jsxs("div", { className: "max-w-2xl", children: [_jsxs("h1", { id: "hero-title", "data-reveal-child": true, style: titleDelay, className: "text-4xl sm:text-5xl lg:text-6xl font-black leading-[1.04] tracking-tight drop-shadow-[0_12px_32px_rgba(0,0,0,0.32)]", children: [_jsx("span", { className: "block text-balance", children: "Phonics, Grammar & Public Speaking" }), _jsxs("span", { className: "block mt-3 text-balance text-2xl sm:text-3xl lg:text-4xl font-semibold text-white/95", children: ["Crafted for ", _jsx("span", { className: "font-extrabold text-white", children: "Ages 3\u201310" })] })] }), _jsx("p", { "data-reveal-child": true, style: bodyDelay, className: "mt-6 max-w-[50ch] text-white/95 text-xl sm:text-2xl leading-relaxed font-medium drop-shadow-[0_12px_28px_rgba(0,0,0,0.35)]", children: "Live online classes for ages 3\u201310 \u2022 Phonics \u2022 Grammar \u2022 Public speaking \u2022 Free trial with digital worksheets and joyful Wordwall practice." }), _jsx("div", { className: "mt-8 inline-flex flex-col gap-3 sm:flex-row", children: _jsx(Link, { to: "/parent-login", className: "inline-flex items-center justify-center rounded-full bg-white px-6 py-3 text-base font-extrabold uppercase tracking-[0.18em] text-[#e05c0a] shadow-lg shadow-black/30 transition hover:-translate-y-0.5 text-center", children: "Book a parent trial" }) })] }) })] }));
}
//# sourceMappingURL=Hero.js.map