import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// React default import removed (using new JSX transform)
import { Link } from 'react-router-dom';
import CountUp from '@components/CountUp'; // Use alias for consistency
import WhyChooseUs from '@components/WhyChooseUs';
import Layout from '@components/Layout';
import FounderArticleCard from '@components/FounderArticleCard';
// Hero Component
const Hero = () => (_jsxs("section", { id: "home", className: "relative py-24 bg-gradient-to-br from-blue-50 via-indigo-50 to-purple-50 overflow-hidden", children: [_jsx("div", { className: "absolute inset-0 bg-gradient-to-r from-blue-400/20 via-purple-400/20 to-pink-400/20 animate-pulse" }), _jsx("div", { className: "container mx-auto px-4 relative z-10", children: _jsxs("div", { className: "grid md:grid-cols-2 gap-8 items-center", children: [_jsxs("div", { className: "text-center md:text-left", children: [_jsx("h1", { className: "text-5xl md:text-7xl font-extrabold text-gray-900 mb-6 animate-fade-in", children: "Phonics, Grammar & Public Speaking" }), _jsx("p", { className: "text-xl md:text-2xl text-gray-700 mb-4 animate-fade-in delay-200", children: "Crafted for Ages 3\u201310" }), _jsx("p", { className: "text-lg text-gray-600 mb-8 animate-fade-in delay-400", children: "Purposeful teaching, playful classrooms, measurable progress" }), _jsxs("div", { className: "flex items-center justify-center md:justify-start gap-4", children: [_jsx("a", { href: "#book-trial", className: "min-h-[50px] px-8 py-3 bg-gradient-to-r from-blue-500 to-purple-600 text-white rounded-2xl shadow-xl hover:shadow-2xl transition duration-300 text-lg font-semibold", children: "Book a Free Trial" }), _jsx(Link, { to: "/login", className: "text-sm text-gray-600 hover:text-gray-900 underline", children: "Admin Login" })] })] }), _jsxs("div", { className: "flex flex-col items-center md:items-end gap-4", children: [_jsxs("div", { className: "inline-flex flex-wrap gap-3 items-center", children: [_jsx(Link, { to: "/phonics", className: "px-3 py-1.5 rounded-full bg-white/90 text-slate-900 font-semibold shadow-sm hover:shadow-md border border-slate-100 text-sm", children: "Phonics" }), _jsx(Link, { to: "/grammar", className: "px-3 py-1.5 rounded-full bg-white/90 text-slate-900 font-semibold shadow-sm hover:shadow-md border border-slate-100 text-sm", children: "Grammar" }), _jsx(Link, { to: "/speaking", className: "px-3 py-1.5 rounded-full bg-white/90 text-slate-900 font-semibold shadow-sm hover:shadow-md border border-slate-100 text-sm", children: "Public Speaking" })] }), _jsx("p", { className: "mt-2 text-sm text-slate-600 text-center md:text-right", children: "Explore each course page for curriculum details, schedules, and sample lessons." })] })] }) })] }));
// Why Section
const WhySection = () => (_jsx("section", { id: "why", className: "py-20 bg-white", children: _jsxs("div", { className: "container mx-auto px-4", children: [_jsx("h2", { className: "text-4xl font-bold text-center mb-16 text-gray-900", children: "Why Tiny Steps Works" }), _jsx("p", { className: "text-xl text-center text-gray-700 mb-12 max-w-3xl mx-auto", children: "Every Tiny Steps session blends research-backed pedagogy with joyful rituals so kids feel energised, parents stay informed, and communication skills grow term after term." }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-8", children: [_jsxs("div", { className: "bg-gradient-to-br from-yellow-100 to-orange-100 rounded-3xl p-8 shadow-lg hover:shadow-xl transition duration-300 transform hover:-translate-y-2", children: [_jsx("h3", { className: "text-2xl font-bold mb-4 text-gray-900", children: "Joyful Learning" }), _jsx("p", { className: "text-gray-700", children: "Children thrive in an environment filled with stories, play, and creativity." })] }), _jsxs("div", { className: "bg-gradient-to-br from-green-100 to-teal-100 rounded-3xl p-8 shadow-lg hover:shadow-xl transition duration-300 transform hover:-translate-y-2", children: [_jsx("h3", { className: "text-2xl font-bold mb-4 text-gray-900", children: "One-to-One Guidance" }), _jsx("p", { className: "text-gray-700", children: "Personal attention helps every child feel seen, supported, and celebrated." })] }), _jsxs("div", { className: "bg-gradient-to-br from-pink-100 to-red-100 rounded-3xl p-8 shadow-lg hover:shadow-xl transition duration-300 transform hover:-translate-y-2", children: [_jsx("h3", { className: "text-2xl font-bold mb-4 text-gray-900", children: "Professional Teachers" }), _jsx("p", { className: "text-gray-700", children: "Certified educators bring patience, expertise, and warmth to every class." })] })] })] }) }));
// Courses Section
const CoursesSection = () => (_jsx("section", { id: "courses", className: "py-20 bg-gray-50", children: _jsxs("div", { className: "container mx-auto px-4", children: [_jsx("h2", { className: "text-4xl font-bold text-center mb-16 text-gray-900", children: "Beautifully Crafted Learning Tracks" }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-8", children: [_jsxs("div", { className: "bg-white rounded-3xl p-8 shadow-lg hover:shadow-xl transition duration-300", children: [_jsx("h3", { className: "text-2xl font-bold mb-4 text-blue-600", children: "Phonics Foundations" }), _jsx("p", { className: "text-gray-700 mb-4", children: "Systematic, multi-sensory lessons that turn sounds into stories your child can read aloud." }), _jsxs("ul", { className: "text-sm text-gray-600 space-y-1", children: [_jsx("li", { children: "\u2022 SATPIN mastery in 6 weeks" }), _jsx("li", { children: "\u2022 Weekly progress reports" }), _jsx("li", { children: "\u2022 Parent play sheets" })] })] }), _jsxs("div", { className: "bg-white rounded-3xl p-8 shadow-lg hover:shadow-xl transition duration-300", children: [_jsx("h3", { className: "text-2xl font-bold mb-4 text-green-600", children: "Grammar & Writing" }), _jsx("p", { className: "text-gray-700 mb-4", children: "Sentence building, creative writing, and grammar games that make structure feel natural and fun." }), _jsxs("ul", { className: "text-sm text-gray-600 space-y-1", children: [_jsx("li", { children: "\u2022 Story-led grammar labs" }), _jsx("li", { children: "\u2022 Cambridge-aligned rubrics" }), _jsx("li", { children: "\u2022 Peer & mentor feedback" })] })] }), _jsxs("div", { className: "bg-white rounded-3xl p-8 shadow-lg hover:shadow-xl transition duration-300", children: [_jsx("h3", { className: "text-2xl font-bold mb-4 text-purple-600", children: "Public Speaking" }), _jsx("p", { className: "text-gray-700 mb-4", children: "Stage presence, storytelling, and vocal confidence coached through playful performances." }), _jsxs("ul", { className: "text-sm text-gray-600 space-y-1", children: [_jsx("li", { children: "\u2022 Weekly spotlight sessions" }), _jsx("li", { children: "\u2022 Body & voice drills" }), _jsx("li", { children: "\u2022 Showcase presentation" })] })] })] })] }) }));
// Program Highlights Section
const HighlightsSection = () => (_jsx("section", { id: "highlights", className: "py-20 bg-gray-50", children: _jsxs("div", { className: "container mx-auto px-4", children: [_jsx("h2", { className: "text-4xl font-bold text-center mb-16 text-gray-900", children: "Program Highlights" }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8", children: [_jsxs("div", { className: "bg-white rounded-3xl p-8 shadow-lg hover:shadow-xl transition duration-300", children: [_jsx("h3", { className: "text-2xl font-bold mb-4 text-blue-600", children: "35-Min Sessions" }), _jsx("p", { className: "text-gray-700", children: "Short, focused classes designed for young learners." })] }), _jsxs("div", { className: "bg-white rounded-3xl p-8 shadow-lg hover:shadow-xl transition duration-300", children: [_jsx("h3", { className: "text-2xl font-bold mb-4 text-green-600", children: "1:1 or Group" }), _jsx("p", { className: "text-gray-700", children: "Choose personalized or collaborative learning formats." })] }), _jsxs("div", { className: "bg-white rounded-3xl p-8 shadow-lg hover:shadow-xl transition duration-300", children: [_jsx("h3", { className: "text-2xl font-bold mb-4 text-purple-600", children: "Weekly Reports" }), _jsx("p", { className: "text-gray-700", children: "Track your child\u2019s progress with detailed updates." })] }), _jsxs("div", { className: "bg-white rounded-3xl p-8 shadow-lg hover:shadow-xl transition duration-300", children: [_jsx("h3", { className: "text-2xl font-bold mb-4 text-red-600", children: "Parent Portal" }), _jsx("p", { className: "text-gray-700", children: "Access resources and insights anytime, anywhere." })] })] })] }) }));
// Our Teachers Section
const TeachersSection = () => (_jsx("section", { id: "teachers", className: "py-20 bg-white", children: _jsxs("div", { className: "container mx-auto px-4 flex flex-col md:flex-row items-center", children: [_jsx("div", { className: "md:w-1/2 mb-8 md:mb-0", children: _jsx("img", { src: "/images/teacher.jpg", alt: "Teacher", className: "rounded-3xl shadow-lg" }) }), _jsxs("div", { className: "md:w-1/2 md:pl-12", children: [_jsx("h2", { className: "text-4xl font-bold text-gray-900 mb-6", children: "Our Teachers" }), _jsx("p", { className: "text-gray-700 text-lg", children: "Every Tiny Steps teacher is trained in phonics, fluency, and early childhood care. They bring patience, expertise, and warmth to every class." })] })] }) }));
// Stats Section
const StatsSection = () => (_jsx("section", { className: "py-20 bg-gradient-to-br from-blue-500 to-purple-600 text-white", children: _jsxs("div", { className: "container mx-auto px-4 text-center", children: [_jsx("h2", { className: "text-4xl font-bold mb-8", children: "Our Achievements" }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-8", children: [_jsxs("div", { className: "bg-white text-blue-600 rounded-3xl p-8 shadow-lg", children: [_jsxs("h3", { className: "text-6xl font-extrabold mb-4", children: [_jsx(CountUp, { from: 0, to: 3000, separator: ",", duration: 2, className: "count-up-text" }), "+"] }), _jsx("p", { className: "text-xl font-medium", children: "Students Educated" })] }), _jsxs("div", { className: "bg-white text-blue-600 rounded-3xl p-8 shadow-lg", children: [_jsxs("h3", { className: "text-6xl font-extrabold mb-4", children: [_jsx(CountUp, { from: 0, to: 6, duration: 2, className: "count-up-text" }), "+"] }), _jsx("p", { className: "text-xl font-medium", children: "Years of Excellence" })] })] })] }) }));
// Testimonials Section
const TestimonialsSection = () => (_jsx("section", { className: "py-20 bg-white", children: _jsxs("div", { className: "container mx-auto px-4", children: [_jsx("h2", { className: "text-4xl font-bold text-center mb-16 text-gray-900", children: "Families See Measurable Progress" }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8", children: [_jsxs("div", { className: "bg-gray-50 rounded-3xl p-6 shadow-lg", children: [_jsx("p", { className: "text-gray-700 mb-4", children: "\"Within four weeks Kavya was decoding storybooks independently.\"" }), _jsx("p", { className: "font-semibold text-gray-900", children: "Anita Rao, Bengaluru" })] }), _jsxs("div", { className: "bg-gray-50 rounded-3xl p-6 shadow-lg", children: [_jsx("p", { className: "text-gray-700 mb-4", children: "\"The SATPIN routine made reading feel like playtime for Vihaan.\"" }), _jsx("p", { className: "font-semibold text-gray-900", children: "Siddharth & Nisha Patel, Ahmedabad" })] }), _jsxs("div", { className: "bg-gray-50 rounded-3xl p-6 shadow-lg", children: [_jsx("p", { className: "text-gray-700 mb-4", children: "\"Aarav finally understands grammar rules and applies them in stories.\"" }), _jsx("p", { className: "font-semibold text-gray-900", children: "Parent Family, Location" })] })] })] }) }));
// Book a Free Trial CTA Section
const FreeTrialCTA = () => (_jsx("section", { id: "book-trial", className: "py-16 bg-gradient-to-r from-blue-500 to-purple-600 text-white text-center", children: _jsxs("div", { className: "container mx-auto px-4", children: [_jsx("h2", { className: "text-4xl font-bold mb-4", children: "Book a Free Trial" }), _jsx("p", { className: "text-lg mb-8", children: "Experience the joy of learning with Tiny Steps." }), _jsx("button", { className: "px-8 py-4 bg-white text-blue-600 rounded-2xl shadow-lg hover:shadow-xl transition duration-300 font-semibold text-xl", children: "Get Started" })] }) }));
// FAQ Section
const FAQSection = () => (_jsx("section", { id: "faq", className: "py-20 bg-gray-50", children: _jsxs("div", { className: "container mx-auto px-4", children: [_jsx("h2", { className: "text-4xl font-bold text-center mb-16 text-gray-900", children: "Frequently Asked Questions" }), _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "bg-white rounded-3xl p-6 shadow-lg", children: [_jsx("h3", { className: "text-xl font-semibold text-gray-900", children: "What age group do you teach?" }), _jsx("p", { className: "text-gray-700 mt-2", children: "We teach children aged 3\u201312 years, tailoring lessons to their developmental stage." })] }), _jsxs("div", { className: "bg-white rounded-3xl p-6 shadow-lg", children: [_jsx("h3", { className: "text-xl font-semibold text-gray-900", children: "Can I pick a teacher?" }), _jsx("p", { className: "text-gray-700 mt-2", children: "Yes, you can choose from our roster of certified educators based on availability." })] }), _jsxs("div", { className: "bg-white rounded-3xl p-6 shadow-lg", children: [_jsx("h3", { className: "text-xl font-semibold text-gray-900", children: "How are sessions scheduled?" }), _jsx("p", { className: "text-gray-700 mt-2", children: "Sessions are scheduled flexibly to suit your family\u2019s routine." })] })] })] }) }));
// Footer and Header are now provided by Layout component (imported above)
// Main Home Component — wrapped with Layout to include header/footer
const Home = () => (_jsxs(Layout, { children: [_jsx(Hero, {}), _jsx(WhySection, {}), _jsx(CoursesSection, {}), _jsx(HighlightsSection, {}), _jsx(WhyChooseUs, {}), _jsx(TeachersSection, {}), _jsx(StatsSection, {}), _jsx(TestimonialsSection, {}), _jsx(FreeTrialCTA, {}), _jsx("div", { className: "px-4", children: _jsx(FounderArticleCard, {}) }), _jsx(FAQSection, {})] }));
export default Home;
