import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from 'framer-motion';
import Button from '../Button/Button';
import { trackEvent } from '../../lib/analytics';
const ConversionHero = () => {
    return (_jsxs("section", { "data-animate": "fade-up", className: "relative overflow-hidden bg-[radial-gradient(circle_at_top,_#ffe6cc,_#fff8ec,_#dff2ff_70%)] py-20 md:py-28", children: [_jsxs("div", { className: "pointer-events-none absolute inset-0 opacity-30", children: [_jsx("div", { "data-parallax": true, "data-parallax-speed": "-0.2", className: "absolute -left-16 top-6 h-48 w-48 rounded-full bg-[#ff9f43]/60 blur-3xl" }), _jsx("div", { "data-parallax": true, "data-parallax-speed": "0.1", className: "absolute right-8 top-16 h-56 w-56 rounded-full bg-[#66c4ff]/45 blur-3xl" }), _jsx("div", { "data-parallax": true, "data-parallax-speed": "-0.05", className: "absolute bottom-6 left-1/4 h-40 w-72 rounded-full bg-[#ffc857]/40 blur-3xl" }), _jsx("div", { "data-parallax": true, "data-parallax-speed": "0.15", className: "absolute top-1/2 left-0 h-24 w-24 rounded-full bg-[#8b5cf6]/25 blur-3xl" })] }), _jsxs("div", { className: "relative z-10 mx-auto grid max-w-6xl items-center gap-10 px-6 text-left lg:grid-cols-[1.05fr_0.95fr]", children: [_jsxs("div", { children: [_jsx("div", { className: "inline-flex items-center gap-2 rounded-full bg-white/70 px-4 py-1 text-sm font-semibold text-gray-700 shadow-sm", children: "Tiny Steps \u2022 Foundations Forever" }), _jsxs(motion.h1, { className: "font-heading text-4xl font-extrabold text-gray-900 md:text-5xl", initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.8 }, children: ["IB-aligned Phonics, Grammar & Public Speaking for Ages 3\u201312.", _jsx("span", { className: "block bg-gradient-to-r from-[#ff8f5c] via-[#ffb347] to-[#59c3ff] bg-clip-text text-3xl text-transparent md:text-4xl", children: "Bright-sky calm. Live mentors. AI-curated journeys." })] }), _jsx(motion.p, { className: "mt-4 max-w-2xl text-lg text-gray-700", initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.8, delay: 0.2 }, children: "3500+ students across India, US, UK, Canada, Singapore, Malaysia, Vietnam, UAE & Australia learn with Tiny Steps. Our AI engine maps every child's needs and sends parents weekly learning path insights." }), _jsxs(motion.div, { className: "mt-6 flex flex-col gap-3 sm:flex-row", initial: { opacity: 0, y: 20, scale: 0.95 }, animate: { opacity: 1, y: 0, scale: 1 }, transition: { duration: 0.6, delay: 0.4 }, children: [_jsx(Button, { size: "lg", "aria-label": "Book Free Trial", onClick: () => {
                                            var _a;
                                            trackEvent('cta_click', { location: 'hero', label: 'book_free_trial' });
                                            (_a = document.getElementById('book-trial')) === null || _a === void 0 ? void 0 : _a.scrollIntoView({ behavior: 'smooth' });
                                        }, children: "Book Free Trial" }), _jsx("a", { href: "/courses", onClick: () => trackEvent('cta_click', { location: 'hero', label: 'see_courses' }), className: "rounded-2xl border border-white/70 bg-white/80 px-6 py-3 text-center font-semibold text-[#ff8f5c] shadow-sm hover:shadow transition", children: "Explore Courses" })] }), _jsx("div", { className: "mt-5 flex flex-wrap gap-3 text-sm font-semibold text-gray-700", children: ['Live 1:1 mentors', 'AI learning paths', 'Parent insights dashboard'].map((chip) => (_jsx("span", { className: "rounded-full bg-white/80 px-3 py-1", children: chip }, chip))) })] }), _jsx("div", { className: "relative", children: _jsxs("div", { className: "rounded-[32px] bg-white/90 p-6 shadow-[0_20px_45px_rgba(255,143,92,0.25)]", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("div", { className: "text-sm uppercase tracking-widest text-gray-500", children: "Next live demo" }), _jsx("div", { className: "text-2xl font-bold text-gray-900", children: "Today \u2022 7:00 PM" })] }), _jsx("span", { className: "rounded-full bg-[#ffe8c2] px-3 py-1 text-xs font-semibold text-[#ff8f5c]", children: "Watch preview" })] }), _jsxs("div", { className: "mt-5 space-y-3 text-sm text-gray-600", children: [_jsxs("div", { className: "flex items-center justify-between rounded-2xl bg-gray-50 px-4 py-3", children: [_jsx("span", { children: "\uD83E\uDDE0 AI-curated curriculum" }), _jsx("span", { className: "text-xs text-gray-500", children: "Personalised weekly plan" })] }), _jsxs("div", { className: "flex items-center justify-between rounded-2xl bg-gray-50 px-4 py-3", children: [_jsx("span", { children: "\uD83D\uDCC8 Parent dashboard" }), _jsx("span", { className: "text-xs text-gray-500", children: "Weekly insights" })] }), _jsxs("div", { className: "flex items-center justify-between rounded-2xl bg-gray-50 px-4 py-3", children: [_jsx("span", { children: "\uD83C\uDF0D Countries" }), _jsx("span", { className: "text-xs text-gray-500", children: "IN \u2022 US \u2022 UK \u2022 CA \u2022 SG \u2022 MY \u2022 VN \u2022 UAE \u2022 AU" })] })] }), _jsx("div", { className: "mt-5 rounded-2xl border border-dashed border-gray-200 p-4 text-xs text-gray-600", children: "Screen experience stays calm for parents and kids\u2014clear blues, gentle gradients, and clean typography across every page." })] }) })] }), _jsx("div", { className: "fixed bottom-4 left-0 right-0 z-30 flex justify-center px-4 sm:hidden", children: _jsx("a", { href: "#book-trial", onClick: () => trackEvent('cta_click', { location: 'sticky_mobile', label: 'book_free_trial' }), className: "w-full max-w-md rounded-full bg-gradient-to-r from-primary-500 to-secondary-500 px-6 py-3 text-center text-white font-semibold shadow-xl", "aria-label": "Book Free Trial", children: "Book Free Trial" }) })] }));
};
export default ConversionHero;
