/* AUTO-GENERATED: Hershey baseline tracing letters
   Font: hershey_sans_med
   Generated by: scripts/generate-traceletters-hershey.cjs
*/
import type { TraceLetter, LetterId } from "./traceLetters";

export const HERSHEY_TRACE_LETTERS: Partial<Record<LetterId, TraceLetter>> = {
  "A": {
    "id": "A",
    "label": "A",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "A_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 50.00 88.00 L 21.07 12.00"
      },
      {
        "id": "A_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 50.00 77.09 L 24.63 12.00 L 21.07 12.00"
      },
      {
        "id": "A_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 50.00 77.09 L 75.26 12.00 L 78.93 12.00"
      },
      {
        "id": "A_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 50.00 88.00 L 78.93 12.00"
      },
      {
        "id": "A_stroke_5",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 31.86 33.70 L 68.02 33.70"
      },
      {
        "id": "A_stroke_6",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 28.19 30.14 L 71.58 30.14"
      }
    ],
    "skillTags": [
      "letter:A",
      "case:upper",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "B": {
    "id": "B",
    "label": "B",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "B_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 26.47 88.00 L 26.47 12.00"
      },
      {
        "id": "B_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 30.14 84.33 L 30.14 15.62"
      },
      {
        "id": "B_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 26.47 88.00 L 55.40 88.00 L 66.30 84.33 L 69.86 80.65 L 73.53 73.53 L 73.53 62.63 L 69.86 55.40 L 66.30 51.72 L 55.40 48.16"
      },
      {
        "id": "B_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 30.14 84.33 L 55.40 84.33 L 66.30 80.65 L 69.86 73.53 L 69.86 62.63 L 66.30 55.40 L 55.40 51.72"
      },
      {
        "id": "B_stroke_5",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 30.14 51.72 L 55.40 51.72 L 66.30 48.16 L 69.86 44.60 L 73.53 37.26 L 73.53 26.47 L 69.86 19.23 L 66.30 15.62 L 55.40 12.00 L 26.47 12.00"
      },
      {
        "id": "B_stroke_6",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 30.14 48.16 L 55.40 48.16 L 66.30 44.60 L 69.86 37.26 L 69.86 26.47 L 66.30 19.23 L 55.40 15.62 L 30.14 15.62"
      }
    ],
    "skillTags": [
      "letter:B",
      "case:upper",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "C": {
    "id": "C",
    "label": "C",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "C_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 77.15 69.86 L 73.48 77.09 L 66.24 84.33 L 59.01 88.00 L 44.55 88.00 L 37.31 84.33 L 30.08 77.09 L 26.41 69.86 L 22.85 59.07 L 22.85 40.93 L 26.41 30.14 L 30.08 22.85 L 37.31 15.62 L 44.55 12.00 L 59.01 12.00 L 66.24 15.62 L 73.48 22.85 L 77.15 30.14"
      },
      {
        "id": "C_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 77.15 69.86 L 73.48 69.86 L 69.80 77.09 L 66.24 80.65 L 59.01 84.33 L 44.55 84.33 L 37.31 80.65 L 30.08 69.86 L 26.41 59.07 L 26.41 40.93 L 30.08 30.14 L 37.31 19.23 L 44.55 15.62 L 59.01 15.62 L 66.24 19.23 L 69.80 22.85 L 73.48 30.14 L 77.15 30.14"
      }
    ],
    "skillTags": [
      "letter:C",
      "case:upper",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "D": {
    "id": "D",
    "label": "D",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "D_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 24.63 88.00 L 24.63 12.00"
      },
      {
        "id": "D_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 28.30 84.33 L 28.30 15.62"
      },
      {
        "id": "D_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 24.63 88.00 L 50.00 88.00 L 60.91 84.33 L 68.02 77.09 L 71.70 69.86 L 75.37 59.07 L 75.37 40.93 L 71.70 30.14 L 68.02 22.85 L 60.91 15.62 L 50.00 12.00 L 24.63 12.00"
      },
      {
        "id": "D_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 28.30 84.33 L 50.00 84.33 L 60.91 80.65 L 64.47 77.09 L 68.02 69.86 L 71.70 59.07 L 71.70 40.93 L 68.02 30.14 L 64.47 22.85 L 60.91 19.23 L 50.00 15.62 L 28.30 15.62"
      }
    ],
    "skillTags": [
      "letter:D",
      "case:upper",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "E": {
    "id": "E",
    "label": "E",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "E_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 28.30 88.00 L 28.30 12.00"
      },
      {
        "id": "E_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 31.98 84.33 L 31.98 15.62"
      },
      {
        "id": "E_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 28.30 88.00 L 71.70 88.00"
      },
      {
        "id": "E_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 31.98 84.33 L 71.70 84.33 L 71.70 88.00"
      },
      {
        "id": "E_stroke_5",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 31.98 51.72 L 53.67 51.72 L 53.67 48.16"
      },
      {
        "id": "E_stroke_6",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 31.98 48.16 L 53.67 48.16"
      },
      {
        "id": "E_stroke_7",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 31.98 15.62 L 71.70 15.62 L 71.70 12.00"
      },
      {
        "id": "E_stroke_8",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 28.30 12.00 L 71.70 12.00"
      }
    ],
    "skillTags": [
      "letter:E",
      "case:upper",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "F": {
    "id": "F",
    "label": "F",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "F_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 28.30 88.00 L 28.30 12.00"
      },
      {
        "id": "F_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 31.98 84.33 L 31.98 12.00 L 28.30 12.00"
      },
      {
        "id": "F_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 28.30 88.00 L 71.70 88.00"
      },
      {
        "id": "F_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 31.98 84.33 L 71.70 84.33 L 71.70 88.00"
      },
      {
        "id": "F_stroke_5",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 31.98 51.72 L 53.67 51.72 L 53.67 48.16"
      },
      {
        "id": "F_stroke_6",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 31.98 48.16 L 53.67 48.16"
      }
    ],
    "skillTags": [
      "letter:F",
      "case:upper",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "G": {
    "id": "G",
    "label": "G",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "G_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 77.15 69.86 L 73.48 77.09 L 66.24 84.33 L 59.01 88.00 L 44.55 88.00 L 37.31 84.33 L 30.08 77.09 L 26.41 69.86 L 22.85 59.07 L 22.85 40.93 L 26.41 30.14 L 30.08 22.85 L 37.31 15.62 L 44.55 12.00 L 59.01 12.00 L 66.24 15.62 L 73.48 22.85 L 77.15 30.14 L 77.15 44.60 L 59.01 44.60"
      },
      {
        "id": "G_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 77.15 69.86 L 73.48 69.86 L 69.80 77.09 L 66.24 80.65 L 59.01 84.33 L 44.55 84.33 L 37.31 80.65 L 33.76 77.09 L 30.08 69.86 L 26.41 59.07 L 26.41 40.93 L 30.08 30.14 L 33.76 22.85 L 37.31 19.23 L 44.55 15.62 L 59.01 15.62 L 66.24 19.23 L 69.80 22.85 L 73.48 30.14 L 73.48 40.93 L 59.01 40.93 L 59.01 44.60"
      }
    ],
    "skillTags": [
      "letter:G",
      "case:upper",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "H": {
    "id": "H",
    "label": "H",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "H_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 24.63 88.00 L 24.63 12.00"
      },
      {
        "id": "H_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 24.63 88.00 L 28.30 88.00 L 28.30 12.00 L 24.63 12.00"
      },
      {
        "id": "H_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 75.37 88.00 L 71.70 88.00 L 71.70 12.00 L 75.37 12.00"
      },
      {
        "id": "H_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 75.37 88.00 L 75.37 12.00"
      },
      {
        "id": "H_stroke_5",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 28.30 51.72 L 71.70 51.72"
      },
      {
        "id": "H_stroke_6",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 28.30 48.16 L 71.70 48.16"
      }
    ],
    "skillTags": [
      "letter:H",
      "case:upper",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "I": {
    "id": "I",
    "label": "I",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "I_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 48.16 88.00 L 48.16 12.00 L 51.84 12.00"
      },
      {
        "id": "I_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 48.16 88.00 L 51.84 88.00 L 51.84 12.00"
      }
    ],
    "skillTags": [
      "letter:I",
      "case:upper",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "J": {
    "id": "J",
    "label": "J",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "J_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 64.41 88.00 L 64.41 30.14 L 60.85 19.23 L 53.62 15.62 L 46.38 15.62 L 39.15 19.23 L 35.48 30.14 L 31.92 30.14"
      },
      {
        "id": "J_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 64.41 88.00 L 68.08 88.00 L 68.08 30.14 L 64.41 19.23 L 60.85 15.62 L 53.62 12.00 L 46.38 12.00 L 39.15 15.62 L 35.48 19.23 L 31.92 30.14"
      }
    ],
    "skillTags": [
      "letter:J",
      "case:upper",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "K": {
    "id": "K",
    "label": "K",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "K_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 24.63 88.00 L 24.63 12.00 L 28.30 12.00"
      },
      {
        "id": "K_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 24.63 88.00 L 28.30 88.00 L 28.30 12.00"
      },
      {
        "id": "K_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 75.37 88.00 L 71.70 88.00 L 28.30 44.60"
      },
      {
        "id": "K_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 75.37 88.00 L 28.30 40.93"
      },
      {
        "id": "K_stroke_5",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 39.09 55.40 L 71.70 12.00 L 75.37 12.00"
      },
      {
        "id": "K_stroke_6",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 42.77 55.40 L 75.37 12.00"
      }
    ],
    "skillTags": [
      "letter:K",
      "case:upper",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "L": {
    "id": "L",
    "label": "L",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "L_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 28.30 88.00 L 28.30 12.00"
      },
      {
        "id": "L_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 28.30 88.00 L 31.98 88.00 L 31.98 15.62"
      },
      {
        "id": "L_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 31.98 15.62 L 71.70 15.62 L 71.70 12.00"
      },
      {
        "id": "L_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 28.30 12.00 L 71.70 12.00"
      }
    ],
    "skillTags": [
      "letter:L",
      "case:upper",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "M": {
    "id": "M",
    "label": "M",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "M_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 21.07 88.00 L 21.07 12.00"
      },
      {
        "id": "M_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 24.74 69.86 L 24.74 12.00 L 21.07 12.00"
      },
      {
        "id": "M_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 24.74 69.86 L 50.00 12.00"
      },
      {
        "id": "M_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 21.07 88.00 L 50.00 22.85"
      },
      {
        "id": "M_stroke_5",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 78.93 88.00 L 50.00 22.85"
      },
      {
        "id": "M_stroke_6",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 75.37 69.86 L 50.00 12.00"
      },
      {
        "id": "M_stroke_7",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 75.37 69.86 L 75.37 12.00 L 78.93 12.00"
      },
      {
        "id": "M_stroke_8",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 78.93 88.00 L 78.93 12.00"
      }
    ],
    "skillTags": [
      "letter:M",
      "case:upper",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "N": {
    "id": "N",
    "label": "N",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "N_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 24.63 88.00 L 24.63 12.00"
      },
      {
        "id": "N_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 28.30 77.09 L 28.30 12.00 L 24.63 12.00"
      },
      {
        "id": "N_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 28.30 77.09 L 75.37 12.00"
      },
      {
        "id": "N_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 24.63 88.00 L 71.70 22.85"
      },
      {
        "id": "N_stroke_5",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 71.70 88.00 L 71.70 22.85"
      },
      {
        "id": "N_stroke_6",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 71.70 88.00 L 75.37 88.00 L 75.37 12.00"
      }
    ],
    "skillTags": [
      "letter:N",
      "case:upper",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "O": {
    "id": "O",
    "label": "O",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "O_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 42.77 88.00 L 35.53 84.33 L 28.30 77.09 L 24.63 69.86 L 21.07 59.07 L 21.07 40.93 L 24.63 30.14 L 28.30 22.85 L 35.53 15.62 L 42.77 12.00 L 57.23 12.00 L 64.47 15.62 L 71.70 22.85 L 75.37 30.14 L 78.93 40.93 L 78.93 59.07 L 75.37 69.86 L 71.70 77.09 L 64.47 84.33 L 57.23 88.00 L 42.77 88.00"
      },
      {
        "id": "O_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 46.44 84.33 L 35.53 80.65 L 28.30 69.86 L 24.63 59.07 L 24.63 40.93 L 28.30 30.14 L 35.53 19.23 L 46.44 15.62 L 53.56 15.62 L 64.47 19.23 L 71.70 30.14 L 75.37 40.93 L 75.37 59.07 L 71.70 69.86 L 64.47 80.65 L 53.56 84.33 L 46.44 84.33"
      }
    ],
    "skillTags": [
      "letter:O",
      "case:upper",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "P": {
    "id": "P",
    "label": "P",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "P_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 26.47 88.00 L 26.47 12.00"
      },
      {
        "id": "P_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 30.14 84.33 L 30.14 12.00 L 26.47 12.00"
      },
      {
        "id": "P_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 26.47 88.00 L 59.07 88.00 L 66.30 84.33 L 69.86 80.65 L 73.53 73.53 L 73.53 62.63 L 69.86 55.40 L 66.30 51.72 L 59.07 48.16 L 30.14 48.16"
      },
      {
        "id": "P_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 30.14 84.33 L 59.07 84.33 L 66.30 80.65 L 69.86 73.53 L 69.86 62.63 L 66.30 55.40 L 59.07 51.72 L 30.14 51.72"
      }
    ],
    "skillTags": [
      "letter:P",
      "case:upper",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "Q": {
    "id": "Q",
    "label": "Q",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "Q_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 43.40 88.00 L 36.79 84.65 L 30.19 78.04 L 26.83 71.44 L 23.58 61.58 L 23.58 45.02 L 26.83 35.17 L 30.19 28.51 L 36.79 21.91 L 43.40 18.60 L 56.60 18.60 L 63.21 21.91 L 69.81 28.51 L 73.17 35.17 L 76.42 45.02 L 76.42 61.58 L 73.17 71.44 L 69.81 78.04 L 63.21 84.65 L 56.60 88.00 L 43.40 88.00"
      },
      {
        "id": "Q_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 46.75 84.65 L 36.79 81.29 L 30.19 71.44 L 26.83 61.58 L 26.83 45.02 L 30.19 35.17 L 36.79 25.21 L 46.75 21.91 L 53.25 21.91 L 63.21 25.21 L 69.81 35.17 L 73.17 45.02 L 73.17 61.58 L 69.81 71.44 L 63.21 81.29 L 53.25 84.65 L 46.75 84.65"
      },
      {
        "id": "Q_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 53.25 28.51 L 69.81 12.00 L 73.17 12.00"
      },
      {
        "id": "Q_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 53.25 28.51 L 56.60 28.51 L 73.17 12.00"
      }
    ],
    "skillTags": [
      "letter:Q",
      "case:upper",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "R": {
    "id": "R",
    "label": "R",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "R_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 26.47 88.00 L 26.47 12.00"
      },
      {
        "id": "R_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 30.14 84.33 L 30.14 12.00 L 26.47 12.00"
      },
      {
        "id": "R_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 26.47 88.00 L 55.40 88.00 L 66.30 84.33 L 69.86 80.65 L 73.53 73.53 L 73.53 62.63 L 69.86 55.40 L 66.30 51.72 L 55.40 48.16 L 30.14 48.16"
      },
      {
        "id": "R_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 30.14 84.33 L 55.40 84.33 L 66.30 80.65 L 69.86 73.53 L 69.86 62.63 L 66.30 55.40 L 55.40 51.72 L 30.14 51.72"
      },
      {
        "id": "R_stroke_5",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 48.28 48.16 L 69.86 12.00 L 73.53 12.00"
      },
      {
        "id": "R_stroke_6",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 51.84 48.16 L 73.53 12.00"
      }
    ],
    "skillTags": [
      "letter:R",
      "case:upper",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "S": {
    "id": "S",
    "label": "S",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "S_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 75.31 77.09 L 68.08 84.33 L 57.18 88.00 L 42.71 88.00 L 31.92 84.33 L 24.69 77.09 L 24.69 69.86 L 28.24 62.63 L 31.92 59.07 L 39.15 55.40 L 57.18 48.16 L 64.52 44.60 L 68.08 40.93 L 71.64 33.70 L 71.64 22.85 L 68.08 19.23 L 57.18 15.62 L 42.71 15.62 L 35.59 19.23 L 31.92 22.85 L 24.69 22.85"
      },
      {
        "id": "S_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 75.31 77.09 L 68.08 77.09 L 64.52 80.65 L 57.18 84.33 L 42.71 84.33 L 31.92 80.65 L 28.24 77.09 L 28.24 69.86 L 31.92 62.63 L 39.15 59.07 L 57.18 51.72 L 64.52 48.16 L 71.64 40.93 L 75.31 33.70 L 75.31 22.85 L 68.08 15.62 L 57.18 12.00 L 42.71 12.00 L 31.92 15.62 L 24.69 22.85"
      }
    ],
    "skillTags": [
      "letter:S",
      "case:upper",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "T": {
    "id": "T",
    "label": "T",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "T_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 48.11 84.33 L 48.11 12.00"
      },
      {
        "id": "T_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 51.78 84.33 L 51.78 12.00 L 48.11 12.00"
      },
      {
        "id": "T_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 26.52 88.00 L 73.48 88.00 L 73.48 84.33"
      },
      {
        "id": "T_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 26.52 88.00 L 26.52 84.33 L 73.48 84.33"
      }
    ],
    "skillTags": [
      "letter:T",
      "case:upper",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "U": {
    "id": "U",
    "label": "U",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "U_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 24.63 88.00 L 24.63 33.70 L 28.30 22.85 L 35.53 15.62 L 46.44 12.00 L 53.56 12.00 L 64.47 15.62 L 71.70 22.85 L 75.37 33.70 L 75.37 88.00"
      },
      {
        "id": "U_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 24.63 88.00 L 28.30 88.00 L 28.30 33.70 L 31.98 22.85 L 35.53 19.23 L 46.44 15.62 L 53.56 15.62 L 64.47 19.23 L 68.02 22.85 L 71.70 33.70 L 71.70 88.00 L 75.37 88.00"
      }
    ],
    "skillTags": [
      "letter:U",
      "case:upper",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "V": {
    "id": "V",
    "label": "V",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "V_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 21.07 88.00 L 50.00 12.00"
      },
      {
        "id": "V_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 21.07 88.00 L 24.63 88.00 L 50.00 22.85"
      },
      {
        "id": "V_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 78.93 88.00 L 75.26 88.00 L 50.00 22.85"
      },
      {
        "id": "V_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 78.93 88.00 L 50.00 12.00"
      }
    ],
    "skillTags": [
      "letter:V",
      "case:upper",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "W": {
    "id": "W",
    "label": "W",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "W_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 12.00 86.35 L 32.65 13.65"
      },
      {
        "id": "W_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 12.00 86.35 L 15.40 86.35 L 32.65 24.03"
      },
      {
        "id": "W_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 50.00 86.35 L 32.65 24.03"
      },
      {
        "id": "W_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 50.00 75.92 L 32.65 13.65"
      },
      {
        "id": "W_stroke_5",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 50.00 75.92 L 67.35 13.65"
      },
      {
        "id": "W_stroke_6",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 50.00 86.35 L 67.35 24.03"
      },
      {
        "id": "W_stroke_7",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 88.00 86.35 L 84.60 86.35 L 67.35 24.03"
      },
      {
        "id": "W_stroke_8",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 88.00 86.35 L 67.35 13.65"
      }
    ],
    "skillTags": [
      "letter:W",
      "case:upper",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "X": {
    "id": "X",
    "label": "X",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "X_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 24.69 88.00 L 71.64 12.00 L 75.31 12.00"
      },
      {
        "id": "X_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 24.69 88.00 L 28.24 88.00 L 75.31 12.00"
      },
      {
        "id": "X_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 75.31 88.00 L 71.64 88.00 L 24.69 12.00"
      },
      {
        "id": "X_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 75.31 88.00 L 28.24 12.00 L 24.69 12.00"
      }
    ],
    "skillTags": [
      "letter:X",
      "case:upper",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "Y": {
    "id": "Y",
    "label": "Y",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "Y_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 22.91 88.00 L 48.16 51.72 L 48.16 12.00 L 51.84 12.00"
      },
      {
        "id": "Y_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 22.91 88.00 L 26.47 88.00 L 51.84 51.72"
      },
      {
        "id": "Y_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 77.09 88.00 L 73.42 88.00 L 48.16 51.72"
      },
      {
        "id": "Y_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 77.09 88.00 L 51.84 51.72 L 51.84 12.00"
      }
    ],
    "skillTags": [
      "letter:Y",
      "case:upper",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "Z": {
    "id": "Z",
    "label": "Z",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "Z_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 71.64 88.00 L 24.69 12.00"
      },
      {
        "id": "Z_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 75.31 88.00 L 28.24 12.00"
      },
      {
        "id": "Z_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 24.69 88.00 L 75.31 88.00"
      },
      {
        "id": "Z_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 24.69 88.00 L 24.69 84.33 L 71.64 84.33"
      },
      {
        "id": "Z_stroke_5",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 28.24 15.62 L 75.31 15.62 L 75.31 12.00"
      },
      {
        "id": "Z_stroke_6",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 24.69 12.00 L 75.31 12.00"
      }
    ],
    "skillTags": [
      "letter:Z",
      "case:upper",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "a": {
    "id": "a",
    "label": "a",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "a_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 79.90 88.00 L 79.90 12.00 L 85.24 12.00"
      },
      {
        "id": "a_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 79.90 88.00 L 85.24 88.00 L 85.24 12.00"
      },
      {
        "id": "a_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 79.90 71.63 L 69.04 82.66 L 58.19 88.00 L 41.81 88.00 L 31.13 82.66 L 20.10 71.63 L 14.76 55.43 L 14.76 44.57 L 20.10 28.29 L 31.13 17.43 L 41.81 12.00 L 58.19 12.00 L 69.04 17.43 L 79.90 28.29"
      },
      {
        "id": "a_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 79.90 71.63 L 58.19 82.66 L 41.81 82.66 L 31.13 77.14 L 25.61 71.63 L 20.10 55.43 L 20.10 44.57 L 25.61 28.29 L 31.13 22.86 L 41.81 17.43 L 58.19 17.43 L 79.90 28.29"
      }
    ],
    "skillTags": [
      "letter:a",
      "case:lower",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "b": {
    "id": "b",
    "label": "b",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "b_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 26.47 88.00 L 26.47 12.00 L 30.14 12.00"
      },
      {
        "id": "b_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 26.47 88.00 L 30.14 88.00 L 30.14 12.00"
      },
      {
        "id": "b_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 30.14 51.72 L 37.37 59.07 L 44.60 62.63 L 55.40 62.63 L 62.74 59.07 L 69.86 51.72 L 73.53 40.93 L 73.53 33.70 L 69.86 22.85 L 62.74 15.62 L 55.40 12.00 L 44.60 12.00 L 37.37 15.62 L 30.14 22.85"
      },
      {
        "id": "b_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 30.14 51.72 L 44.60 59.07 L 55.40 59.07 L 62.74 55.40 L 66.30 51.72 L 69.86 40.93 L 69.86 33.70 L 66.30 22.85 L 62.74 19.23 L 55.40 15.62 L 44.60 15.62 L 30.14 22.85"
      }
    ],
    "skillTags": [
      "letter:b",
      "case:lower",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "c": {
    "id": "c",
    "label": "c",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "c_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 82.57 71.63 L 71.71 82.66 L 60.86 88.00 L 44.49 88.00 L 33.80 82.66 L 22.77 71.63 L 17.43 55.43 L 17.43 44.57 L 22.77 28.29 L 33.80 17.43 L 44.49 12.00 L 60.86 12.00 L 71.71 17.43 L 82.57 28.29"
      },
      {
        "id": "c_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 82.57 71.63 L 77.23 66.29 L 71.71 77.14 L 60.86 82.66 L 44.49 82.66 L 33.80 77.14 L 28.29 71.63 L 22.77 55.43 L 22.77 44.57 L 28.29 28.29 L 33.80 22.86 L 44.49 17.43 L 60.86 17.43 L 71.71 22.86 L 77.23 33.71 L 82.57 28.29"
      }
    ],
    "skillTags": [
      "letter:c",
      "case:lower",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "d": {
    "id": "d",
    "label": "d",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "d_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 69.92 88.00 L 69.92 12.00 L 73.48 12.00"
      },
      {
        "id": "d_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 69.92 88.00 L 73.48 88.00 L 73.48 12.00"
      },
      {
        "id": "d_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 69.92 51.72 L 62.69 59.07 L 55.45 62.63 L 44.55 62.63 L 37.43 59.07 L 30.08 51.72 L 26.52 40.93 L 26.52 33.70 L 30.08 22.85 L 37.43 15.62 L 44.55 12.00 L 55.45 12.00 L 62.69 15.62 L 69.92 22.85"
      },
      {
        "id": "d_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 69.92 51.72 L 55.45 59.07 L 44.55 59.07 L 37.43 55.40 L 33.76 51.72 L 30.08 40.93 L 30.08 33.70 L 33.76 22.85 L 37.43 19.23 L 44.55 15.62 L 55.45 15.62 L 69.92 22.85"
      }
    ],
    "skillTags": [
      "letter:d",
      "case:lower",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "e": {
    "id": "e",
    "label": "e",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "e_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 22.77 49.91 L 82.57 49.91 L 82.57 66.29 L 77.23 77.14 L 71.71 82.66 L 60.86 88.00 L 44.49 88.00 L 33.80 82.66 L 22.77 71.63 L 17.43 55.43 L 17.43 44.57 L 22.77 28.29 L 33.80 17.43 L 44.49 12.00 L 60.86 12.00 L 71.71 17.43 L 82.57 28.29"
      },
      {
        "id": "e_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 22.77 55.43 L 77.23 55.43 L 77.23 66.29 L 71.71 77.14 L 60.86 82.66 L 44.49 82.66 L 33.80 77.14 L 28.29 71.63 L 22.77 55.43 L 22.77 44.57 L 28.29 28.29 L 33.80 22.86 L 44.49 17.43 L 60.86 17.43 L 71.71 22.86 L 77.23 33.71 L 82.57 28.29"
      }
    ],
    "skillTags": [
      "letter:e",
      "case:lower",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "f": {
    "id": "f",
    "label": "f",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "f_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 64.47 88.00 L 57.23 88.00 L 50.00 84.33 L 46.44 73.53 L 46.44 12.00 L 50.00 12.00"
      },
      {
        "id": "f_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 64.47 88.00 L 64.47 84.33 L 57.23 84.33 L 50.00 80.65"
      },
      {
        "id": "f_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 53.56 84.33 L 50.00 73.53 L 50.00 12.00"
      },
      {
        "id": "f_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 35.53 62.63 L 60.91 62.63 L 60.91 59.07"
      },
      {
        "id": "f_stroke_5",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 35.53 62.63 L 35.53 59.07 L 60.91 59.07"
      }
    ],
    "skillTags": [
      "letter:f",
      "case:lower",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "g": {
    "id": "g",
    "label": "g",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "g_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 73.51 88.00 L 69.95 88.00 L 69.95 33.67 L 66.38 22.81 L 62.70 19.13 L 55.46 15.56 L 48.22 15.56 L 40.97 19.13 L 37.41 22.81 L 30.05 22.81"
      },
      {
        "id": "g_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 73.51 88.00 L 73.51 33.67 L 69.95 22.81 L 62.70 15.56 L 55.46 12.00 L 44.54 12.00 L 37.41 15.56 L 30.05 22.81"
      },
      {
        "id": "g_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 69.95 77.08 L 62.70 84.44 L 55.46 88.00 L 44.54 88.00 L 37.41 84.44 L 30.05 77.08 L 26.49 66.27 L 26.49 59.03 L 30.05 48.16 L 37.41 40.92 L 44.54 37.30 L 55.46 37.30 L 62.70 40.92 L 69.95 48.16"
      },
      {
        "id": "g_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 69.95 77.08 L 55.46 84.44 L 44.54 84.44 L 37.41 80.76 L 33.73 77.08 L 30.05 66.27 L 30.05 59.03 L 33.73 48.16 L 37.41 44.54 L 44.54 40.92 L 55.46 40.92 L 69.95 48.16"
      }
    ],
    "skillTags": [
      "letter:g",
      "case:lower",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "h": {
    "id": "h",
    "label": "h",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "h_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 28.30 88.00 L 28.30 12.00 L 31.98 12.00"
      },
      {
        "id": "h_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 28.30 88.00 L 31.98 88.00 L 31.98 12.00"
      },
      {
        "id": "h_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 31.98 48.16 L 42.77 59.07 L 50.11 62.63 L 60.91 62.63 L 68.14 59.07 L 71.70 48.16 L 71.70 12.00"
      },
      {
        "id": "h_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 31.98 48.16 L 42.77 55.40 L 50.11 59.07 L 57.23 59.07 L 64.58 55.40 L 68.14 48.16 L 68.14 12.00 L 71.70 12.00"
      }
    ],
    "skillTags": [
      "letter:h",
      "case:lower",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "i": {
    "id": "i",
    "label": "i",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "i_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 48.11 88.00 L 44.55 84.33 L 44.55 80.65 L 48.11 77.09 L 51.78 77.09 L 55.45 80.65 L 55.45 84.33 L 51.78 88.00 L 48.11 88.00"
      },
      {
        "id": "i_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 48.11 84.33 L 48.11 80.65 L 51.78 80.65 L 51.78 84.33 L 48.11 84.33"
      },
      {
        "id": "i_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 48.11 62.63 L 48.11 12.00 L 51.78 12.00"
      },
      {
        "id": "i_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 48.11 62.63 L 51.78 62.63 L 51.78 12.00"
      }
    ],
    "skillTags": [
      "letter:i",
      "case:lower",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "j": {
    "id": "j",
    "label": "j",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "j_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 48.58 88.00 L 45.91 85.24 L 45.91 82.49 L 48.58 79.81 L 51.34 79.81 L 54.09 82.49 L 54.09 85.24 L 51.34 88.00 L 48.58 88.00"
      },
      {
        "id": "j_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 48.58 85.24 L 48.58 82.49 L 51.34 82.49 L 51.34 85.24 L 48.58 85.24"
      },
      {
        "id": "j_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 48.58 68.96 L 48.58 12.00 L 51.34 12.00"
      },
      {
        "id": "j_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 48.58 68.96 L 51.34 68.96 L 51.34 12.00"
      }
    ],
    "skillTags": [
      "letter:j",
      "case:lower",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "k": {
    "id": "k",
    "label": "k",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "k_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 28.30 88.00 L 28.30 12.00 L 31.98 12.00"
      },
      {
        "id": "k_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 28.30 88.00 L 31.98 88.00 L 31.98 12.00"
      },
      {
        "id": "k_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 71.70 62.63 L 68.14 62.63 L 31.98 26.47"
      },
      {
        "id": "k_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 71.70 62.63 L 31.98 22.85"
      },
      {
        "id": "k_stroke_5",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 42.77 37.26 L 64.58 12.00 L 71.70 12.00"
      },
      {
        "id": "k_stroke_6",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 46.44 40.93 L 71.70 12.00"
      }
    ],
    "skillTags": [
      "letter:k",
      "case:lower",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "l": {
    "id": "l",
    "label": "l",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "l_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 48.16 88.00 L 48.16 12.00 L 51.84 12.00"
      },
      {
        "id": "l_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 48.16 88.00 L 51.84 88.00 L 51.84 12.00"
      }
    ],
    "skillTags": [
      "letter:l",
      "case:lower",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "m": {
    "id": "m",
    "label": "m",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "m_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 12.00 73.11 L 12.00 26.89 L 15.35 26.89"
      },
      {
        "id": "m_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 12.00 73.11 L 15.35 73.11 L 15.35 26.89"
      },
      {
        "id": "m_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 15.35 59.91 L 25.21 69.86 L 31.92 73.11 L 41.77 73.11 L 48.38 69.86 L 51.62 59.91 L 51.62 26.89"
      },
      {
        "id": "m_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 15.35 59.91 L 25.21 66.51 L 31.92 69.86 L 38.42 69.86 L 45.13 66.51 L 48.38 59.91 L 48.38 26.89 L 51.62 26.89"
      },
      {
        "id": "m_stroke_5",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 51.62 59.91 L 61.58 69.86 L 68.19 73.11 L 78.04 73.11 L 84.75 69.86 L 88.00 59.91 L 88.00 26.89"
      },
      {
        "id": "m_stroke_6",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 51.62 59.91 L 61.58 66.51 L 68.19 69.86 L 74.79 69.86 L 81.40 66.51 L 84.75 59.91 L 84.75 26.89 L 88.00 26.89"
      }
    ],
    "skillTags": [
      "letter:m",
      "case:lower",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "n": {
    "id": "n",
    "label": "n",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "n_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 17.43 88.00 L 17.43 12.00 L 22.94 12.00"
      },
      {
        "id": "n_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 17.43 88.00 L 22.94 88.00 L 22.94 12.00"
      },
      {
        "id": "n_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 22.94 66.29 L 39.14 82.66 L 50.17 88.00 L 66.37 88.00 L 77.23 82.66 L 82.57 66.29 L 82.57 12.00"
      },
      {
        "id": "n_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 22.94 66.29 L 39.14 77.14 L 50.17 82.66 L 60.86 82.66 L 71.89 77.14 L 77.23 66.29 L 77.23 12.00 L 82.57 12.00"
      }
    ],
    "skillTags": [
      "letter:n",
      "case:lower",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "o": {
    "id": "o",
    "label": "o",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "o_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 41.81 88.00 L 31.13 82.66 L 20.10 71.63 L 14.76 55.43 L 14.76 44.57 L 20.10 28.29 L 31.13 17.43 L 41.81 12.00 L 58.19 12.00 L 69.04 17.43 L 79.90 28.29 L 85.24 44.57 L 85.24 55.43 L 79.90 71.63 L 69.04 82.66 L 58.19 88.00 L 41.81 88.00"
      },
      {
        "id": "o_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 41.81 82.66 L 31.13 77.14 L 25.61 71.63 L 20.10 55.43 L 20.10 44.57 L 25.61 28.29 L 31.13 22.86 L 41.81 17.43 L 58.19 17.43 L 69.04 22.86 L 74.56 28.29 L 79.90 44.57 L 79.90 55.43 L 74.56 71.63 L 69.04 77.14 L 58.19 82.66 L 41.81 82.66"
      }
    ],
    "skillTags": [
      "letter:o",
      "case:lower",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "p": {
    "id": "p",
    "label": "p",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "p_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 26.43 88.00 L 26.43 12.00 L 30.11 12.00"
      },
      {
        "id": "p_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 26.43 88.00 L 30.11 88.00 L 30.11 12.00"
      },
      {
        "id": "p_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 30.11 77.08 L 37.35 84.44 L 44.60 88.00 L 55.40 88.00 L 62.76 84.44 L 69.89 77.08 L 73.57 66.27 L 73.57 59.03 L 69.89 48.16 L 62.76 40.92 L 55.40 37.30 L 44.60 37.30 L 37.35 40.92 L 30.11 48.16"
      },
      {
        "id": "p_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 30.11 77.08 L 44.60 84.44 L 55.40 84.44 L 62.76 80.76 L 66.33 77.08 L 69.89 66.27 L 69.89 59.03 L 66.33 48.16 L 62.76 44.54 L 55.40 40.92 L 44.60 40.92 L 30.11 48.16"
      }
    ],
    "skillTags": [
      "letter:p",
      "case:lower",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "q": {
    "id": "q",
    "label": "q",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "q_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 69.95 88.00 L 69.95 12.00 L 73.51 12.00"
      },
      {
        "id": "q_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 69.95 88.00 L 73.51 88.00 L 73.51 12.00"
      },
      {
        "id": "q_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 69.95 77.08 L 62.70 84.44 L 55.46 88.00 L 44.54 88.00 L 37.41 84.44 L 30.05 77.08 L 26.49 66.27 L 26.49 59.03 L 30.05 48.16 L 37.41 40.92 L 44.54 37.30 L 55.46 37.30 L 62.70 40.92 L 69.95 48.16"
      },
      {
        "id": "q_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 69.95 77.08 L 55.46 84.44 L 44.54 84.44 L 37.41 80.76 L 33.73 77.08 L 30.05 66.27 L 30.05 59.03 L 33.73 48.16 L 37.41 44.54 L 44.54 40.92 L 55.46 40.92 L 69.95 48.16"
      }
    ],
    "skillTags": [
      "letter:q",
      "case:lower",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "r": {
    "id": "r",
    "label": "r",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "r_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 25.53 88.00 L 25.53 12.00 L 31.04 12.00"
      },
      {
        "id": "r_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 25.53 88.00 L 31.04 88.00 L 31.04 12.00"
      },
      {
        "id": "r_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 31.04 55.43 L 36.56 71.63 L 47.24 82.66 L 58.27 88.00 L 74.47 88.00"
      },
      {
        "id": "r_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 31.04 55.43 L 36.56 66.29 L 47.24 77.14 L 58.27 82.66 L 74.47 82.66 L 74.47 88.00"
      }
    ],
    "skillTags": [
      "letter:r",
      "case:lower",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "s": {
    "id": "s",
    "label": "s",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "s_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 79.90 71.63 L 74.39 82.66 L 58.19 88.00 L 41.81 88.00 L 25.44 82.66 L 20.10 71.63 L 25.44 60.94 L 36.47 55.43 L 63.53 44.57 L 74.39 39.23"
      },
      {
        "id": "s_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 68.87 44.57 L 74.39 33.71 L 74.39 28.29 L 68.87 17.43"
      },
      {
        "id": "s_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 74.39 22.86 L 58.19 17.43 L 41.81 17.43 L 25.44 22.86"
      },
      {
        "id": "s_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 30.96 17.43 L 25.44 28.29 L 20.10 28.29"
      },
      {
        "id": "s_stroke_5",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 79.90 71.63 L 74.39 71.63 L 68.87 82.66"
      },
      {
        "id": "s_stroke_6",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 74.39 77.14 L 58.19 82.66 L 41.81 82.66 L 25.44 77.14"
      },
      {
        "id": "s_stroke_7",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 30.96 82.66 L 25.44 71.63 L 30.96 60.94"
      },
      {
        "id": "s_stroke_8",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 25.44 66.29 L 36.47 60.94 L 63.53 49.91 L 74.39 44.57 L 79.90 33.71 L 79.90 28.29 L 74.39 17.43 L 58.19 12.00 L 41.81 12.00 L 25.44 17.43 L 20.10 28.29"
      }
    ],
    "skillTags": [
      "letter:s",
      "case:lower",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "t": {
    "id": "t",
    "label": "t",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "t_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 48.16 88.00 L 48.16 12.00 L 51.84 12.00"
      },
      {
        "id": "t_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 48.16 88.00 L 51.84 88.00 L 51.84 12.00"
      },
      {
        "id": "t_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 37.37 62.63 L 62.63 62.63 L 62.63 59.07"
      },
      {
        "id": "t_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 37.37 62.63 L 37.37 59.07 L 62.63 59.07"
      }
    ],
    "skillTags": [
      "letter:t",
      "case:lower",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "u": {
    "id": "u",
    "label": "u",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "u_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 17.43 88.00 L 17.43 33.71 L 22.94 17.43 L 33.80 12.00 L 50.17 12.00 L 60.86 17.43 L 77.23 33.71"
      },
      {
        "id": "u_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 17.43 88.00 L 22.94 88.00 L 22.94 33.71 L 28.46 22.86 L 39.14 17.43 L 50.17 17.43 L 60.86 22.86 L 77.23 33.71"
      },
      {
        "id": "u_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 77.23 88.00 L 77.23 12.00 L 82.57 12.00"
      },
      {
        "id": "u_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 77.23 88.00 L 82.57 88.00 L 82.57 12.00"
      }
    ],
    "skillTags": [
      "letter:u",
      "case:lower",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "v": {
    "id": "v",
    "label": "v",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "v_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 17.43 88.00 L 49.83 12.00"
      },
      {
        "id": "v_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 17.43 88.00 L 22.77 88.00 L 49.83 22.86"
      },
      {
        "id": "v_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 82.57 88.00 L 77.06 88.00 L 49.83 22.86"
      },
      {
        "id": "v_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 82.57 88.00 L 49.83 12.00"
      }
    ],
    "skillTags": [
      "letter:v",
      "case:lower",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "w": {
    "id": "w",
    "label": "w",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "w_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 12.00 79.56 L 33.04 20.44"
      },
      {
        "id": "w_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 12.00 79.56 L 16.16 79.56 L 33.04 33.11"
      },
      {
        "id": "w_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 49.93 79.56 L 33.04 33.11"
      },
      {
        "id": "w_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 49.93 66.82 L 33.04 20.44"
      },
      {
        "id": "w_stroke_5",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 49.93 66.82 L 66.82 20.44"
      },
      {
        "id": "w_stroke_6",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 49.93 79.56 L 66.82 33.11"
      },
      {
        "id": "w_stroke_7",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 88.00 79.56 L 83.71 79.56 L 66.82 33.11"
      },
      {
        "id": "w_stroke_8",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 88.00 79.56 L 66.82 20.44"
      }
    ],
    "skillTags": [
      "letter:w",
      "case:lower",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "x": {
    "id": "x",
    "label": "x",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "x_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 17.43 88.00 L 77.23 12.00 L 82.57 12.00"
      },
      {
        "id": "x_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 17.43 88.00 L 22.77 88.00 L 82.57 12.00"
      },
      {
        "id": "x_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 82.57 88.00 L 77.23 88.00 L 17.43 12.00"
      },
      {
        "id": "x_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 82.57 88.00 L 22.77 12.00 L 17.43 12.00"
      }
    ],
    "skillTags": [
      "letter:x",
      "case:lower",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "y": {
    "id": "y",
    "label": "y",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "y_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 28.27 88.00 L 49.89 37.30"
      },
      {
        "id": "y_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 28.27 88.00 L 31.83 88.00 L 49.89 44.54"
      },
      {
        "id": "y_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 71.73 88.00 L 68.05 88.00 L 49.89 44.54 L 35.40 12.00"
      },
      {
        "id": "y_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 71.73 88.00 L 49.89 37.30 L 39.08 12.00 L 35.40 12.00"
      }
    ],
    "skillTags": [
      "letter:y",
      "case:lower",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  },
  "z": {
    "id": "z",
    "label": "z",
    "viewBox": "0 0 100 100",
    "strokes": [
      {
        "id": "z_stroke_1",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 71.71 82.66 L 17.43 12.00"
      },
      {
        "id": "z_stroke_2",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 82.57 88.00 L 28.29 17.43"
      },
      {
        "id": "z_stroke_3",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 17.43 88.00 L 82.57 88.00"
      },
      {
        "id": "z_stroke_4",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 17.43 88.00 L 17.43 82.66 L 71.71 82.66"
      },
      {
        "id": "z_stroke_5",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 28.29 17.43 L 82.57 17.43 L 82.57 12.00"
      },
      {
        "id": "z_stroke_6",
        "kind": "trace",
        "startT": 0.02,
        "endT": 0.98,
        "pathD": "M 17.43 12.00 L 82.57 12.00"
      }
    ],
    "skillTags": [
      "letter:z",
      "case:lower",
      "subtopic:tracing",
      "source:hersheytext",
      "font:hershey_sans_med"
    ]
  }
};
