import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import NavBar from './NavBar/NavBar';
export const Header = () => {
    const [open, setOpen] = useState(false);
    const { pathname } = useLocation();
    const isActive = (path) => pathname === path;
    return (_jsxs("header", { className: "sticky top-0 z-50 w-full bg-white/90 backdrop-blur-md shadow-lg border-b border-gray-200", children: [_jsxs("div", { className: "container mx-auto px-4 py-4 flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center space-x-2", children: [_jsx("div", { className: "w-10 h-10 bg-gradient-to-br from-blue-500 to-purple-600 rounded-full flex items-center justify-center text-white font-bold text-lg", children: "T" }), _jsx("span", { className: "text-2xl font-bold text-gray-900", children: "TinySteps" })] }), _jsx(NavBar, {}), _jsx("button", { className: "md:hidden p-2 rounded-md bg-white border border-gray-200 shadow-sm", onClick: () => setOpen(!open), "aria-label": "Toggle menu", children: !open ? (_jsx("svg", { className: "h-6 w-6 text-gray-700", xmlns: "http://www.w3.org/2000/svg", fill: "none", viewBox: "0 0 24 24", strokeWidth: 2, stroke: "currentColor", "aria-hidden": true, children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", d: "M4 6h16M4 12h16M4 18h16" }) })) : (_jsx("svg", { className: "h-6 w-6 text-gray-700", xmlns: "http://www.w3.org/2000/svg", fill: "none", viewBox: "0 0 24 24", strokeWidth: 2, stroke: "currentColor", "aria-hidden": true, children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", d: "M6 18L18 6M6 6l12 12" }) })) })] }), _jsx("div", { className: `md:hidden fixed inset-x-0 top-0 z-40 transform transition-transform duration-300 ${open ? 'translate-y-0' : '-translate-y-full'}`, children: _jsx("div", { className: "bg-white border-b border-gray-200 shadow", children: _jsxs("div", { className: "px-4 py-4 space-y-2", children: [_jsx(Link, { to: "/", className: `block px-3 py-2 rounded-md text-base font-medium ${isActive('/') ? 'text-blue-600 bg-gray-50' : 'text-gray-700 hover:bg-gray-50'}`, children: "Home" }), _jsx(Link, { to: "/phonics", className: `block px-3 py-2 rounded-md text-base font-medium ${isActive('/phonics') ? 'text-blue-600 bg-gray-50' : 'text-gray-700 hover:bg-gray-50'}`, children: "Phonics" }), _jsx(Link, { to: "/grammar", className: `block px-3 py-2 rounded-md text-base font-medium ${isActive('/grammar') ? 'text-blue-600 bg-gray-50' : 'text-gray-700 hover:bg-gray-50'}`, children: "Grammar" }), _jsx(Link, { to: "/speaking", className: `block px-3 py-2 rounded-md text-base font-medium ${isActive('/speaking') ? 'text-blue-600 bg-gray-50' : 'text-gray-700 hover:bg-gray-50'}`, children: "Public Speaking" }), _jsx("a", { href: "#book-trial", className: "block px-3 py-2 rounded-md text-base font-medium text-gray-700 hover:bg-gray-50", children: "Book Trial" })] }) }) })] }));
};
export const Footer = () => (_jsx("footer", { className: "bg-gray-900 text-white py-16", children: _jsxs("div", { className: "container mx-auto px-4", children: [_jsxs("div", { className: "grid grid-cols-1 md:grid-cols-4 gap-8", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex items-center space-x-2 mb-4", children: [_jsx("div", { className: "w-10 h-10 bg-gradient-to-br from-blue-500 to-purple-600 rounded-full flex items-center justify-center text-white font-bold text-lg", children: "T" }), _jsx("span", { className: "text-2xl font-bold", children: "TinySteps" })] }), _jsx("p", { className: "text-gray-400", children: "Empowering kids through fun learning." })] }), _jsxs("div", { children: [_jsx("h3", { className: "font-semibold mb-4", children: "Programs" }), _jsxs("ul", { className: "space-y-2", children: [_jsx("li", { children: _jsx(Link, { to: "/phonics", className: "hover:text-blue-400 transition", children: "Phonics Foundations" }) }), _jsx("li", { children: _jsx(Link, { to: "/grammar", className: "hover:text-blue-400 transition", children: "Grammar & Writing Lab" }) }), _jsx("li", { children: _jsx(Link, { to: "/speaking", className: "hover:text-blue-400 transition", children: "Public Speaking Studio" }) })] })] }), _jsxs("div", { children: [_jsx("h3", { className: "font-semibold mb-4", children: "Explore" }), _jsxs("ul", { className: "space-y-2", children: [_jsx("li", { children: _jsx("a", { href: "#pricing", className: "hover:text-blue-400 transition", children: "Pricing" }) }), _jsx("li", { children: _jsx("a", { href: "#faq", className: "hover:text-blue-400 transition", children: "FAQ" }) }), _jsx("li", { children: _jsx("a", { href: "#blog", className: "hover:text-blue-400 transition", children: "Blog" }) })] })] }), _jsxs("div", { children: [_jsx("h3", { className: "font-semibold mb-4", children: "Connect" }), _jsxs("ul", { className: "space-y-2", children: [_jsx("li", { children: _jsx("a", { href: "mailto:hello@tinystepslearning.com", className: "hover:text-blue-400 transition", children: "hello@tinystepslearning.com" }) }), _jsx("li", { children: _jsx("a", { href: "tel:+919666095553", className: "hover:text-blue-400 transition", children: "+91 96660 95553" }) }), _jsx("li", { children: _jsx("a", { href: "#", className: "hover:text-blue-400 transition", children: "Book a Learning Call" }) })] })] })] }), _jsx("div", { className: "mt-8 pt-8 border-t border-gray-800 text-center", children: _jsx("p", { children: "\u00A9 2025 Tiny Steps Learning. All rights reserved." }) })] }) }));
const Layout = ({ children }) => (_jsxs("div", { className: "min-h-screen", children: [_jsx(Header, {}), _jsx("main", { children: children }), _jsx(Footer, {})] }));
export default Layout;
