import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// @ts-nocheck
import { useState } from 'react';
import { cn } from '../lib/utils';
import Button from '../Button/Button';
import { Link } from 'react-router-dom';
export const CourseCard = ({ icon, name, track, age, duration, frequency, level, overview, outcomes, price, reviews, slug, ibLens = [] }) => {
    const [open, setOpen] = useState(false);
    return (_jsxs("div", { className: cn('hover-highlight rounded-3xl border border-gray-100 bg-gradient-to-br from-sky-50 via-white to-indigo-50 shadow-[0_10px_30px_rgba(2,6,23,0.06)] transition-all hover:shadow-2xl hover:-translate-y-1'), onClick: () => setOpen((v) => !v), children: [_jsxs("div", { className: "p-6", children: [_jsxs("div", { className: "mb-2 flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-2 text-lg font-semibold text-gray-900", children: [_jsx("span", { className: "text-2xl", children: icon }), name] }), _jsx("div", { className: "text-sm text-gray-600", children: duration })] }), _jsxs("div", { className: "text-sm text-gray-700", children: [age, " \u2022 ", frequency, " \u2022 Level: ", level] }), _jsxs("div", { className: "mt-3 text-sm text-gray-800", children: [_jsx("div", { className: "font-medium", children: "Quick Overview:" }), _jsx("ul", { className: "list-disc pl-5", children: overview.map((o) => _jsx("li", { children: o }, o)) })] }), _jsxs("div", { className: "mt-4 flex flex-wrap items-center gap-2", children: [slug ? (_jsx(Link, { to: `/courses/${slug}`, className: "interactive-link text-sm font-semibold text-primary-600", children: "View Full Curriculum \u2192" })) : (_jsx(Button, { size: "sm", variant: "outline", className: "min-w-[150px] whitespace-nowrap", children: "View Curriculum" })), _jsxs(Button, { size: "sm", className: "min-w-[170px] whitespace-nowrap", children: ["Enroll \u00B7 ", price] })] }), ibLens.length > 0 && (_jsxs("div", { className: "mt-3 text-xs text-gray-600", children: [_jsx("div", { className: "font-semibold text-gray-900", children: "IB lens" }), _jsx("ul", { className: "list-disc pl-4", children: ibLens.slice(0, 2).map((lens) => (_jsx("li", { children: lens }, lens))) })] })), reviews && _jsx("div", { className: "mt-3 text-xs text-gray-600", children: reviews })] }), _jsx("div", { className: cn('hover-details-body px-6 pb-6', open ? 'open' : ''), children: _jsxs("div", { className: "text-sm text-gray-900", children: [_jsx("div", { className: "font-medium", children: "Learning Outcomes:" }), _jsx("ul", { className: "list-disc pl-5", children: outcomes.map((o) => _jsx("li", { children: o }, o)) })] }) })] }));
};
