import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from 'framer-motion';
const MotivationCenter = () => {
    const dailyTip = "Did you know? There are 44 sounds in English! You're learning them one by one! 🎵";
    const messages = {
        parent: "Great job in your session today! ❤️ Keep up the amazing work!",
        teacher: "You're doing amazing! Keep practicing! 🌟",
        nextMilestone: "Only 2 more words to unlock 'Word Master'!"
    };
    return (_jsxs("div", { className: "p-6", children: [_jsx("h1", { className: "text-3xl font-bold text-center mb-6", children: "You're Amazing! \uD83D\uDCAB" }), _jsxs(motion.div, { className: "bg-gradient-to-r from-yellow-300 to-orange-400 rounded-3xl p-6 mb-6 text-center text-white", initial: { scale: 0.9 }, animate: { scale: 1 }, transition: { type: "spring", stiffness: 300 }, children: [_jsx("h2", { className: "text-2xl font-bold mb-4", children: "Daily Tip \uD83D\uDCA1" }), _jsx("p", { className: "text-lg", children: dailyTip })] }), _jsxs(motion.div, { className: "bg-pink-100 rounded-3xl p-6 mb-6", initial: { opacity: 0, x: -50 }, animate: { opacity: 1, x: 0 }, transition: { delay: 0.2 }, children: [_jsxs("div", { className: "flex items-center mb-2", children: [_jsx("span", { className: "text-3xl mr-3", children: "\uD83D\uDC68\u200D\uD83D\uDC69\u200D\uD83D\uDC67\u200D\uD83D\uDC66" }), _jsx("h3", { className: "text-xl font-bold", children: "From Your Parents" })] }), _jsx("p", { className: "text-lg text-pink-800", children: messages.parent })] }), _jsxs(motion.div, { className: "bg-blue-100 rounded-3xl p-6 mb-6", initial: { opacity: 0, x: 50 }, animate: { opacity: 1, x: 0 }, transition: { delay: 0.4 }, children: [_jsxs("div", { className: "flex items-center mb-2", children: [_jsx("span", { className: "text-3xl mr-3", children: "\uD83D\uDC69\u200D\uD83C\uDFEB" }), _jsx("h3", { className: "text-xl font-bold", children: "From Your Teacher" })] }), _jsx("p", { className: "text-lg text-blue-800", children: messages.teacher })] }), _jsxs(motion.div, { className: "bg-green-100 rounded-3xl p-6 mb-6", initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { delay: 0.6 }, children: [_jsxs("div", { className: "flex items-center mb-2", children: [_jsx("span", { className: "text-3xl mr-3", children: "\uD83C\uDFAF" }), _jsx("h3", { className: "text-xl font-bold", children: "Next Milestone" })] }), _jsx("p", { className: "text-lg text-green-800", children: messages.nextMilestone })] }), _jsxs(motion.div, { className: "bg-gradient-to-r from-purple-400 to-indigo-500 rounded-3xl p-6 text-center text-white", initial: { opacity: 0, scale: 0.8 }, animate: { opacity: 1, scale: 1 }, transition: { delay: 0.8 }, children: [_jsx("p", { className: "text-xl font-bold mb-2", children: "\"Every expert was once a beginner!\"" }), _jsx("p", { className: "text-lg", children: "You're on your way to becoming a learning superstar! \uD83C\uDF1F" })] })] }));
};
export default MotivationCenter;
