import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Link } from "react-router-dom";
/** Shared dashboard layout used across teacher, parent, and learning manager previews. */
export default function DashboardShell({ navItems, header, rightRail, children }) {
    return (_jsx("div", { className: "bg-gradient-to-br from-[#eef6ff] via-[#f6f3ff] to-[#ffeef4] text-slate-900", children: _jsxs("div", { className: "mx-auto flex min-h-screen max-w-7xl gap-6 px-4 pb-12 pt-8 md:px-6 lg:px-8", children: [_jsxs("aside", { className: "hidden w-64 shrink-0 rounded-3xl border border-white/50 bg-white/80 p-6 shadow-xl shadow-slate-900/5 backdrop-blur lg:flex lg:flex-col", children: [_jsxs(Link, { to: "/", className: "flex items-center gap-3 transition hover:opacity-90", children: [_jsx("img", { src: "/assets/images/logo.png", alt: "Tiny Steps logo", className: "h-11 w-11 rounded-2xl border border-white/70 bg-white/90 p-1 shadow-sm shadow-slate-900/10" }), _jsxs("div", { children: [_jsx("p", { className: "text-xs font-semibold uppercase tracking-[0.28em] text-[#7c2d58]", children: "Tiny Steps" }), _jsx("p", { className: "text-base font-semibold text-slate-800", children: "Learning suite" })] })] }), _jsx("nav", { className: "mt-8 space-y-2", "aria-label": "Section navigation", children: navItems.map((item) => {
                                const className = [
                                    "flex w-full items-center gap-3 rounded-2xl px-4 py-3 text-sm font-semibold transition",
                                    item.active
                                        ? "bg-gradient-to-r from-[#7dd3fc]/40 via-[#c4b5fd]/40 to-[#f9a8d4]/40 text-[#1d4ed8] ring-2 ring-[#7dd3fc]/40"
                                        : "text-slate-600 hover:bg-white/70 hover:text-[#1d4ed8]",
                                ].join(" ");
                                const content = (_jsxs(_Fragment, { children: [item.icon && (_jsx("span", { className: `grid h-9 w-9 place-content-center rounded-xl ${item.active ? "bg-white text-[#1d4ed8]" : "bg-white/60 text-[#7c2d58]"}`, children: item.icon })), _jsx("span", { className: "flex-1 text-left", children: item.label }), item.badge && (_jsx("span", { className: "rounded-full bg-white/80 px-2 py-0.5 text-xs font-bold text-[#1d4ed8] shadow-sm shadow-slate-900/5", children: item.badge }))] }));
                                if (item.href) {
                                    return (_jsx(Link, { to: item.href, className: className, onClick: item.onSelect, children: content }, item.key));
                                }
                                return (_jsx("button", { type: "button", className: className, onClick: item.onSelect, children: content }, item.key));
                            }) }), _jsxs("div", { className: "mt-auto rounded-2xl bg-gradient-to-r from-[#7dd3fc]/30 via-[#c4b5fd]/30 to-[#f9a8d4]/30 p-4 text-sm text-[#1f2937]", children: [_jsx("p", { className: "font-semibold text-[#1d4ed8]", children: "Need something?" }), _jsx("p", { className: "mt-1 text-slate-600", children: "Learning Managers coordinate parents, teachers, and lesson plans so everyone stays aligned." })] })] }), _jsxs("div", { className: "flex flex-1 flex-col gap-6", children: [_jsxs("header", { className: "rounded-3xl border border-white/60 bg-white/85 px-6 py-6 shadow-lg shadow-slate-900/8 backdrop-blur", children: [_jsxs("div", { className: "flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between", children: [_jsxs("div", { children: [_jsxs("p", { className: "inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.3em] text-[#2563eb]/80", children: [_jsx("span", { className: "h-1.5 w-1.5 rounded-full bg-[#2563eb]" }), "Workspace preview"] }), _jsx("h1", { className: "mt-2 text-3xl font-bold text-[#1f2937]", children: header.title }), header.subtitle && _jsx("p", { className: "mt-2 max-w-xl text-sm text-slate-500", children: header.subtitle })] }), _jsxs("div", { className: "flex flex-col gap-3 self-stretch sm:flex-row sm:items-center sm:justify-end sm:self-auto", children: [header.toolbar, _jsx(Link, { to: "/", className: "inline-flex items-center justify-center rounded-full border border-[#1d4ed8]/20 bg-white/90 px-4 py-2 text-xs font-semibold uppercase tracking-[0.22em] text-[#1d4ed8] shadow-sm transition hover:bg-[#1d4ed8]/10", children: "\u2190 Back to main site" })] })] }), _jsx("nav", { className: "mt-6 flex gap-2 overflow-x-auto pb-1 lg:hidden", "aria-label": "Workspace navigation", children: navItems.map((item) => {
                                        const className = `flex shrink-0 items-center gap-2 rounded-full px-4 py-2 text-sm font-semibold transition ${item.active ? "bg-[#2563eb]/10 text-[#1d4ed8]" : "bg-white/80 text-slate-500"}`;
                                        const content = (_jsxs(_Fragment, { children: [_jsx("span", { className: "text-[#7c2d58]", children: item.icon }), item.label, item.badge && (_jsx("span", { className: "rounded-full bg-white/90 px-2 py-0.5 text-xs font-bold text-[#1d4ed8]", children: item.badge }))] }));
                                        if (item.href) {
                                            return (_jsx(Link, { to: item.href, className: className, onClick: item.onSelect, children: content }, item.key));
                                        }
                                        return (_jsx("button", { type: "button", className: className, onClick: item.onSelect, children: content }, item.key));
                                    }) })] }), _jsxs("div", { className: "flex flex-1 flex-col gap-6 lg:flex-row", children: [_jsx("main", { className: "flex-1 space-y-6", children: children }), rightRail && (_jsx("aside", { className: "w-full shrink-0 space-y-6 lg:w-72", children: rightRail }))] })] })] }) }));
}
//# sourceMappingURL=DashboardShell.js.map