#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
OUT_FILE="$ROOT_DIR/docs/firebase-upgrade-packet/repo-inventory-baseline.md"

cd "$ROOT_DIR"

append_section() {
  local title="$1"
  local pattern="$2"
  shift 2

  {
    echo "## $title"
    echo
    local output
    output="$(
      rg -n --hidden -S \
        --glob '!node_modules/**' \
        --glob '!.git/**' \
        --glob '!docs/firebase-upgrade-packet/repo-inventory-baseline.md' \
        --glob '!scripts/inventory-firebase-auth.sh' \
        --glob '!scripts/audit-firebase-upgrade.sh' \
        "$pattern" "$@" || true
    )"
    if [[ -n "$output" ]]; then
      echo '```text'
      echo "$output"
      echo '```'
    else
      echo "_No matches found._"
    fi
    echo
  } >> "$OUT_FILE"
}

{
  echo "# Repo Inventory Baseline"
  echo
  echo "Generated: $(date '+%Y-%m-%d %H:%M:%S %Z')"
  echo
  echo "This file is generated by \`npm run inventory:firebase-auth\`."
  echo
} > "$OUT_FILE"

append_section \
  "Token-Based Auth Signals" \
  "FIREBASE_TOKEN|login:ci|firebase-token-generator|FirebaseTokenGenerator|database secret" \
  .github/workflows scripts functions src package.json functions/package.json docs

append_section \
  "Service Account File References" \
  "firebase-adminsdk-[A-Za-z0-9_-]+\\.json|serviceAccount\\.json|GOOGLE_APPLICATION_CREDENTIALS" \
  .github/workflows scripts functions src docs

append_section \
  "Admin SDK Initialization Points" \
  "admin\\.initializeApp\\(|firebase-admin" \
  functions/src src/functions scripts/dev-tools

append_section \
  "Realtime Database Usage Signals" \
  "firebaseio\\.com|getDatabase\\(|firebase\\.database\\(|databaseURL|realtime database" \
  functions/src src scripts

echo "Wrote $OUT_FILE"
