/**
 * SpellBee Words Database
 * Enhanced with visual icons, simplified meanings, and phoneme highlights
 */

export interface Word {
  word: string;
  ipa: string;
  meaning: string; // Original meaning
  forms: string;
  example: string;
  icon: string; // Visual emoji for memory hook
  simpleMeaning: string; // Kid-friendly ≤6 words
  phonemeHighlight?: string; // Which part to emphasize
}

export const WORDS: Word[] = [
  // E-words
  {
    word: "Enjoy",
    ipa: "/ɪnˈdʒɔɪ/",
    meaning: "to get happiness out of something",
    simpleMeaning: "to have fun doing something",
    icon: "😊",
    forms: "enjoys, enjoying, enjoyed, enjoyment",
    example: "I enjoy reading books every night.",
    phonemeHighlight: "joy"
  },
  {
    word: "Enough",
    ipa: "/ɪˈnʌf/",
    meaning: "as much as needed",
    simpleMeaning: "all you need",
    icon: "✅",
    forms: "—",
    example: "We have enough food for everyone.",
    phonemeHighlight: "nough"
  },
  {
    word: "Enter",
    ipa: "/ˈɛntər/",
    meaning: "to go into a place",
    simpleMeaning: "to go inside",
    icon: "🚪",
    forms: "enters, entering, entered",
    example: "Please enter the room quietly.",
    phonemeHighlight: "en"
  },
  {
    word: "Entry",
    ipa: "/ˈɛntri/",
    meaning: "a point through which one enters",
    simpleMeaning: "a way to go in",
    icon: "🚪",
    forms: "entries",
    example: "The entry to the building is on the left.",
    phonemeHighlight: "en"
  },
  {
    word: "Equal",
    ipa: "/ˈiːkwəl/",
    meaning: "same in size, value, or amount",
    simpleMeaning: "the same size",
    icon: "⚖️",
    forms: "equals, equalling, equalled, equality",
    example: "Both teams have an equal chance to win.",
    phonemeHighlight: "e"
  },
  {
    word: "Equip",
    ipa: "/ɪˈkwɪp/",
    meaning: "to provide with needed items or skills",
    simpleMeaning: "to give what's needed",
    icon: "🎒",
    forms: "equips, equipping, equipped, equipment",
    example: "The school will equip students with new tablets.",
    phonemeHighlight: "quip"
  },
  {
    word: "Err",
    ipa: "/ɜːr/",
    meaning: "to make a mistake",
    simpleMeaning: "to make a mistake",
    icon: "❌",
    forms: "errs, erred, erring, error",
    example: "To err is human, to forgive divine.",
    phonemeHighlight: "err"
  },
  {
    word: "Ever",
    ipa: "/ˈɛvər/",
    meaning: "at all times, always",
    simpleMeaning: "always, any time",
    icon: "♾️",
    forms: "—",
    example: "Have you ever been to the zoo?",
    phonemeHighlight: "ev"
  },
  {
    word: "Everybody",
    ipa: "/ˈevribɒdi/",
    meaning: "every single person",
    simpleMeaning: "all people",
    icon: "👥",
    forms: "—",
    example: "Everybody loves a good story.",
    phonemeHighlight: "body"
  },
  {
    word: "Evict",
    ipa: "/ɪˈvɪkt/",
    meaning: "to force someone to leave a place",
    simpleMeaning: "to make someone leave",
    icon: "🚫",
    forms: "evicts, evicting, evicted, eviction",
    example: "The landlord had to evict the tenant.",
    phonemeHighlight: "vict"
  },
  {
    word: "Eyeball",
    ipa: "/ˈaɪbɔːl/",
    meaning: "the round part of your eye",
    simpleMeaning: "the round part of eye",
    icon: "👁️",
    forms: "eyeballs",
    example: "The doctor checked my eyeball with a light.",
    phonemeHighlight: "eye"
  },
  {
    word: "Extra",
    ipa: "/ˈɛkstrə/",
    meaning: "more than usual",
    simpleMeaning: "more than usual",
    icon: "➕",
    forms: "extras",
    example: "I ordered extra cheese on my pizza.",
    phonemeHighlight: "ex"
  },
  {
    word: "Ewe",
    ipa: "/juː/",
    meaning: "a female sheep",
    simpleMeaning: "a girl sheep",
    icon: "🐑",
    forms: "ewes",
    example: "The ewe was grazing in the field.",
    phonemeHighlight: "ewe"
  },

  // F-words
  {
    word: "Face",
    ipa: "/feɪs/",
    meaning: "the front of your head",
    simpleMeaning: "front of your head",
    icon: "😀",
    forms: "faces, facing, faced",
    example: "She has a beautiful smiling face.",
    phonemeHighlight: "face"
  },
  {
    word: "Fact",
    ipa: "/fækt/",
    meaning: "something that is true",
    simpleMeaning: "something that is true",
    icon: "📌",
    forms: "—",
    example: "It's a fact that the Earth is round.",
    phonemeHighlight: "fact"
  },
  {
    word: "Fail",
    ipa: "/feɪl/",
    meaning: "to not succeed",
    simpleMeaning: "to not succeed",
    icon: "😔",
    forms: "fails, failing, failed, failure",
    example: "Don't be afraid to fail; it helps you learn.",
    phonemeHighlight: "fail"
  },
  {
    word: "Fair",
    ipa: "/feə(r)/",
    meaning: "treating everyone equally; (n) big fun event",
    simpleMeaning: "being nice to everyone",
    icon: "🎪",
    forms: "fairs, fairer, fairest, fairness",
    example: "The teacher is always fair to all students.",
    phonemeHighlight: "fair"
  },
  {
    word: "Fable",
    ipa: "/ˈfeɪbəl/",
    meaning: "a short story with a moral",
    simpleMeaning: "a teaching story",
    icon: "📖",
    forms: "fables, fabled",
    example: "We read a fable about a clever fox.",
    phonemeHighlight: "fa"
  },

  // Fl-words
  {
    word: "Flame",
    ipa: "/fleɪm/",
    meaning: "the hot, glowing part of fire",
    simpleMeaning: "bright hot fire",
    icon: "🔥",
    forms: "flames, flaming, flamed, flammable",
    example: "The candle flame flickered in the wind.",
    phonemeHighlight: "flame"
  },
  {
    word: "Flap",
    ipa: "/flæp/",
    meaning: "to move up and down like wings",
    simpleMeaning: "to move like wings",
    icon: "🦅",
    forms: "flaps, flapping, flapped",
    example: "The bird began to flap its wings.",
    phonemeHighlight: "flap"
  },
  {
    word: "Flat",
    ipa: "/flæt/",
    meaning: "having a smooth even surface",
    simpleMeaning: "smooth and even",
    icon: "📏",
    forms: "flatter, flattest, flatly, flatness",
    example: "The table has a flat surface.",
    phonemeHighlight: "flat"
  },
  {
    word: "Flaw",
    ipa: "/flɔː/",
    meaning: "a mistake or weakness",
    simpleMeaning: "a mistake or problem",
    icon: "❗",
    forms: "flaws, flawed",
    example: "The plan has one major flaw.",
    phonemeHighlight: "flaw"
  },
  {
    word: "Flight",
    ipa: "/flaɪt/",
    meaning: "a journey in an aircraft",
    simpleMeaning: "a trip on plane",
    icon: "✈️",
    forms: "flights, flighted, flighting",
    example: "Our flight to Paris leaves at noon.",
    phonemeHighlight: "flight"
  },
  {
    word: "Float",
    ipa: "/floʊt/",
    meaning: "to move on water without sinking",
    simpleMeaning: "to stay on water",
    icon: "🛟",
    forms: "floats, floating, floated, floatable",
    example: "The boat will float on the lake.",
    phonemeHighlight: "float"
  },
  {
    word: "Flock",
    ipa: "/flɒk/",
    meaning: "group of birds, sheep or goats",
    simpleMeaning: "a group of birds",
    icon: "🐦",
    forms: "flocks, flocking, flocked",
    example: "A flock of birds flew across the sky.",
    phonemeHighlight: "flock"
  },
  {
    word: "Flood",
    ipa: "/flʌd/",
    meaning: "overflow of large amounts of water",
    simpleMeaning: "too much water everywhere",
    icon: "🌊",
    forms: "floods, flooding, flooded, floodable",
    example: "Heavy rain caused a flood in the town.",
    phonemeHighlight: "flood"
  },
  {
    word: "Floor",
    ipa: "/flɔːr/",
    meaning: "ground surface of a room",
    simpleMeaning: "ground you walk on",
    icon: "🏠",
    forms: "floors, flooring, floored",
    example: "Please don't walk on the wet floor.",
    phonemeHighlight: "floor"
  },
  {
    word: "Flop",
    ipa: "/flɒp/",
    meaning: "a complete failure",
    simpleMeaning: "a big failure",
    icon: "💔",
    forms: "flops, flopping, flopped",
    example: "The movie was a total flop.",
    phonemeHighlight: "flop"
  },

  // Fo-words
  {
    word: "Folder",
    ipa: "/ˈfoʊldər/",
    meaning: "a file for keeping sheets of paper",
    simpleMeaning: "a paper holder",
    icon: "📁",
    forms: "folders",
    example: "Keep your homework in this folder.",
    phonemeHighlight: "fold"
  },
  {
    word: "Folk",
    ipa: "/foʊk/",
    meaning: "people in general or of a group",
    simpleMeaning: "people, a group",
    icon: "👨‍👩‍👧‍👦",
    forms: "folks, folksy, folklore",
    example: "The folk in this village are very friendly.",
    phonemeHighlight: "folk"
  },

  // Foo-words
  {
    word: "Food",
    ipa: "/fuːd/",
    meaning: "anything nutritious that people/animals eat",
    simpleMeaning: "things we eat",
    icon: "🍎",
    forms: "foods",
    example: "We need food and water to survive.",
    phonemeHighlight: "food"
  },
  {
    word: "Footpath",
    ipa: "/ˈfʊtpɑːθ/",
    meaning: "a path used mainly for walking",
    simpleMeaning: "a path for walking",
    icon: "🚶",
    forms: "footpaths",
    example: "Let's walk along the footpath in the park.",
    phonemeHighlight: "foot"
  },
  {
    word: "Forearm",
    ipa: "/ˈfɔːr.ɑːrm/",
    meaning: "part of the arm from elbow to wrist",
    simpleMeaning: "arm from elbow to wrist",
    icon: "💪",
    forms: "forearms",
    example: "He has a tattoo on his forearm.",
    phonemeHighlight: "fore"
  },
  {
    word: "Forehead",
    ipa: "/ˈfɔːrhed/",
    meaning: "upper face between eyebrows and hair",
    simpleMeaning: "top part of face",
    icon: "🧑",
    forms: "foreheads",
    example: "She wiped the sweat from her forehead.",
    phonemeHighlight: "fore"
  },

  // Fun/Fu-words
  {
    word: "Fun",
    ipa: "/fʌn/",
    meaning: "pleasure or enjoyment",
    simpleMeaning: "joy and play",
    icon: "🎉",
    forms: "funny, funniest, funnier",
    example: "We had so much fun at the party.",
    phonemeHighlight: "fun"
  },
  {
    word: "Fund",
    ipa: "/fʌnd/",
    meaning: "a sum of money",
    simpleMeaning: "some money saved",
    icon: "💰",
    forms: "funds, funding, funded",
    example: "They need to raise funds for the trip.",
    phonemeHighlight: "fund"
  },
  {
    word: "Fur",
    ipa: "/fɜːr/",
    meaning: "thick hair covering animals",
    simpleMeaning: "animal's thick hair",
    icon: "🐻",
    forms: "furs, furred, furry",
    example: "The cat's fur is soft and fluffy.",
    phonemeHighlight: "fur"
  },

  // Fr-words
  {
    word: "Friend",
    ipa: "/frɛnd/",
    meaning: "person one likes and enjoys being with",
    simpleMeaning: "someone you like",
    icon: "🤝",
    forms: "friends, friendly, friendliest",
    example: "She is my best friend from school.",
    phonemeHighlight: "friend"
  },
  {
    word: "Frill",
    ipa: "/frɪl/",
    meaning: "decoration with small folds of cloth",
    simpleMeaning: "fancy cloth decoration",
    icon: "🎀",
    forms: "frills, frilly",
    example: "The dress has frills around the collar.",
    phonemeHighlight: "frill"
  },
  {
    word: "Frock",
    ipa: "/frɒk/",
    meaning: "dress worn by girls",
    simpleMeaning: "a girl's dress",
    icon: "👗",
    forms: "frocks, frocking, frocked",
    example: "She wore a pretty pink frock to the party.",
    phonemeHighlight: "frock"
  },
  {
    word: "Front",
    ipa: "/frʌnt/",
    meaning: "the surface facing forward",
    simpleMeaning: "the part facing you",
    icon: "⬆️",
    forms: "fronts, fronting, fronted",
    example: "Please sit at the front of the class.",
    phonemeHighlight: "front"
  },

  // Fruit
  {
    word: "Fruit",
    ipa: "/fruːt/",
    meaning: "seed-bearing fleshy part of a plant",
    simpleMeaning: "sweet food from plants",
    icon: "🍓",
    forms: "fruits, fruity, fruited",
    example: "Apples and oranges are my favorite fruits.",
    phonemeHighlight: "fruit"
  },

  // Fry
  {
    word: "Fry",
    ipa: "/fraɪ/",
    meaning: "to cook in hot oil",
    simpleMeaning: "to cook in oil",
    icon: "🍳",
    forms: "fries, frying, fried",
    example: "Mom will fry some eggs for breakfast.",
    phonemeHighlight: "fry"
  },
  {
    word: "Fuel",
    ipa: "/fjuːəl/",
    meaning: "substance used for heat/energy",
    simpleMeaning: "stuff that makes energy",
    icon: "⛽",
    forms: "fuels, fueling, fueled",
    example: "Cars need fuel to run.",
    phonemeHighlight: "fuel"
  },
  {
    word: "Few",
    ipa: "/fjuː/",
    meaning: "a small number",
    simpleMeaning: "not many",
    icon: "🔢",
    forms: "fewer, fewest, fewness",
    example: "Only a few people came to the meeting.",
    phonemeHighlight: "few"
  },
  {
    word: "Fence",
    ipa: "/fɛns/",
    meaning: "a wall that encloses an area",
    simpleMeaning: "a wall around area",
    icon: "🚧",
    forms: "fences, fencing, fenced",
    example: "There's a wooden fence around our garden.",
    phonemeHighlight: "fence"
  },
  {
    word: "Feet",
    ipa: "/fiːt/",
    meaning: "plural of foot",
    simpleMeaning: "more than one foot",
    icon: "👣",
    forms: "—",
    example: "I can stand on my own two feet.",
    phonemeHighlight: "feet"
  },
  {
    word: "Feel",
    ipa: "/fiːl/",
    meaning: "to touch/experience emotion",
    simpleMeaning: "to touch or sense",
    icon: "✋",
    forms: "feels, feeling, felt",
    example: "I feel happy when I play with friends.",
    phonemeHighlight: "feel"
  },
  {
    word: "Feed",
    ipa: "/fiːd/",
    meaning: "to give food",
    simpleMeaning: "to give food",
    icon: "🍽️",
    forms: "feeds, feeding, fed",
    example: "Don't forget to feed the dog.",
    phonemeHighlight: "feed"
  },
  {
    word: "Feast",
    ipa: "/fiːst/",
    meaning: "a large special meal",
    simpleMeaning: "a big special meal",
    icon: "🍗",
    forms: "feasts, feasting, feasted",
    example: "We had a feast on Thanksgiving Day.",
    phonemeHighlight: "feast"
  },
  {
    word: "Fever",
    ipa: "/ˈfiːvər/",
    meaning: "illness with high temperature",
    simpleMeaning: "being very hot sick",
    icon: "🤒",
    forms: "fevers, feverish, feverishly",
    example: "He stayed home because he had a fever.",
    phonemeHighlight: "fev"
  },
  {
    word: "Fig",
    ipa: "/fɪɡ/",
    meaning: "soft fruit with seeds",
    simpleMeaning: "a sweet soft fruit",
    icon: "🫐",
    forms: "figs",
    example: "Fresh figs are sweet and delicious.",
    phonemeHighlight: "fig"
  },
  {
    word: "Fight",
    ipa: "/faɪt/",
    meaning: "attack between individuals/groups",
    simpleMeaning: "when people hurt each other",
    icon: "🥊",
    forms: "fights, fighting, fought, fighter",
    example: "The two boys had a fight over a toy.",
    phonemeHighlight: "fight"
  },
  // A-words
  { word: "Action", ipa: "/ˈækʃən/", meaning: "a movement; a process of doing something", simpleMeaning: "doing something", icon: "⚡", forms: "actions, actioning, actioned", example: "Taking action is better than waiting.", phonemeHighlight: "act" },
  { word: "Adapt", ipa: "/əˈdæpt/", meaning: "to adjust to fit", simpleMeaning: "to change to fit", icon: "🔄", forms: "adapting, adapted, adaptive, adaptation", example: "Animals adapt to their environment.", phonemeHighlight: "dapt" },
  { word: "Add", ipa: "/æd/", meaning: "to sum up; to include", simpleMeaning: "to put together", icon: "➕", forms: "adds, adding, added, addition", example: "Add two and three to get five.", phonemeHighlight: "add" },
  { word: "Admit", ipa: "/ədˈmɪt/", meaning: "to let in; to accept", simpleMeaning: "to say it's true", icon: "✅", forms: "admits, admitting, admitted, admission", example: "I must admit I was wrong.", phonemeHighlight: "mit" },
  { word: "Afraid", ipa: "/əˈfreɪd/", meaning: "being scared", simpleMeaning: "feeling scared", icon: "😨", forms: "—", example: "Don't be afraid of the dark.", phonemeHighlight: "fraid" },
  { word: "After", ipa: "/ˈæftər/", meaning: "later", simpleMeaning: "coming next", icon: "⏭️", forms: "afterward, afterwards", example: "We'll play after dinner.", phonemeHighlight: "af" },
  { word: "Age", ipa: "/eɪdʒ/", meaning: "the number of years lived; lifetime", simpleMeaning: "how old you are", icon: "🎂", forms: "ages, ageing/aging, aged", example: "What is your age?", phonemeHighlight: "age" },
  { word: "Ago", ipa: "/əˈɡoʊ/", meaning: "in the past", simpleMeaning: "time before now", icon: "⏰", forms: "—", example: "That happened long ago.", phonemeHighlight: "go" },
  { word: "Aide", ipa: "/eɪd/", meaning: "a person or thing that helps", simpleMeaning: "a helper", icon: "🤝", forms: "aides", example: "The teacher's aide helps in class.", phonemeHighlight: "aide" },
  { word: "Aim", ipa: "/eɪm/", meaning: "goal or target", simpleMeaning: "what you try for", icon: "🎯", forms: "aims, aiming, aimed", example: "Take aim before you throw.", phonemeHighlight: "aim" },
  { word: "Air", ipa: "/eə(r)/", meaning: "a mixture of gases", simpleMeaning: "what we breathe", icon: "💨", forms: "—", example: "Fresh air is good for you.", phonemeHighlight: "air" },
  { word: "Alike", ipa: "/əˈlaɪk/", meaning: "similar or just the same", simpleMeaning: "the same", icon: "👯", forms: "—", example: "The twins look alike.", phonemeHighlight: "like" },
  { word: "Allow", ipa: "/əˈlaʊ/", meaning: "to let or permit", simpleMeaning: "to let happen", icon: "✓", forms: "allows, allowing, allowed, allowance", example: "Mom will allow us to play.", phonemeHighlight: "low" },
  { word: "Alone", ipa: "/əˈləʊn/", meaning: "without others", simpleMeaning: "by yourself", icon: "🚶", forms: "—", example: "I like to read alone.", phonemeHighlight: "lone" },
  { word: "Along", ipa: "/əˈlɒŋ/", meaning: "together with someone", simpleMeaning: "going with", icon: "➡️", forms: "—", example: "Come along with us!", phonemeHighlight: "long" },
  { word: "Angry", ipa: "/ˈæŋɡri/", meaning: "being furious", simpleMeaning: "very mad", icon: "😠", forms: "angrier, angriest, angrily", example: "She was angry about the mess.", phonemeHighlight: "ang" },
  { word: "Ankle", ipa: "/ˈæŋkəl/", meaning: "the joint between the foot and the leg", simpleMeaning: "joint above your foot", icon: "🦶", forms: "ankles, ankled, ankling", example: "I hurt my ankle playing soccer.", phonemeHighlight: "ank" },
  { word: "Ant", ipa: "/ænt/", meaning: "a kind of small insect that lives in a large group", simpleMeaning: "tiny bug", icon: "🐜", forms: "ants", example: "Ants work together as a team.", phonemeHighlight: "ant" },
  { word: "Any", ipa: "/ˈeni/", meaning: "one or the other", simpleMeaning: "one of them", icon: "❓", forms: "—", example: "Pick any card you want.", phonemeHighlight: "any" },
  { word: "Anyone", ipa: "/ˈɛniwʌn/", meaning: "any single person", simpleMeaning: "any person", icon: "👤", forms: "—", example: "Can anyone help me?", phonemeHighlight: "any" },
  { word: "Ape", ipa: "/eɪp/", meaning: "a large monkey with no tail", simpleMeaning: "big monkey", icon: "🦍", forms: "apes", example: "The ape swung from tree to tree.", phonemeHighlight: "ape" },
  { word: "Apple", ipa: "/ˈæpəl/", meaning: "a firm, round fruit, usually red or green", simpleMeaning: "round crunchy fruit", icon: "🍎", forms: "apples", example: "An apple a day keeps the doctor away.", phonemeHighlight: "app" },
  { word: "Arch", ipa: "/ɑːtʃ/", meaning: "a curved structure", simpleMeaning: "curved shape", icon: "🌉", forms: "arches, arching, arched", example: "The arch over the door is beautiful.", phonemeHighlight: "arch" },
  { word: "Area", ipa: "/ˈeəriə/", meaning: "a region or a piece of land", simpleMeaning: "a space or place", icon: "📍", forms: "areas", example: "This area is for playing.", phonemeHighlight: "air" },
  { word: "Argue", ipa: "/ˈɑːɡjuː/", meaning: "to disagree and discuss", simpleMeaning: "to fight with words", icon: "🗣️", forms: "argues, arguing, argued, argument", example: "Don't argue with your sister.", phonemeHighlight: "ar" },
  { word: "Arm", ipa: "/ɑːm/", meaning: "a part of the human body from shoulder to hand", simpleMeaning: "body part with hand", icon: "💪", forms: "arms, armed", example: "Raise your arm if you know the answer.", phonemeHighlight: "arm" },
  { word: "Army", ipa: "/ˈɑːmi/", meaning: "a trained group of people who protect a country", simpleMeaning: "soldiers together", icon: "🪖", forms: "armies", example: "The army protects our country.", phonemeHighlight: "ar" },
  { word: "Aroma", ipa: "/əˈrəʊmə/", meaning: "a pleasant smell", simpleMeaning: "nice smell", icon: "👃", forms: "aromas, aromatic", example: "The aroma of cookies filled the kitchen.", phonemeHighlight: "ro" },
  { word: "Around", ipa: "/əˈraʊnd/", meaning: "nearby or surrounding something", simpleMeaning: "all around", icon: "🔄", forms: "—", example: "Look around before you cross the street.", phonemeHighlight: "round" },
  { word: "Art", ipa: "/ɑːt/", meaning: "the making of objects/pictures", simpleMeaning: "creative work", icon: "🎨", forms: "—", example: "I love to make art in school.", phonemeHighlight: "art" },
  { word: "Ask", ipa: "/ɑːsk/", meaning: "to question", simpleMeaning: "to question", icon: "❓", forms: "asks, asking, asked", example: "Ask your teacher if you don't understand.", phonemeHighlight: "ask" },
  { word: "Audio", ipa: "/ˈɔːdiəʊ/", meaning: "related to sound or its playback", simpleMeaning: "sound", icon: "🔊", forms: "—", example: "Turn up the audio so we can hear.", phonemeHighlight: "au" },
  { word: "Aunt", ipa: "/ɑːnt/", meaning: "a sister of one's father or mother", simpleMeaning: "parent's sister", icon: "👩", forms: "aunts", example: "My aunt is coming to visit.", phonemeHighlight: "aunt" },
  { word: "Await", ipa: "/əˈweɪt/", meaning: "to wait for someone or something", simpleMeaning: "to wait for", icon: "⏳", forms: "awaits, awaiting, awaited", example: "We await your arrival.", phonemeHighlight: "wait" },
  { word: "Awake", ipa: "/əˈweɪk/", meaning: "to wake from sleep; not asleep", simpleMeaning: "not sleeping", icon: "👀", forms: "awakes, awoke/awakened, awoken", example: "I am wide awake now.", phonemeHighlight: "wake" },
  { word: "Award", ipa: "/əˈwɔːd/", meaning: "a prize or present", simpleMeaning: "a prize", icon: "🏆", forms: "awards, awarding, awarded", example: "She won an award for her painting.", phonemeHighlight: "ward" },
  { word: "Away", ipa: "/əˈweɪ/", meaning: "somewhere else; at a distance", simpleMeaning: "not here", icon: "🚀", forms: "—", example: "The birds flew away.", phonemeHighlight: "way" },
  // B-words
  { word: "Back", ipa: "/bæk/", meaning: "behind; the other side of something", simpleMeaning: "the rear side", icon: "↩️", forms: "backs, backing, backed", example: "Go back to your seat.", phonemeHighlight: "back" },
  { word: "Bark", ipa: "/bɑːk/", meaning: "the sound made by a dog", simpleMeaning: "dog's sound", icon: "🐕", forms: "barks, barking, barked", example: "The dog will bark at strangers.", phonemeHighlight: "bark" },
  { word: "Base", ipa: "/beɪs/", meaning: "the bottom part", simpleMeaning: "the bottom", icon: "⬇️", forms: "bases, based, baser, basest", example: "The base of the mountain is wide.", phonemeHighlight: "base" },
  { word: "Bask", ipa: "/bɑːsk/", meaning: "to sit or lie in the warm sun and relax", simpleMeaning: "to enjoy warmth", icon: "☀️", forms: "basks, basking, basked", example: "The cat likes to bask in the sun.", phonemeHighlight: "bask" },
  { word: "Bathe", ipa: "/beɪð/", meaning: "to wash one's body", simpleMeaning: "to take a bath", icon: "🛁", forms: "bathes, bathing, bathed", example: "I bathe every evening.", phonemeHighlight: "bathe" },
  { word: "Bay", ipa: "/beɪ/", meaning: "a part of a sea that cuts into the shore", simpleMeaning: "water near land", icon: "🏖️", forms: "bays, baying, bayed", example: "We sailed into the bay.", phonemeHighlight: "bay" },
  { word: "Bee", ipa: "/biː/", meaning: "a flying insect with a hairy body", simpleMeaning: "buzzing insect", icon: "🐝", forms: "bees", example: "The bee collects nectar from flowers.", phonemeHighlight: "bee" },
  { word: "Been", ipa: "/biːn, bɪn/", meaning: "travelled/visited", simpleMeaning: "went before", icon: "✈️", forms: "—", example: "I have been to the zoo before.", phonemeHighlight: "been" },
  { word: "Beg", ipa: "/beɡ/", meaning: "to request or plead", simpleMeaning: "to ask strongly", icon: "🙏", forms: "begs, begging, begged, beggar", example: "I beg you to help me.", phonemeHighlight: "beg" },
  { word: "Belt", ipa: "/belt/", meaning: "a strap one wears around the waist", simpleMeaning: "waist strap", icon: "👔", forms: "belts, belting, belted", example: "Wear a belt to keep your pants up.", phonemeHighlight: "belt" },
  { word: "Bench", ipa: "/bentʃ/", meaning: "a long seat", simpleMeaning: "long seat", icon: "🪑", forms: "benches, benched", example: "We sat on the bench in the park.", phonemeHighlight: "bench" },
  { word: "Better", ipa: "/ˈbetə/", meaning: "improved", simpleMeaning: "more good", icon: "⬆️", forms: "better, best; betters, bettering, bettered", example: "I feel better today.", phonemeHighlight: "bet" },
  { word: "Bike", ipa: "/baɪk/", meaning: "a vehicle with two wheels", simpleMeaning: "two-wheel ride", icon: "🚲", forms: "bikes, biking, biked, biker", example: "I ride my bike to school.", phonemeHighlight: "bike" },
  { word: "Bin", ipa: "/bɪn/", meaning: "a container used to store or to dump", simpleMeaning: "trash can", icon: "🗑️", forms: "bins, binning, binned", example: "Put the trash in the bin.", phonemeHighlight: "bin" },
  { word: "Bird", ipa: "/bɜːd/", meaning: "an egg-laying animal with wings, feathers and a beak", simpleMeaning: "flying animal", icon: "🐦", forms: "birds", example: "The bird sings in the morning.", phonemeHighlight: "bird" },
  { word: "Bit", ipa: "/bɪt/", meaning: "a small piece", simpleMeaning: "small amount", icon: "🔸", forms: "bits", example: "Can I have a bit of cake?", phonemeHighlight: "bit" },
  { word: "Blade", ipa: "/bleɪd/", meaning: "a flat, sharp cutting tool", simpleMeaning: "sharp edge", icon: "🔪", forms: "blades, blading, bladed", example: "The blade of the knife is sharp.", phonemeHighlight: "blade" },
  { word: "Blame", ipa: "/bleɪm/", meaning: "to throw fault on someone or something", simpleMeaning: "to say it's your fault", icon: "👉", forms: "blames, blaming, blamed, blameable", example: "Don't blame me for the mistake.", phonemeHighlight: "blame" },
  { word: "Bleat", ipa: "/bliːt/", meaning: "the sound of a sheep or goat", simpleMeaning: "sheep's sound", icon: "🐑", forms: "bleats, bleating, bleated", example: "The sheep bleat in the field.", phonemeHighlight: "bleat" },
  { word: "Bless", ipa: "/bles/", meaning: "wish with prayers; make something sacred/holy", simpleMeaning: "to wish good things", icon: "🙏", forms: "blesses, blessing, blessed, blest", example: "Bless you when you sneeze.", phonemeHighlight: "bless" },
  { word: "Blood", ipa: "/blʌd/", meaning: "the red liquid that flows through the body", simpleMeaning: "red body liquid", icon: "🩸", forms: "—", example: "Blood carries oxygen in your body.", phonemeHighlight: "blood" },
  { word: "Blow", ipa: "/bləʊ/", meaning: "to force air out of one's mouth", simpleMeaning: "to push air out", icon: "💨", forms: "blows, blowing, blew, blown", example: "Blow out the candles on your cake.", phonemeHighlight: "blow" },
  { word: "Blue", ipa: "/bluː/", meaning: "the colour of the clear sky", simpleMeaning: "sky color", icon: "🔵", forms: "bluer, bluest", example: "The sky is blue today.", phonemeHighlight: "blue" },
  { word: "Blurred", ipa: "/blɜːd/", meaning: "being unclear or dim", simpleMeaning: "not clear", icon: "😵‍💫", forms: "blur, blurs, blurring, blurred", example: "My vision was blurred without glasses.", phonemeHighlight: "blur" },
  { word: "Bow", ipa: "/baʊ/", meaning: "to bend your body respectfully", simpleMeaning: "to bend down", icon: "🙇", forms: "bows, bowing, bowed", example: "Bow to show respect.", phonemeHighlight: "bow" },
  { word: "Bray", ipa: "/breɪ/", meaning: "a loud, unpleasant noise like a donkey", simpleMeaning: "donkey's sound", icon: "🫏", forms: "brays, braying, brayed", example: "The donkey will bray loudly.", phonemeHighlight: "bray" },
  { word: "Break", ipa: "/breɪk/", meaning: "to split into two or more pieces", simpleMeaning: "to crack apart", icon: "💥", forms: "breaks, breaking, broke, broken, breakable", example: "Don't break the glass.", phonemeHighlight: "break" },
  { word: "Bud", ipa: "/bʌd/", meaning: "an unopened leaf or flower", simpleMeaning: "baby flower", icon: "🌱", forms: "buds, budding, budded", example: "The rose bud will bloom soon.", phonemeHighlight: "bud" },
  { word: "Build", ipa: "/bɪld/", meaning: "to construct or make", simpleMeaning: "to make something", icon: "🏗️", forms: "builds, building, built, builder", example: "We will build a sandcastle.", phonemeHighlight: "build" },
  { word: "Bush", ipa: "/bʊʃ/", meaning: "a plant with many short branches and a woody stem", simpleMeaning: "small plant", icon: "🌳", forms: "bushes, bushy", example: "The bird hid in the bush.", phonemeHighlight: "bush" },
  // C-words
  { word: "Cage", ipa: "/keɪdʒ/", meaning: "a structure where animals/birds are kept", simpleMeaning: "animal box", icon: "🦜", forms: "cages, caged, caging", example: "The bird is in its cage.", phonemeHighlight: "cage" },
  { word: "Cake", ipa: "/keɪk/", meaning: "a sweet snack baked usually in an oven", simpleMeaning: "sweet baked treat", icon: "🎂", forms: "cakes", example: "We ate cake at the party.", phonemeHighlight: "cake" },
  { word: "Calf", ipa: "/kɑːf/", meaning: "a young one of a cow or elephant", simpleMeaning: "baby cow", icon: "🐄", forms: "calves", example: "The calf stays close to its mother.", phonemeHighlight: "calf" },
  { word: "Call", ipa: "/kɔːl/", meaning: "to contact by phone or in person", simpleMeaning: "to phone someone", icon: "📞", forms: "calls, calling, called, caller", example: "Call me when you get home.", phonemeHighlight: "call" },
  { word: "Calm", ipa: "/kɑːm/", meaning: "being quiet or peaceful", simpleMeaning: "not upset", icon: "😌", forms: "calmer, calmest, calmly, calmness", example: "Stay calm during the storm.", phonemeHighlight: "calm" },
  { word: "Camp", ipa: "/kæmp/", meaning: "a place where people stay a short time", simpleMeaning: "outdoor sleeping place", icon: "⛺", forms: "camps, camping, camped", example: "We went to camp in the woods.", phonemeHighlight: "camp" },
  { word: "Card", ipa: "/kɑːd/", meaning: "a small thick piece of paper or plastic", simpleMeaning: "stiff paper", icon: "🃏", forms: "cards", example: "I got a birthday card.", phonemeHighlight: "card" },
  { word: "Care", ipa: "/keə/", meaning: "to look after someone or something", simpleMeaning: "to look after", icon: "❤️", forms: "cares, caring, cared", example: "I care about my friends.", phonemeHighlight: "care" },
  { word: "Cash", ipa: "/kæʃ/", meaning: "money in notes and coins", simpleMeaning: "paper money", icon: "💵", forms: "—", example: "I need some cash to buy lunch.", phonemeHighlight: "cash" },
  { word: "Cave", ipa: "/keɪv/", meaning: "a big hole or passage in rock", simpleMeaning: "hole in mountain", icon: "🏔️", forms: "caves", example: "The bear lives in a cave.", phonemeHighlight: "cave" },
  { word: "Chair", ipa: "/tʃeə/", meaning: "a seat", simpleMeaning: "something to sit on", icon: "🪑", forms: "chairs, chaired", example: "Sit in your chair please.", phonemeHighlight: "chair" },
  { word: "Chalk", ipa: "/tʃɔːk/", meaning: "a soft, white stone used for writing on a blackboard", simpleMeaning: "board writing stick", icon: "✏️", forms: "chalks, chalking, chalked", example: "Write on the board with chalk.", phonemeHighlight: "chalk" },
  { word: "Chase", ipa: "/tʃeɪs/", meaning: "to run after someone or something", simpleMeaning: "to run after", icon: "🏃", forms: "chases, chasing, chased", example: "The cat will chase the mouse.", phonemeHighlight: "chase" },
  { word: "Chat", ipa: "/tʃæt/", meaning: "to talk in a friendly way", simpleMeaning: "to talk nicely", icon: "💬", forms: "chats, chatting, chatted", example: "Let's chat about your day.", phonemeHighlight: "chat" },
  { word: "Check", ipa: "/tʃek/", meaning: "to make sure that something is correct", simpleMeaning: "to look and see", icon: "✓", forms: "checks, checking, checked", example: "Check your answers before submitting.", phonemeHighlight: "check" },
  { word: "Cheer", ipa: "/tʃɪə/", meaning: "to shout in joy or in support", simpleMeaning: "to yell happily", icon: "📣", forms: "cheers, cheering, cheered", example: "Let's cheer for our team!", phonemeHighlight: "cheer" },
  { word: "Cheese", ipa: "/tʃiːz/", meaning: "a solid milk product", simpleMeaning: "food made from milk", icon: "🧀", forms: "cheeses", example: "I love cheese on my pizza.", phonemeHighlight: "cheese" },
  { word: "Chew", ipa: "/tʃuː/", meaning: "to bite/crush food with one's teeth", simpleMeaning: "to bite food", icon: "😋", forms: "chews, chewing, chewed", example: "Chew your food slowly.", phonemeHighlight: "chew" },
  { word: "Child", ipa: "/tʃaɪld/", meaning: "a baby or a kid", simpleMeaning: "young person", icon: "👶", forms: "children, childish, childlike", example: "Every child deserves love.", phonemeHighlight: "child" },
  { word: "Chin", ipa: "/tʃɪn/", meaning: "the lowermost part of the face", simpleMeaning: "bottom of face", icon: "😊", forms: "chins", example: "Wipe your chin after eating.", phonemeHighlight: "chin" },
  { word: "Chips", ipa: "/tʃɪps/", meaning: "small, thin pieces of something", simpleMeaning: "thin crispy slices", icon: "🍟", forms: "chips, chipping, chipped", example: "I like potato chips as a snack.", phonemeHighlight: "chips" },
  { word: "Chubby", ipa: "/ˈtʃʌbi/", meaning: "being fat in a pleasant way", simpleMeaning: "pleasantly round", icon: "🤗", forms: "chubbier, chubbiest, chubbily, chubbiness", example: "The baby has chubby cheeks.", phonemeHighlight: "chub" },
  { word: "City", ipa: "/ˈsɪti/", meaning: "a large, well-connected town", simpleMeaning: "big town", icon: "🏙️", forms: "cities", example: "I live in the city.", phonemeHighlight: "cit" },
  { word: "Clap", ipa: "/klæp/", meaning: "to hit one's palms together many times", simpleMeaning: "to hit hands together", icon: "👏", forms: "claps, clapping, clapped", example: "Clap your hands if you're happy!", phonemeHighlight: "clap" },
  { word: "Clash", ipa: "/klæʃ/", meaning: "a fight or an argument", simpleMeaning: "a big fight", icon: "⚔️", forms: "clashes, clashing, clashed", example: "The two armies will clash tomorrow.", phonemeHighlight: "clash" },
  { word: "Claw", ipa: "/klɔː/", meaning: "a bird's sharp, curved nail", simpleMeaning: "sharp animal nail", icon: "🦅", forms: "claws, clawing, clawed", example: "The cat has sharp claws.", phonemeHighlight: "claw" },
  { word: "Clay", ipa: "/kleɪ/", meaning: "a type of sticky soil used for pots/bricks", simpleMeaning: "soft moldable dirt", icon: "🏺", forms: "clays", example: "We made pots from clay.", phonemeHighlight: "clay" },
  // D-words
  { word: "Daily", ipa: "/ˈdeɪli/", meaning: "every day", simpleMeaning: "each day", icon: "📅", forms: "dailies", example: "I read the daily newspaper.", phonemeHighlight: "day" },
  { word: "Dame", ipa: "/deɪm/", meaning: "a woman of high social rank", simpleMeaning: "important lady", icon: "👸", forms: "dames", example: "The dame lived in a grand house.", phonemeHighlight: "dame" },
  { word: "Date", ipa: "/deɪt/", meaning: "a particular day in a month", simpleMeaning: "day of the month", icon: "📆", forms: "dates", example: "What is today's date?", phonemeHighlight: "date" },
  { word: "Day", ipa: "/deɪ/", meaning: "a period of 24 hours", simpleMeaning: "one full day", icon: "☀️", forms: "days, daytime", example: "Have a great day!", phonemeHighlight: "day" },
  { word: "Daybreak", ipa: "/ˈdeɪbreɪk/", meaning: "the beginning of a day", simpleMeaning: "when day starts", icon: "🌅", forms: "daybreaks", example: "We left at daybreak.", phonemeHighlight: "day" },
  { word: "Deaf", ipa: "/def/", meaning: "not being able to hear", simpleMeaning: "can't hear", icon: "👂", forms: "deafer, deafest, deafly, deafness", example: "Some deaf people use sign language.", phonemeHighlight: "deaf" },
  { word: "Deep", ipa: "/diːp/", meaning: "being far down from the surface to the bottom", simpleMeaning: "very far down", icon: "🌊", forms: "deeper, deepest, deeply, deepness", example: "The ocean is very deep.", phonemeHighlight: "deep" },
  { word: "Deer", ipa: "/dɪə/", meaning: "a wild grass-eating animal", simpleMeaning: "forest animal with horns", icon: "🦌", forms: "deer", example: "We saw a deer in the forest.", phonemeHighlight: "deer" },
  { word: "Den", ipa: "/den/", meaning: "the hidden home of lions or other wild animals", simpleMeaning: "animal's home", icon: "🦁", forms: "dens", example: "The lion sleeps in its den.", phonemeHighlight: "den" },
  { word: "Dental", ipa: "/ˈdentl/", meaning: "relating to teeth", simpleMeaning: "about teeth", icon: "🦷", forms: "dentals, dentistry", example: "I went for a dental checkup.", phonemeHighlight: "dent" },
  { word: "Deny", ipa: "/dɪˈnaɪ/", meaning: "to not accept", simpleMeaning: "to say no", icon: "🚫", forms: "denies, denying, denied", example: "Don't deny what you did.", phonemeHighlight: "ny" },
  { word: "Desk", ipa: "/desk/", meaning: "a work table", simpleMeaning: "table for work", icon: "🪑", forms: "desks", example: "My homework is on my desk.", phonemeHighlight: "desk" },
  { word: "Dew", ipa: "/djuː/", meaning: "water droplets", simpleMeaning: "morning water drops", icon: "💧", forms: "dews", example: "Dew covers the grass in the morning.", phonemeHighlight: "dew" },
  { word: "Dial", ipa: "/ˈdaɪəl/", meaning: "call a telephone number", simpleMeaning: "to call a number", icon: "☎️", forms: "dials, dialling/dialing, dialled/dialed, dialler", example: "Dial my number to reach me.", phonemeHighlight: "dial" },
  { word: "Dice", ipa: "/daɪs/", meaning: "small cube(s) used for games", simpleMeaning: "game cubes", icon: "🎲", forms: "dice, dicing, diced", example: "Roll the dice to play the game.", phonemeHighlight: "dice" },
  { word: "Dim", ipa: "/dɪm/", meaning: "being less bright", simpleMeaning: "not very bright", icon: "🔅", forms: "dimmer, dimmest, dimly, dimness", example: "The light is too dim to read.", phonemeHighlight: "dim" },
  { word: "Dine", ipa: "/daɪn/", meaning: "to eat", simpleMeaning: "to have a meal", icon: "🍽️", forms: "dines, dining, dined, diner", example: "We will dine at the restaurant.", phonemeHighlight: "dine" },
  { word: "Dip", ipa: "/dɪp/", meaning: "to wet in a liquid", simpleMeaning: "to put in liquid", icon: "🫕", forms: "dips, dipping, dipped", example: "Dip the cookie in milk.", phonemeHighlight: "dip" },
  { word: "Dirt", ipa: "/dɜːt/", meaning: "the dust/soil that makes something unclean", simpleMeaning: "mud and dust", icon: "🟤", forms: "dirty", example: "Wash the dirt off your hands.", phonemeHighlight: "dirt" },
  { word: "Dirty", ipa: "/ˈdɜːti/", meaning: "not being clean", simpleMeaning: "not clean", icon: "🧼", forms: "dirtier, dirtiest, dirtiness, dirtily", example: "Your shoes are dirty.", phonemeHighlight: "dirt" },
  { word: "Dish", ipa: "/dɪʃ/", meaning: "food prepared in a particular way; a flat-bottomed container", simpleMeaning: "a plate or meal", icon: "🍽️", forms: "dishes, dishing, dished", example: "This dish is delicious!", phonemeHighlight: "dish" },
  { word: "Disk", ipa: "/dɪsk/", meaning: "a thin, circular object", simpleMeaning: "round flat thing", icon: "💿", forms: "disks", example: "Save the file on a disk.", phonemeHighlight: "disk" },
  { word: "Dislike", ipa: "/dɪsˈlaɪk/", meaning: "to not like something", simpleMeaning: "to not like", icon: "👎", forms: "dislikes, disliking, disliked", example: "I dislike cold weather.", phonemeHighlight: "like" },
  { word: "Dismiss", ipa: "/dɪsˈmɪs/", meaning: "to ask someone to leave", simpleMeaning: "to send away", icon: "👋", forms: "dismisses, dismissing, dismissed, dismissal", example: "The teacher will dismiss the class.", phonemeHighlight: "miss" },
  { word: "Display", ipa: "/dɪˈspleɪ/", meaning: "to show or exhibit", simpleMeaning: "to show", icon: "🖼️", forms: "displays, displaying, displayed", example: "Display your artwork on the wall.", phonemeHighlight: "play" },
  { word: "Does", ipa: "/dʌz/", meaning: "word form from 'do'", simpleMeaning: "form of do", icon: "✅", forms: "do, did, done", example: "She does her homework every day.", phonemeHighlight: "does" },
  { word: "Doll", ipa: "/dɒl/", meaning: "a child's toy", simpleMeaning: "toy person", icon: "🪆", forms: "dolls", example: "She plays with her doll.", phonemeHighlight: "doll" },
  { word: "Door", ipa: "/dɔː/", meaning: "a solid, flat object that opens/closes an entry", simpleMeaning: "entry cover", icon: "🚪", forms: "doors", example: "Please close the door.", phonemeHighlight: "door" },
  { word: "Dose", ipa: "/dəʊs/", meaning: "an amount of medicine", simpleMeaning: "medicine amount", icon: "💊", forms: "doses, dosing, dosed", example: "Take one dose of medicine.", phonemeHighlight: "dose" },
  { word: "Double", ipa: "/ˈdʌbəl/", meaning: "being twice the amount", simpleMeaning: "two times", icon: "✌️", forms: "doubles, doubling, doubled", example: "Double the recipe to make more.", phonemeHighlight: "dub" },
  { word: "Doubt", ipa: "/daʊt/", meaning: "a feeling of not being sure about something", simpleMeaning: "not being sure", icon: "🤔", forms: "doubts, doubting, doubted, doubtless", example: "I have no doubt you can do it.", phonemeHighlight: "doubt" },
  { word: "Down", ipa: "/daʊn/", meaning: "at a lower level", simpleMeaning: "toward the ground", icon: "⬇️", forms: "downs, downing, downed", example: "Come down from the tree.", phonemeHighlight: "down" },
  { word: "Downfall", ipa: "/ˈdaʊnfɔːl/", meaning: "sudden loss of power, money or health", simpleMeaning: "sudden loss", icon: "📉", forms: "downfalls", example: "Greed was his downfall.", phonemeHighlight: "fall" },
  { word: "Download", ipa: "/ˌdaʊnˈləʊd/", meaning: "to receive/copy data onto one's computer", simpleMeaning: "to save from internet", icon: "⬇️", forms: "downloads, downloading, downloaded, downloadable", example: "Download the app from the store.", phonemeHighlight: "load" },
  { word: "Doze", ipa: "/dəʊz/", meaning: "to take a short nap", simpleMeaning: "to sleep briefly", icon: "😴", forms: "dozes, dozing, dozed, dozer", example: "Grandpa likes to doze in his chair.", phonemeHighlight: "doze" },
  { word: "Dozen", ipa: "/ˈdʌz.ən/", meaning: "a set of 12", simpleMeaning: "twelve things", icon: "🥚", forms: "dozens, dozenth", example: "I bought a dozen eggs.", phonemeHighlight: "doz" },
  { word: "Drain", ipa: "/dreɪn/", meaning: "a pipe that lets out water or liquid waste", simpleMeaning: "water escape pipe", icon: "🚰", forms: "drains, draining, drained, drainage", example: "The water goes down the drain.", phonemeHighlight: "drain" },
  { word: "Drama", ipa: "/ˈdrɑː.mə/", meaning: "a play on a stage", simpleMeaning: "a stage play", icon: "🎭", forms: "dramas, dramatic", example: "We watched a drama at the theater.", phonemeHighlight: "dra" },
  { word: "Draw", ipa: "/drɔː/", meaning: "to make pictures", simpleMeaning: "to make pictures", icon: "✏️", forms: "draws, drawing, drew, drawn, drawable", example: "I like to draw animals.", phonemeHighlight: "draw" },
  { word: "Dream", ipa: "/driːm/", meaning: "events/images seen while sleeping", simpleMeaning: "sleep pictures", icon: "💭", forms: "dreams, dreaming, dreamed, dreamt", example: "I had a strange dream last night.", phonemeHighlight: "dream" },
  { word: "Drink", ipa: "/drɪŋk/", meaning: "to swallow a liquid", simpleMeaning: "to swallow liquid", icon: "🥤", forms: "drinkable, drinks, drinking, drank, drunk", example: "Drink plenty of water.", phonemeHighlight: "drink" },
  { word: "Drive", ipa: "/draɪv/", meaning: "to control and move a vehicle", simpleMeaning: "to move a car", icon: "🚗", forms: "drives, driving, drove, driven", example: "Dad will drive us to school.", phonemeHighlight: "drive" },
  { word: "Drop", ipa: "/drɒp/", meaning: "to let something fall", simpleMeaning: "to let fall", icon: "💧", forms: "drops, dropping, dropped", example: "Don't drop the glass!", phonemeHighlight: "drop" },
  { word: "Drown", ipa: "/draʊn/", meaning: "to sink in water", simpleMeaning: "to die in water", icon: "🌊", forms: "drowns, drowning, drowned, drowner", example: "Learn to swim so you don't drown.", phonemeHighlight: "drown" },
  { word: "Drug", ipa: "/drʌɡ/", meaning: "a medicine", simpleMeaning: "medicine", icon: "💊", forms: "drugs, drugging, drugged", example: "The drug helped her feel better.", phonemeHighlight: "drug" },
  { word: "Drum", ipa: "/drʌm/", meaning: "a musical instrument", simpleMeaning: "round music maker", icon: "🥁", forms: "drums, drumming, drummed, drummer", example: "He plays the drum in the band.", phonemeHighlight: "drum" },
  { word: "Due", ipa: "/djuː/", meaning: "expected at a certain time", simpleMeaning: "should arrive soon", icon: "⏰", forms: "dues", example: "The homework is due tomorrow.", phonemeHighlight: "due" },
  { word: "Dull", ipa: "/dʌl/", meaning: "being boring or not interesting", simpleMeaning: "not exciting", icon: "😑", forms: "duller, dullest, dullness, dully", example: "The movie was dull and boring.", phonemeHighlight: "dull" },
  { word: "Dummy", ipa: "/ˈdʌmi/", meaning: "a duplicate model", simpleMeaning: "a fake copy", icon: "🎎", forms: "dummies", example: "They used a dummy for the test.", phonemeHighlight: "dum" },
  { word: "During", ipa: "/ˈdjʊərɪŋ/", meaning: "referring to a period of time", simpleMeaning: "while something happens", icon: "⏳", forms: "—", example: "Stay quiet during the movie.", phonemeHighlight: "dur" },
  { word: "Dust", ipa: "/dʌst/", meaning: "tiny particles that cover a surface", simpleMeaning: "fine dirt", icon: "🌫️", forms: "dusts, dusting, dusted, dusty", example: "Dust the furniture with a cloth.", phonemeHighlight: "dust" },
  { word: "Duster", ipa: "/ˈdʌstə/", meaning: "an object used to clean dust", simpleMeaning: "cleaning cloth", icon: "🧹", forms: "dusters", example: "Use the duster to clean the shelves.", phonemeHighlight: "dust" },
  { word: "Duty", ipa: "/ˈdjuːti/", meaning: "a task that one has to do", simpleMeaning: "a job to do", icon: "📋", forms: "duties", example: "It's your duty to help your family.", phonemeHighlight: "du" },
  { word: "Dye", ipa: "/daɪ/", meaning: "a liquid used to change the colour of something", simpleMeaning: "color changer", icon: "🎨", forms: "dyes, dyeing, dyed", example: "We used dye to color the fabric.", phonemeHighlight: "dye" },
];

/**
 * SpellbeeEntry type for simplified word list (A-Z groups)
 */
export type SpellbeeEntry = {
  id: string;        // kebab-case unique
  word: string;      // capitalized display
  ipa: string;       // keep slashes if present
  meaning: string;   // short, kid-friendly
  forms?: string[];  // optional; omit if "—"
};

/**
 * Additional SpellBee words parsed from RAW_WORDS
 * Organized A-Z for group dashboard
 */
export const SPELLBEE_WORDS: SpellbeeEntry[] = [
  // A-words
  { id: "action", word: "Action", ipa: "/ˈækʃən/", meaning: "a movement; a process of doing something", forms: ["actions", "actioning", "actioned"] },
  { id: "adapt", word: "Adapt", ipa: "/əˈdæpt/", meaning: "to adjust to fit", forms: ["adapting", "adapted", "adaptive", "adaptation"] },
  { id: "add", word: "Add", ipa: "/æd/", meaning: "to sum up; to include", forms: ["adds", "adding", "added", "addition"] },
  { id: "admit", word: "Admit", ipa: "/ədˈmɪt/", meaning: "to let in; to accept", forms: ["admits", "admitting", "admitted", "admission"] },
  { id: "afraid", word: "Afraid", ipa: "/əˈfreɪd/", meaning: "being scared" },
  { id: "after", word: "After", ipa: "/ˈæftər/", meaning: "later", forms: ["afterward", "afterwards"] },
  { id: "age", word: "Age", ipa: "/eɪdʒ/", meaning: "the number of years lived; lifetime", forms: ["ages", "ageing/aging", "aged"] },
  { id: "ago", word: "Ago", ipa: "/əˈɡoʊ/", meaning: "in the past" },
  { id: "aide", word: "Aide", ipa: "/eɪd/", meaning: "a person or thing that helps", forms: ["aides"] },
  { id: "aim", word: "Aim", ipa: "/eɪm/", meaning: "goal or target", forms: ["aims", "aiming", "aimed"] },
  { id: "air", word: "Air", ipa: "/eə(r)/", meaning: "a mixture of gases" },
  { id: "alike", word: "Alike", ipa: "/əˈlaɪk/", meaning: "similar or just the same" },
  { id: "allow", word: "Allow", ipa: "/əˈlaʊ/", meaning: "to let or permit", forms: ["allows", "allowing", "allowed", "allowance"] },
  { id: "alone", word: "Alone", ipa: "/əˈləʊn/", meaning: "without others" },
  { id: "along", word: "Along", ipa: "/əˈlɒŋ/", meaning: "together with someone" },
  { id: "angry", word: "Angry", ipa: "/ˈæŋɡri/", meaning: "being furious", forms: ["angrier", "angriest", "angrily"] },
  { id: "ankle", word: "Ankle", ipa: "/ˈæŋkəl/", meaning: "the joint between the foot and the leg", forms: ["ankles", "ankled", "ankling"] },
  { id: "ant", word: "Ant", ipa: "/ænt/", meaning: "a kind of small insect that lives in a large group", forms: ["ants"] },
  { id: "any", word: "Any", ipa: "/ˈeni/", meaning: "one or the other" },
  { id: "anyone", word: "Anyone", ipa: "/ˈɛniwʌn/", meaning: "any single person" },
  { id: "ape", word: "Ape", ipa: "/eɪp/", meaning: "a large monkey with no tail", forms: ["apes"] },
  { id: "apple", word: "Apple", ipa: "/ˈæpəl/", meaning: "a firm, round fruit, usually red or green", forms: ["apples"] },
  { id: "arch", word: "Arch", ipa: "/ɑːtʃ/", meaning: "a curved structure (like an upside-down \"U\")", forms: ["arches", "arching", "arched"] },
  { id: "area", word: "Area", ipa: "/ˈeəriə/", meaning: "a region or a piece of land", forms: ["areas"] },
  { id: "argue", word: "Argue", ipa: "/ˈɑːɡjuː/", meaning: "to disagree and discuss", forms: ["argues", "arguing", "argued", "argument"] },
  { id: "arm", word: "Arm", ipa: "/ɑːm/", meaning: "a part of the human body from shoulder to hand; to supply with a weapon", forms: ["arms", "armed"] },
  { id: "army", word: "Army", ipa: "/ˈɑːmi/", meaning: "a trained group of people who protect a country", forms: ["armies"] },
  { id: "aroma", word: "Aroma", ipa: "/əˈrəʊmə/", meaning: "a pleasant smell", forms: ["aromas", "aromatic"] },
  { id: "around", word: "Around", ipa: "/əˈraʊnd/", meaning: "nearby or surrounding something" },
  { id: "art", word: "Art", ipa: "/ɑːt/", meaning: "the making of objects/pictures (e.g., painting, dance, poetry)" },
  { id: "ask", word: "Ask", ipa: "/ɑːsk/", meaning: "to question", forms: ["asks", "asking", "asked"] },
  { id: "audio", word: "Audio", ipa: "/ˈɔːdiəʊ/", meaning: "related to sound or its playback" },
  { id: "aunt", word: "Aunt", ipa: "/ɑːnt/", meaning: "a sister of one's father or mother", forms: ["aunts"] },
  { id: "await", word: "Await", ipa: "/əˈweɪt/", meaning: "to wait for someone or something", forms: ["awaits", "awaiting", "awaited"] },
  { id: "awake", word: "Awake", ipa: "/əˈweɪk/", meaning: "to wake from sleep; not asleep", forms: ["awakes", "awoke/awakened", "awoken; awake (adj)"] },
  { id: "award", word: "Award", ipa: "/əˈwɔːd/", meaning: "a prize or present", forms: ["awards", "awarding", "awarded"] },
  { id: "away", word: "Away", ipa: "/əˈweɪ/", meaning: "somewhere else; at a distance" },

  // B-words
  { id: "back", word: "Back", ipa: "/bæk/", meaning: "behind; the other side of something", forms: ["backs", "backing", "backed"] },
  { id: "bark", word: "Bark", ipa: "/bɑːk/", meaning: "the sound made by a dog; the tough outer covering of a tree's trunk", forms: ["barks", "barking", "barked"] },
  { id: "base", word: "Base", ipa: "/beɪs/", meaning: "the bottom part", forms: ["bases", "based", "baser", "basest"] },
  { id: "bask", word: "Bask", ipa: "/bɑːsk/", meaning: "to sit or lie in the warm sun and relax", forms: ["basks", "basking", "basked"] },
  { id: "bathe", word: "Bathe", ipa: "/beɪð/", meaning: "to wash one's body", forms: ["bathes", "bathing", "bathed"] },
  { id: "bay", word: "Bay", ipa: "/beɪ/", meaning: "a part of a sea that cuts into the shore", forms: ["bays", "baying", "bayed"] },
  { id: "bee", word: "Bee", ipa: "/biː/", meaning: "a flying insect with a hairy body", forms: ["bees"] },
  { id: "been", word: "Been", ipa: "/biːn, bɪn/", meaning: "travelled/visited (past participle of \"be\")" },
  { id: "beg", word: "Beg", ipa: "/beɡ/", meaning: "to request or plead", forms: ["begs", "begging", "begged", "beggar"] },
  { id: "belt", word: "Belt", ipa: "/belt/", meaning: "a strap one wears around the waist", forms: ["belts", "belting", "belted"] },
  { id: "bench", word: "Bench", ipa: "/bentʃ/", meaning: "a long seat", forms: ["benches", "benched"] },
  { id: "better", word: "Better", ipa: "/ˈbetə/", meaning: "improved", forms: ["better", "best; betters", "bettering", "bettered"] },
  { id: "bike", word: "Bike", ipa: "/baɪk/", meaning: "a vehicle with two wheels", forms: ["bikes", "biking", "biked", "biker"] },
  { id: "bin", word: "Bin", ipa: "/bɪn/", meaning: "a container used to store or to dump", forms: ["bins", "binning", "binned"] },
  { id: "bird", word: "Bird", ipa: "/bɜːd/", meaning: "an egg-laying animal with wings, feathers and a beak", forms: ["birds"] },
  { id: "bit", word: "Bit", ipa: "/bɪt/", meaning: "a small piece", forms: ["bits"] },
  { id: "blade", word: "Blade", ipa: "/bleɪd/", meaning: "a flat, sharp cutting tool", forms: ["blades", "blading", "bladed"] },
  { id: "blame", word: "Blame", ipa: "/bleɪm/", meaning: "to throw fault on someone or something (cause)", forms: ["blames", "blaming", "blamed", "blameable"] },
  { id: "bleat", word: "Bleat", ipa: "/bliːt/", meaning: "the sound of a sheep or goat", forms: ["bleats", "bleating", "bleated"] },
  { id: "bless", word: "Bless", ipa: "/bles/", meaning: "wish with prayers; make something sacred/holy", forms: ["blesses", "blessing", "blessed", "blest"] },
  { id: "blood", word: "Blood", ipa: "/blʌd/", meaning: "the red liquid that flows through the body" },
  { id: "blow", word: "Blow", ipa: "/bləʊ/", meaning: "to force air out of one's mouth; a hit", forms: ["blows", "blowing", "blew", "blown"] },
  { id: "blue", word: "Blue", ipa: "/bluː/", meaning: "the colour of the clear sky; being sad or unhappy", forms: ["bluer", "bluest"] },
  { id: "blurred", word: "Blurred", ipa: "/blɜːd/", meaning: "being unclear or dim", forms: ["blur", "blurs", "blurring", "blurred"] },
  { id: "bow", word: "Bow", ipa: "/baʊ/", meaning: "a weapon for shooting arrows; to bend your body respectfully", forms: ["bows", "bowing", "bowed"] },
  { id: "bray", word: "Bray", ipa: "/breɪ/", meaning: "a loud, unpleasant noise like a donkey", forms: ["brays", "braying", "brayed"] },
  { id: "break", word: "Break", ipa: "/breɪk/", meaning: "to split into two or more pieces", forms: ["breaks", "breaking", "broke", "broken", "breakable"] },
  { id: "bud", word: "Bud", ipa: "/bʌd/", meaning: "an unopened leaf or flower", forms: ["buds", "budding", "budded"] },
  { id: "build", word: "Build", ipa: "/bɪld/", meaning: "to construct or make", forms: ["builds", "building", "built", "builder"] },
  { id: "bush", word: "Bush", ipa: "/bʊʃ/", meaning: "a plant with many short branches and a woody stem", forms: ["bushes", "bushy"] },

  // C-words
  { id: "cage", word: "Cage", ipa: "/keɪdʒ/", meaning: "a structure where animals/birds are kept", forms: ["cages", "caged", "caging"] },
  { id: "cake", word: "Cake", ipa: "/keɪk/", meaning: "a sweet snack baked usually in an oven", forms: ["cakes"] },
  { id: "calf", word: "Calf", ipa: "/kɑːf/", meaning: "a young one of a cow or elephant", forms: ["calves"] },
  { id: "call", word: "Call", ipa: "/kɔːl/", meaning: "to contact/attempt to contact by phone or in person", forms: ["calls", "calling", "called", "caller"] },
  { id: "calm", word: "Calm", ipa: "/kɑːm/", meaning: "being quiet or peaceful", forms: ["calmer", "calmest", "calmly", "calmness"] },
  { id: "camp", word: "Camp", ipa: "/kæmp/", meaning: "a place where people stay a short time", forms: ["camps", "camping", "camped"] },
  { id: "card", word: "Card", ipa: "/kɑːd/", meaning: "a small thick piece of paper or plastic", forms: ["cards"] },
  { id: "care", word: "Care", ipa: "/keə/", meaning: "to look after someone or something", forms: ["cares", "caring", "cared"] },
  { id: "cash", word: "Cash", ipa: "/kæʃ/", meaning: "money in notes and coins" },
  { id: "cave", word: "Cave", ipa: "/keɪv/", meaning: "a big hole or passage in rock", forms: ["caves"] },
  { id: "chair", word: "Chair", ipa: "/tʃeə/", meaning: "a person in charge of a meeting or company; a seat", forms: ["chairs", "chaired"] },
  { id: "chalk", word: "Chalk", ipa: "/tʃɔːk/", meaning: "a soft, white stone used for writing on a blackboard", forms: ["chalks", "chalking", "chalked"] },
  { id: "chase", word: "Chase", ipa: "/tʃeɪs/", meaning: "to run after someone or something", forms: ["chases", "chasing", "chased"] },
  { id: "chat", word: "Chat", ipa: "/tʃæt/", meaning: "to talk in a friendly way", forms: ["chats", "chatting", "chatted"] },
  { id: "check", word: "Check", ipa: "/tʃek/", meaning: "to make sure that something is correct", forms: ["checks", "checking", "checked"] },
  { id: "cheer", word: "Cheer", ipa: "/tʃɪə/", meaning: "to shout in joy or in support", forms: ["cheers", "cheering", "cheered"] },
  { id: "cheese", word: "Cheese", ipa: "/tʃiːz/", meaning: "a solid milk product", forms: ["cheeses"] },
  { id: "chew", word: "Chew", ipa: "/tʃuː/", meaning: "to bite/crush food with one's teeth", forms: ["chews", "chewing", "chewed"] },
  { id: "child", word: "Child", ipa: "/tʃaɪld/", meaning: "a baby or a kid", forms: ["children", "childish", "childlike"] },
  { id: "chin", word: "Chin", ipa: "/tʃɪn/", meaning: "the lowermost part of the face", forms: ["chins"] },
  { id: "chips", word: "Chips", ipa: "/tʃɪps/", meaning: "small, thin pieces of something (e.g., potato chips, wood chips)", forms: ["chips", "chipping", "chipped"] },
  { id: "chubby", word: "Chubby", ipa: "/ˈtʃʌbi/", meaning: "being fat in a pleasant way", forms: ["chubbier", "chubbiest", "chubbily", "chubbiness"] },
  { id: "city", word: "City", ipa: "/ˈsɪti/", meaning: "a large, well-connected town", forms: ["cities"] },
  { id: "clap", word: "Clap", ipa: "/klæp/", meaning: "to hit one's palms together many times", forms: ["claps", "clapping", "clapped"] },
  { id: "clash", word: "Clash", ipa: "/klæʃ/", meaning: "a fight or an argument", forms: ["clashes", "clashing", "clashed"] },
  { id: "claw", word: "Claw", ipa: "/klɔː/", meaning: "a bird's sharp, curved nail", forms: ["claws", "clawing", "clawed"] },
  { id: "clay", word: "Clay", ipa: "/kleɪ/", meaning: "a type of sticky soil used for pots/bricks", forms: ["clays"] },
  { id: "cleaned", word: "Cleaned", ipa: "/kliːnd/", meaning: "removed dirt or stain", forms: ["cleans", "cleaning", "cleaned"] },
  { id: "cleaner", word: "Cleaner", ipa: "/ˈkliːnə/", meaning: "someone who cleans; being more clean", forms: ["cleaners; cleaner (comparative)"] },
  { id: "cleanest", word: "Cleanest", ipa: "/ˈkliːnɪst/", meaning: "being most clean", forms: ["cleanest"] },
  { id: "cleaning", word: "Cleaning", ipa: "/ˈkliːnɪŋ/", meaning: "present continuous of clean; the act of cleaning", forms: ["cleaning"] },
  { id: "cleans", word: "Cleans", ipa: "/kliːnz/", meaning: "present simple of clean (e.g., \"He cleans\")", forms: ["cleans"] },
  { id: "comeback", word: "Comeback", ipa: "/ˈkʌmˌbæk/", meaning: "a quick, clever reply; a return after a break", forms: ["comebacks"] },
  { id: "comic", word: "Comic", ipa: "/ˈkɒmɪk/", meaning: "a book with stories told mainly through pictures; funny", forms: ["comics", "comical"] },
  { id: "cool", word: "Cool", ipa: "/kuːl/", meaning: "being slightly cold in a pleasant way", forms: ["cooler", "coolest", "cools", "cooling", "cooled", "coolly"] },
  { id: "cop", word: "Cop", ipa: "/kɒp/", meaning: "a police officer; to catch or arrest", forms: ["cops", "copping", "copped"] },
  { id: "cosy", word: "Cosy", ipa: "/ˈkəʊzi/", meaning: "being warm and comfortable", forms: ["cosier", "cosiest", "cosily"] },
  { id: "cough", word: "Cough", ipa: "/kɒf/", meaning: "an action of forcing air out through the mouth, mainly because of illness", forms: ["coughs", "coughing", "coughed", "cougher"] },

  // D-words
  { id: "daily", word: "Daily", ipa: "/ˈdeɪli/", meaning: "every day", forms: ["dailies"] },
  { id: "dame", word: "Dame", ipa: "/deɪm/", meaning: "a woman of high social rank", forms: ["dames"] },
  { id: "date", word: "Date", ipa: "/deɪt/", meaning: "a particular day in a month", forms: ["dates"] },
  { id: "day", word: "Day", ipa: "/deɪ/", meaning: "a period of 24 hours", forms: ["days", "daytime"] },
  { id: "daybreak", word: "Daybreak", ipa: "/ˈdeɪbreɪk/", meaning: "the beginning of a day (dawn)", forms: ["daybreaks"] },
  { id: "deaf", word: "Deaf", ipa: "/def/", meaning: "not being able to hear", forms: ["deafer", "deafest", "deafly", "deafness"] },
  { id: "deep", word: "Deep", ipa: "/diːp/", meaning: "being far down from the surface to the bottom", forms: ["deeper", "deepest", "deeply", "deepness"] },
  { id: "deer", word: "Deer", ipa: "/dɪə/", meaning: "a wild grass-eating animal; male deer has horns", forms: ["deer (plural same)"] },
  { id: "den", word: "Den", ipa: "/den/", meaning: "the hidden home of lions or other wild animals", forms: ["dens"] },
  { id: "dental", word: "Dental", ipa: "/ˈdentl/", meaning: "relating to teeth", forms: ["dentals", "dentistry", "dentality (rare)"] },
  { id: "deny", word: "Deny", ipa: "/dɪˈnaɪ/", meaning: "to not accept", forms: ["denies", "denying", "denied"] },
  { id: "desk", word: "Desk", ipa: "/desk/", meaning: "a work table", forms: ["desks"] },
  { id: "dew", word: "Dew", ipa: "/djuː/", meaning: "water droplets", forms: ["dews"] },
  { id: "dial", word: "Dial", ipa: "/ˈdaɪəl/", meaning: "the face of a clock; call a telephone number", forms: ["dials", "dialling/dialing", "dialled/dialed", "dialler"] },
  { id: "dice", word: "Dice", ipa: "/daɪs/", meaning: "small cube(s) used for games; cut into small cubes", forms: ["dice (pl.)", "dicing", "diced"] },
  { id: "dim", word: "Dim", ipa: "/dɪm/", meaning: "being less bright", forms: ["dimmer", "dimmest", "dimly", "dimness"] },
  { id: "dine", word: "Dine", ipa: "/daɪn/", meaning: "to eat (usually dinner at restaurants)", forms: ["dines", "dining", "dined", "diner"] },
  { id: "dip", word: "Dip", ipa: "/dɪp/", meaning: "to wet in a liquid; a quick swim", forms: ["dips", "dipping", "dipped"] },
  { id: "dirt", word: "Dirt", ipa: "/dɜːt/", meaning: "the dust/soil that makes something unclean", forms: ["dirts (rare)", "dirty (adj)"] },
  { id: "dirty", word: "Dirty", ipa: "/ˈdɜːti/", meaning: "not being clean", forms: ["dirtier", "dirtiest", "dirtiness", "dirtily"] },
  { id: "dish", word: "Dish", ipa: "/dɪʃ/", meaning: "food prepared in a particular way; a flat-bottomed container", forms: ["dishes", "dishing", "dished"] },
  { id: "disk", word: "Disk", ipa: "/dɪsk/", meaning: "a thin, circular object (e.g., CD)", forms: ["disks"] },
  { id: "dislike", word: "Dislike", ipa: "/dɪsˈlaɪk/", meaning: "to not like something", forms: ["dislikes", "disliking", "disliked"] },
  { id: "dismiss", word: "Dismiss", ipa: "/dɪsˈmɪs/", meaning: "to ask someone/a group to leave; to reject as not important", forms: ["dismisses", "dismissing", "dismissed", "dismissive", "dismissal"] },
  { id: "display", word: "Display", ipa: "/dɪˈspleɪ/", meaning: "to show or exhibit", forms: ["displays", "displaying", "displayed", "displayable", "display"] },
  { id: "does", word: "Does", ipa: "/dʌz/", meaning: "word form from \"do\" (He/She/It does)", forms: ["do", "did", "done"] },
  { id: "doll", word: "Doll", ipa: "/dɒl/", meaning: "a child's toy (person)", forms: ["dolls"] },
  { id: "door", word: "Door", ipa: "/dɔː/", meaning: "a solid, flat object that opens/closes an entry", forms: ["doors"] },
  { id: "dose", word: "Dose", ipa: "/dəʊs/", meaning: "an amount of medicine", forms: ["doses", "dosing", "dosed"] },
  { id: "double", word: "Double", ipa: "/ˈdʌbəl/", meaning: "being twice the amount", forms: ["doubles", "doubling", "doubled", "doublet", "doubling"] },
  { id: "doubt", word: "Doubt", ipa: "/daʊt/", meaning: "a feeling of not being sure about something", forms: ["doubts", "doubting", "doubted", "doubtless"] },
  { id: "down", word: "Down", ipa: "/daʊn/", meaning: "at a lower level", forms: ["downs", "downing", "downed"] },
  { id: "downfall", word: "Downfall", ipa: "/ˈdaʊnfɔːl/", meaning: "sudden loss of power, money or health", forms: ["downfalls"] },
  { id: "download", word: "Download", ipa: "/ˌdaʊnˈləʊd/", meaning: "to receive/copy data onto one's computer", forms: ["downloads", "downloading", "downloaded", "downloadable"] },
  { id: "doze", word: "Doze", ipa: "/dəʊz/", meaning: "to take a short nap", forms: ["dozes", "dozing", "dozed", "dozer"] },
  { id: "dozen", word: "Dozen", ipa: "/ˈdʌz.ən/", meaning: "a set of 12", forms: ["dozens", "dozenth"] },
  { id: "drain", word: "Drain", ipa: "/dreɪn/", meaning: "a pipe that lets out rainwater or liquid waste; to let out (e.g., brain drain)", forms: ["drains", "draining", "drained", "drainage"] },
  { id: "drama", word: "Drama", ipa: "/ˈdrɑː.mə/", meaning: "a play on a stage", forms: ["dramas", "dramatic"] },
  { id: "draw", word: "Draw", ipa: "/drɔː/", meaning: "a match that ends in the same score; to make pictures; to pull or drag", forms: ["draws", "drawing", "drew", "drawn", "drawable"] },
  { id: "dream", word: "Dream", ipa: "/driːm/", meaning: "events/images seen while sleeping; an imagined goal", forms: ["dreams", "dreaming", "dreamed", "dreamt", "dreamingly"] },
  { id: "drink", word: "Drink", ipa: "/drɪŋk/", meaning: "a liquid taken as refreshment; to swallow a liquid", forms: ["drinkable", "drinks", "drinking", "drank", "drunk"] },
  { id: "drive", word: "Drive", ipa: "/draɪv/", meaning: "to control and move a vehicle; a computer storage device", forms: ["drives", "driving", "drove", "driven"] },
  { id: "drop", word: "Drop", ipa: "/drɒp/", meaning: "to let something fall; a small, roughly spherical amount of liquid", forms: ["drops", "dropping", "dropped"] },
  { id: "drown", word: "Drown", ipa: "/draʊn/", meaning: "to sink in water", forms: ["drowns", "drowning", "drowned", "drowner"] },
  { id: "drug", word: "Drug", ipa: "/drʌɡ/", meaning: "a medicine", forms: ["drugs", "drugging", "drugged"] },
  { id: "drum", word: "Drum", ipa: "/drʌm/", meaning: "a musical instrument; a cylindrical container", forms: ["drums", "drumming", "drummed", "drummer"] },
  { id: "due", word: "Due", ipa: "/djuː/", meaning: "a fee; expected at a certain time", forms: ["dues"] },
  { id: "dull", word: "Dull", ipa: "/dʌl/", meaning: "being boring or not interesting", forms: ["duller", "dullest", "dulls", "dulling", "dulled", "dullish", "dullness", "dully"] },
  { id: "dummy", word: "Dummy", ipa: "/ˈdʌmi/", meaning: "a duplicate model", forms: ["dummies"] },
  { id: "during", word: "During", ipa: "/ˈdjʊərɪŋ/", meaning: "referring to a period of time" },
  { id: "dust", word: "Dust", ipa: "/dʌst/", meaning: "tiny particles that cover a surface", forms: ["dusts", "dusting", "dusted", "dusty"] },
  { id: "duster", word: "Duster", ipa: "/ˈdʌstə/", meaning: "an object used to clean dust", forms: ["dusters"] },
  { id: "duty", word: "Duty", ipa: "/ˈdjuːti/", meaning: "a task that one has to do", forms: ["duties"] },
  { id: "dye", word: "Dye", ipa: "/daɪ/", meaning: "a liquid used to change the colour of something", forms: ["dyes", "dyeing", "dyed"] },

  // E-words
  { id: "each", word: "Each", ipa: "/iːtʃ/", meaning: "every single thing" },
  { id: "eager", word: "Eager", ipa: "/ˈiː.ɡə/", meaning: "being interested in doing something", forms: ["eagerly", "eagerness"] },
  { id: "early", word: "Early", ipa: "/ˈɜː.li/", meaning: "before the said time", forms: ["earlier", "earliest"] },
  { id: "earn", word: "Earn", ipa: "/ɜːn/", meaning: "to get something as a result of one's hard work", forms: ["earns", "earning", "earned"] },
  { id: "earshot", word: "Earshot", ipa: "/ˈɪəʃɒt/", meaning: "the distance over which one can hear" },
  { id: "earth", word: "Earth", ipa: "/ɜːθ/", meaning: "the world we live in; the soil", forms: ["earths", "earthen", "earthy"] },
  { id: "east", word: "East", ipa: "/iːst/", meaning: "the direction from which the sun rises", forms: ["eastern", "easterly", "eastward"] },
  { id: "easy", word: "Easy", ipa: "/ˈiːzi/", meaning: "not needing much effort", forms: ["easier", "easiest", "easily", "easiness"] },
  { id: "echo", word: "Echo", ipa: "/ˈɛkəʊ/", meaning: "a sound being repeated (reflected)", forms: ["echoes", "echoing", "echoed"] },
  { id: "edge", word: "Edge", ipa: "/ɛdʒ/", meaning: "the corner/edge part of any surface", forms: ["edges", "edging", "edged"] },
  { id: "elbow", word: "Elbow", ipa: "/ˈɛlbəʊ/", meaning: "the joint where the arm bends", forms: ["elbows", "elbowing", "elbowed"] },
  { id: "elder", word: "Elder", ipa: "/ˈɛldə/", meaning: "being of older age", forms: ["elders", "elderly", "eldest"] },
  { id: "else", word: "Else", ipa: "/ɛls/", meaning: "other or another" },
  { id: "empty", word: "Empty", ipa: "/ˈɛmpti/", meaning: "to drain/vacate/remove; not having anything", forms: ["emptier", "emptiest", "empties", "emptying", "emptied", "emptiness"] },
  { id: "endless", word: "Endless", ipa: "/ˈɛndləs/", meaning: "having no end or limit", forms: ["endlessly", "endlessness"] },
  { id: "enemy", word: "Enemy", ipa: "/ˈɛnəmi/", meaning: "a person/country that hates and wants to harm another", forms: ["enemies"] },
  { id: "energy", word: "Energy", ipa: "/ˈɛnədʒi/", meaning: "the strength to do work", forms: ["energies", "energise/energize", "energising/energizing", "energised/energized", "energetic"] },
  { id: "evict", word: "Evict", ipa: "/ɪˈvɪkt/", meaning: "to force someone to leave one's land/house", forms: ["evicts", "evicting", "evicted", "eviction", "evictee", "evictor"] },
  { id: "ewe", word: "Ewe", ipa: "/juː/", meaning: "a female sheep", forms: ["ewes"] },
  { id: "extra", word: "Extra", ipa: "/ˈɛk.strə/", meaning: "having more than what is needed", forms: ["extras"] },
  { id: "eyeball", word: "Eyeball", ipa: "/ˈaɪ.bɔːl/", meaning: "the whole eye", forms: ["eyeballs"] },

  // F-words
  { id: "fable", word: "Fable", ipa: "/ˈfeɪbəl/", meaning: "a short story with a moral", forms: ["fables"] },
  { id: "face", word: "Face", ipa: "/feɪs/", meaning: "the front part of the head; to deal with", forms: ["faces", "facing", "faced", "facial"] },
  { id: "fact", word: "Fact", ipa: "/fækt/", meaning: "an actual or correct information", forms: ["facts", "factual"] },
  { id: "fail", word: "Fail", ipa: "/feɪl/", meaning: "to not win or to not pass", forms: ["fails", "failing", "failed", "failure"] },
  { id: "fair", word: "Fair", ipa: "/feə/", meaning: "a large public event; light-coloured; treating everyone equally", forms: ["fairer", "fairest", "fairs", "fairness"] },
  { id: "fall", word: "Fall", ipa: "/fɔːl/", meaning: "to drop down", forms: ["falls", "falling", "fell", "fallen"] },
  { id: "false", word: "False", ipa: "/fɔːls/", meaning: "being not true", forms: ["falsely", "falseness", "falsify", "falsehood"] },
  { id: "fame", word: "Fame", ipa: "/feɪm/", meaning: "the state of being popular", forms: ["famed", "famous"] },
  { id: "fancy", word: "Fancy", ipa: "/ˈfæn.si/", meaning: "decorative; to like something", forms: ["fancies", "fancying", "fancied", "fancily", "fanciful", "fanciness"] },
  { id: "far", word: "Far", ipa: "/fɑː/", meaning: "a long distance", forms: ["farther", "farthest", "further", "furthest"] },
  { id: "farm", word: "Farm", ipa: "/fɑːm/", meaning: "land where crops are grown and animals are raised", forms: ["farms", "farming", "farmed", "farmer"] },
  { id: "fast", word: "Fast", ipa: "/fæst/", meaning: "being quick; to not eat", forms: ["faster", "fastest", "fasts", "fasted"] },
  { id: "father", word: "Father", ipa: "/ˈfɑː.ðə/", meaning: "the male parent of a child", forms: ["fathers", "fathering", "fathered", "fatherhood"] },
  { id: "fault", word: "Fault", ipa: "/fɔːlt/", meaning: "a mistake", forms: ["faults", "faulting", "faulted"] },
  { id: "fear", word: "Fear", ipa: "/fɪə/", meaning: "the state of being scared", forms: ["fears", "fearing", "feared", "fearful", "fearless"] },
  { id: "feast", word: "Feast", ipa: "/fiːst/", meaning: "a large and special meal with many dishes", forms: ["feasts", "feasting", "feasted", "feaster"] },
  { id: "feed", word: "Feed", ipa: "/fiːd/", meaning: "to give food to someone", forms: ["feeds", "feeding", "fed"] },
  { id: "feel", word: "Feel", ipa: "/fiːl/", meaning: "to touch and sense; to experience an emotion", forms: ["feels", "feeling", "felt"] },
  { id: "feet", word: "Feet", ipa: "/fiːt/", meaning: "the lower part of the leg with which a person walks; unit equal to 30.48 cm", forms: ["foot"] },
  { id: "fence", word: "Fence", ipa: "/fens/", meaning: "a structure/wall that encloses an area and prevents entry", forms: ["fences", "fencing", "fenced"] },
  { id: "fever", word: "Fever", ipa: "/ˈfiːvə/", meaning: "an illness that causes high body temperature", forms: ["fevers", "feverish", "feverishly"] },
  { id: "few", word: "Few", ipa: "/fjuː/", meaning: "a small number", forms: ["fewer", "fewest", "fewness"] },
  { id: "fig", word: "Fig", ipa: "/fɪɡ/", meaning: "a soft fruit with many tiny seeds", forms: ["figs"] },
  { id: "file", word: "File", ipa: "/faɪl/", meaning: "a folder for important papers; to arrange and keep documents in order", forms: ["files", "filing", "filed", "filer"] },
  { id: "fill", word: "Fill", ipa: "/fɪl/", meaning: "to occupy a space with something", forms: ["fills", "filling", "filled", "filler"] },
  { id: "fin", word: "Fin", ipa: "/fɪn/", meaning: "a part of a fish that helps it to swim", forms: ["fins"] },
  { id: "final", word: "Final", ipa: "/ˈfaɪ.nəl/", meaning: "the last one", forms: ["finals", "finally"] },
  { id: "find", word: "Find", ipa: "/faɪnd/", meaning: "to search and spot", forms: ["finds", "finding", "found"] },
  { id: "fine", word: "Fine", ipa: "/faɪn/", meaning: "money paid as punishment; good; very thin/tiny", forms: ["fines", "fining", "fined"] },
  { id: "fingernail", word: "Fingernail", ipa: "/ˈfɪŋ.ɡə.neɪl/", meaning: "the hard, slightly curvy, smooth upper surface at the end of a finger", forms: ["fingernails"] },
  { id: "fingers", word: "Fingers", ipa: "/ˈfɪŋ.ɡəz/", meaning: "long, thin, jointed parts at the ends of either hand", forms: ["finger"] },
  { id: "finish", word: "Finish", ipa: "/ˈfɪn.ɪʃ/", meaning: "to complete something; to conclude", forms: ["finishes", "finishing", "finished", "finisher"] },
  { id: "fire", word: "Fire", ipa: "/faɪə/", meaning: "a flame produced when burning something; to dismiss someone from a job", forms: ["fires", "firing", "fired"] },
  { id: "firearm", word: "Firearm", ipa: "/ˈfaɪər.ɑːm/", meaning: "a small gun", forms: ["firearms"] },
  { id: "first", word: "First", ipa: "/fɜːst/", meaning: "coming before others; topmost in rank or importance", forms: ["firsts", "firstly"] },
  { id: "fish", word: "Fish", ipa: "/fɪʃ/", meaning: "an animal that lives in water and swims with fins and tail", forms: ["fish", "fishes", "fishy"] },
  { id: "fist", word: "Fist", ipa: "/fɪst/", meaning: "one's hand with tightly closed fingers", forms: ["fists", "fistful", "fisted", "fisting"] },
  { id: "fizz", word: "Fizz", ipa: "/fɪz/", meaning: "to produce many bubbles in a liquid with a continuous hissing sound", forms: ["fizzes", "fizzing", "fizzed", "fizzy"] },
  { id: "flag", word: "Flag", ipa: "/flæg/", meaning: "a cloth with a design used as a country's or group's symbol; to mark something", forms: ["flags", "flagging", "flagged"] },
  { id: "flair", word: "Flair", ipa: "/fleə/", meaning: "a natural talent" },
  { id: "flake", word: "Flake", ipa: "/fleɪk/", meaning: "a small, flat, thin piece of something (e.g., corn flakes)", forms: ["flakes", "flaking", "flaked", "flaky"] },
  { id: "flame", word: "Flame", ipa: "/fleɪm/", meaning: "the hot, glowing gas of fire", forms: ["flames", "flaming", "flamed", "flammable"] },
  { id: "flap", word: "Flap", ipa: "/flæp/", meaning: "a piece of cloth/metal etc. used to open/close something; to move up and down like wings", forms: ["flaps", "flapping", "flapped"] },
  { id: "flat", word: "Flat", ipa: "/flæt/", meaning: "having a smooth and even surface", forms: ["flatter", "flattest", "flatly", "flatness"] },
  { id: "flaw", word: "Flaw", ipa: "/flɔː/", meaning: "a mistake", forms: ["flaws", "flawy", "flawed"] },
  { id: "flight", word: "Flight", ipa: "/flaɪt/", meaning: "a journey in an aircraft", forms: ["flights", "flighted", "flighting"] },
  { id: "float", word: "Float", ipa: "/fləʊt/", meaning: "to move on a liquid surface without sinking", forms: ["floats", "floating", "floated", "floatable", "floatability"] },
  { id: "flock", word: "Flock", ipa: "/flɒk/", meaning: "a group of birds, sheep or goats", forms: ["flocks", "flocking", "flocked"] },
  { id: "flood", word: "Flood", ipa: "/flʌd/", meaning: "an overflow of a large amount of water", forms: ["floods", "flooding", "flooded", "floodable", "floodability"] },
  { id: "floor", word: "Floor", ipa: "/flɔː/", meaning: "the ground surface of a room", forms: ["floors", "flooring", "floored"] },
  { id: "flop", word: "Flop", ipa: "/flɒp/", meaning: "a complete failure", forms: ["flops", "flopping", "flopped"] },
  { id: "flour", word: "Flour", ipa: "/flaʊə/", meaning: "powdered grain (e.g., wheat flour, corn flour)", forms: ["flours", "flouring", "floured", "floury"] },
  { id: "flow", word: "Flow", ipa: "/fləʊ/", meaning: "to move or run smoothly", forms: ["flows", "flowing", "flowed"] },
  { id: "flower", word: "Flower", ipa: "/ˈflaʊə/", meaning: "a brightly coloured part of a plant with a pleasant smell", forms: ["flowers", "flowering", "flowered"] },
  { id: "fluff", word: "Fluff", ipa: "/flʌf/", meaning: "something very light and soft (like wool)", forms: ["fluffs", "fluffing", "fluffed", "fluffy"] },
  { id: "fluid", word: "Fluid", ipa: "/ˈfluː.ɪd/", meaning: "a substance that flows easily (gas or liquid)", forms: ["fluids", "fluidic", "fluidly", "fluidity"] },
  { id: "flute", word: "Flute", ipa: "/fluːt/", meaning: "a thin tube-like musical wind instrument (often bamboo)", forms: ["flutes", "flutist/flautist", "fluty"] },
  { id: "focus", word: "Focus", ipa: "/ˈfəʊ.kəs/", meaning: "main/central point of interest; to bring something to attention", forms: ["foci", "focuses", "focusing", "focussed", "focuser"] },
  { id: "foe", word: "Foe", ipa: "/fəʊ/", meaning: "an enemy", forms: ["foes"] },
  { id: "fog", word: "Fog", ipa: "/fɒɡ/", meaning: "a thick water cloud in/near the air that makes it hard to see through", forms: ["fogs", "fogging", "fogged", "foggy"] },
  { id: "fold", word: "Fold", ipa: "/fəʊld/", meaning: "to bend something into a shape (e.g., cloth, paper)", forms: ["folds", "folding", "folded", "foldable"] },
  { id: "folder", word: "Folder", ipa: "/ˈfəʊldə/", meaning: "a file for keeping sheets of paper", forms: ["folders"] },
  { id: "folk", word: "Folk", ipa: "/fəʊk/", meaning: "people in general or those of a particular group", forms: ["folks"] },
  { id: "fond", word: "Fond", ipa: "/fɒnd/", meaning: "liking something or someone", forms: ["fonder", "fondest", "fondly", "fondness"] },
  { id: "food", word: "Food", ipa: "/fuːd/", meaning: "any edible, nutritious substance that people and animals eat or plants absorb", forms: ["foods"] },
  { id: "fool", word: "Fool", ipa: "/fuːl/", meaning: "someone silly or unwise", forms: ["fools", "fooling", "fooled", "foolish", "foolishly", "foolishness"] },
  { id: "footpath", word: "Footpath", ipa: "/ˈfʊtpɑːθ/", meaning: "a path used mainly for walking", forms: ["footpaths"] },
  { id: "forearm", word: "Forearm", ipa: "/ˈfɔːrɑːm/", meaning: "the part of the arm from the elbow to the wrist", forms: ["forearms"] },
  { id: "forehead", word: "Forehead", ipa: "/ˈfɒrɪd, ˈfɔːhed/", meaning: "the upper part of the face between hair and eyebrows", forms: ["foreheads"] },
  { id: "forest", word: "Forest", ipa: "/ˈfɒrɪst/", meaning: "a large area covered with many trees and plants that shelters animals", forms: ["forests", "forestry"] },
  { id: "fork", word: "Fork", ipa: "/fɔːk/", meaning: "an object with pointy edges, used for eating", forms: ["forks", "forking", "forked"] },
  { id: "form", word: "Form", ipa: "/fɔːm/", meaning: "the shape of something; a printed document with spaces to fill in information", forms: ["forms", "forming", "formed", "formation"] },
  { id: "fort", word: "Fort", ipa: "/fɔːt/", meaning: "a strong building with high walls, used as a military post", forms: ["forts", "fortify"] },
  { id: "forty", word: "Forty", ipa: "/ˈfɔːti/", meaning: "the number 40", forms: ["forties"] },
  { id: "fountain", word: "Fountain", ipa: "/ˈfaʊn.tɪn/", meaning: "a natural or artificial water spring", forms: ["fountains"] },
  { id: "frame", word: "Frame", ipa: "/freɪm/", meaning: "a border", forms: ["frames", "framing", "framed", "framer"] },
  { id: "frank", word: "Frank", ipa: "/fræŋk/", meaning: "being open and honest", forms: ["franker", "frankest", "frankly", "frankness"] },
  { id: "freeze", word: "Freeze", ipa: "/friːz/", meaning: "to become very cold and turn into ice", forms: ["freezes", "freezing", "froze", "frozen"] },
  { id: "fresh", word: "Fresh", ipa: "/freʃ/", meaning: "being recent or new", forms: ["fresher", "freshest", "freshly", "freshness"] },
  { id: "fridge", word: "Fridge", ipa: "/frɪdʒ/", meaning: "a device/case used to keep food fresh and cool", forms: ["fridges", "refrigerator"] },
  { id: "friend", word: "Friend", ipa: "/frend/", meaning: "a person whom one likes and enjoys being with", forms: ["friends", "friendly", "friendlier", "friendliest", "friendliness"] },
  { id: "frill", word: "Frill", ipa: "/frɪl/", meaning: "a decoration with small foldings of cloth", forms: ["frills", "frilly", "frilled"] },
  { id: "frock", word: "Frock", ipa: "/frɒk/", meaning: "a dress worn by girls", forms: ["frocks"] },
  { id: "front", word: "Front", ipa: "/frʌnt/", meaning: "the surface that faces forward", forms: ["fronts", "fronting", "fronted"] },
  { id: "fruit", word: "Fruit", ipa: "/fruːt/", meaning: "a soft, fleshy, edible product (part of a tree or plant)", forms: ["fruits", "fruity"] },
  { id: "fry", word: "Fry", ipa: "/fraɪ/", meaning: "to cook in hot oil", forms: ["fries", "frying", "fried"] },
  { id: "fuel", word: "Fuel", ipa: "/ˈfjuːəl/", meaning: "a substance used to provide heat or power", forms: ["fuels", "fuelling/fueling", "fuelled/fueled"] },
  { id: "fun", word: "Fun", ipa: "/fʌn/", meaning: "a pleasure or enjoyment", forms: ["funny"] },
  { id: "fund", word: "Fund", ipa: "/fʌnd/", meaning: "a sum of money", forms: ["funds", "funding", "funded", "funder"] },
  { id: "fur", word: "Fur", ipa: "/fɜː/", meaning: "the thick hair that covers some kinds of animals", forms: ["furs", "furred", "furry"] },
];
